"use client";

import { useEffect, useState } from "react";
import styles from "./rapport.module.css";

type Signature={actorName:string;createdAt:string;tier?:number|null;comment?:string|null};
type Component={employeeKey:string|null;matricule:string|null;employeeName:string;population:string;jobKey:string;sectorLabel:string|null;teamCode:string|null;presenceHours:number|null;billedHours:number|null;absenceHours:number|null;productivity:number|null;absenceRate:number|null;thresholds:(number|null)[];theoreticalTier:number|null;teamTier:number|null;serviceTier:number|null;finalTier:number|null;teamSignature:Signature|null;serviceSignature:Signature|null;coefficient:number|null;individualBaseEur:number|null;individualAmountEur:number|null;collectiveLabel:string|null;collectiveAmountEur:number|null;collectiveProration:number|null;exceptionalAmountEur:number|null;totalAmountEur:number|null;sourcePayload:Record<string,unknown>};
type Detail={workflow:{id:string;month:string;status:string;validationMode:string;sourceFilename:string|null;sourceSha256:string|null;sourceSnapshot:Record<string,unknown>;audit:Record<string,unknown>;totals:Record<string,unknown>;frozenHash:string|null;directionSignature:Signature|null};components:Component[]};
function money(v:number|null|undefined){return v==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(v)}
function num(v:number|null|undefined,d=1){return v==null?"—":new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(v)}
function pct(v:number|null|undefined){return v==null?"—":`${num(v*100,1)} %`}
function monthLabel(month:string){const [y,m]=month.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(y,m-1,1));}
function threshold(c:Component,v:number|null|undefined){if(v==null)return"—";return c.population==="productif"?pct(v):num(v,4);}
function signatureLabel(signature:Signature|null,legacy:boolean){if(legacy)return"Non disponible · historique Excel";if(!signature)return"En attente";return `✓ Signé numériquement par ${signature.actorName} · ${new Date(signature.createdAt).toLocaleString("fr-FR")}`;}

export default function BonusReportPage(){
  const [detail,setDetail]=useState<Detail|null>(null);const [component,setComponent]=useState<Component|null>(null);const [error,setError]=useState("");
  useEffect(()=>{const p=new URLSearchParams(location.search);const workflowId=p.get("workflowId"),employeeKey=p.get("employeeKey");if(!workflowId||!employeeKey){setError("Paramètres du rapport manquants.");return;}fetch(`/api/monthly-animation?workflowId=${encodeURIComponent(workflowId)}`,{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Rapport indisponible.");const d=data as Detail;const c=d.components.find(item=>item.employeeKey===employeeKey);if(!c)throw new Error("Collaborateur hors périmètre ou introuvable.");setDetail(d);setComponent(c);}).catch(e=>setError(e instanceof Error?e.message:"Rapport indisponible."));},[]);
  if(error)return <main className={styles.page}><div className={styles.sheet}><div className={styles.error}>{error}</div></div></main>;
  if(!detail||!component)return <main className={styles.page}><div className={styles.sheet}><div className={styles.error}>Chargement du rapport…</div></div></main>;
  const c=component,w=detail.workflow,legacy=w.validationMode==="legacy_excel";const sourceComment=String(c.sourcePayload?.sourceComment??"");
  return <main className={styles.page}><div className={styles.actions}><button onClick={()=>window.print()}>IMPRIMER / ENREGISTRER PDF</button></div><article className={styles.sheet}>
    <header className={styles.header}><div><span>KPI CRVO · ANIMATION VARIABLE</span><h1>Rapport individuel de prime</h1><p>{monthLabel(w.month)} · workflow {legacy?"historique figé":"clôturé"}</p></div><img src="/crvo-logo.png" alt="CRVO"/></header>
    <div className={styles.content}>
      {legacy&&<div className={styles.banner}><b>Référence historique Excel.</b> Ce rapport restitue les valeurs figées de juillet 2026 sans inventer les données absentes du classeur source. Certaines heures achetées/vendues ne sont donc pas disponibles pour les populations qui n'étaient pas suivies individuellement dans les feuilles historiques.</div>}
      <section className={styles.identity}><div className={styles.cell}><span>Collaborateur</span><strong>{c.employeeName}</strong></div><div className={styles.cell}><span>Matricule</span><strong>{c.matricule??"—"}</strong></div><div className={styles.cell}><span>Métier</span><strong>{c.jobKey}</strong></div><div className={styles.cell}><span>Organisation</span><strong>{c.sectorLabel??"—"} · Équipe {c.teamCode??"—"}</strong></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Performance du mois</h2><i/></div><div className={styles.metrics}><div className={styles.metric}><span>Heures achetées</span><strong>{num(c.presenceHours,2)} h</strong></div><div className={styles.metric}><span>Heures vendues</span><strong>{num(c.billedHours,2)} h</strong></div><div className={styles.metric}><span>Rendement</span><strong>{pct(c.productivity)}</strong></div><div className={styles.metric}><span>Absence</span><strong>{num(c.absenceHours,2)} h</strong></div><div className={styles.metric}><span>Absentéisme</span><strong>{pct(c.absenceRate)}</strong></div></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Chaîne de validation</h2><i/></div><div className={styles.tiers}><div className={styles.tier}><span>Palier théorique</span><strong>{c.theoreticalTier==null?"—":`P${c.theoreticalTier}`}</strong></div><div className={styles.tier}><span>Chef d'équipe</span><strong>{c.teamTier==null?"—":`✓ P${c.teamTier}`}</strong></div><div className={styles.tier}><span>Chef de service</span><strong>{c.serviceTier==null?"—":`✓ P${c.serviceTier}`}</strong></div><div className={styles.tier}><span>Palier figé</span><strong>{c.finalTier==null?"—":`P${c.finalTier}`}</strong></div></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Calcul financier</h2><i/></div><div className={styles.money}><div className={styles.metric}><span>Base individuelle</span><strong>{money(c.individualBaseEur)}</strong></div><div className={styles.metric}><span>Prime individuelle</span><strong>{money(c.individualAmountEur)}</strong></div><div className={styles.metric}><span>Part collective après proratisation individuelle</span><strong>{c.collectiveAmountEur==null?(c.collectiveLabel??"—"):money((c.collectiveAmountEur??0)*(c.collectiveProration??1))}</strong></div><div className={styles.metric}><span>Total du mois</span><strong>{money(c.totalAmountEur)}</strong></div></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Explication & traçabilité</h2><i/></div><div className={styles.trace}><div className={styles.traceRow}><b>Seuils du métier</b><span>{(c.thresholds??[]).map((v,i)=>`P${i+1}: ${threshold(c,v)}`).join(" · ")||"—"}</span></div><div className={styles.traceRow}><b>Coefficient de prime</b><span>{pct(c.coefficient)}</span></div><div className={styles.traceRow}><b>Proratisation individuelle</b><span>{pct(c.collectiveProration)}</span></div><div className={styles.traceRow}><b>Prime exceptionnelle</b><span>{money(c.exceptionalAmountEur)}</span></div><div className={styles.traceRow}><b>Signature numérique CE</b><span>{signatureLabel(c.teamSignature,legacy)}</span></div><div className={styles.traceRow}><b>Signature numérique CDS</b><span>{signatureLabel(c.serviceSignature,legacy)}</span></div><div className={styles.traceRow}><b>Signature numérique Direction</b><span>{signatureLabel(w.directionSignature,legacy)}</span></div></div>{sourceComment&&<div className={styles.sourceComment}><b>Commentaire source / management :</b><br/>{sourceComment}</div>}</section>
    </div>
  </article></main>;
}
