"use client";

import { type ReactNode, useEffect, useState } from "react";
import type { EmployeeProration, ProrationContext, ProrationEventImpact, ProrationMode } from "../../lib/bonus-proration";
import styles from "./rapport.module.css";

type Signature={actorName:string;createdAt:string;tier?:number|null;comment?:string|null};
type Component={employeeKey:string|null;matricule:string|null;employeeName:string;population:string;jobKey:string;sectorLabel:string|null;teamCode:string|null;presenceHours:number|null;billedHours:number|null;absenceHours:number|null;absenceReasons?:Record<string,number>;productivity:number|null;absenceRate:number|null;thresholds:(number|null)[];theoreticalTier:number|null;teamTier:number|null;serviceTier:number|null;finalTier:number|null;teamSignature:Signature|null;serviceSignature:Signature|null;coefficient:number|null;individualBaseEur:number|null;individualAmountEur:number|null;collectiveLabel:string|null;collectiveAmountEur:number|null;collectiveProration:number|null;exceptionalAmountEur:number|null;totalAmountEur:number|null;sourcePayload:Record<string,unknown>};
type Detail={workflow:{id:string;month:string;status:string;validationMode:string;sourceFilename:string|null;sourceSha256:string|null;sourceSnapshot:Record<string,unknown>;audit:Record<string,unknown>;totals:Record<string,unknown>;frozenHash:string|null;directionSignature:Signature|null};components:Component[]};
const ABSENCE_LABELS:Record<string,string>={cp:"Congé payé",maladie:"Maladie",ald:"Absence longue durée",at:"Accident du travail",absenceInjustifieeAutorisee:"Absence injustifiée / autorisée",autreAutorise:"Autre absence autorisée",annualisationNegative:"Heures moins annualisation"};
const MODE_LABEL:Record<Exclude<ProrationMode,"inherit">,string>={ignore:"Aucun impact",prorate:"Proratisation",suppress:"Prime supprimée"};
function money(v:number|null|undefined){return v==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(v)}
function num(v:number|null|undefined,d=1){return v==null?"—":new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(v)}
function pct(v:number|null|undefined){return v==null?"—":`${num(v*100,1)} %`}
function monthLabel(month:string){const [y,m]=month.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(y,m-1,1));}
function threshold(c:Component,v:number|null|undefined){if(v==null)return"—";return c.population==="productif"?pct(v):num(v,4);}
function signatureLabel(signature:Signature|null,legacy:boolean){if(legacy)return"Non disponible · historique Excel";if(!signature)return"En attente";return `✓ Signé numériquement par ${signature.actorName} · ${new Date(signature.createdAt).toLocaleString("fr-FR")}`;}
function absenceReason(c:Component){const entries=Object.entries(c.absenceReasons??{}).filter(([,v])=>Number(v)>0);return entries.length?entries.map(([key,value])=>`${ABSENCE_LABELS[key]??key} : ${num(Number(value),2)} h`).join(" · "):"Aucun motif d'absence enregistré";}
function period(event:ProrationEventImpact){if(!event.from)return"—";const a=new Date(`${event.from}T12:00:00Z`).toLocaleDateString("fr-FR");const b=new Date(`${event.to}T12:00:00Z`).toLocaleDateString("fr-FR");return a===b?a:`${a} → ${b}`;}
function ruleText(mode:Exclude<ProrationMode,"inherit">,thresholdDays:number,triggered:boolean){if(mode==="ignore")return"Aucun impact";const condition=thresholdDays>0?` si > ${num(thresholdDays,1)} j`:"";return `${MODE_LABEL[mode]}${condition}${triggered?" · appliquée":" · non déclenchée"}`;}
function SourceValue({source,children}:{source:string;children:ReactNode}){return <span className={styles.sourceValue} data-source={`Source · ${source}`} title={`Source : ${source}`}>{children}</span>}

export default function BonusReportPage(){
  const[detail,setDetail]=useState<Detail|null>(null);const[component,setComponent]=useState<Component|null>(null);const[proration,setProration]=useState<EmployeeProration|null>(null);const[prorationContext,setProrationContext]=useState<ProrationContext|null>(null);const[error,setError]=useState("");
  useEffect(()=>{const p=new URLSearchParams(location.search);const workflowId=p.get("workflowId"),employeeKey=p.get("employeeKey");if(!workflowId||!employeeKey){setError("Paramètres du rapport manquants.");return;}void(async()=>{try{const response=await fetch(`/api/monthly-animation?workflowId=${encodeURIComponent(workflowId)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Rapport indisponible.");const d=data as Detail;const c=d.components.find(item=>item.employeeKey===employeeKey);if(!c)throw new Error("Collaborateur hors périmètre ou introuvable.");setDetail(d);setComponent(c);try{const prResponse=await fetch(`/api/monthly-animation/proration?workflowId=${encodeURIComponent(workflowId)}`,{cache:"no-store"});const prData=await prResponse.json();if(prResponse.ok){const context=prData as ProrationContext;setProrationContext(context);setProration(context.components.find(item=>item.employeeKey===employeeKey)??null);}}catch{/* Le rapport historique reste lisible même si le moteur de proratisation est indisponible. */}}catch(e){setError(e instanceof Error?e.message:"Rapport indisponible.");}})();},[]);
  if(error)return <main className={styles.page}><div className={styles.sheet}><div className={styles.error}>{error}</div></div></main>;
  if(!detail||!component)return <main className={styles.page}><div className={styles.sheet}><div className={styles.error}>Chargement du rapport…</div></div></main>;
  const c=component,w=detail.workflow,legacy=w.validationMode==="legacy_excel";const sourceComment=String(c.sourcePayload?.sourceComment??"");
  const individualPaid=proration?.individualAfterEur??c.individualAmountEur;
  const collectivePaid=proration?.collectiveAfterEur??(c.collectiveAmountEur==null?null:(c.collectiveAmountEur??0)*(c.collectiveProration??1));
  const totalPaid=proration?.totalAfterEur??c.totalAmountEur;
  const individualFactor=proration?.individualFactor??1;
  const collectiveFactor=proration?.collectiveFactor??c.collectiveProration;
  const calculationSource=proration?.sourceSummary??"Moteur historique KPI CRVO";
  return <main className={styles.page}><div className={styles.actions}><a href={`/animation-mensuelle/proratisation?workflowId=${encodeURIComponent(w.id)}`}>VOIR LES RÈGLES</a><button onClick={()=>window.print()}>IMPRIMER / ENREGISTRER PDF</button></div><article className={styles.sheet}>
    <header className={styles.header}><div><span>KPI CRVO · ANIMATION VARIABLE</span><h1>Rapport individuel de prime</h1><p><SourceValue source="Workflow mensuel KPI CRVO">{monthLabel(w.month)} · workflow {legacy?"historique figé":w.status==="closed"?"clôturé":"en cours"}</SourceValue></p></div><img src="/crvo-logo.png" alt="CRVO"/></header>
    <div className={styles.content}>
      {legacy&&<div className={styles.banner}><b>Référence historique Excel.</b> Ce rapport restitue les valeurs figées de juillet 2026 sans inventer les données absentes du classeur source.</div>}
      <section className={styles.identity}><div className={styles.cell}><span>Collaborateur</span><strong><SourceValue source="Référentiel collaborateurs Data RH">{c.employeeName}</SourceValue></strong></div><div className={styles.cell}><span>Matricule</span><strong><SourceValue source="Référentiel collaborateurs Data RH">{c.matricule??"—"}</SourceValue></strong></div><div className={styles.cell}><span>Métier</span><strong><SourceValue source="Référentiel collaborateurs / affectation Payplan">{c.jobKey}</SourceValue></strong></div><div className={styles.cell}><span>Organisation</span><strong><SourceValue source="Référentiel collaborateurs Data RH">{c.sectorLabel??"—"} · Équipe {c.teamCode??"—"}</SourceValue></strong></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Performance du mois</h2><i/></div><div className={styles.metrics}><div className={styles.metric}><span>Heures achetées</span><strong><SourceValue source="Data RH · présence mensuelle">{num(c.presenceHours,2)} h</SourceValue></strong></div><div className={styles.metric}><span>Heures vendues</span><strong><SourceValue source="Données de productivité / temps facturés KPI CRVO">{num(c.billedHours,2)} h</SourceValue></strong></div><div className={styles.metric}><span>Rendement</span><strong><SourceValue source="Calcul KPI CRVO · heures vendues / heures achetées">{pct(c.productivity)}</SourceValue></strong></div><div className={styles.metric}><span>Absence</span><strong><SourceValue source="Data RH · événements d'absence du mois">{num(c.absenceHours,2)} h</SourceValue></strong></div><div className={styles.metric}><span>Absentéisme</span><strong><SourceValue source="Calcul KPI CRVO à partir de Data RH">{pct(c.absenceRate)}</SourceValue></strong></div></div><div className={styles.sourceComment}><b>Motif(s) d'absence :</b><br/><SourceValue source="Data RH · ventilation mensuelle des absences">{absenceReason(c)}</SourceValue></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Chaîne de validation</h2><i/></div><div className={styles.tiers}><div className={styles.tier}><span>Palier théorique</span><strong><SourceValue source="Payplan mensuel figé + performance KPI">{c.theoreticalTier==null?"—":`P${c.theoreticalTier}`}</SourceValue></strong></div><div className={styles.tier}><span>Chef d'équipe</span><strong><SourceValue source="Validation numérique du workflow · Chef d'équipe">{c.teamTier==null?"—":`✓ P${c.teamTier}`}</SourceValue></strong></div><div className={styles.tier}><span>Chef de service</span><strong><SourceValue source="Validation numérique du workflow · Chef de service">{c.serviceTier==null?"—":`✓ P${c.serviceTier}`}</SourceValue></strong></div><div className={styles.tier}><span>Palier figé</span><strong><SourceValue source="Workflow de prime · dernier palier validé">{c.finalTier==null?"—":`P${c.finalTier}`}</SourceValue></strong></div></div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Calcul financier</h2><i/></div><div className={styles.money}><div className={styles.metric}><span>Base individuelle</span><strong><SourceValue source="Payplan mensuel figé">{money(c.individualBaseEur)}</SourceValue></strong></div><div className={styles.metric}><span>Prime individuelle après règles RH</span><strong><SourceValue source={calculationSource}>{money(individualPaid)}</SourceValue></strong>{proration&&proration.individualImpactEur!==0&&<small className={styles.delta}>{money(proration.individualImpactEur)} lié aux événements RH</small>}</div><div className={styles.metric}><span>Collectif / sortie usine après règles RH</span><strong><SourceValue source={calculationSource}>{c.collectiveAmountEur==null?(c.collectiveLabel??"—"):money(collectivePaid)}</SourceValue></strong>{proration&&proration.collectiveImpactEur!==0&&<small className={styles.delta}>{money(proration.collectiveImpactEur)} lié aux événements RH</small>}</div><div className={styles.metric}><span>Total du mois</span><strong><SourceValue source={calculationSource}>{money(totalPaid)}</SourceValue></strong>{proration&&proration.totalImpactEur!==0&&<small className={styles.delta}>{money(proration.totalImpactEur)} vs calcul avant règles</small>}</div></div></section>
      {proration&&<section className={styles.section}><div className={styles.sectionTitle}><h2>Événements RH & poids sur la prime</h2><i/></div><div className={styles.prorationSummary}><div><span>Événements</span><strong><SourceValue source="Data RH · événements normalisés du mois">{proration.events.length}</SourceValue></strong></div><div><span>Facteur individuel</span><strong><SourceValue source="Règles de proratisation du workflow">{pct(individualFactor)}</SourceValue></strong></div><div><span>Facteur collectif / sortie usine</span><strong><SourceValue source="Règles de proratisation du workflow">{pct(collectiveFactor)}</SourceValue></strong></div><div><span>Impact total</span><strong><SourceValue source={calculationSource}>{money(proration.totalImpactEur)}</SourceValue></strong></div></div>{proration.events.length===0?<div className={styles.noEvent}>Aucun événement RH ayant une incidence potentielle n’est enregistré pour ce collaborateur sur le mois.</div>:<div className={styles.eventTableWrap}><table className={styles.eventTable}><thead><tr><th>Événement</th><th>Période / durée</th><th>Prime individuelle</th><th>Collectif / sortie usine</th><th>Poids</th></tr></thead><tbody>{proration.events.map(event=><tr key={`${event.reasonCode}-${event.from}-${event.to}`}><td><strong><SourceValue source={`${event.sourceLabel}${event.sourceTimeCodes.length?` · code(s) ${event.sourceTimeCodes.join("/")}`:""}`}>{event.label}</SourceValue></strong><small>{event.sourceTimeCodes.length?event.sourceTimeCodes.join(" / "):event.reasonCode}</small></td><td><SourceValue source="Data RH · dates et durée de l'événement">{period(event)} · {num(event.days,2)} j / {num(event.hours,2)} h</SourceValue></td><td className={event.individualTriggered&&event.individualEffectiveMode!=="ignore"?styles.ruleActive:""}><SourceValue source="Règle individuelle du workflow">{ruleText(event.individualEffectiveMode,event.individualThresholdDays,event.individualTriggered)}</SourceValue></td><td className={event.collectiveTriggered&&event.collectiveEffectiveMode!=="ignore"?styles.ruleActive:""}><SourceValue source="Règle collective / sortie usine du workflow">{ruleText(event.collectiveEffectiveMode,event.collectiveThresholdDays,event.collectiveTriggered)}</SourceValue></td><td><b><SourceValue source="Poids = jours pris en compte / jours ouvrés du workflow">Ind. −{num(event.individualImpactPct*100,1)} % · Coll. −{num(event.collectiveImpactPct*100,1)} %</SourceValue></b></td></tr>)}</tbody></table></div>}<div className={styles.method}><b>Méthode :</b> <SourceValue source={proration.workingDaysSource}>{num(proration.workingDays,2)} jours ouvrés</SourceValue> · <SourceValue source={proration.referenceHoursSource}>{num(proration.referenceHoursPerDay,2)} h/j de référence</SourceValue>. Un seuil « &gt; 2 j » ne déclenche la règle que lorsque la durée cumulée de l’événement dépasse strictement 2 jours.</div></section>}
      <section className={styles.section}><div className={styles.sectionTitle}><h2>Explication & traçabilité</h2><i/></div><div className={styles.trace}><div className={styles.traceRow}><b>Seuils du métier</b><span><SourceValue source="Payplan mensuel figé">{(c.thresholds??[]).map((v,i)=>`P${i+1}: ${threshold(c,v)}`).join(" · ")||"—"}</SourceValue></span></div><div className={styles.traceRow}><b>Coefficient de prime</b><span><SourceValue source="Payplan mensuel figé + palier validé">{pct(c.coefficient)}</SourceValue></span></div><div className={styles.traceRow}><b>Facteur individuel RH</b><span><SourceValue source="Moteur de proratisation par événement">{pct(individualFactor)}</SourceValue></span></div><div className={styles.traceRow}><b>Facteur collectif / sortie usine</b><span><SourceValue source="Moteur de proratisation par événement">{pct(collectiveFactor)}</SourceValue></span></div><div className={styles.traceRow}><b>Prime exceptionnelle</b><span><SourceValue source="Donnée du workflow · saisie managériale tracée">{money(c.exceptionalAmountEur)}</SourceValue></span></div><div className={styles.traceRow}><b>Signature numérique CE</b><span><SourceValue source="Journal de validation du workflow">{signatureLabel(c.teamSignature,legacy)}</SourceValue></span></div><div className={styles.traceRow}><b>Signature numérique CDS</b><span><SourceValue source="Journal de validation du workflow">{signatureLabel(c.serviceSignature,legacy)}</SourceValue></span></div><div className={styles.traceRow}><b>Signature numérique Direction</b><span><SourceValue source="Journal de clôture du workflow">{signatureLabel(w.directionSignature,legacy)}</SourceValue></span></div>{prorationContext&&<div className={styles.traceRow}><b>Règles de proratisation</b><span><SourceValue source={prorationContext.sources?.rules??"Règles mensuelles"}>{prorationContext.rules.length} règles · calcul au {new Date(prorationContext.calculatedAt).toLocaleString("fr-FR")}</SourceValue></span></div>}</div>{sourceComment&&<div className={styles.sourceComment}><b>Commentaire source / management :</b><br/><SourceValue source="Commentaire enregistré dans le workflow">{sourceComment}</SourceValue></div>}</section>
    </div>
  </article></main>;
}
