"use client";

export type ExportVehicle={sector?:string|null;registration?:string|null;workOrder?:string|null;model?:string|null;status?:string|null;ageDays?:number|null;partOrderedDays?:number|null;blockingCause?:string|null};
export type ExportSector={sector?:string|null;stock?:number;over15?:number;over20?:number;avgAge?:number;oldestAge?:number;urgents?:number};
export type ExportPayload={sourceModifiedAt?:string|null;selected:{name:string;title:string;teams:string[];sectors:string[];allAccess:boolean};sectorSummary:ExportSector[];oldestVehicles:ExportVehicle[];store?:{avgOrderLeadDays?:number|null;foldersOver3Days?:number;foldersWithPartsOrder?:number;oldestOrderDays?:number|null;oldest?:ExportVehicle[]}};
const BLUE="#004f9f",CYAN="#009edb",INK="#0a3157",MUTED="#6f8798",PALE="#f3f8fb",LINE="#d6e4ec",RED="#e45d58",YELLOW="#fec82f",TEAL="#47b9b4";
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r=18){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function wrap(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,w:number,line=18,max=2){const words=text.split(/\s+/);let current="",row=0;for(let i=0;i<words.length;i++){const test=current?`${current} ${words[i]}`:words[i];if(current&&ctx.measureText(test).width>w){ctx.fillText(current,x,y+row*line);row++;current=words[i];if(row>=max-1){let rest=[current,...words.slice(i+1)].join(" ");while(rest.length>4&&ctx.measureText(rest+"…").width>w)rest=rest.slice(0,-1);ctx.fillText(rest+"…",x,y+row*line);return;}}else current=test;}if(current&&row<max)ctx.fillText(current,x,y+row*line);}
function concat(parts:Uint8Array[]){const n=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
function jpegPdf(jpeg:Uint8Array,w:number,h:number){const enc=new TextEncoder(),pw=841.89,ph=595.28,stream=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ\n`;const obj:Uint8Array[]=[new Uint8Array(),enc.encode("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"),enc.encode("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"),enc.encode(`3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>\nendobj\n`),concat([enc.encode(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,enc.encode("\nendstream\nendobj\n")]),enc.encode(`5 0 obj\n<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}endstream\nendobj\n`)];const header=enc.encode("%PDF-1.4\n%CRVO\n"),offset=[0];let cur=header.length;for(let i=1;i<obj.length;i++){offset[i]=cur;cur+=obj[i].length;}const xrefStart=cur;let xref=`xref\n0 ${obj.length}\n0000000000 65535 f \n`;for(let i=1;i<obj.length;i++)xref+=`${String(offset[i]).padStart(10,"0")} 00000 n \n`;return new Blob([concat([header,...obj.slice(1),enc.encode(xref),enc.encode(`trailer\n<< /Size ${obj.length} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`)])],{type:"application/pdf"});}
function labelSector(value?:string|null){const m:Record<string,string>={expertise:"Expertise",mecanique:"Mécanique",carrosserie:"Carrosserie",preparation:"Préparation",qualite:"Qualité",dsp:"DSP",jantes:"Jantes",photo:"Photo",controle_technique:"Contrôle technique",parc_travaux:"Parc travaux",sortie_usine:"Sortie usine",chiffrage:"Chiffrage",anomalie:"Anomalie",magasin:"Magasin / MPR"};return m[value??""]??value??"Autre";}
function card(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,accent:string,label:string,value:string,detail:string){rounded(ctx,x,y,w,h);ctx.fillStyle="#fff";ctx.fill();ctx.strokeStyle=LINE;ctx.stroke();ctx.fillStyle=accent;ctx.fillRect(x,y,6,h);ctx.fillStyle=MUTED;ctx.font='800 13px "Exo",Arial';ctx.fillText(label.toUpperCase(),x+22,y+26);ctx.fillStyle=INK;ctx.font='800 italic 31px "Exo",Arial';ctx.fillText(value,x+22,y+62);ctx.fillStyle=MUTED;ctx.font='600 11px "Exo",Arial';wrap(ctx,detail,x+22,y+84,w-44,15,2);}
export async function createAnimationExportPdf(data:ExportPayload){if(document.fonts?.ready)await document.fonts.ready;const c=document.createElement("canvas");c.width=1684;c.height=1191;const ctx=c.getContext("2d");if(!ctx)throw new Error("Moteur PDF indisponible");ctx.fillStyle=PALE;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle=BLUE;ctx.fillRect(0,0,c.width,14);ctx.fillStyle=CYAN;ctx.fillRect(0,14,c.width,5);rounded(ctx,42,40,1600,115,25);ctx.fillStyle="#fff";ctx.fill();ctx.fillStyle=BLUE;ctx.font='800 italic 43px "Exo",Arial';ctx.fillText("SUPPORT D'ANIMATION",70,90);ctx.fillStyle=INK;ctx.font='800 italic 24px "Exo",Arial';ctx.fillText(data.selected.name,70,125);ctx.fillStyle=MUTED;ctx.font='600 15px "Exo",Arial';ctx.fillText(`${data.selected.title} · ${data.selected.teams.includes("*")?"Toutes équipes":data.selected.teams.map(t=>"Équipe "+t).join(" / ")}`,480,124);ctx.textAlign="right";ctx.fillText(`Source ${data.sourceModifiedAt?new Date(data.sourceModifiedAt).toLocaleString("fr-FR"):"—"}`,1605,91);ctx.textAlign="left";
const sectors=(data.sectorSummary??[]).slice(0,4);const gap=16,w=(1600-gap*3)/4;sectors.forEach((s,i)=>card(ctx,42+i*(w+gap),177,w,126,i===0?CYAN:i===1?BLUE:i===2?YELLOW:RED,labelSector(s.sector),`${s.stock??0} dossiers`,`${s.over20??0} >20j · âge moy. ${s.avgAge??0}j · plus vieux ${s.oldestAge??0}j`));
rounded(ctx,42,326,1000,810,20);ctx.fillStyle="#fff";ctx.fill();ctx.strokeStyle=LINE;ctx.stroke();ctx.fillStyle=BLUE;ctx.font='800 italic 25px "Exo",Arial';ctx.fillText("10 PLUS VIEUX DOSSIERS DU PÉRIMÈTRE",68,368);ctx.fillStyle=MUTED;ctx.font='600 12px "Exo",Arial';ctx.fillText("Priorité FIFO · tri par ancienneté usine",68,393);const rows=(data.oldestVehicles??[]).slice(0,10);rows.forEach((v,i)=>{const y=425+i*66;ctx.fillStyle=i<3?"#fdf5f4":"#f8fbfd";rounded(ctx,65,y,952,55,10);ctx.fill();ctx.fillStyle=i<3?RED:BLUE;ctx.font='800 15px "Exo",Arial';ctx.fillText(String(i+1).padStart(2,"0"),82,y+22);ctx.fillStyle=INK;ctx.font='800 13px "Exo",Arial';ctx.fillText(`${v.registration??"—"} · OR ${v.workOrder??"—"}`,125,y+21);ctx.fillStyle=MUTED;ctx.font='600 10px "Exo",Arial';wrap(ctx,`${labelSector(v.sector)} · ${v.status??"—"} · ${v.model??""}`,125,y+40,690,13,1);ctx.textAlign="right";ctx.fillStyle=i<3?RED:INK;ctx.font='800 italic 18px "Exo",Arial';ctx.fillText(`J+${Math.round(Number(v.ageDays??0))}`,985,y+31);ctx.textAlign="left";});if(!rows.length){ctx.fillStyle=MUTED;ctx.font='600 14px "Exo",Arial';ctx.fillText("Aucun dossier dans le périmètre sélectionné.",68,445);}
rounded(ctx,1060,326,582,810,20);ctx.fillStyle="#fff";ctx.fill();ctx.strokeStyle=LINE;ctx.stroke();ctx.fillStyle=BLUE;ctx.font='800 italic 25px "Exo",Arial';ctx.fillText("FOCUS MAGASIN / MPR",1088,368);const st=data.store??{};card(ctx,1088,405,526,115,TEAL,"Lead time commande",`${Number(st.avgOrderLeadDays??0).toFixed(1)} j","Moyenne des dossiers avec commande pièce");card(ctx,1088,536,526,115,YELLOW,"Commandes > 3 jours",`${st.foldersOver3Days??0}","Dossiers avec pièces commandées depuis plus de 3 jours");
ctx.fillStyle=INK;ctx.font='800 italic 20px "Exo",Arial';ctx.fillText("PLUS VIEUX DOSSIERS PIÈCES",1088,695);(st.oldest??[]).slice(0,6).forEach((v,i)=>{const y=720+i*59;ctx.fillStyle="#f8fbfd";rounded(ctx,1088,y,526,48,9);ctx.fill();ctx.fillStyle=INK;ctx.font='800 11px "Exo",Arial';ctx.fillText(`${v.registration??"—"} · OR ${v.workOrder??"—"}`,1102,y+19);ctx.fillStyle=MUTED;ctx.font='600 9px "Exo",Arial';ctx.fillText(v.status??"—",1102,y+36);ctx.textAlign="right";ctx.fillStyle=Number(v.partOrderedDays??0)>10?RED:BLUE;ctx.font='800 italic 15px "Exo",Arial';ctx.fillText(`${Math.round(Number(v.partOrderedDays??0))} j`,1597,y+27);ctx.textAlign="left";});ctx.fillStyle=MUTED;ctx.font='600 10px "Exo",Arial';wrap(ctx,"Note : la source FTP actuelle est au niveau dossier/véhicule. Le KPI mesure donc les dossiers avec pièces commandées, pas le nombre physique de références pièces.",1088,1092,510,14,3);
const url=c.toDataURL("image/jpeg",.93),bytes=atob(url.split(",")[1]),arr=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)arr[i]=bytes.charCodeAt(i);return jpegPdf(arr,c.width,c.height);}
