"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import styles from "./expertise-mobile.module.css";
import { EXPERTISE_FORFAITS, GRADE_RULES, REPAIR_METHODS, type ExpertiseForfait, type GradeKey } from "../developpement/expertise/expertise-data";

type Vehicle = {
  registration:string|null;workOrder:string|null;client:string|null;vin:string|null;model:string|null;mileage:number;status:string;statusAgeDays:number;factoryAgeDays:number;
  location:string|null;site:string|null;manufacturer:string|null;folderNumber:string|null;sourceType:string;processProfile:"EFF"|"BMW"|"AUTRE"|"EXCLU";inFactory:boolean;
};
type Payload={connected:boolean;sourceModifiedAt:string|null;vehicles:Vehicle[];error?:string};
type FileRef={id:string;name:string;type:string;createdAt:string};
type GeneralSection={maintenanceHistory:""|"OUI"|"NON"|"INCONNU";historyComment:string;generalComment:string;exteriorPhotos:FileRef[];interiorPhotos:FileRef[];maintenanceDocuments:FileRef[];otherDocuments:FileRef[]};
type Tyre={position:"AVG"|"AVD"|"ARG"|"ARD";brand:string;dimension:string;treadMm:string;status:""|"OK"|"SURVEILLER"|"REMPLACER";runflat:boolean};
type MechanicsSection={category:""|"A"|"B"|"C";serviceDue:""|"OUI"|"NON";serviceForfaitId:string;tyres:Tyre[];tyreForfaitId:string;brakeFront:""|"OK"|"PLAQUETTES"|"DISQUES_PLAQUETTES";brakeRear:""|"OK"|"PLAQUETTES"|"DISQUES_PLAQUETTES";brakeFrontForfaitId:string;brakeRearForfaitId:string;shockFront:""|"OK"|"FUITE"|"JEU"|"REMPLACER";shockRear:""|"OK"|"FUITE"|"JEU"|"REMPLACER";shockManualHt:string;notes:string};
type Damage={id:string;zone:string;zoneLevel:""|"HAUTE"|"BASSE";type:string;description:string;sizeCm:string;method:string;paintFinish:""|"AVEC_DIFF"|"SANS_DIFF";forfaitId:string;manualLabel:string;manualHt:string;photos:FileRef[]};
type ExpertiseRecord={vehicleKey:string;grade:GradeKey|null;general:GeneralSection;mechanics:MechanicsSection;damages:Damage[];status:"draft"|"completed";updatedAt:string};
type ExpertiseStore=Record<string,ExpertiseRecord>;
type ElementFamily="wheel"|"glass"|"mirror"|"bumper"|"roof"|"simple"|"complex"|"interior"|"other";

type BodyPart={zone:string;label:string;className:string};

const STORE_KEY="crvo-expertise-sandbox-v1";
const PHOTO_DB="crvo-expertise-dev-photos-v1";
const PHOTO_STORE="photos";
const TYRE_POSITIONS:Tyre["position"][]=["AVG","AVD","ARG","ARD"];
const METHOD_LABELS:Record<string,string>=Object.fromEntries([...REPAIR_METHODS.map(item=>[item.id,item.label]),["LUSTRAGE","Lustrage / correction légère"]]);
const BODY_PARTS:BodyPart[]=[
  {zone:"Capot",label:"Capot",className:styles.hood},{zone:"Pavillon",label:"Pavillon",className:styles.roof},{zone:"Hayon / coffre",label:"Hayon",className:styles.tailgate},
  {zone:"Bouclier AV",label:"Bouclier AV",className:styles.frontBumper},{zone:"Bouclier AR",label:"Bouclier AR",className:styles.rearBumper},
  {zone:"Porte AVG",label:"Porte AVG",className:styles.leftFrontDoor},{zone:"Porte ARG",label:"Porte ARG",className:styles.leftRearDoor},
  {zone:"Porte AVD",label:"Porte AVD",className:styles.rightFrontDoor},{zone:"Porte ARD",label:"Porte ARD",className:styles.rightRearDoor},
  {zone:"Aile AVG",label:"Aile AVG",className:styles.leftFrontWing},{zone:"Aile ARG",label:"Aile ARG",className:styles.leftRearWing},
  {zone:"Aile AVD",label:"Aile AVD",className:styles.rightFrontWing},{zone:"Aile ARD",label:"Aile ARD",className:styles.rightRearWing},
  {zone:"Pare-brise",label:"Pare-brise",className:styles.windshield},{zone:"Rétroviseur AVG",label:"Rétro G",className:styles.leftMirror},{zone:"Rétroviseur AVD",label:"Rétro D",className:styles.rightMirror},
];

function vehicleKey(v:Vehicle){return String(v.vin||v.registration||v.workOrder||`${v.client}-${v.model}`);}
function money(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(value);}
function emptyTyres():Tyre[]{return TYRE_POSITIONS.map(position=>({position,brand:"",dimension:"",treadMm:"",status:"",runflat:false}));}
function emptyRecord(key:string):ExpertiseRecord{return{vehicleKey:key,grade:null,general:{maintenanceHistory:"",historyComment:"",generalComment:"",exteriorPhotos:[],interiorPhotos:[],maintenanceDocuments:[],otherDocuments:[]},mechanics:{category:"",serviceDue:"",serviceForfaitId:"",tyres:emptyTyres(),tyreForfaitId:"",brakeFront:"",brakeRear:"",brakeFrontForfaitId:"",brakeRearForfaitId:"",shockFront:"",shockRear:"",shockManualHt:"",notes:""},damages:[],status:"draft",updatedAt:new Date().toISOString()};}
function normalizeRecord(value:Partial<ExpertiseRecord>|undefined,key:string):ExpertiseRecord{const base=emptyRecord(key);if(!value)return base;return{...base,...value,vehicleKey:key,general:{...base.general,...(value.general||{})},mechanics:{...base.mechanics,...(value.mechanics||{}),tyres:Array.isArray(value.mechanics?.tyres)&&value.mechanics!.tyres.length?value.mechanics!.tyres:base.mechanics.tyres},damages:Array.isArray(value.damages)?value.damages:[]};}
function familyForZone(zone:string):ElementFamily{if(/^Jante/i.test(zone))return"wheel";if(/Pare-brise/i.test(zone))return"glass";if(/Rétroviseur/i.test(zone))return"mirror";if(/Bouclier/i.test(zone))return"bumper";if(/Pavillon/i.test(zone))return"roof";if(/Capot|Aile AR/i.test(zone))return"complex";if(/Aile AV|Porte|Hayon/i.test(zone))return"simple";if(/Intérieur/i.test(zone))return"interior";return"other";}
function damageTypesForZone(zone:string){const f=familyForZone(zone);if(f==="wheel")return["Rayure / frottement","Coup / choc","Déformation / voile","Vernis / peinture endommagé"];if(f==="glass")return["Impact","Fissure","Multi-impact","Rayure vitrage"];if(f==="mirror")return["Rayure / griffe","Coup / choc","Coquille cassée","Glace endommagée"];if(f==="bumper")return["Rayure / griffe","Coup / enfoncement","Bosse","Fissure","Déchirure / percement"];return["Rayure / griffe","Coup / enfoncement","Bosse","Impact / gravillonnage","Déformation","Éclat peinture"]};
function methodsForZone(zone:string){const f=familyForZone(zone);if(f==="wheel")return["JANTE","REMPLACEMENT","SURVEILLANCE","HORS_FORFAIT"];if(f==="glass")return["PARE_BRISE","REMPLACEMENT","SURVEILLANCE","HORS_FORFAIT"];if(f==="mirror")return["LUSTRAGE","PEINTURE","PLUME","REMPLACEMENT","SURVEILLANCE","HORS_FORFAIT"];return["LUSTRAGE","DSP","PEINTURE","PLUME","REMPLACEMENT","SURVEILLANCE","HORS_FORFAIT"]};
function defaultMethodForZone(zone:string){const f=familyForZone(zone);return f==="wheel"?"JANTE":f==="glass"?"PARE_BRISE":"";}
function newDamage(zone:string):Damage{return{id:crypto.randomUUID(),zone,zoneLevel:"",type:"",description:"",sizeCm:"",method:defaultMethodForZone(zone),paintFinish:"",forfaitId:"",manualLabel:"",manualHt:"",photos:[]};}
function forfaitById(id:string){return EXPERTISE_FORFAITS.find(item=>item.id===id)||null;}
function lineHt(d:Damage){const f=forfaitById(d.forfaitId);if(f)return f.ht;const n=Number(String(d.manualHt).replace(",","."));return Number.isFinite(n)?Math.max(0,n):0;}
function lineTtc(d:Damage){const f=forfaitById(d.forfaitId);return f?f.ttc:lineHt(d)*1.2;}
function forfaitsForDamage(d:Damage):ExpertiseForfait[]{if(d.method==="JANTE")return EXPERTISE_FORFAITS.filter(f=>f.section==="JANTE");if(d.method==="PARE_BRISE")return EXPERTISE_FORFAITS.filter(f=>f.id==="forfait-50");if(d.method==="DSP")return EXPERTISE_FORFAITS.filter(f=>f.section.trim()==="DSP");if(d.method==="PLUME")return EXPERTISE_FORFAITS.filter(f=>f.id==="forfait-59");if(d.method==="PEINTURE")return EXPERTISE_FORFAITS.filter(f=>f.section==="CARROSSERIE"&&/peinture|élément|element|bouclier|pavillon|rétro/i.test(f.label));return[];}
function mechanicForfaits(category:MechanicsSection["category"]){if(!category)return[];return EXPERTISE_FORFAITS.filter(f=>f.section==="MECANIQUE"&&f.category?.startsWith(`CATÉGORIE ${category}`));}
function photoDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(PHOTO_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(PHOTO_STORE))request.result.createObjectStore(PHOTO_STORE);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function putFile(id:string,file:File){const db=await photoDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,"readwrite");tx.objectStore(PHOTO_STORE).put(file,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}

export default function ExpertiseMobilePage(){
  const [payload,setPayload]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[selectedKey,setSelectedKey]=useState<string|null>(null);const[records,setRecords]=useState<ExpertiseStore>({});const[ready,setReady]=useState(false);const[section,setSection]=useState<"identity"|"general"|"mechanics"|"body"|"summary">("identity");
  async function load(){setLoading(true);try{const r=await fetch(`/api/development/expertise-mobile?_=${Date.now()}`,{cache:"no-store"});const data=await r.json() as Payload;if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);setPayload(data);setError("");}catch(e){setError(e instanceof Error?e.message:"Reflet FTP indisponible");}finally{setLoading(false);}}
  useEffect(()=>{void load();try{const raw=localStorage.getItem(STORE_KEY);if(raw){const parsed=JSON.parse(raw) as Record<string,Partial<ExpertiseRecord>>;setRecords(Object.fromEntries(Object.entries(parsed).map(([k,v])=>[k,normalizeRecord(v,k)])));}}catch{}setReady(true);if("serviceWorker"in navigator)navigator.serviceWorker.register("/expertise-sw.js").catch(()=>undefined);},[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORE_KEY,JSON.stringify(records));},[records,ready]);
  const vehicles=payload?.vehicles||[];const filtered=useMemo(()=>vehicles.filter(v=>{const hay=`${v.registration||""} ${v.workOrder||""} ${v.vin||""} ${v.client||""} ${v.model||""} ${v.folderNumber||""}`.toLowerCase();return !query.trim()||hay.includes(query.trim().toLowerCase());}),[vehicles,query]);
  const selected=useMemo(()=>vehicles.find(v=>vehicleKey(v)===selectedKey)||null,[vehicles,selectedKey]);const record=selectedKey?normalizeRecord(records[selectedKey],selectedKey):null;
  function mutate(fn:(r:ExpertiseRecord)=>ExpertiseRecord){if(!selectedKey)return;setRecords(current=>{const base=normalizeRecord(current[selectedKey],selectedKey);return{...current,[selectedKey]:{...fn(base),updatedAt:new Date().toISOString()}};});}
  function choose(v:Vehicle){const k=vehicleKey(v);setSelectedKey(k);setRecords(c=>c[k]?c:{...c,[k]:emptyRecord(k)});setSection("identity");window.scrollTo({top:0,behavior:"smooth"});}
  function addDamage(zone:string){if(!record)return;const d=newDamage(zone);mutate(r=>({...r,damages:[...r.damages,d]}));setTimeout(()=>document.getElementById(`mobile-damage-${d.id}`)?.scrollIntoView({behavior:"smooth",block:"center"}),80);}
  function updateDamage(id:string,patch:Partial<Damage>){mutate(r=>({...r,damages:r.damages.map(d=>d.id===id?{...d,...patch,...(patch.zone!==undefined?{type:"",method:defaultMethodForZone(String(patch.zone)),forfaitId:""}:{}),...(patch.method!==undefined?{forfaitId:""}:{})}:d)}));}
  async function addPhotos(bucket:"exteriorPhotos"|"interiorPhotos",files:FileList|null){if(!files?.length)return;const refs:FileRef[]=[];for(const file of Array.from(files).filter(f=>f.type.startsWith("image/")).slice(0,12)){const id=crypto.randomUUID();try{await putFile(id,file);refs.push({id,name:file.name,type:file.type,createdAt:new Date().toISOString()});}catch{}}if(refs.length)mutate(r=>({...r,general:{...r.general,[bucket]:[...r.general[bucket],...refs]}}));}
  async function addDamagePhoto(id:string,files:FileList|null){if(!files?.length)return;const file=Array.from(files).find(f=>f.type.startsWith("image/"));if(!file)return;const ref={id:crypto.randomUUID(),name:file.name,type:file.type,createdAt:new Date().toISOString()};try{await putFile(ref.id,file);mutate(r=>({...r,damages:r.damages.map(d=>d.id===id?{...d,photos:[...d.photos,ref]}:d)}));}catch{}}
  const mechForfaits=record?mechanicForfaits(record.mechanics.category):[];const mechanicsHt=record?[record.mechanics.serviceForfaitId,record.mechanics.tyreForfaitId,record.mechanics.brakeFrontForfaitId,record.mechanics.brakeRearForfaitId].reduce((s,id)=>s+(forfaitById(id)?.ht||0),0):0;const bodyHt=record?record.damages.reduce((s,d)=>s+lineHt(d),0):0;const totalHt=mechanicsHt+bodyHt;

  if(!selected)return <main className={styles.page}><header className={styles.mobileHeader}><img src="/crvo-logo.png" alt="CRVO"/><div><span>EXPERTISE MOBILE · PWA</span><h1>Dossiers à expertiser</h1></div><button onClick={()=>void load()}>{loading?"…":"↻"}</button></header><section className={styles.searchPanel}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Immat, OR, VIN, client, dossier MPF…"/><small>{filtered.length} dossier{filtered.length>1?"s":""} · miroir FTP/MPF</small></section>{error&&<div className={styles.error}>{error}</div>}<section className={styles.list}>{filtered.map(v=><button className={styles.card} key={vehicleKey(v)} onClick={()=>choose(v)}><div><strong>{v.registration||"Sans immat"}</strong><span>{v.manufacturer||"—"} {v.model||""}</span><small>{v.client||"Client non renseigné"} · OR {v.workOrder||"—"} · MPF {v.folderNumber||"—"}</small></div><b>›</b></button>)}</section></main>;

  return <main className={styles.page}><header className={styles.dossierHeader}><button onClick={()=>setSelectedKey(null)}>‹</button><div><span>DOSSIER MPF {selected.folderNumber||"—"}</span><strong>{selected.registration||"Sans immat"} · {selected.manufacturer||""} {selected.model||""}</strong><small>{selected.client||"Client non renseigné"}</small></div><button onClick={()=>void load()}>↻</button></header>
    <nav className={styles.tabs}>{[["identity","Identité"],["general","Général"],["mechanics","Méca"],["body","Carrosserie"],["summary","Synthèse"]].map(([key,label])=><button key={key} className={section===key?styles.active:""} onClick={()=>setSection(key as typeof section)}>{label}</button>)}</nav>

    {section==="identity"&&<section className={styles.section}><div className={styles.sectionTitle}><span>00 · PRÉAMBULE</span><h2>Identité client & véhicule</h2><p>Données lues depuis le dossier MPF / miroir FTP, sans ressaisie.</p></div><div className={styles.identityHero}><div><span>CLIENT / DONNEUR D'ORDRE</span><strong>{selected.client||"Non renseigné"}</strong><small>Source MPF</small></div><div><span>VÉHICULE</span><strong>{selected.manufacturer||"Marque —"} {selected.model||""}</strong><small>{selected.registration||"Immat —"}</small></div></div><div className={styles.identityGrid}><Info label="Dossier MPF" value={selected.folderNumber}/><Info label="Ordre de réparation" value={selected.workOrder}/><Info label="VIN" value={selected.vin}/><Info label="Kilométrage" value={`${Math.round(selected.mileage).toLocaleString("fr-FR")} km`}/><Info label="Site" value={selected.site}/><Info label="Position" value={selected.location}/><Info label="Statut MPF" value={selected.status}/><Info label="Ancienneté usine" value={`J+${Math.round(selected.factoryAgeDays)}`}/></div><button className={styles.primary} onClick={()=>setSection("general")}>COMMENCER L'EXPERTISE</button></section>}

    {section==="general"&&record&&<section className={styles.section}><div className={styles.sectionTitle}><span>01 · ASPECT GÉNÉRAL</span><h2>Contrôle initial</h2></div><label><span>Grade véhicule</span><select value={record.grade||""} onChange={e=>mutate(r=>({...r,grade:(e.target.value||null) as GradeKey|null}))}><option value="">À définir</option>{Object.entries(GRADE_RULES).map(([k,v])=><option value={k} key={k}>{v.label}</option>)}</select></label><label><span>Historique entretien disponible</span><select value={record.general.maintenanceHistory} onChange={e=>mutate(r=>({...r,general:{...r.general,maintenanceHistory:e.target.value as GeneralSection["maintenanceHistory"]}}))}><option value="">À contrôler</option><option>OUI</option><option>NON</option><option>INCONNU</option></select></label><label><span>Historique / commentaire</span><textarea value={record.general.historyComment} onChange={e=>mutate(r=>({...r,general:{...r.general,historyComment:e.target.value}}))}/></label><div className={styles.photoGrid}><Capture title="Photos extérieur" count={record.general.exteriorPhotos.length} onFiles={f=>void addPhotos("exteriorPhotos",f)}/><Capture title="Photos intérieur" count={record.general.interiorPhotos.length} onFiles={f=>void addPhotos("interiorPhotos",f)}/></div><button className={styles.primary} onClick={()=>setSection("mechanics")}>CONTINUER · MÉCANIQUE</button></section>}

    {section==="mechanics"&&record&&<section className={styles.section}><div className={styles.sectionTitle}><span>02 · MÉCANIQUE</span><h2>Contrôles & chiffrage</h2></div><label><span>Catégorie tarifaire</span><select value={record.mechanics.category} onChange={e=>mutate(r=>({...r,mechanics:{...r.mechanics,category:e.target.value as MechanicsSection["category"],serviceForfaitId:""}}))}><option value="">À définir</option><option value="A">Catégorie A</option><option value="B">Catégorie B</option><option value="C">Catégorie C</option></select></label><label><span>Entretien sous 6 mois / 10 000 km</span><select value={record.mechanics.serviceDue} onChange={e=>mutate(r=>({...r,mechanics:{...r.mechanics,serviceDue:e.target.value as MechanicsSection["serviceDue"]}}))}><option value="">À contrôler</option><option>OUI</option><option>NON</option></select></label><label><span>Forfait entretien</span><select value={record.mechanics.serviceForfaitId} onChange={e=>mutate(r=>({...r,mechanics:{...r.mechanics,serviceForfaitId:e.target.value}}))}><option value="">Aucun</option>{mechForfaits.filter(f=>/Révision/i.test(f.label)).map(f=><option key={f.id} value={f.id}>{f.label} · {money(f.ht)} HT</option>)}</select></label><div className={styles.tyres}>{record.mechanics.tyres.map(t=><article key={t.position}><strong>{t.position}</strong><input placeholder="Usure mm" inputMode="decimal" value={t.treadMm} onChange={e=>mutate(r=>({...r,mechanics:{...r.mechanics,tyres:r.mechanics.tyres.map(x=>x.position===t.position?{...x,treadMm:e.target.value}:x)}}))}/><select value={t.status} onChange={e=>mutate(r=>({...r,mechanics:{...r.mechanics,tyres:r.mechanics.tyres.map(x=>x.position===t.position?{...x,status:e.target.value as Tyre["status"]}:x)}}))}><option value="">État</option><option>OK</option><option>SURVEILLER</option><option>REMPLACER</option></select></article>)}</div><label><span>Notes mécanique</span><textarea value={record.mechanics.notes} onChange={e=>mutate(r=>({...r,mechanics:{...r.mechanics,notes:e.target.value}}))}/></label><button className={styles.primary} onClick={()=>setSection("body")}>CONTINUER · CARROSSERIE 360°</button></section>}

    {section==="body"&&record&&<section className={styles.section}><div className={styles.sectionTitle}><span>03 · CARROSSERIE</span><h2>Vue éclatée 3D · 360°</h2><p>Glissez horizontalement pour tourner le véhicule. Touchez un élément de carrosserie pour créer le dommage.</p></div><ExplodedBody3D damageZones={record.damages.map(d=>d.zone)} onSelect={addDamage}/><button className={styles.secondary} onClick={()=>addDamage("")}>+ DOMMAGE LIBRE</button><div className={styles.damageList}>{record.damages.map((d,index)=>{const forfaits=forfaitsForDamage(d);return <article id={`mobile-damage-${d.id}`} className={styles.damage} key={d.id}><header><div><span>DOMMAGE #{index+1}</span><strong>{d.zone||"Élément à préciser"}</strong></div><button onClick={()=>mutate(r=>({...r,damages:r.damages.filter(x=>x.id!==d.id)}))}>×</button></header><label><span>Élément</span><input value={d.zone} onChange={e=>updateDamage(d.id,{zone:e.target.value})}/></label><label><span>Type de dommage</span><select value={d.type} onChange={e=>updateDamage(d.id,{type:e.target.value})}><option value="">Sélectionner</option>{damageTypesForZone(d.zone).map(x=><option key={x}>{x}</option>)}</select></label><label><span>Méthode</span><select value={d.method} onChange={e=>updateDamage(d.id,{method:e.target.value})}><option value="">Sélectionner</option>{methodsForZone(d.zone).map(x=><option value={x} key={x}>{METHOD_LABELS[x]||x}</option>)}</select></label><label><span>Forfait</span><select value={d.forfaitId} onChange={e=>updateDamage(d.id,{forfaitId:e.target.value})}><option value="">{forfaits.length?"Sélectionner":"Chiffrage manuel"}</option>{forfaits.map(f=><option value={f.id} key={f.id}>{f.label} · {money(f.ht)} HT</option>)}</select></label>{!d.forfaitId&&<label><span>Montant manuel HT</span><input inputMode="decimal" value={d.manualHt} onChange={e=>updateDamage(d.id,{manualHt:e.target.value})}/></label>}<label><span>Description / décision expert</span><textarea value={d.description} onChange={e=>updateDamage(d.id,{description:e.target.value})}/></label><Capture title="Photo dommage" count={d.photos.length} onFiles={f=>void addDamagePhoto(d.id,f)}/><div className={styles.price}>{money(lineHt(d))} HT · {money(lineTtc(d))} TTC</div></article>})}</div><button className={styles.primary} onClick={()=>setSection("summary")}>CONTINUER · SYNTHÈSE</button></section>}

    {section==="summary"&&record&&<section className={styles.section}><div className={styles.sectionTitle}><span>04 · SYNTHÈSE</span><h2>Validation expertise</h2></div><div className={styles.summary}><article><span>Client</span><strong>{selected.client||"—"}</strong></article><article><span>Dossier MPF</span><strong>{selected.folderNumber||"—"}</strong></article><article><span>Dommages</span><strong>{record.damages.length}</strong></article><article><span>Total HT</span><strong>{money(totalHt)}</strong></article></div><label><span>Conclusion générale expert</span><textarea value={record.general.generalComment} onChange={e=>mutate(r=>({...r,general:{...r.general,generalComment:e.target.value}}))}/></label><button className={`${styles.primary} ${record.status==="completed"?styles.done:""}`} onClick={()=>mutate(r=>({...r,status:r.status==="completed"?"draft":"completed"}))}>{record.status==="completed"?"EXPERTISE VALIDÉE DEV ✓":"VALIDER L'EXPERTISE DEV"}</button><small className={styles.sandboxNote}>SAS DEV : la saisie reste locale à cet appareil. Aucune écriture MPF / Fleetback n'est effectuée.</small></section>}
  </main>;
}

function Info({label,value}:{label:string;value:string|null|undefined}){return <article className={styles.info}><span>{label}</span><strong>{value||"—"}</strong></article>}
function Capture({title,count,onFiles}:{title:string;count:number;onFiles:(files:FileList|null)=>void}){return <label className={styles.capture}><strong>{title}</strong><span>{count} fichier{count>1?"s":""}</span><b>OUVRIR L'APPAREIL PHOTO</b><input type="file" accept="image/*" capture="environment" multiple onChange={e=>{onFiles(e.target.files);e.currentTarget.value="";}}/></label>}

function ExplodedBody3D({damageZones,onSelect}:{damageZones:string[];onSelect:(zone:string)=>void}){
  const[yaw,setYaw]=useState(-28);const[pitch,setPitch]=useState(-12);const drag=useRef<{x:number;y:number;yaw:number;pitch:number;moved:boolean}|null>(null);const damaged=new Set(damageZones);
  function down(e:React.PointerEvent<HTMLDivElement>){if((e.target as HTMLElement).closest("button"))return;drag.current={x:e.clientX,y:e.clientY,yaw,pitch,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}
  function move(e:React.PointerEvent<HTMLDivElement>){const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>4)d.moved=true;setYaw(d.yaw+dx*.55);setPitch(Math.max(-35,Math.min(18,d.pitch-dy*.22)));}
  function up(e:React.PointerEvent<HTMLDivElement>){drag.current=null;try{e.currentTarget.releasePointerCapture(e.pointerId);}catch{}}
  return <div className={styles.viewer}><div className={styles.viewerTop}><div><strong>CARROSSERIE ÉCLATÉE</strong><span>Rotation tactile 360°</span></div><button onClick={()=>{setYaw(-28);setPitch(-12)}}>RECENTRER</button></div><div className={styles.stage} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><div className={styles.floor}/><div className={styles.scene} style={{transform:`rotateX(${pitch}deg) rotateY(${yaw}deg)`}}><div className={styles.chassis}><i className={styles.cabin}/><i className={styles.frameFront}/><i className={styles.frameRear}/></div>{BODY_PARTS.map(part=><button type="button" key={part.zone} aria-label={`Sélectionner ${part.zone}`} onClick={()=>onSelect(part.zone)} className={`${styles.bodyPart} ${part.className} ${damaged.has(part.zone)?styles.damaged:""}`}><span>{part.label}</span></button>)}</div><div className={styles.rotateHint}>↔ GLISSER POUR TOURNER</div></div><div className={styles.viewerControls}><button onClick={()=>setYaw(v=>v-45)}>↶ 45°</button><button onClick={()=>setYaw(v=>v+45)}>45° ↷</button></div></div>;
}
