"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "../payplan/payplan.module.css";

type Workflow={id:string;month:string;status:string;validationMode:string};
type Rule={id:string;population:string;jobKey:string;label:string;ruleType:string;thresholds:(number|null)[];coefficients:number[];baseAmountEur:number|null;settings:Record<string,unknown>};
type Payplan={canManage:boolean;rules:Rule[]};
type Input={id:string;scopeType:string;scopeKey:string;inputKey:string;numericValue:number|null;textValue:string|null;comment:string|null};
type Component={id:string;employeeKey:string|null;employeeName:string;matricule:string|null;population:string;jobKey:string;sectorKey:string|null;teamCode:string|null;theoreticalTier:number|null};
type Detail={actor:{canManage:boolean};workflow:{id:string;month:string;status:string};manualInputs:Input[];components:Component[]};
type Suggestion={jobKey:string;inputKey:string;scopeType?:string;scopeKey?:string;value:number|null;label:string;aggregation:string;source:string;coverageDays:number;lastDate:string|null;confidence:"complete"|"provisional"|"unavailable"};
type Unsupported={jobKey:string;reason:string};
type Suggestions={suggestions:Suggestion[];unsupported:Unsupported[]};

const COMMON_FIELDS=[
  ["working_days","Jours ouvrés"],
  ["small_supplies","Petites fournitures"],
  ["quality_claim_rate","Taux réclamation qualité (0,0135 = 1,35 %)"],
  ["collective_amount_eur","Montant collectif sortie usine €"]
] as const;
const CE_FIELDS=[
  ["safety_cleanliness","Audit sécurité / propreté + EPI","number"],
  ["team_p3","Équipe au palier 3","yesno"],
  ["lead_time","Lead Time","number"],
  ["quality_claim_rate","Qualité · taux réclamation","number"],
  ["at_count","Sécurité · nombre d'AT","number"]
] as const;

function monthLabel(month:string){const [y,m]=month.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(y,m-1,1));}
function num(v:number|null|undefined,d=2){return v==null?"—":new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(v);}
function criterion2(rule:Rule){return Array.isArray(rule.settings?.criterion_2)?rule.settings.criterion_2 as number[]:[];}
function label1(rule:Rule){return String(rule.settings?.criterion_1_label??"Critère 1");}
function label2(rule:Rule){return String(rule.settings?.criterion_2_label??"Critère 2");}
function direction(rule:Rule){return String(rule.settings?.direction??"lte")==="gte"?"gte":"lte";}
function inputEntry(inputs:Input[],scopeType:string,scopeKey:string,inputKey:string){return inputs.find(i=>i.scopeType===scopeType&&i.scopeKey===scopeKey&&i.inputKey===inputKey);}
function numeric(inputs:Input[],scopeType:string,scopeKey:string,inputKey:string,fallbackGlobal=false):number|null{const own=inputEntry(inputs,scopeType,scopeKey,inputKey)?.numericValue;if(own!=null)return own;return fallbackGlobal?(inputEntry(inputs,"global","*",inputKey)?.numericValue??null):null;}
function text(inputs:Input[],scopeType:string,scopeKey:string,inputKey:string,fallbackGlobal=false):string|null{const own=inputEntry(inputs,scopeType,scopeKey,inputKey)?.textValue;if(own)return own;return fallbackGlobal?(inputEntry(inputs,"global","*",inputKey)?.textValue??null):null;}
function proposedTier(rule:Rule,v1:number|null,v2:number|null){if(Boolean(rule.settings?.manual_tier))return v1==null?null:Math.max(0,Math.min(5,Math.round(v1)));if(v1==null)return null;const c2=criterion2(rule);if(c2.length&&v2==null)return null;let passed=0;rule.thresholds.forEach((t,i)=>{if(t==null)return;const one=direction(rule)==="gte"?v1>=t:v1<=t;const two=!c2.length||(direction(rule)==="gte"?Number(v2)>=c2[i]:Number(v2)<=c2[i]);if(one&&two)passed++;});return passed;}
function sourceClass(confidence:Suggestion["confidence"]){return confidence==="complete"?styles.sourceBadge:`${styles.sourceBadge} ${styles.provisional}`;}

export default function MonthlyResultsPage(){
  const [workflows,setWorkflows]=useState<Workflow[]>([]);const [workflowId,setWorkflowId]=useState("");const [detail,setDetail]=useState<Detail|null>(null);const [payplan,setPayplan]=useState<Payplan|null>(null);const [suggestions,setSuggestions]=useState<Suggestions>({suggestions:[],unsupported:[]});const [error,setError]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState("");
  async function api(url:string,options?:RequestInit){const r=await fetch(url,{...options,cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Opération impossible.");return p;}
  async function loadDetail(id:string){if(!id){setDetail(null);setPayplan(null);setSuggestions({suggestions:[],unsupported:[]});return;}const encoded=encodeURIComponent(id);const [d,s,pp]=await Promise.all([api(`/api/monthly-animation?workflowId=${encoded}`),api(`/api/monthly-animation/suggestions?workflowId=${encoded}`).catch(()=>({suggestions:[],unsupported:[]})),api(`/api/payplan?workflowId=${encoded}`)]);setDetail(d as Detail);setSuggestions(s as Suggestions);setPayplan(pp as Payplan);}
  async function load(){setError("");try{const list=await api("/api/monthly-animation");const ws=(list.workflows??[]) as Workflow[];setWorkflows(ws);const open=ws.find(w=>w.status!=="closed"&&w.status!=="legacy_closed")??ws[0];if(open){setWorkflowId(open.id);await loadDetail(open.id);}}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.");}}
  useEffect(()=>{void load();},[]);
  async function save(scopeType:string,scopeKey:string,inputKey:string,value:number|null,textValue:string|null=null){if(!workflowId)return;const key=`${scopeType}:${scopeKey}:${inputKey}`;setSaving(key);setError("");setNotice("");try{await api("/api/monthly-animation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"input",workflowId,scopeType,scopeKey,inputKey,numericValue:textValue?null:value,textValue})});setNotice("Résultat enregistré et moteur recalculé.");await loadDetail(workflowId);}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setSaving("");}}
  const rules=payplan?.rules??[];const adminRules=useMemo(()=>rules.filter(r=>r.population==="preprod"),[rules]);const fixlineRule=rules.find(r=>r.population==="fixline");const ceRule=rules.find(r=>r.population==="chef_equipe");const ces=useMemo(()=>detail?.components.filter(c=>c.population==="chef_equipe"&&c.employeeKey).sort((a,b)=>a.employeeName.localeCompare(b.employeeName,"fr"))??[],[detail]);const locked=detail?.workflow.status==="closed"||detail?.workflow.status==="legacy_closed";
  function suggestion(jobKey:string,inputKey:string){return suggestions.suggestions.find(s=>s.jobKey===jobKey&&s.inputKey===inputKey);}
  function unsupported(jobKey:string){return suggestions.unsupported.find(s=>s.jobKey===jobKey)?.reason;}

  return <main className={styles.page}>
    <header className={styles.header}><div><a href="/animation-mensuelle">← ANIMATION VARIABLE</a><span>WORKFLOW · RÉSULTATS RÉALISÉS</span><h1>Résultats du mois</h1><p>Ici on renseigne uniquement le <b>réalisé</b>. Les productifs ne sont pas saisis : leur palier vient automatiquement du rendement. Pour les autres populations, le système reprend le même principe que l'Excel et pré-calculera progressivement les KPI disponibles dans les flux CRVO.</p></div><div className={styles.headerTools}><div className={styles.badge}>{detail?.actor.canManage?"RESPONSABLE PAYPLAN":"LECTURE SEULE"}</div><a className={styles.primaryLink} href="/animation-mensuelle/payplan">VOIR LES ATTENDUS →</a></div></header>
    <div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
      <section className={styles.version}><div><span>Workflow</span><strong>{detail?monthLabel(detail.workflow.month):"—"}</strong></div><div><span>Statut</span><strong>{detail?.workflow.status?.toUpperCase()??"—"}</strong></div><div><span>Productifs</span><strong>AUTOMATIQUES</strong></div><div><span>Autres populations</span><strong>RÉALISÉ + COMPARAISON PAYPLAN</strong></div></section>
      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>MOIS À RENSEIGNER</span><h2>Choisir le workflow</h2></div></div><select value={workflowId} onChange={async e=>{setWorkflowId(e.target.value);await loadDetail(e.target.value);}} style={{minHeight:42,border:"1px solid #cbdce6",borderRadius:10,padding:"0 12px",minWidth:280}}>{workflows.map(w=><option key={w.id} value={w.id}>{monthLabel(w.month)} · {w.status}</option>)}</select>{locked&&<p className={styles.footer}>Ce mois est clôturé : résultats visibles mais non modifiables.</p>}</section>

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>DONNÉES COMMUNES</span><h2>Paramètres du mois</h2></div></div><div className={styles.resultGrid}>{COMMON_FIELDS.map(([key,label])=><ResultCard key={key} label={label} value={numeric(detail?.manualInputs??[],"global","*",key)} disabled={Boolean(locked||!detail?.actor.canManage)} saving={saving===`global:*:${key}`} onSave={v=>save("global","*",key,v)}/>)}</div></section>

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>FIXLINE · UN SEUL RÉSULTAT POUR LE SERVICE</span><h2>Véhicules passés dans le mois</h2><p className={styles.footer}>Même logique que l'Excel : on saisit une seule valeur Fixline. Le système la compare aux seuils P1 → P5 et propose le même palier à toute la population Fixline.</p></div></div>{fixlineRule&&<div className={styles.resultGrid}><ResultCard label="Résultat Fixline du mois" value={numeric(detail?.manualInputs??[],"global","*","fixline_result")} disabled={Boolean(locked||!detail?.actor.canManage)} saving={saving==="global:*:fixline_result"} onSave={v=>save("global","*","fixline_result",v)} footer={`Attendus : ${fixlineRule.thresholds.map((v,i)=>`P${i+1} ≥ ${num(v)}`).join(" · ")}`}/><div className={styles.resultCard}><span className={`${styles.sourceBadge} ${styles.manual}`}>SAISIE SERVICE</span><h3>Palier proposé</h3><strong className={styles.proposed}>{(()=>{const v=numeric(detail?.manualInputs??[],"global","*","fixline_result");const p=proposedTier({...fixlineRule,settings:{...fixlineRule.settings,direction:"gte"}},v,null);return p==null?"—":`P${p}`;})()}</strong><p>Le flux « véhicules passés Fixline » n'est pas encore certifié au même sens que le fichier Excel. Je conserve donc une saisie unique fiable plutôt qu'un faux automatisme.</p></div></div>}</section>

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>ADMINISTRATIF / PRÉ-PRODUCTION</span><h2>Résultat par métier · 1 ou 2 critères</h2><p className={styles.footer}>Une valeur de résultat est commune à tous les collaborateurs du même métier, exactement comme dans le Lexique Excel. Lorsqu'il y a deux sujets, les deux doivent satisfaire le palier.</p></div></div><div className={styles.criteriaCards}>{adminRules.map(rule=><AdminResult key={rule.id} rule={rule} inputs={detail?.manualInputs??[]} suggested1={suggestion(rule.jobKey,rule.jobKey==="jockey"?"factory_output":"criterion_1")} suggested2={suggestion(rule.jobKey,"criterion_2")} unsupportedReason={unsupported(rule.jobKey)} disabled={Boolean(locked||!detail?.actor.canManage)} saving={saving} onSave={save}/>)}</div></section>

      {ceRule&&<section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>CHEFS D'ÉQUIPE · MATRICE 5 SUJETS</span><h2>Résultat individuel de chaque CE</h2><p className={styles.footer}>Chaque ligne est un Chef d'équipe. Les cinq colonnes reprennent les cinq sujets du fichier Excel. Une colonne validée = 1 point ; le nombre de points donne directement le palier théorique proposé.</p></div></div><div className={styles.tableWrap}><table className={`${styles.table} ${styles.ceResults}`}><thead><tr><th>Chef d'équipe</th>{CE_FIELDS.map(([key,label])=><th key={key}>{label}</th>)}<th>Proposition</th></tr></thead><tbody>{ces.map(c=><CeResultRow key={c.id} component={c} rule={ceRule} inputs={detail?.manualInputs??[]} disabled={Boolean(locked||!detail?.actor.canManage)} saving={saving} onSave={save}/>)}</tbody></table></div></section>}

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>AUTOMATISATION</span><h2>Ce que KPI CRVO peut déjà calculer</h2></div></div><div className={styles.settings}><div className={styles.setting}><span>EXPERT DYNAMIQUE</span><strong>Moyenne quotidienne des véhicules « En attente d'expertise dynamique »</strong></div><div className={styles.setting}><span>JOCKEY CT / ASSISTANTE</span><strong>Moyenne quotidienne du stock départ / contrôle CT</strong></div><div className={styles.setting}><span>JOCKEY</span><strong>Cumul des sorties usine Factory-j+1</strong></div></div><p className={styles.footer}>Les suggestions affichent leur source et le nombre de jours couverts. Tant que l'historique FTP ne couvre pas suffisamment le mois, elles restent marquées « provisoire ». Facturation, Acheteur et Magasin restent manuels tant que leur définition Excel n'est pas reliée sans ambiguïté à un champ source.</p></section>
    </div>
  </main>;
}

function ResultCard({label,value,disabled,saving,onSave,footer}:{label:string;value:number|null;disabled:boolean;saving:boolean;onSave:(v:number|null)=>void;footer?:string}){const [v,setV]=useState(value==null?"":String(value));useEffect(()=>setV(value==null?"":String(value)),[value]);return <div className={styles.resultCard}><span className={`${styles.sourceBadge} ${styles.manual}`}>SAISIE MOIS</span><h3>{label}</h3><div className={styles.resultEntry}><input value={v} disabled={disabled} onChange={e=>setV(e.target.value)}/><button disabled={disabled||saving||v.trim()===""} onClick={()=>{const n=Number(v.replace(",","."));onSave(Number.isFinite(n)?n:null);}}>{saving?"…":"OK"}</button></div>{footer&&<p>{footer}</p>}</div>}

function AdminResult({rule,inputs,suggested1,suggested2,unsupportedReason,disabled,saving,onSave}:{rule:Rule;inputs:Input[];suggested1?:Suggestion;suggested2?:Suggestion;unsupportedReason?:string;disabled:boolean;saving:string;onSave:(scopeType:string,scopeKey:string,inputKey:string,value:number|null,textValue?:string|null)=>void}){
  const manual=Boolean(rule.settings?.manual_tier),c2=criterion2(rule);const key1=rule.jobKey==="jockey"?"factory_output":manual?"manual_tier":"criterion_1";const scope1=rule.jobKey==="jockey"?"global":"job";const scopeKey1=rule.jobKey==="jockey"?"*":rule.jobKey;const current1=numeric(inputs,scope1,scopeKey1,key1);const current2=numeric(inputs,"job",rule.jobKey,"criterion_2");const effective1=current1??suggested1?.value??null;const effective2=current2??suggested2?.value??null;const tier=manual?(current1==null?null:Math.round(current1)):proposedTier(rule,effective1,effective2);
  return <article className={styles.criteriaCard}><div className={styles.criteriaTitle}><div><strong>{rule.label}</strong><small>{manual?"Palier manuel":`${direction(rule)==="gte"?"≥":"≤"} · ${c2.length?"2 critères":"1 critère"}`}</small></div><strong className={styles.proposed}>{tier==null?"—":`P${tier}`}</strong></div><AdminCriterion label={manual?"Palier constaté":label1(rule)} current={current1} suggested={suggested1} disabled={disabled} saving={saving===`${scope1}:${scopeKey1}:${key1}`} onSave={v=>onSave(scope1,scopeKey1,key1,v)}/>{!manual&&c2.length>0&&<AdminCriterion label={label2(rule)} current={current2} suggested={suggested2} disabled={disabled} saving={saving===`job:${rule.jobKey}:criterion_2`} onSave={v=>onSave("job",rule.jobKey,"criterion_2",v)}/>}<div className={styles.autoHint}><b>Attendus :</b> {rule.thresholds.map((v,i)=>`P${i+1} ${direction(rule)==="gte"?"≥":"≤"} ${num(v)}${c2[i]!=null?` / ${num(c2[i])}`:""}`).join(" · ")}</div>{unsupportedReason&&!suggested1&&<div className={styles.autoHint}><b>Automatisation non certifiée :</b> {unsupportedReason}</div>}</article>
}
function AdminCriterion({label,current,suggested,disabled,saving,onSave}:{label:string;current:number|null;suggested?:Suggestion;disabled:boolean;saving:boolean;onSave:(v:number|null)=>void}){const [v,setV]=useState(current==null?"":String(current));useEffect(()=>setV(current==null?"":String(current)),[current]);return <div className={styles.resultCard} style={{marginTop:8,padding:10}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><b style={{fontSize:10}}>{label}</b>{suggested&&suggested.value!=null?<span className={sourceClass(suggested.confidence)}>{suggested.confidence==="complete"?"AUTO":"AUTO PROVISOIRE"} · {suggested.coverageDays} j</span>:<span className={`${styles.sourceBadge} ${styles.manual}`}>MANUEL</span>}</div>{suggested&&suggested.value!=null&&<p>{suggested.aggregation} : <b>{num(suggested.value)}</b> · {suggested.source} · dernière donnée {suggested.lastDate?new Date(`${suggested.lastDate}T12:00:00`).toLocaleDateString("fr-FR"):"—"}</p>}<div className={styles.resultEntry}><input value={v} disabled={disabled} placeholder={suggested?.value!=null?String(suggested.value):"Résultat du mois"} onChange={e=>setV(e.target.value)}/><button disabled={disabled||saving||v.trim()===""} onClick={()=>{const n=Number(v.replace(",","."));onSave(Number.isFinite(n)?n:null);}}>{saving?"…":"OK"}</button>{suggested?.value!=null&&<button disabled={disabled||saving} onClick={()=>onSave(suggested.value)}>UTILISER AUTO</button>}</div></div>}

function CeResultRow({component,rule,inputs,disabled,saving,onSave}:{component:Component;rule:Rule;inputs:Input[];disabled:boolean;saving:string;onSave:(scopeType:string,scopeKey:string,inputKey:string,value:number|null,textValue?:string|null)=>void}){const k=component.employeeKey!;const clean=numeric(inputs,"employee",k,"safety_cleanliness",true);const team=text(inputs,"employee",k,"team_p3",true);const lt=numeric(inputs,"employee",k,"lead_time",true);const quality=numeric(inputs,"employee",k,"quality_claim_rate",true);const at=numeric(inputs,"employee",k,"at_count",true);const states=[clean==null?null:clean>Number(rule.thresholds[0]),team?team.toUpperCase()==="OUI":null,lt==null?null:lt<Number(rule.thresholds[2]),quality==null?null:quality<Number(rule.thresholds[3]),at==null?null:at===Number(rule.thresholds[4])];const complete=states.every(v=>v!==null);const tier=complete?states.filter(Boolean).length:null;return <tr><td><strong>{component.employeeName}</strong><small style={{display:"block",color:"#8396a2"}}>{component.matricule??"—"} · Équipe {component.teamCode??"—"}</small></td><td><CeNumberCell value={clean} percent target={`> ${num(Number(rule.thresholds[0])*100)} %`} pass={states[0]} disabled={disabled} saving={saving===`employee:${k}:safety_cleanliness`} onSave={v=>onSave("employee",k,"safety_cleanliness",v)}/></td><td><CeYesNoCell value={team} pass={states[1]} disabled={disabled} saving={saving===`employee:${k}:team_p3`} onSave={v=>onSave("employee",k,"team_p3",null,v)}/></td><td><CeNumberCell value={lt} target={`< ${num(rule.thresholds[2])}`} pass={states[2]} disabled={disabled} saving={saving===`employee:${k}:lead_time`} onSave={v=>onSave("employee",k,"lead_time",v)}/></td><td><CeNumberCell value={quality} percent target={`< ${num(Number(rule.thresholds[3])*100)} %`} pass={states[3]} disabled={disabled} saving={saving===`employee:${k}:quality_claim_rate`} onSave={v=>onSave("employee",k,"quality_claim_rate",v)}/></td><td><CeNumberCell value={at} target={`= ${num(rule.thresholds[4])}`} pass={states[4]} disabled={disabled} saving={saving===`employee:${k}:at_count`} onSave={v=>onSave("employee",k,"at_count",v)}/></td><td><strong className={styles.proposed}>{tier==null?"INCOMPLET":`P${tier} · ${tier}/5`}</strong></td></tr>}
function CeNumberCell({value,percent,target,pass,disabled,saving,onSave}:{value:number|null;percent?:boolean;target:string;pass:boolean|null;disabled:boolean;saving:boolean;onSave:(v:number|null)=>void}){const shown=value==null?"":String(percent?Math.round(value*10000)/100:value);const [v,setV]=useState(shown);useEffect(()=>setV(shown),[shown]);return <div className={styles.ceCell}><small>{target}</small><div className={styles.resultEntry}><input value={v} disabled={disabled} onChange={e=>setV(e.target.value)}/><button disabled={disabled||saving||v.trim()===""} onClick={()=>{const n=Number(v.replace(",","."));onSave(Number.isFinite(n)?(percent?n/100:n):null);}}>OK</button></div><span className={pass===null?"":pass?styles.pass:styles.fail}>{pass===null?"À renseigner":pass?"✓ Validé":"✕ Non validé"}</span></div>}
function CeYesNoCell({value,pass,disabled,saving,onSave}:{value:string|null;pass:boolean|null;disabled:boolean;saving:boolean;onSave:(v:string)=>void}){const [v,setV]=useState(value??"");useEffect(()=>setV(value??""),[value]);return <div className={styles.ceCell}><small>= OUI</small><div className={styles.resultEntry}><select value={v} disabled={disabled} onChange={e=>setV(e.target.value)}><option value="">—</option><option>OUI</option><option>NON</option></select><button disabled={disabled||saving||!v} onClick={()=>onSave(v)}>OK</button></div><span className={pass===null?"":pass?styles.pass:styles.fail}>{pass===null?"À renseigner":pass?"✓ Validé":"✕ Non validé"}</span></div>}
