import { NextResponse } from "next/server";
import { authRpc, currentSession } from "../../lib/crvo-auth";

export const dynamic = "force-dynamic";

type Vehicle={registration:string;work_order:string|null;client:null;vin:null;status:string|null;primary_activity:string|null;alert:string|null;urgency:string|null;factory_age_days:number|null;age_days:number|null;remaining_minutes:null;estimated_total_minutes:null;potential_revenue_total:null};
type FifoRow={sector_key:string;sector_label:string;registration:string|null;work_order:string|null;status:string|null;alert:string|null;urgency:string|null;status_age_days:number|string|null;factory_age_days:number|string|null;fifo_age_days:number|string|null};
type Payload={date:string;dailyExitTarget:number|string|null;fifoRows:FifoRow[];operationalCount:number;alertCount:number;leadTime:Record<string,unknown>|null;live:{snapshotAt:string;sourceName:string;metrics:Record<string,number>;sourceModifiedAt:string|null;factoryModifiedAt:string|null;parkModifiedAt:string|null};freshness:{refreshAt:string|null;depositAt:string|null;depositFilename:string|null};generatedAt:string};

const baseTargets:Record<string,number>={expertise:90,dsp:48,mecanique:85,carrosserie:63,preparation:90,qualite:90};
const labels:Record<string,string>={expertise:"Expertise",dsp:"DSP",mecanique:"Mécanique",carrosserie:"Carrosserie",preparation:"Préparation",qualite:"Qualité",sortie_usine:"Sortie usine"};
function n(value:unknown){const x=Number(value);return Number.isFinite(x)?x:0;}function num(value:unknown){const x=Number(value);return Number.isFinite(x)?x:null;}
function vehicleFromFifo(row:FifoRow):Vehicle{const age=num(row.fifo_age_days)??num(row.factory_age_days)??num(row.status_age_days);const alert=row.alert?String(row.alert):null;return{registration:String(row.registration??""),work_order:row.work_order?String(row.work_order):null,client:null,vin:null,status:row.status?String(row.status):null,primary_activity:alert?`À faire : ${alert}`:row.status?String(row.status):null,alert,urgency:row.urgency?String(row.urgency):null,factory_age_days:num(row.factory_age_days),age_days:age,remaining_minutes:null,estimated_total_minutes:null,potential_revenue_total:null};}

export async function GET(){
  try{
    const current=await currentSession();
    const allowed=Boolean(current&&(current.session.role==="admin"||current.session.page_permissions?.includes("*")||current.session.page_permissions?.includes("cockpit")));
    if(!current)return NextResponse.json({error:"Session CRVO requise."},{status:401,headers:{"Cache-Control":"no-store"}});
    if(!allowed)return NextResponse.json({error:"Droit Cockpit requis."},{status:403,headers:{"Cache-Control":"no-store"}});
    const data=await authRpc<Payload>("kpi_pilotage_secure_payload",{p_session_hash:current.tokenHash});
    const targetExit=n(data.dailyExitTarget);if(targetExit<=0)throw new Error("Objectif Sortie usine du jour indisponible");
    const targets={...baseTargets,sortie_usine:targetExit};const metrics=data.live?.metrics??{};
    const production=[{name:"Expertise",value:n(metrics.production_expertise),tone:"coral"},{name:"Mécanique",value:n(metrics.production_mechanics),tone:"green"},{name:"DSP",value:n(metrics.production_dsp),tone:"cyan"},{name:"Carrosserie",value:n(metrics.production_bodywork),tone:"red"},{name:"Préparation",value:n(metrics.production_preparation),tone:"purple"},{name:"Qualité",value:n(metrics.production_quality),tone:"orange"},{name:"Sortie usine",value:n(metrics.production_factory_exit??metrics.exits_vop),tone:"blue"}];
    const snapshot={date:data.live.snapshotAt,label:new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${data.live.snapshotAt}T12:00:00Z`)),source:data.live.sourceName,entries:n(metrics.entries_vop),exits:n(metrics.exits_vop),stock:n(metrics.factory_stock),over15:n(metrics.stock_over_15d),over20:n(metrics.stock_over_20d),production};
    const grouped=new Map<string,FifoRow[]>();for(const row of data.fifoRows??[]){const list=grouped.get(row.sector_key)??[];list.push(row);grouped.set(row.sector_key,list);}
    const actualFor=(key:string)=>production.find(item=>item.name===labels[key])?.value??(key==="sortie_usine"?snapshot.exits:0);
    const plans=Object.keys(labels).map(sectorKey=>{const label=labels[sectorKey],actual=actualFor(sectorKey),target=targets[sectorKey]??0,gap=Math.max(target-actual,0);const fifoCandidates=(grouped.get(sectorKey)??[]).map(vehicleFromFifo);const recommendation=fifoCandidates.slice(0,gap).map((item,index)=>({...item,strategy:"FIFO" as const,reason:`FIFO EtatduParc · ${item.age_days?.toLocaleString("fr-FR",{maximumFractionDigits:1})??"?"} j${item.alert?` · ${item.alert}`:""}`,rank:index+1}));return{sectorKey,label,actual,target,gap,attainment:target>0?Math.round(actual/target*100):0,queue:fifoCandidates.length,workloadReady:fifoCandidates.length>0,timeReady:false,runMaxMinutes:60,fifoShare:1,highTimeOld:0,runPool:0,remainingHours:0,potentialRevenue:0,oldest:fifoCandidates.slice(0,10),fifoCandidates:fifoCandidates.slice(0,20),runCandidates:[],recommendation};});
    const major=plans.filter(item=>item.gap>0).sort((a,b)=>a.attainment-b.attainment||b.gap-a.gap).slice(0,5);const lead=data.leadTime;
    return NextResponse.json({snapshot,dataConnected:true,workloadSnapshot:snapshot.date,ftpVehicleSnapshot:snapshot.date,ftpVehicleLoadedAt:data.live.parkModifiedAt,productionMode:"ftp",dailyExitTarget:targetExit,sources:{ftp:true,sftp:false,production:"ftp",workloadFtp:(data.fifoRows??[]).length>0,workloadSql:false,workloadTime:false,alertsFtp:data.alertCount>0,invoicesSql:false,financeBook:false},invoiceToday:{revenue:0,invoices:0,available:false,source:"none"},workloadSummary:{workOrders:data.operationalCount,remainingHours:0,potentialRevenue:0},major,plans,fifoRowsLoaded:(data.fifoRows??[]).length,ftpRefresh:{lastRefreshAt:data.freshness.refreshAt,lastDepositAt:data.freshness.depositAt,lastDepositFilename:data.freshness.depositFilename},leadTime:lead?{available:true,sourceModifiedAt:lead.source_modified_at??null,vehicleCount:num(lead.vehicle_count)??0,avgFactoryDays:num(lead.avg_factory_days),medianFactoryDays:num(lead.median_factory_days),avgStorageDays:num(lead.avg_storage_days),avgPartsDays:num(lead.avg_parts_days),vopEffCount:num(lead.vop_eff_count)??0,vopExtCount:num(lead.vop_ext_count)??0,historyReady:true,latestHistoryEventDate:snapshot.date,latestHistoryEventTime:null}:null,methodology:{fifo:"FIFO sécurisé par secteur issu d'EtatduParc, trié sur l'ancienneté usine ; Alerte alimente chaque secteur restant à réaliser.",run:"RUN reste neutralisé tant qu'un temps fiable par dossier n'est pas disponible ; aucune durée n'est inventée."}},{headers:{"Cache-Control":"private, no-store"}});
  }catch(error){console.error(JSON.stringify({event:"pilotage_live_failed",message:error instanceof Error?error.message:"unknown"}));return NextResponse.json({error:"Pilotage live indisponible."},{status:503,headers:{"Cache-Control":"no-store"}});}
}
