"use client";

import { useEffect, useMemo, useState } from "react";
import type { ProrationContext, ProrationMode, ProrationRule } from "../../lib/bonus-proration";
import styles from "./proratisation.module.css";

type WorkflowSummary={id:string;month:string;status:string;closedAt?:string|null};
type WorkflowList={workflows:WorkflowSummary[]};
type Draft={individualMode:ProrationMode;individualThresholdDays:number;collectiveMode:ProrationMode;collectiveThresholdDays:number};

const MODE_OPTIONS:Array<[ProrationMode,string,string]>=[
  ["inherit","Calcul actuel","Conserve le comportement du moteur historique"],
  ["ignore","Aucun impact","L'événement est neutralisé pour cette prime"],
  ["prorate","Proratiser","La durée de l'événement réduit la prime au prorata"],
  ["suppress","Supprimer la prime","Si le seuil est franchi, la prime concernée passe à 0 €"],
];

function monthLabel(month:string){const[y,m]=month.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(y,m-1,1));}
function displayDate(value?:string|null){return value?new Date(value).toLocaleString("fr-FR"):"Jamais modifié";}
function fmt(value:number,digits=1){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:digits}).format(value);}
function sourceTitle(rule:ProrationRule,isDefaults:boolean){const codes=rule.sourceTimeCodes?.length?`Codes Data RH : ${rule.sourceTimeCodes.join(", ")}`:"Événement normalisé RH";return `Source : ${codes} · ${isDefaults?"politique par défaut":"règle mensuelle"} version ${rule.sourceRevision??1}`;}

export default function ProrationRulesPage(){
  const[data,setData]=useState<ProrationContext|null>(null);const[workflows,setWorkflows]=useState<WorkflowSummary[]>([]);const[workflowId,setWorkflowId]=useState("");const[drafts,setDrafts]=useState<Record<string,Draft>>({});const[saving,setSaving]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[filter,setFilter]=useState("");

  async function api(url:string,options?:RequestInit){const response=await fetch(url,{...options,cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Opération impossible.");return payload;}
  function hydrate(payload:ProrationContext){setData(payload);setDrafts(Object.fromEntries(payload.rules.map(rule=>[rule.reasonCode,{individualMode:rule.individualMode,individualThresholdDays:Number(rule.individualThresholdDays??0),collectiveMode:rule.collectiveMode,collectiveThresholdDays:Number(rule.collectiveThresholdDays??0)}])));}
  async function load(id:string){if(!id)return;setError("");try{const url=id==="__defaults__"?"/api/monthly-animation/proration?scope=defaults":`/api/monthly-animation/proration?workflowId=${encodeURIComponent(id)}`;hydrate(await api(url) as ProrationContext);}catch(cause){setError(cause instanceof Error?cause.message:"Lecture impossible.");}}
  useEffect(()=>{void(async()=>{try{const list=await api("/api/monthly-animation") as WorkflowList;setWorkflows(list.workflows??[]);const requested=new URLSearchParams(location.search).get("workflowId");const id=requested||"__defaults__";setWorkflowId(id);await load(id);}catch(cause){setError(cause instanceof Error?cause.message:"Chargement impossible.");}})();},[]);

  const filtered=useMemo(()=>{const q=filter.trim().toLowerCase();return(data?.rules??[]).filter(rule=>!q||`${rule.label} ${rule.reasonCode} ${(rule.sourceTimeCodes??[]).join(" ")}`.toLowerCase().includes(q));},[data,filter]);
  const impactByReason=useMemo(()=>{const map=new Map<string,{people:Set<string>;individual:number;collective:number}>();for(const component of data?.components??[]){for(const event of component.events){const row=map.get(event.reasonCode)??{people:new Set<string>(),individual:0,collective:0};if(event.individualTriggered&&event.individualEffectiveMode!=="ignore"){row.people.add(component.employeeKey);row.individual+=Math.abs(event.individualImpactPct);}if(event.collectiveTriggered&&event.collectiveEffectiveMode!=="ignore"){row.people.add(component.employeeKey);row.collective+=Math.abs(event.collectiveImpactPct);}map.set(event.reasonCode,row);}}return map;},[data]);
  const isDefaults=data?.status==="defaults";const locked=Boolean(data&&["closed","legacy_closed"].includes(data.status));

  function patch(reasonCode:string,field:keyof Draft,value:string|number){setDrafts(current=>({...current,[reasonCode]:{...current[reasonCode],[field]:field.includes("Threshold")?Math.max(0,Math.min(31,Number(value)||0)):value}}));setNotice("");}
  function dirty(rule:ProrationRule){const d=drafts[rule.reasonCode];return Boolean(d&&(d.individualMode!==rule.individualMode||Number(d.individualThresholdDays)!==Number(rule.individualThresholdDays)||d.collectiveMode!==rule.collectiveMode||Number(d.collectiveThresholdDays)!==Number(rule.collectiveThresholdDays)));}
  async function save(rule:ProrationRule){const draft=drafts[rule.reasonCode];if(!draft)return;setSaving(rule.reasonCode);setError("");setNotice("");try{const payload=await api("/api/monthly-animation/proration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workflowId:data?.workflowId,reasonCode:rule.reasonCode,...draft})}) as ProrationContext;hydrate(payload);setNotice(`${rule.label} : règle enregistrée et traçabilité mise à jour.`);}catch(cause){setError(cause instanceof Error?cause.message:"Enregistrement impossible.");}finally{setSaving("");}}

  return <main className={styles.page}>
    <header className={styles.hero}><div><a href="/animation-mensuelle">← WORKFLOW DE PRIME</a><span>PARAMÉTRAGE RH · MOTEUR DE PRORATISATION</span><h1>Règles de proratisation</h1><p>Chaque événement RH peut être neutre, proratisant ou supprimer une prime. Les règles sont séparées entre individuel et collectif / sortie usine, avec un seuil en jours.</p></div><div className={styles.trust}><b>TRACÉ & FIGÉ</b><small>Data RH → règle → calcul → montant → export paie</small></div></header>
    <section className={styles.shell}>
      <div className={styles.toolbar}><label><span>Politique / mois</span><select value={workflowId} onChange={e=>{const id=e.target.value;setWorkflowId(id);void load(id);}}><option value="__defaults__">POLITIQUE PAR DÉFAUT · prochains workflows</option>{workflows.map(item=><option key={item.id} value={item.id}>{monthLabel(item.month)} · {item.status}</option>)}</select></label><label><span>Rechercher un événement</span><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="CP, maladie, AI, A11…"/></label><div className={styles.state}><span>Statut</span><strong>{isDefaults?"POLITIQUE FUTURE":locked?"FIGÉ":"PARAMÉTRABLE"}</strong></div></div>
      {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
      {data&&<>
        <div className={styles.confidence}><div><b>Source RH</b><span title={data.sources?.events}>{isDefaults?"Data RH + Temps de travail":"Data RH + corrections tracées"}</span></div><div><b>{isDefaults?"Portée":"Jours ouvrés"}</b><span title={isDefaults?data.sources?.rules:data.workingDaysSource}>{isDefaults?"Tous les prochains workflows":`${fmt(data.workingDays,2)} jours`}</span></div><div><b>{isDefaults?"Couverture":"Calcul"}</b><span title={data.sources?.calculation}>{isDefaults?`${data.rules.length} types d'événements`:`${data.components.length} collaborateurs analysés`}</span></div><div><b>Droits</b><span>{data.canConfigure&&!locked?"Admin / RH · modification autorisée":"Lecture seule"}</span></div></div>
        {isDefaults&&<div className={styles.notice}><b>Politique par défaut.</b> Ces règles sont copiées au moment où un nouveau workflow mensuel est ouvert. Le mois garde ensuite sa propre copie : une modification future de la politique ne réécrit jamais un mois déjà ouvert ou clôturé.</div>}
        {locked&&<div className={styles.locked}><b>Mois clôturé.</b> Les règles visibles sont celles de ce workflow et ne peuvent plus être modifiées. Aucun recalcul rétroactif silencieux n’est possible.</div>}
        {!isDefaults&&data.rules.length===0&&<div className={styles.locked}><b>Historique antérieur au moteur de règles.</b> Ce mois a été figé avant l’introduction de la proratisation paramétrable. Son calcul historique reste inchangé ; la politique actuelle est consultable via « Politique par défaut ».</div>}
        <div className={styles.legend}><b>Lecture du seuil :</b> une valeur de <strong>2 jours</strong> signifie « appliquer la règle uniquement lorsque la durée cumulée de cet événement est strictement supérieure à 2 jours sur le mois ». Lorsqu’il est franchi, toute la durée de l’événement entre dans la proratisation.</div>
        <div className={styles.tableWrap}><table><thead><tr><th>Événement RH</th><th>Prime individuelle</th><th>Seuil</th><th>Prime collective / sortie usine</th><th>Seuil</th><th>{isDefaults?"Portée":"Impact constaté"}</th><th></th></tr></thead><tbody>{filtered.map(rule=>{const d=drafts[rule.reasonCode];const impact=impactByReason.get(rule.reasonCode);return <tr key={rule.reasonCode}><td><div className={styles.eventName}><span className={styles.sourceDot} title={sourceTitle(rule,Boolean(isDefaults))}>i</span><div><strong>{rule.label}</strong><small>{rule.sourceTimeCodes?.length?`Data RH · ${rule.sourceTimeCodes.join(" / ")}`:"Événement RH normalisé / correction Temps de travail"}</small></div></div></td><td><select disabled={!data.canConfigure||locked} value={d?.individualMode??rule.individualMode} onChange={e=>patch(rule.reasonCode,"individualMode",e.target.value)} title={MODE_OPTIONS.find(([key])=>key===(d?.individualMode??rule.individualMode))?.[2]}>{MODE_OPTIONS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></td><td><div className={styles.threshold}><span>&gt;</span><input type="number" min="0" max="31" step="0.5" disabled={!data.canConfigure||locked||["inherit","ignore"].includes(d?.individualMode??rule.individualMode)} value={d?.individualThresholdDays??rule.individualThresholdDays} onChange={e=>patch(rule.reasonCode,"individualThresholdDays",e.target.value)}/><span>j</span></div></td><td><select disabled={!data.canConfigure||locked} value={d?.collectiveMode??rule.collectiveMode} onChange={e=>patch(rule.reasonCode,"collectiveMode",e.target.value)} title={MODE_OPTIONS.find(([key])=>key===(d?.collectiveMode??rule.collectiveMode))?.[2]}>{MODE_OPTIONS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></td><td><div className={styles.threshold}><span>&gt;</span><input type="number" min="0" max="31" step="0.5" disabled={!data.canConfigure||locked||["inherit","ignore"].includes(d?.collectiveMode??rule.collectiveMode)} value={d?.collectiveThresholdDays??rule.collectiveThresholdDays} onChange={e=>patch(rule.reasonCode,"collectiveThresholdDays",e.target.value)}/><span>j</span></div></td><td>{isDefaults?<div className={styles.impact} title="Cette règle sera évaluée dès l'ouverture du prochain workflow"><strong>FUTUR</strong><small>copiée au prochain mois</small></div>:<div className={styles.impact} title="Calculé sur les événements RH actuellement présents dans ce workflow"><strong>{impact?.people.size??0}</strong><small>collab. impacté(s)</small></div>}</td><td>{data.canConfigure&&!locked&&<button className={dirty(rule)?styles.saveDirty:styles.save} disabled={!dirty(rule)||saving===rule.reasonCode} onClick={()=>void save(rule)}>{saving===rule.reasonCode?"…":"ENREGISTRER"}</button>}</td></tr>})}</tbody></table></div>
        <section className={styles.audit}><div><span>JOURNAL DES RÈGLES</span><h2>Qui a changé quoi ?</h2><p>Chaque modification conserve l’ancienne règle, la nouvelle règle, l’auteur et l’horodatage.</p></div><div className={styles.auditList}>{(data.audit??[]).length===0?<div className={styles.empty}>{isDefaults?"Aucune modification manuelle de la politique par défaut.":"Aucune modification manuelle sur ce workflow."}</div>:(data.audit??[]).slice(0,12).map((entry,index)=><div className={styles.auditRow} key={String(entry.id??index)}><strong>{String(entry.reasonCode??"Règle")}</strong><span>{String(entry.changedByName??"Utilisateur")}</span><small>{displayDate(String(entry.changedAt??""))}</small></div>)}</div></section>
      </>}
    </section>
  </main>;
}
