"use client";

import {useEffect,useState} from "react";
import styles from "./demande.module.css";

type Person={employeeKey:string;employeeName:string;matricule?:string|null;team?:string|null;service?:string|null};
type Track={key:string;label:string;levelLabel?:string|null};
type RequestRow={id:string;employeeKey:string;employeeName:string;team?:string|null;trackKey?:string|null;difficulties:string;acquiredSkills?:string|null;requestedSkills?:string|null;operationalContext?:string|null;urgency:string;status:string;requestedByName?:string|null;createdAt:string;decisionComment?:string|null;decidedByName?:string|null;decidedAt?:string|null};
type Payload={access:{displayName:string;level:string;positionKey?:string|null;teams:string[]};people:Person[];tracks:Track[];requests:RequestRow[];error?:string};
const URGENCY:Record<string,string>={critical:"Critique",high:"Haute",normal:"Normale",low:"Basse"};
const STATUS:Record<string,string>={pending:"En attente",approved:"Validée",refused:"Refusée",cancelled:"Annulée"};
function d(v:string){return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));}

export default function TrainingRequestPage(){
  const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");
  const[employee,setEmployee]=useState("");const[track,setTrack]=useState("");const[difficulties,setDifficulties]=useState("");const[acquired,setAcquired]=useState("");const[requested,setRequested]=useState("");const[context,setContext]=useState("");const[urgency,setUrgency]=useState("normal");const[saving,setSaving]=useState(false);
  async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/training/request?_=${Date.now()}`,{cache:"no-store"});const p=await r.json()as Payload;if(!r.ok)throw new Error(p.error||"Chargement impossible.");setData(p);if(!employee&&p.people[0])setEmployee(p.people[0].employeeKey);}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function submit(){if(!employee){setError("Sélectionne un collaborateur.");return;}if(!difficulties.trim()){setError("Décris les difficultés observées.");return;}setSaving(true);setError("");setNotice("");try{const r=await fetch("/api/training/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeKey:employee,trackKey:track||null,difficulties,acquiredSkills:acquired,requestedSkills:requested,operationalContext:context,urgency})});const p=await r.json()as{error?:string};if(!r.ok)throw new Error(p.error||"Envoi impossible.");setNotice("Demande transmise aux RH / Admin. Elle est maintenant rattachée à l'historique du collaborateur.");setDifficulties("");setAcquired("");setRequested("");setContext("");setUrgency("normal");await load();}catch(e){setError(e instanceof Error?e.message:"Envoi impossible.");}finally{setSaving(false);}}
  return <main className={styles.page}>
    <header className={styles.hero}><p className={styles.eyebrow}>PRODUCTION · CARROSSERIE</p><h1>Demande de formation</h1><p>Décris le besoin terrain avant toute planification. Le dossier conserve les difficultés constatées, les acquis, les compétences à développer et les décisions RH.</p></header>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{loading&&<div className={styles.notice}>Chargement du périmètre autorisé…</div>}
    {data&&<><section className={styles.panel}><h2>État des lieux du besoin</h2><div className={styles.form}><label>Collaborateur<select value={employee} onChange={e=>setEmployee(e.target.value)}>{data.people.map(p=><option key={p.employeeKey} value={p.employeeKey}>{p.employeeName} · Équipe {p.team||"—"} · {p.service||"Carrosserie"}</option>)}</select></label><label>Parcours pressenti<select value={track} onChange={e=>setTrack(e.target.value)}><option value="">À déterminer par le formateur</option>{data.tracks.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label><label>Urgence<select value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="critical">Critique</option><option value="high">Haute</option><option value="normal">Normale</option><option value="low">Basse</option></select></label><label>Demandeur<input value={`${data.access.displayName} · ${data.access.level}`} disabled/></label><label className={styles.span2}>Difficultés constatées *<textarea value={difficulties} onChange={e=>setDifficulties(e.target.value)} placeholder="Gestes non maîtrisés, défaut qualité, manque d'autonomie, lenteur, reprises… Donne des faits observables."/></label><label>Compétences déjà acquises<textarea value={acquired} onChange={e=>setAcquired(e.target.value)} placeholder="Ce que le collaborateur sait déjà faire correctement…"/></label><label>Compétences à développer<textarea value={requested} onChange={e=>setRequested(e.target.value)} placeholder="Ce qu'il devrait savoir faire à l'issue de la formation…"/></label><label className={styles.span2}>Contexte opérationnel<textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Exemples de dossiers, fréquence du problème, impact qualité / délai / production…"/></label><button className={`${styles.primary} ${styles.span2}`} disabled={saving} onClick={()=>void submit()}>{saving?"ENVOI…":"TRANSMETTRE LA DEMANDE"}</button></div></section><section className={styles.panel}><h2>Historique des demandes visibles</h2><div className={styles.history}>{data.requests.map(r=><article className={styles.row} key={r.id}><header><div><h3>{r.employeeName} · Équipe {r.team||"—"}</h3><small>{d(r.createdAt)} · {r.requestedByName||"—"} · urgence {URGENCY[r.urgency]||r.urgency}</small></div><b className={styles.badge} data-status={r.status}>{STATUS[r.status]||r.status}</b></header><p><strong>Difficultés :</strong> {r.difficulties}</p>{r.acquiredSkills&&<p><strong>Acquis :</strong> {r.acquiredSkills}</p>}{r.requestedSkills&&<p><strong>À développer :</strong> {r.requestedSkills}</p>}{r.decisionComment&&<p><strong>Décision {r.decidedByName||"RH"} :</strong> {r.decisionComment}</p>}</article>)}{data.requests.length===0&&<p>Aucune demande enregistrée sur ton périmètre.</p>}</div></section></>}
  </main>;
}
