"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "../network-quality.module.css";

type Claim={id:string;claim_number:string;registration:string;work_order:string|null;vin:string|null;model:string|null;mileage:number|null;category:string;description:string;status:string;decision:string|null;committee_response:string|null;requested_info:string|null;estimate_amount:number|null;accepted_amount:number|null;declared_at:string;decision_at:string|null;closed_at:string|null;updated_at:string};
type Message={id:number;author_role:"NETWORK"|"CRVO";author_name:string|null;body:string;created_at:string};
type Attachment={id:string;kind:string;file_name:string;mime_type:string;size_bytes:number;created_at:string};
type Detail={claim:Claim;messages:Message[];attachments:Attachment[];audit:unknown[]};
type Dashboard={connected:boolean;context:{client:string;partnerLabel:string;dealerCode:string|null;siteCode:string};metrics:{total:number;open:number;waiting:number;accepted:number};claims:Claim[];detail:Detail|null;found?:boolean};
type Lookup={connected:boolean;found:boolean;registration?:string;vehicle?:{registration:string;workOrder:string|null;vin:string|null;model:string|null;mileage:number|null;client:string;status:string|null;lastEventDate?:string;lastEventTime?:string};history?:Array<{event_date:string;event_time:string|null;status:string|null;flow:string|null}>};

type View="home"|"new"|"detail";
const categories=["Mécanique","Carrosserie","Préparation esthétique","Pneus / Jantes","Vitrage","Sellerie","Facturation / Carburant","Autre"];
const statusNames:Record<string,string>={RECEIVED:"Reçue",ANALYSIS:"En analyse",WAITING_NETWORK:"Complément demandé",COMMITTEE:"En comité",ACCEPTED:"Acceptée",REFUSED:"Refusée",CLOSED:"Clôturée"};
function dt(value:string|null|undefined){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(d)}
function money(value:unknown){const x=Number(value);return Number.isFinite(x)?new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(x):"—"}
function tone(status:string){if(status==="ACCEPTED")return styles.good;if(status==="REFUSED"||status==="CLOSED")return styles.muted;if(status==="WAITING_NETWORK")return styles.warn;if(status==="COMMITTEE")return styles.info;return styles.live}
async function fileBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result??"");resolve(s.includes(",")?s.slice(s.indexOf(",")+1):s)};r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}

export default function NetworkQualityPortal({token}:{token:string}){
  const apiRoot=`/api/quality-claims/client/${encodeURIComponent(token)}`;
  const [data,setData]=useState<Dashboard|null>(null);
  const [view,setView]=useState<View>("home");
  const [detail,setDetail]=useState<Detail|null>(null);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState("");
  const [registration,setRegistration]=useState("");
  const [lookup,setLookup]=useState<Lookup|null>(null);
  const [lookupLoading,setLookupLoading]=useState(false);
  const [form,setForm]=useState({category:"Mécanique",description:"",estimateAmount:""});
  const [files,setFiles]=useState<File[]>([]);
  const [message,setMessage]=useState("");
  const [search,setSearch]=useState("");

  async function api<T>(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:"no-store",headers:{"Content-Type":"application/json",...(init?.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.error||"Service temporairement indisponible."));return p as T}
  async function refresh(quiet=false){if(!quiet)setLoading(true);try{const p=await api<Dashboard>(`${apiRoot}?_=${Date.now()}`);setData(p);setError("")}catch(e){setError(e instanceof Error?e.message:"Accès indisponible.")}finally{if(!quiet)setLoading(false)}}
  async function openClaim(id:string){setLoading(true);try{const p=await api<Dashboard>(`${apiRoot}?claimId=${encodeURIComponent(id)}&_=${Date.now()}`);if(p.detail){setDetail(p.detail);setView("detail");window.scrollTo({top:0,behavior:"smooth"})}}catch(e){setError(e instanceof Error?e.message:"Dossier indisponible.")}finally{setLoading(false)}}
  useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(true),60000);return()=>window.clearInterval(t)},[]);

  const claims=useMemo(()=>{const q=search.trim().toLowerCase();return (data?.claims??[]).filter(c=>!q||`${c.claim_number} ${c.registration} ${c.category}`.toLowerCase().includes(q))},[data,search]);

  async function lookupVehicle(){const q=registration.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(q.length<4)return;setLookupLoading(true);setError("");try{const p=await api<Lookup>(`${apiRoot}?registration=${encodeURIComponent(q)}&_=${Date.now()}`);setLookup(p);setRegistration(q)}catch(e){setLookup(null);setError(e instanceof Error?e.message:"Recherche impossible.")}finally{setLookupLoading(false)}}
  function startNew(){setView("new");setDetail(null);setRegistration("");setLookup(null);setForm({category:"Mécanique",description:"",estimateAmount:""});setFiles([]);setError("");window.scrollTo({top:0,behavior:"smooth"})}
  async function createClaim(){if(!registration.trim()||!form.description.trim())return;setSaving(true);setError("");try{const p=await api<{detail:Detail}>(apiRoot,{method:"POST",body:JSON.stringify({action:"create",payload:{registration,category:form.category,description:form.description,estimateAmount:form.estimateAmount||null,workOrder:lookup?.vehicle?.workOrder??null,vin:lookup?.vehicle?.vin??null,model:lookup?.vehicle?.model??null,mileage:lookup?.vehicle?.mileage??null}})});const claim=p.detail.claim;for(const file of files){if(file.size>6291456)throw new Error(`${file.name} dépasse la taille maximale de 6 Mo.`);const fileData=await fileBase64(file);await api(apiRoot,{method:"POST",body:JSON.stringify({action:"attachment",claimId:claim.id,attachment:{kind:file.type.startsWith("image/")?"PHOTO":file.type==="application/pdf"?"QUOTE":"OTHER",fileName:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,fileData}})})}await refresh(true);await openClaim(claim.id)}catch(e){setError(e instanceof Error?e.message:"Impossible de créer la réclamation.")}finally{setSaving(false)}}
  async function sendMessage(){if(!detail||!message.trim())return;setSaving(true);try{const p=await api<{detail:Detail}>(apiRoot,{method:"POST",body:JSON.stringify({action:"message",claimId:detail.claim.id,message:message.trim()})});setDetail(p.detail);setMessage("");await refresh(true)}catch(e){setError(e instanceof Error?e.message:"Message non envoyé.")}finally{setSaving(false)}}
  async function addFiles(fileList:FileList|null){if(!detail||!fileList?.length)return;setSaving(true);try{for(const file of Array.from(fileList)){if(file.size>6291456)throw new Error(`${file.name} dépasse 6 Mo.`);await api(apiRoot,{method:"POST",body:JSON.stringify({action:"attachment",claimId:detail.claim.id,attachment:{kind:file.type.startsWith("image/")?"PHOTO":file.type==="application/pdf"?"QUOTE":"OTHER",fileName:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,fileData:await fileBase64(file)}})})}await openClaim(detail.claim.id)}catch(e){setError(e instanceof Error?e.message:"Ajout impossible.")}finally{setSaving(false)}}

  if(loading&&!data)return <main className={styles.page}><div className={styles.splash}><div className={styles.logo}>CRVO</div><strong>Qualité réseau</strong><span>Chargement de votre espace sécurisé…</span></div></main>;
  if(error&&!data)return <main className={styles.page}><div className={styles.accessError}><div className={styles.logo}>CRVO</div><h1>Accès indisponible</h1><p>{error}</p><small>Contactez votre interlocuteur CRVO si ce lien doit encore être actif.</small></div></main>;

  return <main className={styles.page}><div className={styles.shell}>
    <header className={styles.header}><button className={styles.brand} onClick={()=>{setView("home");setDetail(null)}}><span>CRVO</span><div><strong>Qualité réseau</strong><small>{data?.context.partnerLabel||data?.context.client}</small></div></button><div className={styles.secure}><span></span>ACCÈS SÉCURISÉ</div></header>
    {error&&<div className={styles.error}>{error}<button onClick={()=>setError("")}>×</button></div>}

    {view==="home"&&data&&<>
      <section className={styles.hero}><div><span>RELATION CLIENT · CRVO {data.context.siteCode}</span><h1>Un problème sur un véhicule ?</h1><p>Déclarez l’anomalie en quelques minutes. L’équipe CRVO suit votre dossier jusqu’à la réponse du comité Qualité.</p><button onClick={startNew}>DÉCLARER UNE ANOMALIE</button></div><div className={styles.heroMark}>RQ</div></section>
      <section className={styles.kpis}><article><strong>{data.metrics.open}</strong><span>en cours</span></article><article><strong>{data.metrics.waiting}</strong><span>complément attendu</span></article><article><strong>{data.metrics.accepted}</strong><span>acceptées</span></article><article><strong>{data.metrics.total}</strong><span>historique</span></article></section>
      <section className={styles.history}><div className={styles.sectionHead}><div><span>VOS DEMANDES</span><h2>Historique des réclamations</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Immatriculation ou dossier…"/></div><div className={styles.claims}>{claims.map(c=><button key={c.id} onClick={()=>void openClaim(c.id)}><div className={styles.claimMain}><span>{c.claim_number}</span><strong>{c.registration}</strong><small>{c.category} · {dt(c.declared_at)}</small></div><div className={styles.claimState}><em className={`${styles.badge} ${tone(c.status)}`}>{statusNames[c.status]||c.status}</em><b>›</b></div></button>)}{!claims.length&&<div className={styles.empty}>Aucune réclamation à afficher.</div>}</div></section>
    </>}

    {view==="new"&&<section className={styles.formPage}><button className={styles.back} onClick={()=>setView("home")}>← RETOUR</button><div className={styles.formTitle}><span>NOUVELLE RÉCLAMATION</span><h1>Déclarer une anomalie</h1><p>Commencez par l’immatriculation. Nous récupérons automatiquement les informations dont dispose le CRVO.</p></div><div className={styles.step}><div className={styles.stepNo}>1</div><div className={styles.stepBody}><h2>Identifier le véhicule</h2><div className={styles.registrationSearch}><input value={registration} onChange={e=>{setRegistration(e.target.value.toUpperCase());setLookup(null)}} placeholder="AA-123-BB" autoCapitalize="characters"/><button disabled={lookupLoading||registration.trim().length<4} onClick={()=>void lookupVehicle()}>{lookupLoading?"RECHERCHE…":"RECHERCHER"}</button></div>{lookup&&<div className={lookup.found?styles.vehicleFound:styles.vehicleMissing}>{lookup.found?<><span>VÉHICULE RETROUVÉ</span><strong>{lookup.vehicle?.model||lookup.vehicle?.registration}</strong><div><small>OR {lookup.vehicle?.workOrder||"—"}</small><small>VIN {lookup.vehicle?.vin||"—"}</small><small>{lookup.vehicle?.mileage?`${Number(lookup.vehicle.mileage).toLocaleString("fr-FR")} km`:"Kilométrage non disponible"}</small></div></>:<><span>IMMATRICULATION NON RETROUVÉE</span><p>Vous pouvez poursuivre : le CRVO rapprochera manuellement le véhicule lors de l’analyse.</p></>}</div>}</div></div>
      <div className={styles.step}><div className={styles.stepNo}>2</div><div className={styles.stepBody}><h2>Décrire le problème</h2><label>Nature de l’anomalie<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Ce que vous constatez<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Décrivez précisément le défaut, les circonstances, les contrôles déjà réalisés…"/></label><label>Montant estimé / devis (€) <small>optionnel</small><input type="number" min="0" step="0.01" value={form.estimateAmount} onChange={e=>setForm({...form,estimateAmount:e.target.value})}/></label></div></div>
      <div className={styles.step}><div className={styles.stepNo}>3</div><div className={styles.stepBody}><h2>Ajouter les preuves utiles</h2><p className={styles.hint}>Photos du défaut, vue d’ensemble, devis PDF… jusqu’à 6 Mo par fichier.</p><label className={styles.fileDrop}>PRENDRE / AJOUTER DES PHOTOS OU UN DEVIS<input type="file" multiple accept="image/*,application/pdf" capture="environment" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>{files.length>0&&<div className={styles.fileList}>{files.map((f,i)=><div key={`${f.name}-${i}`}><span>{f.type.startsWith("image/")?"PHOTO":"FICHIER"}</span><strong>{f.name}</strong><small>{Math.round(f.size/1024)} Ko</small></div>)}</div>}</div></div>
      <div className={styles.submitBox}><div><strong>Votre déclaration sera horodatée</strong><span>Vous pourrez ensuite suivre son statut et échanger avec le CRVO.</span></div><button disabled={saving||registration.trim().length<4||!form.description.trim()} onClick={()=>void createClaim()}>{saving?"ENVOI EN COURS…":"ENVOYER LA RÉCLAMATION"}</button></div></section>}

    {view==="detail"&&detail&&<section className={styles.detailPage}><button className={styles.back} onClick={()=>{setView("home");setDetail(null)}}>← VOS RÉCLAMATIONS</button><div className={styles.detailHero}><div><span>{detail.claim.claim_number}</span><h1>{detail.claim.registration}</h1><p>{detail.claim.category} · déclarée le {dt(detail.claim.declared_at)}</p></div><em className={`${styles.badge} ${tone(detail.claim.status)}`}>{statusNames[detail.claim.status]||detail.claim.status}</em></div>
      <div className={styles.timeline}>{["RECEIVED","ANALYSIS","COMMITTEE","ACCEPTED"].map((s,i)=>{const order:Record<string,number>={RECEIVED:0,ANALYSIS:1,WAITING_NETWORK:1,COMMITTEE:2,ACCEPTED:3,REFUSED:3,CLOSED:3};const current=order[detail.claim.status]??0;return <div key={s} className={i<=current?styles.done:""}><span>{i+1}</span><small>{["Réception","Analyse","Comité","Décision"][i]}</small></div>})}</div>
      {detail.claim.status==="WAITING_NETWORK"&&<div className={styles.requestBox}><span>COMPLÉMENT D’INFORMATION DEMANDÉ</span><p>{detail.claim.requested_info||"Le CRVO attend une information complémentaire."}</p></div>}
      {(detail.claim.decision==="ACCEPTED"||detail.claim.decision==="REFUSED")&&<div className={detail.claim.decision==="ACCEPTED"?styles.decisionAccept:styles.decisionRefuse}><span>DÉCISION DU COMITÉ QUALITÉ</span><h2>{detail.claim.decision==="ACCEPTED"?"Réclamation acceptée":"Réclamation refusée"}</h2><p>{detail.claim.committee_response||"La décision a été enregistrée par le comité Qualité."}</p>{detail.claim.accepted_amount!=null&&detail.claim.decision==="ACCEPTED"&&<strong>Prise en charge : {money(detail.claim.accepted_amount)}</strong>}</div>}
      <div className={styles.detailGrid}><section><span>VÉHICULE</span><h2>Informations dossier</h2><dl><div><dt>Immatriculation</dt><dd>{detail.claim.registration}</dd></div><div><dt>OR</dt><dd>{detail.claim.work_order||"—"}</dd></div><div><dt>VIN</dt><dd>{detail.claim.vin||"—"}</dd></div><div><dt>Modèle</dt><dd>{detail.claim.model||"—"}</dd></div></dl></section><section><span>ANOMALIE</span><h2>Votre déclaration</h2><p>{detail.claim.description}</p>{detail.claim.estimate_amount!=null&&<small>Estimation transmise : {money(detail.claim.estimate_amount)}</small>}</section></div>
      <section className={styles.attachSection}><div className={styles.sectionHead}><div><span>PIÈCES JOINTES</span><h2>Photos & documents</h2></div><label className={styles.addFile}>+ AJOUTER<input type="file" multiple accept="image/*,application/pdf" capture="environment" onChange={e=>void addFiles(e.target.files)}/></label></div><div className={styles.attachments}>{detail.attachments.map(a=><button key={a.id} onClick={()=>window.open(`${apiRoot}?attachmentId=${encodeURIComponent(a.id)}`,"_blank","noopener,noreferrer")}><span>{a.kind==="PHOTO"?"PHOTO":a.kind==="QUOTE"?"DEVIS":"FICHIER"}</span><strong>{a.file_name}</strong><small>{Math.round(a.size_bytes/1024)} Ko</small></button>)}{!detail.attachments.length&&<div className={styles.empty}>Aucun document joint.</div>}</div></section>
      <section className={styles.chatSection}><span>ÉCHANGES AVEC LE CRVO</span><h2>Conversation</h2><div className={styles.chat}>{detail.messages.map(m=><div key={m.id} className={m.author_role==="NETWORK"?styles.mine:styles.theirs}><strong>{m.author_role==="NETWORK"?"Vous":m.author_name||"Équipe CRVO"}</strong><p>{m.body}</p><small>{dt(m.created_at)}</small></div>)}{!detail.messages.length&&<div className={styles.empty}>Aucun message pour le moment.</div>}</div><div className={styles.composer}><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Écrire au CRVO…"/><button disabled={saving||!message.trim()} onClick={()=>void sendMessage()}>ENVOYER</button></div></section>
    </section>}
    <footer className={styles.footer}><strong>CRVO · Votre potentiel VO au plus haut</strong><span>Portail sécurisé de suivi des réclamations qualité</span></footer>
  </div></main>
}
