"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./account.module.css";

type AccessProfile="admin"|"service_manager"|"custom";
type User={id:string;username:string;display_name:string;role:"admin"|"user";is_active:boolean;must_change_password:boolean;created_at:string;last_login_at:string|null;access_profile:AccessProfile;page_permissions:string[];productivity_scopes:string[]};
type Me={id:string;username:string;displayName:string;role:"admin"|"user";accessProfile:AccessProfile;pagePermissions:string[];productivityScopes:string[];mustChangePassword:boolean};

type Option={key:string;label:string;detail:string};
const PAGE_OPTIONS:Option[]=[
  {key:"reporting",label:"Reporting principal",detail:"Performance opérationnelle du reporting"},
  {key:"productivity",label:"Productivité",detail:"Productivité par secteur, équipe et collaborateur"},
  {key:"book",label:"Book / CA / goulots",detail:"Veille, goulots, Walking DEAD, chiffre d'affaires et Book"},
  {key:"cockpit",label:"CRVO Cockpit V2",detail:"Pilotage, synthèse, décisions et prévisions"},
  {key:"bodyshop",label:"Focus carrosserie",detail:"Cockpit spécifique carrosserie"},
  {key:"client_dashboard",label:"Dashboard client",detail:"Vues Réseau et BMW / MINI"},
  {key:"intelligence",label:"Analyse / intelligence",detail:"Analyses et aide à la décision"},
];
const SCOPE_OPTIONS:Option[]=[
  {key:"expertise",label:"Expertise",detail:"Expertise + expertise dynamique"},{key:"qualite",label:"Qualité",detail:"Qualité + opérateurs qualité"},{key:"mecanique",label:"Mécanique",detail:"Mécanique"},{key:"carrosserie",label:"Carrosserie",detail:"Fixline, Box et tôlerie"},{key:"dsp",label:"DSP",detail:"DSP"},{key:"preparation",label:"Préparation",detail:"Préparation"},{key:"photo",label:"Photo",detail:"Photo"},{key:"jantes",label:"Jantes",detail:"Jantes"},{key:"lavage",label:"Lavage",detail:"Lavage"},{key:"magasin",label:"Magasin",detail:"Magasin, acheteurs et labo peinture"},{key:"diagnostic",label:"Diagnostic",detail:"Transverse / diagnostic"},{key:"jockey",label:"Jockey",detail:"Jockey"},{key:"encadrement",label:"Encadrement",detail:"Chefs d'équipe"},{key:"administratif",label:"Administratif",detail:"Administratif"},{key:"autre",label:"Autre / entretien",detail:"Entretien et autres"},
];
const ALL_PAGES=PAGE_OPTIONS.map(item=>item.key);

function generatePassword(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%_-";const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);return Array.from(bytes,b=>chars[b%chars.length]).join("");}
function profileLabel(value:AccessProfile){return value==="admin"?"ADMIN":value==="service_manager"?"CHEF DE SERVICE":"ACCÈS PERSONNALISÉ";}
function hasAll(values:string[]|undefined){return Boolean(values?.includes("*"));}
function labelList(values:string[]|undefined,options:Option[]){if(hasAll(values))return "Tous";const set=new Set(values??[]);return options.filter(item=>set.has(item.key)).map(item=>item.label).join(", ")||"Aucun";}
function toggle(values:string[],key:string){return values.includes(key)?values.filter(item=>item!==key):[...values.filter(item=>item!=="*"),key];}

export default function AccountPage(){
  const [me,setMe]=useState<Me|null>(null);const [users,setUsers]=useState<User[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [currentPassword,setCurrentPassword]=useState("");const [newPassword,setNewPassword]=useState("");
  const [username,setUsername]=useState("");const [displayName,setDisplayName]=useState("");const [temporaryPassword,setTemporaryPassword]=useState(generatePassword());const [accessProfile,setAccessProfile]=useState<AccessProfile>("custom");const [pagePermissions,setPagePermissions]=useState<string[]>(["productivity"]);const [productivityScopes,setProductivityScopes]=useState<string[]>(["*"]);
  const [editing,setEditing]=useState<User|null>(null);const [editProfile,setEditProfile]=useState<AccessProfile>("custom");const [editPages,setEditPages]=useState<string[]>([]);const [editScopes,setEditScopes]=useState<string[]>(["*"]);

  async function load(){const response=await fetch("/api/auth/me",{cache:"no-store"});if(!response.ok){location.href="/login";return;}const payload=await response.json();setMe(payload.user);if(payload.user.role==="admin"){const usersResponse=await fetch("/api/auth/users",{cache:"no-store"});if(usersResponse.ok){const data=await usersResponse.json();setUsers(data.users??[]);}}}
  useEffect(()=>{void load();},[]);

  function applyCreateProfile(profile:AccessProfile){setAccessProfile(profile);if(profile==="admin"){setPagePermissions(["*"]);setProductivityScopes(["*"]);}else if(profile==="service_manager"){setPagePermissions(ALL_PAGES);if(!productivityScopes.length)setProductivityScopes(["*"]);}else{setPagePermissions(current=>hasAll(current)?["productivity"]:current);}}
  function applyEditProfile(profile:AccessProfile){setEditProfile(profile);if(profile==="admin"){setEditPages(["*"]);setEditScopes(["*"]);}else if(profile==="service_manager"){setEditPages(ALL_PAGES);if(!editScopes.length)setEditScopes(["*"]);}else{setEditPages(current=>hasAll(current)?["productivity"]:current);}}
  function openRights(user:User){setEditing(user);setEditProfile(user.access_profile??(user.role==="admin"?"admin":"custom"));setEditPages(user.role==="admin"?["*"]:(user.page_permissions??[]));setEditScopes(user.role==="admin"?["*"]:(user.productivity_scopes??[]));setTimeout(()=>document.getElementById("rights-editor")?.scrollIntoView({behavior:"smooth",block:"start"}),0);}

  async function changePassword(event:FormEvent){event.preventDefault();setError("");setNotice("");const response=await fetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Modification impossible.");return;}setCurrentPassword("");setNewPassword("");setNotice("Mot de passe modifié.");await load();}
  async function createUser(event:FormEvent){event.preventDefault();setError("");setNotice("");const response=await fetch("/api/auth/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,displayName,temporaryPassword,accessProfile,pagePermissions,productivityScopes})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Création impossible.");return;}setNotice(`Accès créé pour ${displayName||username}. Les pages et le périmètre de productivité sont actifs dès la première connexion.`);setUsername("");setDisplayName("");setTemporaryPassword(generatePassword());setAccessProfile("custom");setPagePermissions(["productivity"]);setProductivityScopes(["*"]);await load();}
  async function saveRights(){if(!editing)return;setError("");setNotice("");const response=await fetch("/api/auth/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update-access",userId:editing.id,accessProfile:editProfile,pagePermissions:editPages,productivityScopes:editScopes})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Modification impossible.");return;}setNotice(`Droits mis à jour pour ${editing.display_name}. Sa session active a été révoquée afin d'appliquer immédiatement le nouveau périmètre.`);setEditing(null);await load();}
  async function toggleUser(user:User){setError("");const response=await fetch("/api/auth/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set-active",userId:user.id,active:!user.is_active})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Modification impossible.");return;}await load();}
  async function resetPassword(user:User){const value=prompt(`Nouveau mot de passe temporaire pour ${user.display_name}`,generatePassword());if(!value)return;setError("");const response=await fetch("/api/auth/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reset-password",userId:user.id,temporaryPassword:value})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Réinitialisation impossible.");return;}setNotice(`Mot de passe réinitialisé pour ${user.display_name}. Pense à lui transmettre le mot de passe temporaire.`);await load();}

  const active=useMemo(()=>users.filter(user=>user.is_active).length,[users]);
  if(!me)return <main className={styles.loading}>Chargement du compte…</main>;
  const myPages=me.role==="admin"?["*"]:me.pagePermissions;
  const myScopes=me.role==="admin"?["*"]:me.productivityScopes;

  const permissionPicker=(values:string[],setter:(next:string[])=>void,disabled:boolean)=><div className={styles.optionGrid}>{PAGE_OPTIONS.map(item=><label key={item.key} className={`${styles.optionCard} ${values.includes(item.key)||hasAll(values)?styles.selected:""}`}><input type="checkbox" disabled={disabled} checked={values.includes(item.key)||hasAll(values)} onChange={()=>setter(toggle(values,item.key))}/><span><strong>{item.label}</strong><small>{item.detail}</small></span></label>)}</div>;
  const scopePicker=(values:string[],setter:(next:string[])=>void,disabled:boolean)=><><label className={`${styles.allScope} ${hasAll(values)?styles.selected:""}`}><input type="checkbox" disabled={disabled} checked={hasAll(values)} onChange={()=>setter(hasAll(values)?[]:["*"])}/><span><strong>Tous les secteurs</strong><small>Accès à toute la productivité autorisée</small></span></label><div className={styles.optionGrid}>{SCOPE_OPTIONS.map(item=><label key={item.key} className={`${styles.optionCard} ${hasAll(values)||values.includes(item.key)?styles.selected:""}`}><input type="checkbox" disabled={disabled||hasAll(values)} checked={hasAll(values)||values.includes(item.key)} onChange={()=>setter(toggle(values,item.key))}/><span><strong>{item.label}</strong><small>{item.detail}</small></span></label>)}</div></>;

  return <main className={styles.page}>
    <header><div><a href="/">← RETOUR AU REPORTING</a><span>ADMINISTRATION CRVO</span><h1>Mon compte</h1><p>{me.displayName} · {profileLabel(me.accessProfile)}</p></div>{me.mustChangePassword&&<strong>CHANGEMENT DE MOT DE PASSE REQUIS</strong>}</header>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}

    <section className={styles.myAccess}><div><span>MES ACCÈS</span><h2>{profileLabel(me.accessProfile)}</h2></div><div><b>Pages visibles</b><p>{me.role==="admin"?"Accès total, paramètres inclus":labelList(myPages,PAGE_OPTIONS)}</p></div><div><b>Productivité</b><p>{labelList(myScopes,SCOPE_OPTIONS)}</p></div></section>

    <section className={styles.grid}>
      <article className={styles.card}><span>SÉCURITÉ</span><h2>Changer mon mot de passe</h2><form onSubmit={changePassword}><label>Mot de passe actuel<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password"/></label><label>Nouveau mot de passe<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" placeholder="12 caractères minimum"/></label><button disabled={!currentPassword||newPassword.length<12}>ENREGISTRER</button></form></article>
      {me.role==="admin"&&<article className={`${styles.card} ${styles.createCard}`}><span>GESTION DES ACCÈS</span><h2>Créer un utilisateur</h2><form onSubmit={createUser}><div className={styles.twoCols}><label>Nom affiché<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Ex. Yohan VELLE"/></label><label>Identifiant<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="Ex. yohan.velle"/></label></div><label>Profil d'accès<select value={accessProfile} onChange={e=>applyCreateProfile(e.target.value as AccessProfile)}><option value="custom">Accès personnalisé</option><option value="service_manager">Chef de service · tout hors paramètres</option><option value="admin">ADMIN · accès total</option></select></label><fieldset><legend>Pages visibles</legend><p>{accessProfile==="admin"?"ADMIN : toutes les pages et les paramètres.":accessProfile==="service_manager"?"Chef de service : toutes les pages opérationnelles, sans les paramètres.":"Sélectionne précisément ce que cette personne verra."}</p>{permissionPicker(pagePermissions,setPagePermissions,accessProfile!=="custom")}</fieldset><fieldset><legend>Périmètre de productivité</legend><p>Ce filtre est appliqué côté serveur : l'utilisateur ne reçoit jamais les secteurs non autorisés.</p>{scopePicker(productivityScopes,setProductivityScopes,accessProfile==="admin")}</fieldset><label>Mot de passe temporaire<div className={styles.passwordRow}><input value={temporaryPassword} onChange={e=>setTemporaryPassword(e.target.value)}/><button type="button" onClick={()=>setTemporaryPassword(generatePassword())}>GÉNÉRER</button></div></label><button disabled={!username||temporaryPassword.length<12||(accessProfile==="custom"&&!pagePermissions.length)}>CRÉER L'ACCÈS</button></form></article>}
    </section>

    {me.role==="admin"&&<section className={styles.users}><div className={styles.usersHead}><div><span>UTILISATEURS AUTORISÉS</span><h2>{active} accès actifs</h2></div><small>Les droits peuvent être modifiés à tout moment. Une modification de périmètre force une nouvelle connexion.</small></div><div className={styles.userTable}>{users.map(user=><div key={user.id} className={!user.is_active?styles.disabled:""}><div><strong>{user.display_name}</strong><span>{user.username} · {profileLabel(user.access_profile??(user.role==="admin"?"admin":"custom"))}</span><small className={styles.accessLine}>Pages : {user.role==="admin"?"Toutes":labelList(user.page_permissions,PAGE_OPTIONS)} · Productivité : {user.role==="admin"?"Tous secteurs":labelList(user.productivity_scopes,SCOPE_OPTIONS)}</small></div><em>{user.is_active?"ACTIF":"DÉSACTIVÉ"}</em><small>{user.must_change_password?"Mot de passe à changer":user.last_login_at?`Dernière connexion ${new Date(user.last_login_at).toLocaleString("fr-FR")}`:"Jamais connecté"}</small><div className={styles.actions}><button onClick={()=>openRights(user)}>DROITS</button><button onClick={()=>resetPassword(user)}>RÉINITIALISER MDP</button><button onClick={()=>toggleUser(user)}>{user.is_active?"DÉSACTIVER":"RÉACTIVER"}</button></div></div>)}</div></section>}

    {me.role==="admin"&&editing&&<section id="rights-editor" className={styles.rightsEditor}><div className={styles.usersHead}><div><span>PROFIL & DROITS</span><h2>{editing.display_name}</h2><p>{editing.username}</p></div><button className={styles.closeButton} onClick={()=>setEditing(null)}>FERMER</button></div><label className={styles.editorSelect}>Profil d'accès<select value={editProfile} onChange={e=>applyEditProfile(e.target.value as AccessProfile)}><option value="custom">Accès personnalisé</option><option value="service_manager">Chef de service · tout hors paramètres</option><option value="admin">ADMIN · accès total</option></select></label><div className={styles.editorBlock}><h3>Pages visibles</h3>{permissionPicker(editPages,setEditPages,editProfile!=="custom")}</div><div className={styles.editorBlock}><h3>Productivité autorisée</h3>{scopePicker(editScopes,setEditScopes,editProfile==="admin")}</div><div className={styles.editorActions}><button onClick={()=>setEditing(null)}>ANNULER</button><button className={styles.saveButton} onClick={saveRights}>ENREGISTRER LES DROITS</button></div></section>}
  </main>;
}
