"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./account.module.css";

type AccessProfile="admin"|"service_manager"|"team_manager"|"custom"|"transphere"|"transphere_manager"|"hr"|"trainer";
type User={id:string;username:string;display_name:string;role:"admin"|"user";is_active:boolean;must_change_password:boolean;created_at:string;last_login_at:string|null;access_profile:AccessProfile;page_permissions:string[];productivity_scopes:string[];team_scopes:string[];can_manage_bonus_workflow:boolean};
type Me={id:string;username:string;displayName:string;role:"admin"|"user";accessProfile:AccessProfile;pagePermissions:string[];productivityScopes:string[];teamScopes:string[];canManageBonusWorkflow:boolean;mustChangePassword:boolean};
type Option={key:string;label:string;detail:string};
type Position={key:string;entity:"CRVO"|"TRANSPHERE";name:string;title:string;level:string;parent?:string|null;teams:string[];sectors:string[];allAccess:boolean;preferredProfile:AccessProfile;shiftGroup?:string|null;userId?:string|null;username?:string|null};

const PAGE_OPTIONS:Option[]=[
  {key:"reporting",label:"Reporting principal",detail:"Performance opérationnelle du reporting"},
  {key:"productivity",label:"Productivité",detail:"Productivité par secteur, équipe et collaborateur"},
  {key:"monthly_animation",label:"Animation mensuelle",detail:"Primes, workflow, validations et historique figé"},
  {key:"book",label:"Book / CA / goulots",detail:"Dashboard, goulots, Walking Dead, chiffre d'affaires et Book"},
  {key:"cockpit",label:"CRVO Cockpit V2",detail:"Pilotage, synthèse, décisions et prévisions"},
  {key:"bodyshop",label:"Focus carrosserie",detail:"Cockpit spécifique carrosserie"},
  {key:"client_dashboard",label:"Dashboard client",detail:"Vues Réseau et BMW / MINI"},
  {key:"intelligence",label:"Analyse / intelligence",detail:"Analyses et aide à la décision"},
  {key:"worktime",label:"Temps de travail",detail:"Déclarations, absences, retards, départs et suivi RH"},
  {key:"training",label:"Formation & compétences",detail:"Pilotage des compétences, évaluations, parcours, planning et traçabilité formateur"},
  {key:"transphere",label:"Transphère",detail:"Dashboard et reporting Transphère"},
  {key:"settings",label:"Paramètres métier",detail:"Objectifs, seuils, sources et connexions"},
  {key:"data_rh",label:"Data RH",detail:"Imports RH, temps facturés, CA et OR en cours"},
];
const SCOPE_OPTIONS:Option[]=[
  {key:"expertise",label:"Expertise",detail:"Expertise + expertise dynamique"},{key:"qualite",label:"Qualité",detail:"Qualité + opérateurs qualité"},{key:"mecanique",label:"Mécanique",detail:"Mécanique"},{key:"carrosserie",label:"Carrosserie",detail:"Fixline, Box et tôlerie"},{key:"dsp",label:"DSP",detail:"DSP"},{key:"preparation",label:"Préparation",detail:"Préparation"},{key:"photo",label:"Photo",detail:"Photo"},{key:"jantes",label:"Jantes",detail:"Jantes"},{key:"lavage",label:"Lavage",detail:"Lavage"},{key:"magasin",label:"Magasin",detail:"Magasin, acheteurs et labo peinture"},{key:"diagnostic",label:"Diagnostic",detail:"Transverse / diagnostic"},{key:"jockey",label:"Jockey",detail:"Jockey"},{key:"encadrement",label:"Encadrement",detail:"Chefs d'équipe"},{key:"administratif",label:"Administratif",detail:"Administratif"},{key:"autre",label:"Autre / entretien",detail:"Entretien et autres"},
];
const TEAM_OPTIONS:Option[]=[
  {key:"A",label:"Équipe A",detail:"Collaborateurs affectés à l'équipe A"},
  {key:"B",label:"Équipe B",detail:"Collaborateurs affectés à l'équipe B"},
  {key:"C",label:"Équipe C",detail:"Collaborateurs affectés à l'équipe C"},
  {key:"J",label:"Journée / transverse",detail:"Équipe ou organisation de journée"},
  {key:"TRANSPHERE",label:"Transphère",detail:"Équipe Transphère"},
];
const ALL_PAGES=PAGE_OPTIONS.map(item=>item.key);
const SERVICE_MANAGER_PAGES=ALL_PAGES.filter(key=>!["settings","data_rh","transphere"].includes(key));
const SECTOR_LABEL:Record<string,string>={expertise:"Expertise",mecanique:"Mécanique",carrosserie:"Carrosserie",preparation:"Préparation",qualite:"Qualité",magasin:"Magasin / MPR",admin:"Administratif",transphere:"Transphère"};

function generatePassword(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%_-";const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);return Array.from(bytes,b=>chars[b%chars.length]).join("");}
function slug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,".").replace(/^\.|\.$/g,"").slice(0,40);}
function profileLabel(value:AccessProfile){if(value==="admin")return"ADMIN";if(value==="service_manager")return"CHEF DE SERVICE";if(value==="team_manager")return"MANAGER / CHEF D'ÉQUIPE";if(value==="trainer")return"FORMATEUR";if(value==="transphere")return"TRANSPHÈRE UNIQUEMENT";if(value==="transphere_manager")return"RESPONSABLE TRANSPHÈRE";if(value==="hr")return"RH GLOBAL";return"ACCÈS PERSONNALISÉ";}
function hasAll(values:string[]|undefined){return Boolean(values?.includes("*"));}
function labelList(values:string[]|undefined,options:Option[],allLabel="Tous"){if(hasAll(values))return allLabel;const set=new Set(values??[]);return options.filter(item=>set.has(item.key)).map(item=>item.label).join(", ")||"Aucun";}
function toggle(values:string[],key:string){return values.includes(key)?values.filter(item=>item!==key):[...values.filter(item=>item!=="*"),key];}
function positionScope(position:Position){const teams=position.teams.includes("*")?"Toutes équipes":position.teams.map(team=>`Équipe ${team}`).join(" / ");const sectors=position.sectors.includes("*")?"Tous secteurs":position.sectors.map(sector=>SECTOR_LABEL[sector]??sector).join(" / ");return`${teams} · ${sectors}`;}

export default function AccountPage(){
  const[me,setMe]=useState<Me|null>(null);const[users,setUsers]=useState<User[]>([]);const[positions,setPositions]=useState<Position[]>([]);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[currentPassword,setCurrentPassword]=useState("");const[newPassword,setNewPassword]=useState("");
  const[username,setUsername]=useState("");const[displayName,setDisplayName]=useState("");const[temporaryPassword,setTemporaryPassword]=useState(generatePassword());const[accessProfile,setAccessProfile]=useState<AccessProfile>("custom");const[pagePermissions,setPagePermissions]=useState<string[]>(["productivity"]);const[productivityScopes,setProductivityScopes]=useState<string[]>(["*"]);const[teamScopes,setTeamScopes]=useState<string[]>([]);const[positionKey,setPositionKey]=useState("");
  const[editing,setEditing]=useState<User|null>(null);const[editProfile,setEditProfile]=useState<AccessProfile>("custom");const[editPages,setEditPages]=useState<string[]>([]);const[editScopes,setEditScopes]=useState<string[]>(["*"]);const[editTeams,setEditTeams]=useState<string[]>([]);

  async function load(){const response=await fetch("/api/auth/me",{cache:"no-store"});if(!response.ok){location.href="/login";return;}const payload=await response.json();setMe(payload.user);if(payload.user.role==="admin"){const[usersResponse,orgResponse]=await Promise.all([fetch("/api/auth/users",{cache:"no-store"}),fetch("/api/worktime?organization=1",{cache:"no-store"})]);if(usersResponse.ok){const data=await usersResponse.json();setUsers(data.users??[]);}if(orgResponse.ok){const data=await orgResponse.json();setPositions(data.positions??[]);}}}
  useEffect(()=>{void load();},[]);

  const selectedPosition=useMemo(()=>positions.find(position=>position.key===positionKey)??null,[positions,positionKey]);
  const positionByUser=useMemo(()=>new Map(positions.filter(position=>position.userId).map(position=>[position.userId!,position])),[positions]);
  const availablePositions=useMemo(()=>positions.filter(position=>!position.userId),[positions]);

  function applyCreateProfile(profile:AccessProfile){setPositionKey("");setAccessProfile(profile);if(profile==="admin"){setPagePermissions(["*"]);setProductivityScopes(["*"]);setTeamScopes(["*"]);}else if(profile==="hr"){setPagePermissions(["worktime","data_rh","training"]);setProductivityScopes(["*"]);setTeamScopes(["*"]);}else if(profile==="trainer"){setPagePermissions(["training"]);setProductivityScopes([]);setTeamScopes([]);}else if(profile==="transphere"){setPagePermissions(["transphere"]);setProductivityScopes([]);setTeamScopes([]);}else if(profile==="transphere_manager"){setPagePermissions(["transphere","worktime"]);setProductivityScopes([]);setTeamScopes(["TRANSPHERE"]);}else if(profile==="service_manager"){setPagePermissions(SERVICE_MANAGER_PAGES);if(!productivityScopes.length)setProductivityScopes(["*"]);setTeamScopes(["*"]);}else if(profile==="team_manager"){setPagePermissions(["reporting","worktime"]);setProductivityScopes([]);setTeamScopes(current=>hasAll(current)?[]:current);}else{setPagePermissions(current=>hasAll(current)?["productivity"]:current);setTeamScopes(current=>hasAll(current)?[]:current);}}
  function applyPosition(key:string){setPositionKey(key);const position=positions.find(item=>item.key===key);if(!position)return;setDisplayName(position.name);setUsername(slug(position.name));setAccessProfile(position.preferredProfile);setProductivityScopes(position.preferredProfile==="admin"?["*"]:[]);setTeamScopes(position.preferredProfile==="admin"?["*"]:position.preferredProfile==="transphere_manager"?["TRANSPHERE"]:position.teams);if(position.preferredProfile==="admin")setPagePermissions(["*"]);else if(position.preferredProfile==="transphere_manager")setPagePermissions(["transphere","worktime"]);else setPagePermissions(["reporting","worktime"]);}
  function applyEditProfile(profile:AccessProfile){setEditProfile(profile);if(profile==="admin"){setEditPages(["*"]);setEditScopes(["*"]);setEditTeams(["*"]);}else if(profile==="hr"){setEditPages(["worktime","data_rh","training"]);setEditScopes(["*"]);setEditTeams(["*"]);}else if(profile==="trainer"){setEditPages(["training"]);setEditScopes([]);setEditTeams([]);}else if(profile==="transphere"){setEditPages(["transphere"]);setEditScopes([]);setEditTeams([]);}else if(profile==="transphere_manager"){setEditPages(["transphere","worktime"]);setEditScopes([]);setEditTeams(["TRANSPHERE"]);}else if(profile==="service_manager"){setEditPages(SERVICE_MANAGER_PAGES);if(!editScopes.length)setEditScopes(["*"]);setEditTeams(["*"]);}else if(profile==="team_manager"){setEditPages(["reporting","worktime"]);setEditScopes([]);setEditTeams(current=>hasAll(current)?[]:current);}else{setEditPages(current=>hasAll(current)?["productivity"]:current);setEditTeams(current=>hasAll(current)?[]:current);}}
  function openRights(user:User){setEditing(user);setEditProfile(user.access_profile??(user.role==="admin"?"admin":"custom"));setEditPages(user.role==="admin"?["*"]:(user.page_permissions??[]));setEditScopes(user.role==="admin"?["*"]:(user.productivity_scopes??[]));setEditTeams(user.role==="admin"?["*"]:(user.team_scopes??[]));setTimeout(()=>document.getElementById("rights-editor")?.scrollIntoView({behavior:"smooth",block:"start"}),0);}

  async function changePassword(event:FormEvent){event.preventDefault();setError("");setNotice("");const response=await fetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Modification impossible.");return;}setCurrentPassword("");setNewPassword("");setNotice("Mot de passe modifié.");await load();}
  async function bindPosition(userId:string,key:string){if(!key)return;const response=await fetch("/api/worktime",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"bind-position",positionKey:key,userId})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Rattachement à l'organigramme impossible.");}
  async function createUser(event:FormEvent){event.preventDefault();setError("");setNotice("");const profile=selectedPosition?.preferredProfile??accessProfile;const teams=selectedPosition?(profile==="admin"?["*"]:profile==="transphere_manager"?["TRANSPHERE"]:selectedPosition.teams):teamScopes;const response=await fetch("/api/auth/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,displayName,temporaryPassword,accessProfile:profile,pagePermissions,productivityScopes,teamScopes:teams})});const payload=await response.json().catch(()=>({})) as{error?:string;userId?:string};if(!response.ok||!payload.userId){setError(payload.error||"Création impossible.");return;}try{if(selectedPosition)await bindPosition(payload.userId,selectedPosition.key);}catch(cause){setError(cause instanceof Error?cause.message:"Rattachement à l'organigramme impossible.");await load();return;}setNotice(`Accès créé pour ${displayName||username}${selectedPosition?` · ${selectedPosition.title}`:""}. Mot de passe temporaire : ${temporaryPassword}`);setUsername("");setDisplayName("");setTemporaryPassword(generatePassword());setAccessProfile("custom");setPositionKey("");setPagePermissions(["productivity"]);setProductivityScopes(["*"]);setTeamScopes([]);await load();}
  async function saveRights(){if(!editing)return;setError("");setNotice("");const response=await fetch("/api/auth/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update-access",userId:editing.id,accessProfile:editProfile,pagePermissions:editPages,productivityScopes:editScopes,teamScopes:editTeams})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Modification impossible.");return;}setNotice(`Droits mis à jour pour ${editing.display_name}. Sa session active a été révoquée afin d'appliquer immédiatement le nouveau périmètre.`);setEditing(null);await load();}
  async function toggleUser(user:User){setError("");const response=await fetch("/api/auth/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set-active",userId:user.id,active:!user.is_active})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Modification impossible.");return;}await load();}
  async function resetPassword(user:User){const value=prompt(`Nouveau mot de passe temporaire pour ${user.display_name}`,generatePassword());if(!value)return;setError("");const response=await fetch("/api/auth/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reset-password",userId:user.id,temporaryPassword:value})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Réinitialisation impossible.");return;}setNotice(`Mot de passe réinitialisé pour ${user.display_name}. Pense à lui transmettre le mot de passe temporaire.`);await load();}

  const active=useMemo(()=>users.filter(user=>user.is_active).length,[users]);
  if(!me)return <main className={styles.loading}>Chargement du compte…</main>;
  const myPages=me.role==="admin"?["*"]:me.pagePermissions;const myScopes=me.role==="admin"?["*"]:me.productivityScopes;const myTeams=me.role==="admin"?["*"]:me.teamScopes;
  const lockedPreset=accessProfile!=="custom";

  const permissionPicker=(values:string[],setter:(next:string[])=>void,disabled:boolean)=><div className={styles.optionGrid}>{PAGE_OPTIONS.map(item=><label key={item.key} className={`${styles.optionCard} ${values.includes(item.key)||hasAll(values)?styles.selected:""}`}><input type="checkbox" disabled={disabled} checked={values.includes(item.key)||hasAll(values)} onChange={()=>setter(toggle(values,item.key))}/><span><strong>{item.label}</strong><small>{item.detail}</small></span></label>)}</div>;
  const scopePicker=(values:string[],setter:(next:string[])=>void,disabled:boolean,allowAll=true)=><>{allowAll&&<label className={`${styles.allScope} ${hasAll(values)?styles.selected:""}`}><input type="checkbox" disabled={disabled} checked={hasAll(values)} onChange={()=>setter(hasAll(values)?[]:["*"])}/><span><strong>Tous les secteurs</strong><small>Accès à tout le périmètre métier</small></span></label>}<div className={styles.optionGrid}>{SCOPE_OPTIONS.map(item=><label key={item.key} className={`${styles.optionCard} ${hasAll(values)||values.includes(item.key)?styles.selected:""}`}><input type="checkbox" disabled={disabled||hasAll(values)} checked={hasAll(values)||values.includes(item.key)} onChange={()=>setter(toggle(values,item.key))}/><span><strong>{item.label}</strong><small>{item.detail}</small></span></label>)}</div></>;
  const teamPicker=(values:string[],setter:(next:string[])=>void,disabled:boolean)=><div className={styles.optionGrid}>{TEAM_OPTIONS.map(item=><label key={item.key} className={`${styles.optionCard} ${hasAll(values)||values.includes(item.key)?styles.selected:""}`}><input type="checkbox" disabled={disabled||hasAll(values)} checked={hasAll(values)||values.includes(item.key)} onChange={()=>setter(toggle(values,item.key))}/><span><strong>{item.label}</strong><small>{item.detail}</small></span></label>)}</div>;

  return <main className={styles.page}>
    <header><div><a href="/">← RETOUR AU REPORTING</a><span>ADMINISTRATION KPI</span><h1>Mon compte & accès</h1><p>{me.displayName} · {profileLabel(me.accessProfile)}</p></div>{me.mustChangePassword&&<strong>CHANGEMENT DE MOT DE PASSE REQUIS</strong>}</header>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}

    <section className={styles.myAccess}><div><span>MES ACCÈS</span><h2>{profileLabel(me.accessProfile)}</h2>{me.canManageBonusWorkflow&&<p><b>OUVERTURE / CLÔTURE PAYPLAN : AUTORISÉE</b></p>}</div><div><b>Pages visibles</b><p>{me.role==="admin"?"Accès total, paramètres inclus":labelList(myPages,PAGE_OPTIONS)}</p></div><div><b>Périmètre</b><p>{labelList(myScopes,SCOPE_OPTIONS,"Tous secteurs")} · {labelList(myTeams,TEAM_OPTIONS,"Toutes équipes")}</p></div></section>

    <section className={styles.grid}>
      <article className={styles.card}><span>SÉCURITÉ</span><h2>Changer mon mot de passe</h2><form onSubmit={changePassword}><label>Mot de passe actuel<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password"/></label><label>Nouveau mot de passe<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" placeholder="12 caractères minimum"/></label><button disabled={!currentPassword||newPassword.length<12}>ENREGISTRER</button></form></article>

      {me.role==="admin"&&<article className={`${styles.card} ${styles.createCard}`}><span>GESTION DES ACCÈS</span><h2>Créer un utilisateur</h2><p className={styles.helperText}>Tous les accès sont désormais créés ici : CRVO, Temps de travail, Formation, RH et Transphère.</p><form onSubmit={createUser}>
        <fieldset><legend>TYPE D'ACCÈS</legend><label>Poste dans l'organigramme Temps de travail<select value={positionKey} onChange={e=>applyPosition(e.target.value)}><option value="">Aucun poste · utiliser un profil standard</option><optgroup label="CRVO LENS">{availablePositions.filter(p=>p.entity==="CRVO").map(p=><option key={p.key} value={p.key}>{p.name} · {p.title}</option>)}</optgroup><optgroup label="TRANSPHÈRE">{availablePositions.filter(p=>p.entity==="TRANSPHERE").map(p=><option key={p.key} value={p.key}>{p.name} · {p.title}</option>)}</optgroup></select></label>{selectedPosition&&<div className={styles.presetInfo}><strong>{selectedPosition.entity} · {selectedPosition.title}</strong><span>{positionScope(selectedPosition)}</span><small>Le périmètre Temps de travail sera calculé automatiquement par l'organigramme et verrouillé côté serveur.</small></div>}
        <label>Ou profil standard<select value={accessProfile} disabled={Boolean(selectedPosition)} onChange={e=>applyCreateProfile(e.target.value as AccessProfile)}><option value="custom">Accès personnalisé</option><option value="team_manager">Manager / Chef d'équipe</option><option value="service_manager">Chef de service</option><option value="hr">RH global · CRVO + Transphère</option><option value="trainer">Formateur · Formation & compétences</option><option value="transphere">Transphère uniquement</option><option value="transphere_manager">Responsable Transphère + Temps de travail</option><option value="admin">Administrateur · accès total</option></select></label></fieldset>
        <div className={styles.twoCols}><label>Nom affiché<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Ex. Nom Prénom" required/></label><label>Identifiant<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="Ex. prenom.nom" required/></label></div>
        <label>Mot de passe temporaire<div className={styles.passwordRow}><input value={temporaryPassword} onChange={e=>setTemporaryPassword(e.target.value)}/><button type="button" onClick={()=>setTemporaryPassword(generatePassword())}>GÉNÉRER</button></div></label>
        {!selectedPosition&&accessProfile==="custom"&&<><fieldset><legend>PAGES VISIBLES</legend><p>Sélectionne uniquement les modules nécessaires.</p>{permissionPicker(pagePermissions,setPagePermissions,false)}</fieldset><fieldset><legend>PÉRIMÈTRE PRODUCTIVITÉ</legend>{scopePicker(productivityScopes,setProductivityScopes,false)}</fieldset><fieldset><legend>ÉQUIPES</legend>{teamPicker(teamScopes,setTeamScopes,false)}</fieldset></>}
        {!selectedPosition&&accessProfile==="team_manager"&&<fieldset><legend>ÉQUIPES DU MANAGER</legend><p>Pour un périmètre plus précis équipe + secteur, utilise de préférence un poste de l'organigramme ci-dessus.</p>{teamPicker(teamScopes,setTeamScopes,false)}</fieldset>}
        {!selectedPosition&&lockedPreset&&accessProfile!=="team_manager"&&<div className={styles.presetInfo}><strong>{profileLabel(accessProfile)}</strong><span>Les droits de ce profil sont appliqués automatiquement.</span><small>{accessProfile==="trainer"?"Accès exclusivement dédié à Formation & compétences : collaborateurs carrosserie, évaluations, observations, plans et planning.":accessProfile==="hr"?"Vue globale Temps de travail, Data RH et Formation & compétences.":accessProfile==="transphere"?"Dashboard et reporting Transphère uniquement, sans accès CRVO.":accessProfile==="transphere_manager"?"Transphère + déclaration Temps de travail de l'équipe Transphère.":accessProfile==="admin"?"Accès complet à toutes les entités et tous les réglages.":"Profil métier prédéfini."}</small></div>}
        <button disabled={!username||!displayName||temporaryPassword.length<12}>CRÉER L'ACCÈS</button>
      </form></article>}
    </section>

    {me.role==="admin"&&<section className={styles.users}><div className={styles.usersHead}><div><span>UTILISATEURS</span><h2>{active} actifs · {users.length} comptes</h2></div><small>Un seul référentiel pour CRVO, Temps de travail, Formation et Transphère. Les postes d'organigramme sont affichés directement ci-dessous.</small></div><div className={styles.userTable}>{users.map(user=>{const position=positionByUser.get(user.id);return <div key={user.id} className={!user.is_active?styles.disabled:""}><div><strong>{user.display_name}</strong><span>{user.username} · {profileLabel(user.access_profile)}</span>{position&&<small className={styles.accessLine}>{position.entity} · {position.title} · {positionScope(position)}</small>}</div><em>{user.is_active?"ACTIF":"INACTIF"}</em><small>{user.last_login_at?`Dernière connexion ${new Date(user.last_login_at).toLocaleString("fr-FR")}`:"Jamais connecté"}</small><div className={styles.actions}><button onClick={()=>openRights(user)}>DROITS</button><button onClick={()=>resetPassword(user)}>MOT DE PASSE</button><button onClick={()=>toggleUser(user)}>{user.is_active?"DÉSACTIVER":"RÉACTIVER"}</button></div></div>})}</div></section>}

    {me.role==="admin"&&editing&&<section id="rights-editor" className={styles.rightsEditor}><div className={styles.usersHead}><div><span>MODIFIER LES DROITS</span><h2>{editing.display_name}</h2></div><button className={styles.closeButton} onClick={()=>setEditing(null)}>FERMER</button></div>{positionByUser.get(editing.id)&&<div className={styles.presetInfo}><strong>POSTE ORGANIGRAMME : {positionByUser.get(editing.id)!.title}</strong><span>{positionScope(positionByUser.get(editing.id)!)}</span><small>Le périmètre Temps de travail reste piloté par ce poste. Les réglages ci-dessous concernent le profil général du compte.</small></div>}<label className={styles.editorSelect}>Profil<select value={editProfile} onChange={e=>applyEditProfile(e.target.value as AccessProfile)}><option value="custom">Accès personnalisé</option><option value="team_manager">Manager / Chef d'équipe</option><option value="service_manager">Chef de service</option><option value="hr">RH global</option><option value="trainer">Formateur</option><option value="transphere">Transphère uniquement</option><option value="transphere_manager">Responsable Transphère</option><option value="admin">Administrateur</option></select></label>{editProfile==="custom"&&<><div className={styles.editorBlock}><h3>Pages visibles</h3>{permissionPicker(editPages,setEditPages,false)}</div><div className={styles.editorBlock}><h3>Périmètre productivité</h3>{scopePicker(editScopes,setEditScopes,false)}</div><div className={styles.editorBlock}><h3>Équipes</h3>{teamPicker(editTeams,setEditTeams,false)}</div></>}{editProfile==="team_manager"&&<div className={styles.editorBlock}><h3>Équipes</h3>{teamPicker(editTeams,setEditTeams,false)}</div>}<div className={styles.editorActions}><button onClick={()=>setEditing(null)}>ANNULER</button><button className={styles.saveButton} onClick={()=>void saveRights()}>ENREGISTRER LES DROITS</button></div></section>}
  </main>;
}
