import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const SUPABASE_URL = "https://tvmkhvfmdstkunwwuzuz.supabase.co";
const SUPABASE_KEY = "sb_publishable_bGCdOoq05alXNTOtouIQcQ_HX9jpKnv";
const ANON_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bWtodmZtZHN0a3Vud3d1enV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0NTU4NjQsImV4cCI6MjEwMjAzMTg2NH0.w18MDX_dL1YarUElTeo9ID0Egivav18tVqjjbkCaOxc";
const EDGE_BASE = `${SUPABASE_URL}/functions/v1`;

const SECTORS = [
  { key:"expertise", label:"Expertise", cadence:80, threshold:160, target:90, production:"expertise" },
  { key:"chiffrage", label:"Chiffrage", cadence:50, threshold:25, target:null, production:null },
  { key:"controle_technique", label:"Contrôle technique", cadence:50, threshold:70, target:null, production:"technical_control" },
  { key:"dsp", label:"DSP", cadence:30, threshold:80, target:48, production:"dsp" },
  { key:"jantes", label:"Jantes", cadence:35, threshold:80, target:null, production:"wheels" },
  { key:"mecanique", label:"Mécanique", cadence:80, threshold:160, target:85, production:"mechanics" },
  { key:"carrosserie", label:"Carrosserie", cadence:50, threshold:200, target:63, production:"bodywork" },
  { key:"parc_travaux", label:"Parc travaux", cadence:80, threshold:300, target:null, production:null },
  { key:"preparation", label:"Préparation", cadence:80, threshold:150, target:90, production:"preparation" },
  { key:"qualite", label:"Qualité", cadence:90, threshold:150, target:90, production:"quality" },
  { key:"sortie_usine", label:"Sortie usine", cadence:92, threshold:150, target:92, production:"available" },
] as const;

type Vehicle = {
  registration:string|null; work_order:string|null; client:string|null; vin:string|null; model:string|null; status:string|null;
  status_age_days:number|string|null; effective_factory_age_days:number|string|null; alert:string|null; urgency:string|null; part_available:string|null;
  pending_sector_keys:string[]|null; pending_sector_count:number|string|null; current_sector_key:string|null; blocking_cause:string|null;
  actionable_now:boolean|null; priority_score:number|string|null; latest_source_modified_at:string|null;
};
type Snapshot = { date:string; at:string; received:number; expertise:number; mechanics:number; bodywork:number; dsp:number; preparation:number; quality:number; wheels:number; technical_control:number; available:number };
type Flow = { key:string; avgEntries:number; avgExits:number; avgNet:number; daysObserved?:number; lastEventDate?:string|null };

function n(value:unknown){const x=Number(value);return Number.isFinite(x)?x:0;}
function avg(values:number[]){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}
function round(value:number,digits=1){const factor=10**digits;return Math.round(value*factor)/factor;}
function parisDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function parisMinutes(value:string){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Paris",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));return Number(parts.find(p=>p.type==="hour")?.value??0)*60+Number(parts.find(p=>p.type==="minute")?.value??0);}
function risk(ratio:number,over20:number,urgent:number){if(ratio>=1.4||over20>=25||urgent>=8)return "critique" as const;if(ratio>=1||over20>=10||urgent>=3)return "tension" as const;return "maitrise" as const;}
function riskRank(level:string){return level==="critique"?3:level==="tension"?2:1;}
function labelFor(key:string){return SECTORS.find(s=>s.key===key)?.label??key;}
function normalizedStatus(value:unknown){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/\s+/g," ");}
function isPreparationWorkshopWork(vehicle:Vehicle){const status=normalizedStatus(vehicle.status);return status==="en attente de preparation"||status==="preparation en cours";}

async function rest<T>(path:string):Promise<T>{const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY,Accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`Supabase ${response.status}`);return response.json() as Promise<T>;}
async function restAll<T>(path:string,max=5000):Promise<T[]>{const rows:T[]=[];for(let offset=0;offset<max;offset+=1000){const separator=path.includes("?")?"&":"?";const chunk=await rest<T[]>(`${path}${separator}limit=1000&offset=${offset}`);rows.push(...chunk);if(chunk.length<1000)break;}return rows;}
async function edge<T>(name:string):Promise<T>{const response=await fetch(`${EDGE_BASE}/${name}`,{headers:{Authorization:`Bearer ${ANON_JWT}`,apikey:ANON_JWT,Accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`${name} ${response.status}`);return response.json() as Promise<T>;}

function projectProduction(rawSnapshots:Snapshot[]){
  const today=parisDate();const all=rawSnapshots.filter(s=>s.date<=today).sort((a,b)=>a.at.localeCompare(b.at));const todayRows=all.filter(s=>s.date===today);if(!todayRows.length)return {latestAt:null,snapshotCount:0,profileDays:0,sectors:[]};
  const latest=todayRows.at(-1)!;const first=todayRows[0];const previous=todayRows.length>1?todayRows.at(-2)!:first;const elapsed=Math.max((new Date(latest.at).getTime()-new Date(first.at).getTime())/3600000,.25);const recentElapsed=Math.max((new Date(latest.at).getTime()-new Date(previous.at).getTime())/3600000,.25);const remaining=Math.max(0,(20*60-parisMinutes(latest.at))/60);const currentMinute=parisMinutes(latest.at);const historicalDates=[...new Set(all.map(s=>s.date).filter(date=>date<today))];
  const sectors=SECTORS.filter(s=>s.production&&s.target).map(s=>{const field=s.production as keyof Snapshot;const current=n(latest[field]);const paceAll=Math.max(0,(current-n(first[field]))/elapsed);const paceRecent=Math.max(0,(current-n(previous[field]))/recentElapsed);const paceProjection=current+(paceRecent*.6+paceAll*.4)*remaining;const fractions:number[]=[];for(const date of historicalDates){const day=all.filter(x=>x.date===date).sort((a,b)=>a.at.localeCompare(b.at));const final=day.at(-1);const comparable=day.filter(x=>parisMinutes(x.at)<=currentMinute).at(-1);if(!final||!comparable)continue;const fv=n(final[field]),cv=n(comparable[field]);if(fv>0&&cv>0){const fraction=cv/fv;if(fraction>.08&&fraction<=1.2)fractions.push(fraction);}}const profileFraction=fractions.length?avg(fractions):0;const profileProjection=profileFraction?current/profileFraction:0;const projected=Math.max(current,fractions.length>=3?profileProjection*.72+paceProjection*.28:paceProjection);const target=Number(s.target);return{key:s.key,label:s.label,current,target,projected:Math.round(projected),gapProjected:Math.round(projected-target),attainmentProjected:Math.round(projected/target*100),confidence:fractions.length>=7?"haute":fractions.length>=3?"moyenne":todayRows.length>=4?"indicative":"faible",profileDays:fractions.length};});
  return {latestAt:latest.at,snapshotCount:todayRows.length,profileDays:historicalDates.length,sectors};
}

export async function GET(request:Request){
  const mode=new URL(request.url).searchParams.get("mode")==="deep"?"deep":"live";
  try{
    const vehicleSelect="registration,work_order,client,vin,model,status,status_age_days,effective_factory_age_days,alert,urgency,part_available,pending_sector_keys,pending_sector_count,current_sector_key,blocking_cause,actionable_now,priority_score,latest_source_modified_at";
    const [vehicles,bottlenecks,dashboardRows,liveEdge] = await Promise.all([
      restAll<Vehicle>(`kpi_intelligence_vehicle_public?select=${vehicleSelect}&order=priority_score.desc.nullslast`,5000),
      rest<Array<{sector_key:string;vehicle_count:number|string;source_modified_at:string|null}>>(`kpi_bottleneck_live_public?select=sector_key,vehicle_count,source_modified_at`),
      rest<Array<{snapshot_at:string;metrics:Record<string,number>;source_modified_at:string|null}>>(`kpi_ftp_live_dashboard?select=snapshot_at,metrics,source_modified_at&limit=1`),
      edge<{ok:boolean;snapshots:Snapshot[];leadTime:any;generatedAt:string}>("kpi-intelligence-live"),
    ]);
    const bottleneckMap=new Map(bottlenecks.map(row=>[row.sector_key,n(row.vehicle_count)]));const production=projectProduction(liveEdge.snapshots??[]);const metrics=dashboardRows[0]?.metrics??{};
    const sectorRows=SECTORS.map(s=>{const pendingVehicles=vehicles.filter(v=>(v.pending_sector_keys??[]).includes(s.key));const fallbackCurrent=vehicles.filter(v=>v.current_sector_key===s.key).length;const current=s.key==="preparation"?vehicles.filter(isPreparationWorkshopWork).length:bottleneckMap.has(s.key)?bottleneckMap.get(s.key)!:fallbackCurrent;const pending=pendingVehicles.length;const urgent=pendingVehicles.filter(v=>String(v.urgency??"").toLowerCase()==="oui"||String(v.alert??"").toLowerCase().includes("urgence")).length;const over15=pendingVehicles.filter(v=>n(v.effective_factory_age_days)>15).length;const over20=pendingVehicles.filter(v=>n(v.effective_factory_age_days)>20).length;const ages=pendingVehicles.map(v=>n(v.effective_factory_age_days));const priorities=pendingVehicles.filter(v=>v.actionable_now!==false).sort((a,b)=>n(b.priority_score)-n(a.priority_score)).slice(0,10).map(v=>({registration:v.registration,workOrder:v.work_order,client:v.client,status:v.status,ageDays:round(n(v.effective_factory_age_days)),statusAgeDays:round(n(v.status_age_days)),alert:v.alert,urgency:v.urgency,pending:v.pending_sector_keys,score:Math.round(n(v.priority_score))}));return{key:s.key,label:s.label,cadence:s.cadence,threshold:s.threshold,current,pending,currentDefinition:s.key==="preparation"?"En attente de préparation + Préparation en cours":"Photo encours atelier EtatduParc",futureLoad:Math.max(0,pending-current),daysOfDemand:round(pending/s.cadence,2),urgent,over15,over20,avgAge:round(avg(ages)),ageBuckets:{d0_2:ages.filter(a=>a<=2).length,d3_5:ages.filter(a=>a>2&&a<=5).length,d6_10:ages.filter(a=>a>5&&a<=10).length,d11_15:ages.filter(a=>a>10&&a<=15).length,over15:ages.filter(a=>a>15).length},risk:risk(current/s.threshold,over20,urgent),priorities};});
    const walkingVehicles=vehicles.filter(v=>n(v.effective_factory_age_days)>15);const causeMap=new Map<string,{cause:string;vehicles:number;over20:number;over30:number;ages:number[]}>();for(const v of walkingVehicles){const cause=v.blocking_cause||"Autre / à qualifier";const x=causeMap.get(cause)??{cause,vehicles:0,over20:0,over30:0,ages:[]};x.vehicles++;if(n(v.effective_factory_age_days)>20)x.over20++;if(n(v.effective_factory_age_days)>30)x.over30++;x.ages.push(n(v.effective_factory_age_days));causeMap.set(cause,x);}const walkingCauses=[...causeMap.values()].map(x=>({cause:x.cause,vehicles:x.vehicles,over20:x.over20,over30:x.over30,avgAge:round(avg(x.ages)),maxAge:round(Math.max(...x.ages))})).sort((a,b)=>b.vehicles-a.vehicles||b.maxAge-a.maxAge);const walkingTop=[...walkingVehicles].sort((a,b)=>n(b.effective_factory_age_days)-n(a.effective_factory_age_days)).slice(0,30).map(v=>({registration:v.registration,workOrder:v.work_order,client:v.client,status:v.status,cause:v.blocking_cause,ageDays:round(n(v.effective_factory_age_days)),statusAgeDays:round(n(v.status_age_days)),alert:v.alert,partAvailable:v.part_available,pending:v.pending_sector_keys}));
    const critical=sectorRows.filter(s=>s.risk==="critique"),watch=sectorRows.filter(s=>s.risk==="tension");const under=production.sectors.filter(p=>p.projected<p.target*.9);const weatherNow=critical.length>=2?{level:"critique",title:"Usine sous forte tension",detail:`${critical.length} secteurs critiques à traiter immédiatement.`}:critical.length||watch.length>=3?{level:"tension",title:"Usine sous tension",detail:`${critical.length} critique(s) et ${watch.length} secteur(s) à surveiller.`}:{level:"stable",title:"Situation maîtrisée",detail:"Aucun signal majeur de saturation immédiate."};const weatherTonight=under.length>=3?{level:"critique",title:"Clôture du jour en risque",detail:`${under.length} secteurs projetés nettement sous cible.`}:under.length?{level:"tension",title:"Clôture à sécuriser",detail:`${under.map(p=>p.label).join(", ")} sous trajectoire.`}:{level:"stable",title:"Trajectoire de clôture correcte",detail:"Les projections disponibles restent proches des objectifs."};
    const actions=[...sectorRows].sort((a,b)=>riskRank(b.risk)-riskRank(a.risk)||b.over20-a.over20||b.pending-a.pending).slice(0,5).map((s,index)=>({rank:index+1,sectorKey:s.key,sectorLabel:s.label,title:s.risk==="critique"?`Sécuriser ${s.label}`:`Surveiller ${s.label}`,detail:`${s.current} encours · ${s.pending} à traiter · ${s.over20} dossiers >20 j`,vehicles:s.priorities.slice(0,3)}));
    const base:any={connected:true,mode:"live",generatedAt:new Date().toISOString(),sourceModifiedAt:vehicles.map(v=>v.latest_source_modified_at).filter(Boolean).sort().at(-1)??dashboardRows[0]?.source_modified_at??null,summary:{stock:n(metrics.factory_stock),over15:n(metrics.stock_over_15d),over20:n(metrics.stock_over_20d),activeVehicles:vehicles.length,walkingVehicles:walkingVehicles.length},weather:{now:weatherNow,tonight:weatherTonight},sectors:sectorRows,production,actions,walking:{causes:walkingCauses,top:walkingTop},leadTime:liveEdge.leadTime??null,learning:{productionProfileDays:production.profileDays,projectionMode:production.profileDays>=3?"profil historique + cadence du jour":"cadence du jour · apprentissage en cours"}};
    if(mode==="live")return NextResponse.json(base,{headers:{"Cache-Control":"public, max-age=45, stale-while-revalidate=60"}});
    const [deepEdge,reworkEdge] = await Promise.all([
      edge<{ok:boolean;historyDays:number;lastEventDate:string|null;flow:Flow[];stageDurations:any[]}>("kpi-intelligence-deep"),
      edge<{ok:boolean;vehiclesWithRework:number;totalRepeatEntries:number;qualityReturns:number;bySector:Array<{sectorKey:string;vehicles:number;repeatEntries:number}>}>("kpi-intelligence-rework"),
    ]);
    const flowMap=new Map((deepEdge.flow??[]).map(row=>[row.key,row]));const forecast=sectorRows.map(s=>{const f=flowMap.get(s.key)??{key:s.key,avgEntries:0,avgExits:0,avgNet:0};const net=n(f.avgNet);const d1=Math.max(0,Math.round(s.current+net)),d2=Math.max(0,Math.round(d1+net)),d3=Math.max(0,Math.round(d2+net));return{key:s.key,label:s.label,current:s.current,pending:s.pending,avgEntries:n(f.avgEntries),avgExits:n(f.avgExits),avgNet:n(f.avgNet),d1,d2,d3,riskD1:risk(d1/s.threshold,s.over20,s.urgent)};});const tomorrowCritical=forecast.filter(f=>f.riskD1==="critique"),tomorrowWatch=forecast.filter(f=>f.riskD1==="tension");base.mode="deep";base.forecast=forecast;base.flow=deepEdge.flow;base.stageDurations=deepEdge.stageDurations;base.rework=reworkEdge;base.learning.statusHistoryDays=deepEdge.historyDays;base.learning.lastHistoryDate=deepEdge.lastEventDate;base.weather.tomorrow=tomorrowCritical.length>=2?{level:"critique",title:"Demain matin à risque",detail:`${tomorrowCritical.map(f=>f.label).join(", ")} projetés critiques.`}:tomorrowCritical.length||tomorrowWatch.length>=3?{level:"tension",title:"Demain matin sous tension",detail:`Surveiller ${[...tomorrowCritical,...tomorrowWatch].slice(0,4).map(f=>f.label).join(", ")}.`}:{level:"stable",title:"Demain matin maîtrisé",detail:"Pas de saturation majeure projetée sur la tendance récente."};
    return NextResponse.json(base,{headers:{"Cache-Control":"public, max-age=300, stale-while-revalidate=300"}});
  }catch(error){console.error(JSON.stringify({event:"intelligence_api_failed",message:error instanceof Error?error.message:"unknown"}));return NextResponse.json({connected:false,error:"Pilotage prédictif temporairement indisponible."},{status:503,headers:{"Cache-Control":"no-store"}});}
}
