"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./productivite.module.css";

type Row = { sectorKey:string; sectorLabel:string; workcenterKey:string; workcenterLabel:string; teamCode?:string; mechanicName?:string; boughtHours:number; soldHours:number|null; productivity:number|null; individualAvailable?:boolean };
type Payload = { month:string; availableMonths:string[]; totals:{boughtHours:number;soldHours:number;productivity:number|null}; sectors:Row[]; teams:Row[]; collaborators:Row[]; error?:string };

function currentMonth(){const parts=new Intl.DateTimeFormat("fr-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit"}).formatToParts(new Date());return `${parts.find(p=>p.type==="year")?.value}-${parts.find(p=>p.type==="month")?.value}`;}
function hours(value:number|null|undefined){return Number(value??0).toLocaleString("fr-FR",{minimumFractionDigits:1,maximumFractionDigits:1});}
function pct(value:number|null|undefined){return value==null?"—":`${Number(value).toLocaleString("fr-FR",{minimumFractionDigits:1,maximumFractionDigits:1})} %`;}
function monthLabel(value:string){const [year,month]=value.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(year,month-1,1));}
function tone(value:number|null){if(value==null)return "";if(value>=100)return styles.good;if(value>=85)return styles.watch;return styles.low;}

export default function ProductivitePage(){
  const [month,setMonth]=useState(currentMonth()); const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [view,setView]=useState<"sector"|"team"|"person">("sector"); const [sector,setSector]=useState("all");
  useEffect(()=>{let active=true;setLoading(true);setError("");fetch(`/api/productivity?month=${encodeURIComponent(month)}`,{cache:"no-store"}).then(async r=>{const p=await r.json() as Payload;if(!r.ok||p.error)throw new Error(p.error||`HTTP ${r.status}`);if(active)setData(p);}).catch(e=>active&&setError(e instanceof Error?e.message:"Lecture impossible")).finally(()=>active&&setLoading(false));return()=>{active=false};},[month]);
  const sectorOptions=useMemo(()=>{const map=new Map<string,string>();(data?.sectors??[]).forEach(row=>map.set(row.workcenterKey,`${row.sectorLabel} · ${row.workcenterLabel}`));return [...map.entries()].sort((a,b)=>a[1].localeCompare(b[1],"fr"));},[data]);
  const rows=useMemo(()=>{const source=view==="sector"?data?.sectors:view==="team"?data?.teams:data?.collaborators;return (source??[]).filter(row=>sector==="all"||row.workcenterKey===sector);},[data,view,sector]);
  return <main className={styles.page}>
    <header className={styles.hero}><div><a href="/" className={styles.back}>← PERFORMANCE</a><span>PERFORMANCE MENSUELLE</span><h1>Productivité</h1><p>Heures vendues ÷ heures de présence. Les codes RH de présence alimentent les heures achetées ; les temps pointés facturés alimentent les heures vendues.</p></div><div className={styles.filters}><label>Mois<select value={month} onChange={e=>setMonth(e.target.value)}>{[...new Set([month,...(data?.availableMonths??[])])].sort().reverse().map(item=><option key={item} value={item}>{monthLabel(item)}</option>)}</select></label><label>Secteur<select value={sector} onChange={e=>setSector(e.target.value)}><option value="all">Tous les secteurs</option>{sectorOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div></header>
    {error&&<div className={styles.error}>{error}</div>}
    <section className={styles.kpis}><article><span>HEURES ACHETÉES</span><strong>{loading?"…":hours(data?.totals.boughtHours)} h</strong><small>Présence métier confirmée</small></article><article><span>HEURES VENDUES</span><strong>{loading?"…":hours(data?.totals.soldHours)} h</strong><small>Interventions facturées</small></article><article><span>PRODUCTIVITÉ</span><strong className={tone(data?.totals.productivity??null)}>{loading?"…":pct(data?.totals.productivity)}</strong><small>Vendu / acheté</small></article></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><span>LECTURE</span><h2>{view==="sector"?"Par secteur":view==="team"?"Par équipe":"Par collaborateur"}</h2></div><div className={styles.tabs}><button className={view==="sector"?styles.active:""} onClick={()=>setView("sector")}>Secteurs</button><button className={view==="team"?styles.active:""} onClick={()=>setView("team")}>Équipes</button><button className={view==="person"?styles.active:""} onClick={()=>setView("person")}>Collaborateurs</button></div></div>
      <div className={styles.notice}><b>FIXLINE</b><span>Pas de productivité individuelle. Les heures facturées sont mesurées au niveau de l’équipe et attribuées aux superviseurs A / B / C ; les collaborateurs Fixline affichent donc « Équipe uniquement ».</span></div>
      <div className={styles.tableWrap}><table><thead><tr><th>{view==="person"?"Collaborateur":"Secteur / activité"}</th>{view!=="sector"&&<th>Équipe</th>}{view==="person"&&<th>Activité</th>}<th>Heures achetées</th><th>Heures vendues</th><th>Productivité</th></tr></thead><tbody>{!loading&&rows.map((row,index)=><tr key={`${row.mechanicName??row.workcenterKey}-${row.teamCode??""}-${index}`}><td><strong>{view==="person"?row.mechanicName:`${row.sectorLabel} · ${row.workcenterLabel}`}</strong></td>{view!=="sector"&&<td><span className={styles.team}>{row.teamCode==="NON_AFFECTEE"?"—":row.teamCode}</span></td>}{view==="person"&&<td>{row.sectorLabel} · {row.workcenterLabel}</td>}<td>{hours(row.boughtHours)} h</td><td>{view==="person"&&row.individualAvailable===false?<em>Équipe uniquement</em>:`${hours(row.soldHours)} h`}</td><td><b className={tone(row.productivity)}>{view==="person"&&row.individualAvailable===false?"Équipe uniquement":pct(row.productivity)}</b></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={6} className={styles.empty}>Aucune donnée pour ce filtre et ce mois.</td></tr>}</tbody></table></div>
    </section>
  </main>;
}
