"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./formation.module.css";

type Person={employeeKey:string;employeeName:string;matricule?:string|null;team?:string|null;service?:string|null};
type Skill={id:string;skillKey:string;label:string;indicator?:string|null;sourceRef?:string|null;sortOrder:number};
type Block={key:string;code:string;label:string;description?:string|null;sortOrder:number;skills:Skill[]};
type Track={key:string;label:string;levelLabel?:string|null;description?:string|null;sourceLabel?:string|null;sortOrder:number;blocks:Block[]};
type Trainer={id:string;displayName:string;specialty:string;active:boolean;userId?:string|null;notes?:string|null};
type Plan={id:string;employeeKey:string;employeeName:string;matricule?:string|null;team?:string|null;service?:string|null;trackKey:string;status:string;priority:string;targetDate?:string|null;objective?:string|null;trainerId?:string|null;trainerName?:string|null;createdByName?:string|null;createdAt:string;updatedAt:string};
type Evaluation={id:string;employeeKey:string;employeeName:string;trackKey:string;evaluationDate:string;kind:string;sessionId?:string|null;overallScore?:number|null;overallPct?:number|null;pilotageLevel?:string|null;summary?:string|null;evaluatorName?:string|null;createdAt:string;items?:Array<{skillId:string;skillKey:string;skillLabel:string;blockKey:string;score:number;observation?:string|null}>};
type Legacy={id:string;employeeKey?:string|null;employeeName:string;teamLabel?:string|null;trackKey:string;blockScores:Record<string,{points?:number|string|null;pct?:number|string|null}>;overallPoints?:number|null;overallPct?:number|null;legacyStatus?:string|null;comments?:string|null;sourceSheet:string;sourceEvaluationDate?:string|null;importedAt:string};
type SessionRow={id:string;title:string;trackKey:string;trainerId?:string|null;trainerName?:string|null;startAt:string;endAt:string;status:string;location?:string|null;objective?:string|null;focusSkillKeys:string[];notes?:string|null;participants:Array<{employeeKey:string;employeeName:string;status:string;preEvaluationId?:string|null;postEvaluationId?:string|null}>};
type Observation={id:string;employeeKey:string;employeeName:string;category:string;content:string;sessionId?:string|null;trackKey?:string|null;createdByName?:string|null;createdAt:string};
type Dashboard={access:{userId:string;displayName:string;profile:string;canEdit:boolean;canAdmin:boolean};people:Person[];tracks:Track[];trainers:Trainer[];plans:Plan[];evaluations:Evaluation[];legacySnapshots:Legacy[];sessions:SessionRow[];observations:Observation[];error?:string};
type Detail={person:Person;evaluations:Evaluation[];legacySnapshots:Legacy[];plans:Plan[];sessions:SessionRow[];observations:Observation[]};
type Tab="pilotage"|"collaborateurs"|"matrice"|"planning"|"referentiels";
type ScoreCell={pct:number|null;label:string;source:"evaluation"|"legacy"|"none";date?:string|null;partial?:boolean};

const TABS:[Tab,string][]=[["pilotage","Pilotage"],["collaborateurs","Collaborateurs"],["matrice","Matrice de compétences"],["planning","Planning"],["referentiels","Référentiels"]];
const SCORE_LABELS=["0 · Non acquis","1 · En cours d’acquisition","2 · Acquis","3 · Maîtrisé / Autonome"];
const PRIORITY_LABEL:Record<string,string>={critical:"Critique",high:"Haute",normal:"Normale",low:"Basse"};
const STATUS_LABEL:Record<string,string>={to_plan:"À planifier",planned:"Planifiée",in_progress:"En cours",completed:"Terminée",on_hold:"En attente",cancelled:"Annulée"};
const KIND_LABEL:Record<string,string>={baseline:"Évaluation de départ",checkpoint:"Point intermédiaire",post_training:"Après formation",final:"Évaluation finale"};
const OBS_LABEL:Record<string,string>={observation:"Observation",progress:"Progrès",alert:"Point de vigilance",action:"Action à mener",feedback:"Retour formateur"};

function todayParis(){return new Intl.DateTimeFormat("fr-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function fmtPct(value:number|null|undefined){return value==null||!Number.isFinite(Number(value))?"—":`${Math.round(Number(value)*100)} %`;}
function dateLabel(value?:string|null){if(!value)return"Date non renseignée";return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value.slice(0,10)}T12:00:00`));}
function dateTimeLabel(value:string){return new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
function trackLabel(tracks:Track[],key:string){return tracks.find(item=>item.key===key)?.label??key;}
function scoreTone(pct:number|null){if(pct==null)return"unknown";if(pct<.5)return"critical";if(pct<.67)return"warning";if(pct<.84)return"progress";return"good";}
function latestScore(data:Dashboard|Detail,employeeKey:string,trackKey:string):ScoreCell{
  const formal=(data.evaluations??[]).filter(e=>e.employeeKey===employeeKey&&e.trackKey===trackKey).sort((a,b)=>`${b.evaluationDate}${b.createdAt}`.localeCompare(`${a.evaluationDate}${a.createdAt}`))[0];
  if(formal)return{pct:formal.overallPct==null?null:Number(formal.overallPct),label:formal.pilotageLevel??KIND_LABEL[formal.kind]??"Évaluation",source:"evaluation",date:formal.evaluationDate};
  const legacy=(data.legacySnapshots??[]).filter(e=>e.employeeKey===employeeKey&&e.trackKey===trackKey)[0];
  if(legacy)return{pct:legacy.overallPct==null?null:Number(legacy.overallPct),label:legacy.legacyStatus||"Historique",source:"legacy",date:legacy.sourceEvaluationDate,partial:/partiel/i.test(`${legacy.comments??""} ${legacy.legacyStatus??""}`)};
  return{pct:null,label:"À évaluer",source:"none"};
}
function personNeed(data:Dashboard,person:Person){
  const plans=data.plans.filter(p=>p.employeeKey===person.employeeKey&&!['completed','cancelled'].includes(p.status));
  const cells=data.tracks.map(t=>latestScore(data,person.employeeKey,t.key)).filter(c=>c.source!=="none"&&c.pct!=null);
  const min=cells.length?Math.min(...cells.map(c=>Number(c.pct))):null;
  if(plans.some(p=>p.priority==="critical")||min!=null&&min<.5)return{rank:0,label:"Priorité critique",tone:"critical"};
  if(plans.some(p=>p.priority==="high")||min!=null&&min<.67)return{rank:1,label:"Formation prioritaire",tone:"warning"};
  if(plans.length)return{rank:2,label:"Parcours en cours",tone:"progress"};
  if(!cells.length)return{rank:4,label:"À évaluer",tone:"unknown"};
  return{rank:3,label:"Suivi",tone:"good"};
}

export default function FormationPage(){
  const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[tab,setTab]=useState<Tab>("pilotage");
  const[search,setSearch]=useState("");const[team,setTeam]=useState("*");const[service,setService]=useState("*");const[selected,setSelected]=useState<Person|null>(null);const[detail,setDetail]=useState<Detail|null>(null);const[detailLoading,setDetailLoading]=useState(false);
  const[evalTrack,setEvalTrack]=useState("");const[evalKind,setEvalKind]=useState("baseline");const[evalDate,setEvalDate]=useState(todayParis());const[evalSummary,setEvalSummary]=useState("");const[scores,setScores]=useState<Record<string,{score:number;observation:string}>>({});
  const[obsCategory,setObsCategory]=useState("observation");const[obsContent,setObsContent]=useState("");const[obsTrack,setObsTrack]=useState("");
  const[planTrack,setPlanTrack]=useState("");const[planPriority,setPlanPriority]=useState("normal");const[planStatus,setPlanStatus]=useState("to_plan");const[planTarget,setPlanTarget]=useState("");const[planObjective,setPlanObjective]=useState("");const[planTrainer,setPlanTrainer]=useState("");
  const[sessionTitle,setSessionTitle]=useState("");const[sessionTrack,setSessionTrack]=useState("");const[sessionTrainer,setSessionTrainer]=useState("");const[sessionStart,setSessionStart]=useState("");const[sessionEnd,setSessionEnd]=useState("");const[sessionLocation,setSessionLocation]=useState("Zone formation carrosserie");const[sessionObjective,setSessionObjective]=useState("");const[participants,setParticipants]=useState<string[]>([]);

  async function load(){setLoading(true);setError("");try{const response=await fetch(`/api/training?_=${Date.now()}`,{cache:"no-store"});const payload=await response.json()as Dashboard;if(!response.ok)throw new Error(payload.error||"Chargement impossible.");setData(payload);if(!evalTrack&&payload.tracks[0])setEvalTrack(payload.tracks[0].key);if(!planTrack&&payload.tracks[0])setPlanTrack(payload.tracks[0].key);if(!sessionTrack&&payload.tracks[0])setSessionTrack(payload.tracks[0].key);if(!sessionTrainer&&payload.trainers.find(t=>t.active))setSessionTrainer(payload.trainers.find(t=>t.active)!.id);}catch(cause){setError(cause instanceof Error?cause.message:"Chargement impossible.");setData(null);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);

  async function openPerson(person:Person){setSelected(person);setDetail(null);setDetailLoading(true);setNotice("");try{const response=await fetch(`/api/training?employeeKey=${encodeURIComponent(person.employeeKey)}&_=${Date.now()}`,{cache:"no-store"});const payload=await response.json()as Detail&{error?:string};if(!response.ok)throw new Error(payload.error||"Fiche indisponible.");setDetail(payload);const used=(payload.evaluations?.[0]?.trackKey||payload.legacySnapshots?.[0]?.trackKey||payload.plans?.[0]?.trackKey||data?.tracks[0]?.key||"");setEvalTrack(used);setPlanTrack(used);setObsTrack(used);setScores({});setEvalSummary("");setObsContent("");}catch(cause){setError(cause instanceof Error?cause.message:"Fiche indisponible.");}finally{setDetailLoading(false);}}
  function closePerson(){setSelected(null);setDetail(null);setScores({});}
  async function post(body:Record<string,unknown>){setError("");setNotice("");const response=await fetch("/api/training",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}))as{error?:string};if(!response.ok)throw new Error(payload.error||"Enregistrement impossible.");return payload;}
  async function saveEvaluation(){if(!selected||!evalTrack)return;const payloadScores=Object.entries(scores).map(([skillId,value])=>({skillId,score:value.score,observation:value.observation||null}));try{await post({action:"save-evaluation",employeeKey:selected.employeeKey,trackKey:evalTrack,evaluationDate:evalDate,kind:evalKind,summary:evalSummary,scores:payloadScores});setNotice("Évaluation enregistrée et historisée.");setScores({});setEvalSummary("");await load();await openPerson(selected);}catch(cause){setError(cause instanceof Error?cause.message:"Évaluation impossible.");}}
  async function saveObservation(){if(!selected||!obsContent.trim())return;try{await post({action:"add-observation",employeeKey:selected.employeeKey,category:obsCategory,content:obsContent,trackKey:obsTrack||null});setNotice("Observation ajoutée à la fiche du collaborateur.");setObsContent("");await load();await openPerson(selected);}catch(cause){setError(cause instanceof Error?cause.message:"Observation impossible.");}}
  async function savePlan(){if(!selected||!planTrack)return;try{await post({action:"save-plan",employeeKey:selected.employeeKey,trackKey:planTrack,status:planStatus,priority:planPriority,targetDate:planTarget||null,objective:planObjective,trainerId:planTrainer||null});setNotice("Plan de formation enregistré.");setPlanObjective("");setPlanTarget("");await load();await openPerson(selected);}catch(cause){setError(cause instanceof Error?cause.message:"Plan impossible.");}}
  async function saveSession(){if(!sessionTitle.trim()||!sessionTrack||!sessionStart||!sessionEnd)return;try{await post({action:"save-session",title:sessionTitle,trackKey:sessionTrack,trainerId:sessionTrainer||null,startAt:new Date(sessionStart).toISOString(),endAt:new Date(sessionEnd).toISOString(),status:"planned",location:sessionLocation,objective:sessionObjective,focusSkillKeys:[],participantKeys:participants,notes:null});setNotice("Session de formation planifiée.");setSessionTitle("");setSessionObjective("");setParticipants([]);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Planification impossible.");}}

  const filteredPeople=useMemo(()=>{if(!data)return[];const q=search.trim().toLocaleLowerCase("fr");return data.people.filter(p=>(team==="*"||p.team===team)&&(service==="*"||p.service===service)&&(!q||`${p.employeeName} ${p.matricule??""}`.toLocaleLowerCase("fr").includes(q)));},[data,search,team,service]);
  const teams=useMemo(()=>Array.from(new Set((data?.people??[]).map(p=>p.team).filter(Boolean)as string[])).sort(),[data]);
  const services=useMemo(()=>Array.from(new Set((data?.people??[]).map(p=>p.service).filter(Boolean)as string[])).sort(),[data]);
  const priorities=useMemo(()=>!data?[]:data.people.map(person=>({person,need:personNeed(data,person)})).filter(x=>x.need.rank<=2).sort((a,b)=>a.need.rank-b.need.rank||a.person.employeeName.localeCompare(b.person.employeeName,"fr")),[data]);
  const evaluatedPeople=useMemo(()=>!data?0:new Set([...data.evaluations.map(e=>e.employeeKey),...data.legacySnapshots.map(l=>l.employeeKey).filter(Boolean)as string[]]).size,[data]);
  const upcoming=useMemo(()=>!data?[]:data.sessions.filter(s=>s.status==="planned"&&new Date(s.endAt)>=new Date()).sort((a,b)=>a.startAt.localeCompare(b.startAt)),[data]);
  const selectedTrack=data?.tracks.find(t=>t.key===evalTrack)??null;
  const selectedFormalScore=selected&&data?latestScore(data,selected.employeeKey,evalTrack):null;

  return <main className={styles.page}>
    <header className={styles.hero}>
      <div><p className={styles.eyebrow}>DÉVELOPPEMENT DES COMPÉTENCES · CARROSSERIE</p><h1>Formation & compétences</h1><p>Identifier les besoins, planifier les formations et mesurer la progression avant / après avec une traçabilité complète.</p></div>
      <div className={styles.heroMeta}><span>ACCÈS MÉTIER</span><strong>{data?.access.displayName??"—"}</strong><small>{data?.access.profile==="trainer"?"Formateur":data?.access.profile==="hr"?"RH":data?.access.profile==="service_manager"?"Chef de service":data?.access.profile==="admin"?"Administrateur":data?.access.profile??""}</small></div>
    </header>
    <nav className={styles.tabs}>{TABS.map(([key,label])=><button key={key} className={tab===key?styles.activeTab:""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{loading&&<div className={styles.loading}>Chargement du dispositif formation…</div>}

    {!loading&&data&&<>
      {tab==="pilotage"&&<section className={styles.stack}>
        <div className={styles.kpis}>
          <article><span>Collaborateurs carrosserie</span><strong>{data.people.length}</strong><small>effectif actuel issu du référentiel RH</small></article>
          <article><span>Déjà évalués</span><strong>{evaluatedPeople}</strong><small>{Math.max(0,data.people.length-evaluatedPeople)} sans évaluation connue</small></article>
          <article className={styles.warningKpi}><span>Parcours prioritaires</span><strong>{priorities.length}</strong><small>score faible ou plan prioritaire actif</small></article>
          <article className={styles.primaryKpi}><span>Formations planifiées</span><strong>{upcoming.length}</strong><small>{data.trainers.filter(t=>t.active).length} formateur{data.trainers.filter(t=>t.active).length>1?"s":""} actif{data.trainers.filter(t=>t.active).length>1?"s":""}</small></article>
        </div>
        <div className={styles.twoCols}>
          <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>À TRAITER</p><h2>Priorités de formation</h2></div><button onClick={()=>setTab("collaborateurs")}>Tous les collaborateurs</button></div>
            <div className={styles.priorityList}>{priorities.slice(0,14).map(({person,need})=><button key={person.employeeKey} onClick={()=>void openPerson(person)} className={styles.priorityRow}><span className={styles.avatar}>{person.employeeName.split(" ").slice(0,2).map(v=>v[0]).join("")}</span><span><strong>{person.employeeName}</strong><small>{person.service??"Carrosserie"} · Équipe {person.team??"—"}</small></span><b data-tone={need.tone}>{need.label}</b><i>›</i></button>)}{priorities.length===0&&<p className={styles.empty}>Aucune priorité active. Les collaborateurs sans baseline restent visibles dans « Collaborateurs ».</p>}</div>
          </article>
          <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>AGENDA</p><h2>Prochaines formations</h2></div><button onClick={()=>setTab("planning")}>Ouvrir le planning</button></div>
            <div className={styles.sessionList}>{upcoming.slice(0,8).map(s=><div className={styles.sessionCard} key={s.id}><time>{dateTimeLabel(s.startAt)}</time><div><strong>{s.title}</strong><small>{trackLabel(data.tracks,s.trackKey)} · {s.trainerName||"Formateur à définir"}</small></div><span>{s.participants.length} pers.</span></div>)}{upcoming.length===0&&<p className={styles.empty}>Aucune formation planifiée. Le calendrier peut être construit dès maintenant.</p>}</div>
          </article>
        </div>
        <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>ÉQUIPE FORMATION</p><h2>Formateurs carrosserie</h2></div></div><div className={styles.trainerGrid}>{data.trainers.map(t=><div className={styles.trainerCard} key={t.id}><span className={styles.trainerIcon}>F</span><div><strong>{t.displayName}</strong><small>{t.specialty}</small><p>{t.notes||"Formateur du dispositif carrosserie."}</p></div><b data-active={t.active}>{t.active?"ACTIF":"INACTIF"}</b></div>)}</div></article>
      </section>}

      {tab==="collaborateurs"&&<section className={styles.stack}>
        <div className={styles.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un collaborateur ou matricule…"/><select value={team} onChange={e=>setTeam(e.target.value)}><option value="*">Toutes les équipes</option>{teams.map(v=><option key={v} value={v}>Équipe {v}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)}><option value="*">Tous les services</option>{services.map(v=><option key={v} value={v}>{v}</option>)}</select><span>{filteredPeople.length} résultat{filteredPeople.length>1?"s":""}</span></div>
        <div className={styles.peopleGrid}>{filteredPeople.map(person=>{const need=personNeed(data,person);const known=data.tracks.map(t=>({track:t,score:latestScore(data,person.employeeKey,t.key)})).filter(x=>x.score.source!=="none");return <button className={styles.personCard} key={person.employeeKey} onClick={()=>void openPerson(person)}><div className={styles.personTop}><span className={styles.avatar}>{person.employeeName.split(" ").slice(0,2).map(v=>v[0]).join("")}</span><div><strong>{person.employeeName}</strong><small>Mat. {person.matricule||"—"} · {person.service||"Carrosserie"} · Équipe {person.team||"—"}</small></div><b data-tone={need.tone}>{need.label}</b></div><div className={styles.miniScores}>{known.length?known.slice(0,4).map(({track,score})=><span key={track.key} data-tone={scoreTone(score.pct)}><i>{track.levelLabel||track.label}</i><strong>{fmtPct(score.pct)}</strong></span>):<p>Aucune baseline connue · profil métier à évaluer</p>}</div><footer>Ouvrir la fiche de progression <i>›</i></footer></button>})}</div>
      </section>}

      {tab==="matrice"&&<section className={styles.stack}>
        <div className={styles.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher…"/><select value={team} onChange={e=>setTeam(e.target.value)}><option value="*">Toutes les équipes</option>{teams.map(v=><option key={v} value={v}>Équipe {v}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)}><option value="*">Tous les services</option>{services.map(v=><option key={v} value={v}>{v}</option>)}</select></div>
        <article className={styles.matrixPanel}><div className={styles.matrixLegend}><span data-tone="critical">&lt; 50 %</span><span data-tone="warning">50–66 %</span><span data-tone="progress">67–83 %</span><span data-tone="good">≥ 84 %</span><span data-tone="unknown">À évaluer</span></div><div className={styles.matrixScroll}><table><thead><tr><th>Collaborateur</th>{data.tracks.map(t=><th key={t.key}>{t.label}</th>)}</tr></thead><tbody>{filteredPeople.map(p=><tr key={p.employeeKey}><th><button onClick={()=>void openPerson(p)}>{p.employeeName}<small>{p.service} · {p.team||"—"}</small></button></th>{data.tracks.map(t=>{const cell=latestScore(data,p.employeeKey,t.key);return <td key={t.key}><button data-tone={scoreTone(cell.pct)} onClick={()=>void openPerson(p)}><strong>{fmtPct(cell.pct)}</strong><small>{cell.source==="legacy"?cell.partial?"Historique partiel":"Historique":cell.source==="evaluation"?cell.label:"À évaluer"}</small></button></td>})}</tr>)}</tbody></table></div></article>
      </section>}

      {tab==="planning"&&<section className={styles.planningLayout}>
        <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>NOUVELLE SESSION</p><h2>Planifier une formation</h2></div></div><div className={styles.formGrid}>
          <label className={styles.span2}>Titre<input value={sessionTitle} onChange={e=>setSessionTitle(e.target.value)} placeholder="Ex. Ponçage et préparation N1"/></label>
          <label>Parcours<select value={sessionTrack} onChange={e=>setSessionTrack(e.target.value)}>{data.tracks.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label><label>Formateur<select value={sessionTrainer} onChange={e=>setSessionTrainer(e.target.value)}><option value="">À définir</option>{data.trainers.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.displayName}</option>)}</select></label>
          <label>Début<input type="datetime-local" value={sessionStart} onChange={e=>setSessionStart(e.target.value)}/></label><label>Fin<input type="datetime-local" value={sessionEnd} onChange={e=>setSessionEnd(e.target.value)}/></label>
          <label className={styles.span2}>Lieu<input value={sessionLocation} onChange={e=>setSessionLocation(e.target.value)}/></label><label className={styles.span2}>Objectif<textarea value={sessionObjective} onChange={e=>setSessionObjective(e.target.value)} placeholder="Compétences visées, résultat attendu…"/></label>
          <div className={`${styles.span2} ${styles.participantPicker}`}><span>Participants · {participants.length} sélectionné{participants.length>1?"s":""}</span><div>{data.people.map(p=><label key={p.employeeKey}><input type="checkbox" checked={participants.includes(p.employeeKey)} onChange={e=>setParticipants(current=>e.target.checked?[...current,p.employeeKey]:current.filter(k=>k!==p.employeeKey))}/><span>{p.employeeName}<small>{p.service} · {p.team||"—"}</small></span></label>)}</div></div>
          <button className={`${styles.primaryButton} ${styles.span2}`} onClick={()=>void saveSession()}>Planifier la session</button>
        </div></article>
        <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>CALENDRIER</p><h2>Sessions de formation</h2></div></div><div className={styles.fullSessionList}>{data.sessions.map(s=><article key={s.id} data-status={s.status}><div className={styles.sessionDate}><strong>{new Intl.DateTimeFormat("fr-FR",{day:"2-digit"}).format(new Date(s.startAt))}</strong><span>{new Intl.DateTimeFormat("fr-FR",{month:"short"}).format(new Date(s.startAt))}</span></div><div><h3>{s.title}</h3><p>{trackLabel(data.tracks,s.trackKey)} · {s.trainerName||"Formateur à définir"}</p><small>{dateTimeLabel(s.startAt)} → {new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(new Date(s.endAt))} · {s.location||"Lieu à définir"}</small>{s.objective&&<p className={styles.sessionObjective}>{s.objective}</p>}<div className={styles.chips}>{s.participants.map(p=><button key={p.employeeKey} onClick={()=>{const person=data.people.find(x=>x.employeeKey===p.employeeKey);if(person)void openPerson(person);}}>{p.employeeName}</button>)}</div></div><b>{s.status==="planned"?"PLANIFIÉE":s.status==="completed"?"TERMINÉE":"ANNULÉE"}</b></article>)}</div></article>
      </section>}

      {tab==="referentiels"&&<section className={styles.stack}>
        <article className={styles.scalePanel}><div><p className={styles.eyebrow}>RÈGLE COMMUNE</p><h2>Échelle d’évaluation</h2><p>L'échelle reprend les grilles existantes. Le pourcentage sert uniquement au pilotage du module ; l'évaluation détaillée reste la donnée de référence.</p></div><div>{SCORE_LABELS.map((v,i)=><span key={v} data-score={i}><b>{i}</b>{v.split(" · ")[1]}</span>)}</div></article>
        <div className={styles.referenceGrid}>{data.tracks.map(t=><article className={styles.referenceCard} key={t.key}><header><span>{t.levelLabel||"Métier"}</span><h2>{t.label}</h2><p>{t.description}</p><small>Source : {t.sourceLabel}</small></header>{t.blocks.map(b=><section key={b.key}><h3><span>{b.code}</span>{b.label}</h3><ul>{b.skills.map(s=><li key={s.id}><strong>{s.label}</strong>{s.indicator&&<small>{s.indicator}</small>}</li>)}</ul></section>)}</article>)}</div>
      </section>}
    </>}

    {selected&&data&&<><button className={styles.drawerBackdrop} onClick={closePerson} aria-label="Fermer la fiche"/><aside className={styles.drawer}>
      <header><div className={styles.avatar}>{selected.employeeName.split(" ").slice(0,2).map(v=>v[0]).join("")}</div><div><p className={styles.eyebrow}>FICHE DE PROGRESSION</p><h2>{selected.employeeName}</h2><span>Mat. {selected.matricule||"—"} · {selected.service||"Carrosserie"} · Équipe {selected.team||"—"}</span></div><button onClick={closePerson}>×</button></header>
      {detailLoading?<div className={styles.loading}>Chargement de l'historique…</div>:detail&&<div className={styles.drawerBody}>
        <section><div className={styles.drawerSectionHead}><div><p className={styles.eyebrow}>SYNTHÈSE</p><h3>Compétences connues</h3></div></div><div className={styles.trackScores}>{data.tracks.map(t=>{const sc=latestScore(detail,selected.employeeKey,t.key);return <button key={t.key} data-tone={scoreTone(sc.pct)} onClick={()=>{setEvalTrack(t.key);setPlanTrack(t.key);setObsTrack(t.key);}}><span>{t.label}</span><strong>{fmtPct(sc.pct)}</strong><small>{sc.source==="legacy"?`Historique${sc.partial?" · partiel":""}`:sc.source==="evaluation"?`${sc.label} · ${dateLabel(sc.date)}`:"À évaluer"}</small></button>})}</div></section>

        <section><div className={styles.drawerSectionHead}><div><p className={styles.eyebrow}>PLAN DE DÉVELOPPEMENT</p><h3>Décider qui doit être formé</h3></div></div><div className={styles.formGrid}><label>Parcours<select value={planTrack} onChange={e=>setPlanTrack(e.target.value)}>{data.tracks.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label><label>Priorité<select value={planPriority} onChange={e=>setPlanPriority(e.target.value)}><option value="critical">Critique</option><option value="high">Haute</option><option value="normal">Normale</option><option value="low">Basse</option></select></label><label>Statut<select value={planStatus} onChange={e=>setPlanStatus(e.target.value)}>{Object.entries(STATUS_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Échéance<input type="date" value={planTarget} onChange={e=>setPlanTarget(e.target.value)}/></label><label className={styles.span2}>Formateur<select value={planTrainer} onChange={e=>setPlanTrainer(e.target.value)}><option value="">À définir</option>{data.trainers.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.displayName}</option>)}</select></label><label className={styles.span2}>Objectif<textarea value={planObjective} onChange={e=>setPlanObjective(e.target.value)} placeholder="Ce que le collaborateur doit savoir faire à l'issue du parcours…"/></label><button className={`${styles.primaryButton} ${styles.span2}`} onClick={()=>void savePlan()}>Enregistrer le plan</button></div>{detail.plans.length>0&&<div className={styles.historyList}>{detail.plans.map(p=><div key={p.id}><b data-priority={p.priority}>{PRIORITY_LABEL[p.priority]||p.priority}</b><span><strong>{trackLabel(data.tracks,p.trackKey)}</strong><small>{STATUS_LABEL[p.status]||p.status}{p.targetDate?` · cible ${dateLabel(p.targetDate)}`:""}{p.trainerName?` · ${p.trainerName}`:""}</small>{p.objective&&<p>{p.objective}</p>}</span></div>)}</div>}</section>

        <section><div className={styles.drawerSectionHead}><div><p className={styles.eyebrow}>ÉVALUATION</p><h3>Mesurer avant / après</h3></div><span className={styles.previousScore}>{selectedFormalScore?.source!=="none"?`Dernier : ${fmtPct(selectedFormalScore?.pct)}`:"Pas de baseline"}</span></div><div className={styles.evalControls}><select value={evalTrack} onChange={e=>{setEvalTrack(e.target.value);setScores({});}}>{data.tracks.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select><select value={evalKind} onChange={e=>setEvalKind(e.target.value)}>{Object.entries(KIND_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input type="date" value={evalDate} onChange={e=>setEvalDate(e.target.value)}/></div>{selectedTrack&&<div className={styles.skillEditor}>{selectedTrack.blocks.map(b=><article key={b.key}><h4><span>{b.code}</span>{b.label}</h4>{b.skills.map(s=>{const v=scores[s.id];return <div className={styles.skillRow} key={s.id}><div><strong>{s.label}</strong>{s.indicator&&<small>{s.indicator}</small>}</div><div className={styles.scoreButtons}>{[0,1,2,3].map(n=><button key={n} data-selected={v?.score===n} data-score={n} onClick={()=>setScores(current=>({...current,[s.id]:{score:n,observation:current[s.id]?.observation??""}}))}>{n}</button>)}</div><input value={v?.observation??""} onChange={e=>setScores(current=>({...current,[s.id]:{score:current[s.id]?.score??0,observation:e.target.value}}))} placeholder="Observation sur cette compétence…"/></div>})}</article>)}</div>}<label className={styles.blockLabel}>Synthèse de l'évaluation<textarea value={evalSummary} onChange={e=>setEvalSummary(e.target.value)} placeholder="Points forts, écarts, gestes à retravailler, niveau d'autonomie…"/></label><button className={styles.primaryButton} onClick={()=>void saveEvaluation()}>Enregistrer l'évaluation · {Object.keys(scores).length} compétence{Object.keys(scores).length>1?"s":""}</button></section>

        <section><div className={styles.drawerSectionHead}><div><p className={styles.eyebrow}>JOURNAL FORMATEUR</p><h3>Remarques & observations</h3></div></div><div className={styles.obsComposer}><div><select value={obsCategory} onChange={e=>setObsCategory(e.target.value)}>{Object.entries(OBS_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={obsTrack} onChange={e=>setObsTrack(e.target.value)}><option value="">Observation générale</option>{data.tracks.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></div><textarea value={obsContent} onChange={e=>setObsContent(e.target.value)} placeholder="Observation factuelle, progrès constaté, difficulté, action à suivre…"/><button className={styles.secondaryButton} onClick={()=>void saveObservation()}>Ajouter au journal</button></div><div className={styles.timeline}>{detail.observations.map(o=><article key={o.id} data-category={o.category}><span/><div><header><b>{OBS_LABEL[o.category]||o.category}</b><time>{dateTimeLabel(o.createdAt)}</time></header><p>{o.content}</p><small>{o.createdByName||"Utilisateur"}{o.trackKey?` · ${trackLabel(data.tracks,o.trackKey)}`:""}</small></div></article>)}{detail.observations.length===0&&<p className={styles.empty}>Aucune observation saisie pour le moment.</p>}</div></section>

        <section><div className={styles.drawerSectionHead}><div><p className={styles.eyebrow}>TRAÇABILITÉ</p><h3>Historique des évaluations</h3></div></div><div className={styles.evalHistory}>{detail.evaluations.map(e=><article key={e.id}><div data-tone={scoreTone(e.overallPct==null?null:Number(e.overallPct))}><strong>{fmtPct(e.overallPct)}</strong><small>{e.pilotageLevel}</small></div><span><strong>{trackLabel(data.tracks,e.trackKey)} · {KIND_LABEL[e.kind]||e.kind}</strong><small>{dateLabel(e.evaluationDate)} · {e.evaluatorName||"Évaluateur"}</small>{e.summary&&<p>{e.summary}</p>}</span></article>)}{detail.legacySnapshots.map(l=><article key={l.id} className={styles.legacyRow}><div data-tone={scoreTone(l.overallPct==null?null:Number(l.overallPct))}><strong>{fmtPct(l.overallPct)}</strong><small>Historique</small></div><span><strong>{trackLabel(data.tracks,l.trackKey)} · baseline importée</strong><small>{l.sourceEvaluationDate?dateLabel(l.sourceEvaluationDate):"Date source non renseignée"} · {l.legacyStatus||"Évaluation antérieure"}</small>{l.comments&&<p>{l.comments}</p>}</span></article>)}{detail.evaluations.length===0&&detail.legacySnapshots.length===0&&<p className={styles.empty}>Aucune évaluation historique connue.</p>}</div></section>
      </div>}
    </aside></>}
  </main>;
}
