"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./capacitaire.module.css";

type StaffMember={employeeKey:string;matricule?:string|null;fullName:string;jobTitle?:string|null;sectorKey:string;sectorLabel?:string|null;teamCode?:string|null;included:boolean};
type Sector={sectorKey:string;sectorLabel:string;etp:number;people:number;observedPeople?:number;availableEtp?:number;etpSource?:string;boughtHoursPerDay:number;soldHoursPerDay:number;productivity:number|null;productionDays:number;vehiclesPerDay:number;miniHoursPerVehicle:number|null;miniHourSource:string};
type Payload={period?:{start?:string;end?:string;etpAsOf?:string};inputVehiclesPerDay?:number;sectors?:Sector[];miniStandard?:{sampleVehicles?:number;bodyshopHours?:number;mechanicsHours?:number};roster?:StaffMember[];error?:string};
type Verdict="pass"|"tension"|"critical"|"insufficient";
type Result=Sector&{baseVehicles:number;baseBought:number;baseSold:number;miniAtPost:number;miniHours:number;points:number|null;targetProd:number|null;extraEtp:number|null;verdict:Verdict;rosterTotal:number;selectedEtp:number};

const DEFLEET:Record<string,number>={"2026-09":65,"2026-10":113,"2026-11":134,"2026-12":50};
const MONTHS=Object.keys(DEFLEET);
const HIDDEN_MINI_SECTORS=new Set(["jantes","jante","photo","photos"]);
function num(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
function fmt(v:number|null|undefined,d=1){return v==null||!Number.isFinite(Number(v))?"—":Number(v).toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d})}
function monthLabel(v:string){const[y,m]=v.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(y,m-1,1)))}
function dateLabel(v?:string){return v?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`)):"—"}
function workdays(v:string){const[y,m]=v.split("-").map(Number);const last=new Date(Date.UTC(y,m,0)).getUTCDate();let total=0;for(let d=1;d<=last;d++){const day=new Date(Date.UTC(y,m-1,d)).getUTCDay();if(day!==0&&day!==6)total++}return total}
function label(v:Verdict){return v==="pass"?"PASSE":v==="tension"?"TENSION":v==="critical"?"CRITIQUE":"DONNÉE INSUFFISANTE"}
function normalizedSector(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase()}
function visibleMiniSector(sector:Sector){const key=normalizedSector(sector.sectorKey),label=normalizedSector(sector.sectorLabel);return !HIDDEN_MINI_SECTORS.has(key)&&![...HIDDEN_MINI_SECTORS].some(hidden=>label===hidden||label.includes(`${hidden} `)||label.includes(` ${hidden}`))}

export default function CapacitySimulator(){
 const[data,setData]=useState<Payload|null>(null),[month,setMonth]=useState(MONTHS[0]),[mini,setMini]=useState(DEFLEET[MONTHS[0]]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[openSector,setOpenSector]=useState<string|null>(null),[rosterSearch,setRosterSearch]=useState(""),[savingKey,setSavingKey]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/capacity-simple",{cache:"no-store"});const p=await r.json().catch(()=>({})) as Payload;if(!r.ok||p.error)throw new Error(p.error||"Calcul capacitaire indisponible.");setData(p)}catch(e){setError(e instanceof Error?e.message:"Calcul capacitaire indisponible.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const days=useMemo(()=>workdays(month),[month]);
 const rows=useMemo<Result[]>(()=>{const inbound=num(data?.inputVehiclesPerDay),roster=data?.roster??[];return(data?.sectors??[]).filter(visibleMiniSector).map(s=>{const people=roster.filter(p=>p.sectorKey===s.sectorKey),selected=people.length?people.filter(p=>p.included).length:num(s.etp);const baseVehicles=num(s.vehiclesPerDay)*days,baseBought=num(s.boughtHoursPerDay)*days,baseSold=num(s.soldHoursPerDay)*days;const pass=inbound>0?Math.min(1,Math.max(0,num(s.vehiclesPerDay)/inbound)):0;const miniAtPost=s.miniHourSource==="standard_mini_lens"?mini:mini*pass;const h=s.miniHoursPerVehicle==null?null:num(s.miniHoursPerVehicle);const miniHours=h==null?0:mini*h;const points=h!=null&&baseBought>0?miniHours/baseBought*100:null;const prod=s.productivity==null?null:num(s.productivity);const targetProd=points!=null&&prod!=null?prod+points:null;const soldPerSelectedEtp=selected>0&&baseSold>0?baseSold/selected:0;const fallbackPerEtp=7.5*days*(prod&&prod>0?prod/100:1);const capacityPerEtp=soldPerSelectedEtp>0?soldPerSelectedEtp:fallbackPerEtp;const extraEtp=h!=null&&capacityPerEtp>0?miniHours/capacityPerEtp:null;const verdict:Verdict=points==null?"insufficient":points<=5?"pass":points<=10?"tension":"critical";return{...s,etp:selected,baseVehicles,baseBought,baseSold,miniAtPost,miniHours,points,targetProd,extraEtp,verdict,rosterTotal:people.length||num(s.etp),selectedEtp:selected}})},[data,days,mini]);
 const worst=useMemo(()=>rows.filter(r=>r.points!=null).sort((a,b)=>num(b.points)-num(a.points))[0]??null,[rows]);
 const overall:Verdict=rows.some(r=>r.verdict==="critical")?"critical":rows.some(r=>r.verdict==="tension")?"tension":rows.some(r=>r.verdict==="pass")?"pass":"insufficient";
 const openRoster=useMemo(()=>{if(!openSector)return[];const q=rosterSearch.trim().toLowerCase();return(data?.roster??[]).filter(p=>p.sectorKey===openSector).filter(p=>!q||`${p.fullName} ${p.matricule??""} ${p.teamCode??""} ${p.sectorLabel??""}`.toLowerCase().includes(q))},[data,openSector,rosterSearch]);
 const openRow=rows.find(r=>r.sectorKey===openSector)??null;
 function setSelectedMonth(v:string){setMonth(v);setMini(DEFLEET[v]??0)}
 function showRoster(sectorKey:string){setOpenSector(sectorKey);setRosterSearch("")}
 async function toggleStaff(member:StaffMember){if(savingKey)return;const next=!member.included;setSavingKey(member.employeeKey);setData(prev=>prev?{...prev,roster:(prev.roster??[]).map(p=>p.employeeKey===member.employeeKey?{...p,included:next}:p)}:prev);try{const r=await fetch("/api/capacity-simple",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeKey:member.employeeKey,included:next})});const p=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(p.error||"Enregistrement impossible.")}catch(e){setData(prev=>prev?{...prev,roster:(prev.roster??[]).map(p=>p.employeeKey===member.employeeKey?{...p,included:member.included}:p)}:prev);setError(e instanceof Error?e.message:"Enregistrement impossible.")}finally{setSavingKey(null)}}
 return <main className={styles.page}>
  <header className={styles.hero}><div className={styles.heroTop}><a className={styles.back} href="/">← KPI CRVO</a><div className={styles.heroActions}><button onClick={()=>window.print()}>Imprimer / PDF</button><button onClick={()=>void load()} disabled={loading}>{loading?"Actualisation…":"Actualiser"}</button></div></div><div className={styles.heroGrid}><div><span className={styles.eyebrow}>PLANIFICATION INDUSTRIELLE · LENS</span><h1>Simulateur MINI</h1><p>Les MINI sont ajoutées au volume actuel. Le simulateur répond directement à deux questions : combien de points de productivité faut-il gagner, ou combien d'ETP faut-il ajouter ?</p></div><div className={`${styles.decision} ${styles[overall]}`}><span>DÉCISION DU MOIS</span><strong>{label(overall)}</strong><p>{worst?`${worst.sectorLabel} : +${fmt(worst.points)} points ou +${fmt(worst.extraEtp)} ETP.`:"Données insuffisantes."}</p></div></div><div className={styles.meta}><span>Période de référence : <b>{dateLabel(data?.period?.start)} → {dateLabel(data?.period?.end)}</b></span><span>MINI : <b>en complément du flux actuel</b></span><span>Effectif : <b>référentiel RH actif au {dateLabel(data?.period?.etpAsOf)}</b></span></div></header>
  {error&&<div className={styles.error}><strong>Information</strong><span>{error}</span><button onClick={()=>setError("")}>Fermer</button></div>}
  {loading&&!data&&<div className={styles.loading}>Calcul des effectifs, volumes et heures réelles…</div>}
  <section className={styles.controlPanel}><div><span>01 · VOLUME À ABSORBER</span><h2>MINI additionnelles</h2><p>Le DEFLEET Lens est préchargé. Modifie le volume pour tester un autre scénario.</p></div><div className={styles.controls}><label>Mois<select value={month} onChange={e=>setSelectedMonth(e.target.value)}>{MONTHS.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></label><label>Volume MINI<input type="number" min={0} value={mini} onChange={e=>setMini(Math.max(0,Number(e.target.value)||0))}/></label><button onClick={()=>setMini(DEFLEET[month]??0)}>Reprendre DEFLEET</button></div></section>
  <section className={styles.kpis}><article><span>MINI ADDITIONNELLES</span><strong>{fmt(mini,0)}</strong><small>{monthLabel(month)} · {days} jours ouvrés</small></article><article><span>MÉTIER LE PLUS CHARGÉ</span><strong>{worst?.sectorLabel??"—"}</strong><small>sur la base des heures réelles</small></article><article><span>PRODUCTIVITÉ À GAGNER</span><strong>{worst?.points==null?"—":`+${fmt(worst.points)} pts`}</strong><small>si effectif inchangé</small></article><article><span>ETP À AJOUTER</span><strong>{worst?.extraEtp==null?"—":`+${fmt(worst.extraEtp)}`}</strong><small>au rendement actuel par ETP sélectionné</small></article></section>
  <section className={styles.panel}><div className={styles.panelHead}><div><span>02 · PAR MÉTIER</span><h2>Est-ce que le volume passe ?</h2><p>Clique sur le nombre d'ETP pour voir les collaborateurs recensés et choisir précisément qui doit compter dans le scénario. Les choix sont enregistrés. Jantes et Photo restent hors périmètre MINI.</p></div><div className={styles.legend}><span className={styles.pass}>PASSE · ≤ +5 pts</span><span className={styles.tension}>TENSION · +5 à +10 pts</span><span className={styles.critical}>CRITIQUE · &gt; +10 pts</span></div></div><div className={styles.tableWrap}><table className={styles.capacityTable}><thead><tr><th>Métier</th><th>ETP RH actifs</th><th>Volume actuel / mois</th><th>Heures / mois</th><th>MINI au poste</th><th>Heures MINI en +</th><th>Productivité</th><th>Points à gagner</th><th>ETP en +</th><th>Verdict</th></tr></thead><tbody>{rows.map(r=><tr key={r.sectorKey}><td><strong>{r.sectorLabel}</strong><small>{r.miniHourSource==="standard_mini_lens"?"Standard MINI Lens":"Ratio Lens actuel"}{r.productionDays>0&&r.productionDays<5?` · base volume ${fmt(r.productionDays,0)} j`:""}</small></td><td><button className={styles.rosterTrigger} onClick={()=>showRoster(r.sectorKey)} title="Voir les collaborateurs comptabilisés">{fmt(r.selectedEtp,0)} <span>ETP</span></button><small>{fmt(r.selectedEtp,0)} / {fmt(r.rosterTotal,0)} personnes comptées · cliquer pour gérer</small></td><td><b>{fmt(r.baseVehicles,0)} VO</b><small>{fmt(r.vehiclesPerDay)} / jour</small></td><td><b>{fmt(r.baseSold,0)} h vendues</b><small>{fmt(r.baseBought,0)} h achetées</small></td><td><b>{fmt(r.miniAtPost,0)}</b><small>MINI estimées</small></td><td><b>{r.miniHoursPerVehicle==null?"—":`+${fmt(r.miniHours,0)} h`}</b><small>{r.miniHoursPerVehicle==null?"ratio absent":`${fmt(r.miniHoursPerVehicle,2)} h / MINI`}</small></td><td><b>{r.productivity==null?"—":`${fmt(r.productivity)} %`}</b><small>vendues ÷ achetées</small></td><td><b className={r.verdict==="critical"?styles.negative:r.verdict==="tension"?styles.warning:styles.positive}>{r.points==null?"—":`+${fmt(r.points)} pts`}</b><small>{r.targetProd==null?"":`cible ≈ ${fmt(r.targetProd)} %`}</small></td><td><b>{r.extraEtp==null?"—":`+${fmt(r.extraEtp)}`}</b><small>au rendement actuel / ETP</small></td><td><span className={`${styles.verdict} ${styles[r.verdict]}`}>{label(r.verdict)}</span></td></tr>)}</tbody></table></div></section>
  <section className={styles.explainGrid}><article className={styles.panel}><div className={styles.panelHead}><div><span>03 · COMMENT LIRE</span><h2>Deux leviers</h2></div></div><div className={styles.explainList}><div><strong>+6 points</strong><p>Le même effectif doit produire 6 % d'heures vendues en plus par rapport aux heures achetées.</p></div><div><strong>+1,2 ETP</strong><p>Alternative : ajouter 1,2 ETP au rendement actuellement constaté par ETP sélectionné.</p></div></div></article><article className={styles.panel}><div className={styles.panelHead}><div><span>04 · STANDARD MINI LENS</span><h2>Charge par dossier</h2></div></div><div className={styles.standardGrid}><div><span>CARROSSERIE + PEINTURE</span><strong>{fmt(data?.miniStandard?.bodyshopHours??7.92,2)} h</strong></div><div><span>MÉCANIQUE</span><strong>{fmt(data?.miniStandard?.mechanicsHours??1.17,2)} h</strong></div><div><span>ÉCHANTILLON</span><strong>{fmt(data?.miniStandard?.sampleVehicles??569,0)}</strong></div></div><p className={styles.note}>Pour les autres métiers, la charge MINI est estimée avec le ratio Lens actuel entre heures vendues et véhicules entrants.</p></article></section>
  <footer className={styles.footer}><strong>Règle de confiance</strong><span>Le calcul part des ETP sélectionnés, heures achetées, heures vendues et volumes réels. Une personne décochée ne compte plus dans le scénario.</span></footer>
  {openSector&&<div className={styles.rosterOverlay} onMouseDown={e=>{if(e.currentTarget===e.target)setOpenSector(null)}}><section className={styles.rosterModal}><div className={styles.rosterHead}><div><span>EFFECTIF DU SIMULATEUR</span><h2>{openRow?.sectorLabel??openSector}</h2><p><b>{openRow?.selectedEtp??0}</b> personne(s) comptée(s) sur <b>{openRow?.rosterTotal??0}</b>. Décoche une personne pour l'exclure du calcul MINI.</p></div><button className={styles.closeRoster} onClick={()=>setOpenSector(null)} aria-label="Fermer">×</button></div><input className={styles.rosterSearch} value={rosterSearch} onChange={e=>setRosterSearch(e.target.value)} placeholder="Rechercher un nom, matricule ou équipe…"/><div className={styles.rosterList}>{openRoster.map(member=><label key={member.employeeKey} className={`${styles.rosterPerson} ${member.included?styles.rosterIncluded:styles.rosterExcluded}`}><input type="checkbox" checked={member.included} disabled={savingKey===member.employeeKey} onChange={()=>void toggleStaff(member)}/><span className={styles.rosterName}><strong>{member.fullName}</strong><small>{member.sectorLabel||openRow?.sectorLabel}{member.teamCode?` · équipe ${member.teamCode}`:""}{member.matricule?` · ${member.matricule}`:""}</small></span><span className={styles.rosterState}>{savingKey===member.employeeKey?"Enregistrement…":member.included?"COMPTÉ":"EXCLU"}</span></label>)}{openRoster.length===0&&<div className={styles.rosterEmpty}>Aucun collaborateur ne correspond à la recherche.</div>}</div><div className={styles.rosterFoot}><span>La sélection est mémorisée pour les prochaines simulations.</span><button onClick={()=>setOpenSector(null)}>Terminer</button></div></section></div>}
 </main>
}
