type ExportRow = {
  sectorKey: string;
  sectorLabel: string;
  selectedEtp: number;
  baseVehicles: number;
  baseBought: number;
  baseSold: number;
  productivity: number | null;
  miniAtPost: number;
  miniHours: number;
  points: number | null;
  targetProd: number | null;
  extraEtp: number | null;
  verdict: string;
};

type ExportMatrix = {
  rowLabels: number[];
  colLabels: number[];
  values: number[][];
  currentRow: number;
  currentCol: number;
  targetRow: number;
  targetCol: number;
  currentCapacity: number;
  requiredCapacity: number;
};

export type CapacityPptInput = {
  month: string;
  monthLabel: string;
  mini: number;
  days: number;
  overall: string;
  rows: ExportRow[];
  matrix: ExportMatrix | null;
};

const C={blue:"004F9F",cyan:"009EDB",yellow:"FEC82F",red:"EB5B56",teal:"47B9B4",green:"55B779",purple:"8D5EC7",brown:"C66A1B",ink:"173447",muted:"6F8797",pale:"F2F6F9",white:"FFFFFF",line:"D9E6EE"};
const SECTOR:Record<string,string>={expertise:C.red,mecanique:C.green,dsp:C.blue,carrosserie:C.cyan,preparation:C.purple,qualite:C.brown};
const EMU=914400;
const W=13.333,H=7.5;
function e(v:string){return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")}
function n(v:number,d=1){return Number.isFinite(v)?v.toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d}):"—"}
function xy(v:number){return Math.round(v*EMU)}
function tx(id:number,text:string,x:number,y:number,w:number,h:number,size=18,color=C.ink,bold=false,align:"l"|"ctr"|"r"="l",italic=false){
  return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="Text ${id}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${xy(x)}" y="${xy(y)}"/><a:ext cx="${xy(w)}" cy="${xy(h)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/><a:p><a:pPr algn="${align}"/><a:r><a:rPr lang="fr-FR" sz="${size*100}" b="${bold?1:0}" i="${italic?1:0}"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill><a:latin typeface="Arial"/></a:rPr><a:t>${e(text)}</a:t></a:r><a:endParaRPr lang="fr-FR" sz="${size*100}"/></a:p></p:txBody></p:sp>`;
}
function box(id:number,x:number,y:number,w:number,h:number,fill:string,line=C.line,radius=true){
  return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="Shape ${id}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${xy(x)}" y="${xy(y)}"/><a:ext cx="${xy(w)}" cy="${xy(h)}"/></a:xfrm><a:prstGeom prst="${radius?"roundRect":"rect"}"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="${fill}"/></a:solidFill><a:ln w="9000"><a:solidFill><a:srgbClr val="${line}"/></a:solidFill></a:ln></p:spPr></p:sp>`;
}
function slideXml(body:string){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>${body}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`}
function titleBar(title:string,sub:string){let id=2;return box(id++,0,0,W,0.72,C.blue,C.blue,false)+tx(id++,"CRVO",0.35,0.14,0.9,0.28,18,C.white,true)+tx(id++,title,1.25,0.12,7.6,0.32,22,C.white,true)+tx(id++,sub,8.9,0.15,4.0,0.25,11,C.white,false,"r")}
function footer(){return tx(95,"VOTRE POTENTIEL VO AU PLUS HAUT",0.4,7.12,4.5,0.18,7,C.muted,true)+tx(96,"KPI CRVO · Simulation industrielle",9.0,7.12,3.9,0.18,7,C.muted,false,"r")}
function verdictLabel(v:string){return v==="critical"?"CRITIQUE":v==="tension"?"TENSION":v==="pass"?"PASSE":"DONNÉES À COMPLÉTER"}
function slideCover(d:CapacityPptInput){let id=10,b=box(id++,0,0,W,H,C.blue,C.blue,false);b+=box(id++,8.7,0,4.633,H,"0067B9","0067B9",false);b+=tx(id++,"CRVO",0.55,0.55,1.2,0.35,22,C.white,true);b+=tx(id++,"SIMULATEUR MINI",0.55,1.62,7.4,0.62,34,C.white,true,"l",true);b+=tx(id++,`${d.monthLabel} · ${d.mini} MINI additionnelles`,0.58,2.35,7.2,0.35,18,C.white,false);b+=box(id++,0.58,3.15,3.0,1.25,C.white,C.white);b+=tx(id++,"DÉCISION DU MOIS",0.82,3.43,2.5,0.24,10,C.blue,true);b+=tx(id++,verdictLabel(d.overall),0.82,3.75,2.5,0.42,24,d.overall==="critical"?C.red:d.overall==="tension"?"9A7600":C.green,true);b+=tx(id++,"Les MINI sont traitées en complément du flux Lens actuel.",0.58,5.55,7.3,0.35,13,C.white);b+=tx(id++,"Décision basée sur les heures réelles, les ETP actifs et la charge MINI par métier.",0.58,5.95,7.45,0.55,11,"D6EDF8");b+=tx(id++,"KPI CRVO",9.2,2.65,3.7,0.55,28,C.white,true,"ctr");b+=tx(id++,"CAPACITAIRE",9.2,3.28,3.7,0.45,20,C.yellow,true,"ctr");return slideXml(b)}
function slideSummary(d:CapacityPptInput){let id=10,b=titleBar("SYNTHÈSE CAPACITAIRE",`${d.monthLabel} · ${d.mini} MINI`);const loaded=[...d.rows].sort((a,b)=>b.miniHours-a.miniHours)[0];const prod=[...d.rows].filter(r=>r.points!=null).sort((a,b)=>(b.points??0)-(a.points??0))[0];const etp=[...d.rows].filter(r=>r.extraEtp!=null).sort((a,b)=>(b.extraEtp??0)-(a.extraEtp??0))[0];const cards=[["MINI ADDITIONNELLES",`${d.mini}`,`${d.days} jours ouvrés`,C.blue],["MÉTIER LE PLUS CHARGÉ",loaded?.sectorLabel??"—",loaded?`+${n(loaded.miniHours,0)} h`:"—",SECTOR[loaded?.sectorKey??""]??C.cyan],["EFFORT PROD. MAX",prod?.sectorLabel??"—",prod?.points==null?"—":`+${n(prod.points)} pts`,SECTOR[prod?.sectorKey??""]??C.red],["RENFORT ETP MAX",etp?.sectorLabel??"—",etp?.extraEtp==null?"—":`+${n(etp.extraEtp)} ETP`,SECTOR[etp?.sectorKey??""]??C.yellow]] as const;cards.forEach((c,i)=>{const x=.45+i*3.15;b+=box(id++,x,1.15,2.9,1.35,C.white,c[3]);b+=tx(id++,c[0],x+.18,1.35,2.55,.22,9,C.muted,true);b+=tx(id++,c[1],x+.18,1.72,2.55,.32,20,c[3],true);b+=tx(id++,c[2],x+.18,2.12,2.55,.24,11,C.ink,true)});b+=tx(id++,"Lecture métier",.48,2.85,3,.3,17,C.blue,true);const rows=d.rows.slice(0,6);rows.forEach((r,i)=>{const y=3.28+i*.55,col=SECTOR[r.sectorKey]??C.blue;b+=box(id++,0.48,y,0.08,.39,col,col,false);b+=tx(id++,r.sectorLabel,.68,y+.04,2.0,.24,11,C.ink,true);b+=tx(id++,`${n(r.selectedEtp,0)} ETP`,2.75,y+.04,1.05,.24,10,C.muted);b+=tx(id++,r.productivity==null?"Prod —":`Prod ${n(r.productivity)} %`,3.85,y+.04,1.35,.24,10,C.ink,true);b+=tx(id++,r.points==null?"—":`+${n(r.points)} pts`,5.28,y+.04,1.25,.24,10,r.points!=null&&r.points>10?C.red:r.points!=null&&r.points>5?"9A7600":C.green,true);b+=tx(id++,r.extraEtp==null?"—":`+${n(r.extraEtp)} ETP`,6.65,y+.04,1.25,.24,10,C.ink,true);b+=tx(id++,`+${n(r.miniHours,0)} h MINI`,8.05,y+.04,1.5,.24,10,col,true);b+=tx(id++,verdictLabel(r.verdict),10.05,y+.04,2.25,.24,10,r.verdict==="critical"?C.red:r.verdict==="tension"?"9A7600":C.green,true,"r")});b+=footer();return slideXml(b)}
function slideWorkload(d:CapacityPptInput){let id=10,b=titleBar("IMPACT INDUSTRIEL MINI",`${d.mini} MINI · ${d.monthLabel}`);b+=tx(id++,"Charge supplémentaire par métier",.5,1.08,4.5,.32,19,C.blue,true);const max=Math.max(1,...d.rows.map(r=>r.miniHours));d.rows.forEach((r,i)=>{const y=1.65+i*.72,col=SECTOR[r.sectorKey]??C.blue,w=7.3*(r.miniHours/max);b+=tx(id++,r.sectorLabel,.55,y,1.7,.25,11,C.ink,true);b+=box(id++,2.3,y,7.4,.28,"EAF1F5","EAF1F5",false);b+=box(id++,2.3,y,Math.max(.05,w),.28,col,col,false);b+=tx(id++,`+${n(r.miniHours,0)} h`,9.9,y-.01,1.0,.26,11,col,true,"r");b+=tx(id++,`${n(r.miniAtPost,0)} MINI au poste`,11.05,y-.01,1.6,.26,9,C.muted,false,"r")});b+=tx(id++,"La charge absolue identifie l'atelier qui reçoit le plus d'heures MINI. Elle est distincte de la tension relative en points de productivité.",.55,6.3,11.9,.45,11,C.muted);b+=footer();return slideXml(b)}
function slideMatrix(d:CapacityPptInput){let id=10,b=titleBar("MATRICE CARROSSERIE · BOX × FIXLINE",`${d.monthLabel} · ${d.mini} MINI`);const m=d.matrix;if(!m){b+=tx(id++,"Matrice indisponible : données Carrosserie insuffisantes.",.6,2.5,12,.5,22,C.red,true,"ctr");b+=footer();return slideXml(b)}b+=tx(id++,`Débit observé Lens : ${n(m.currentCapacity)} VO/j · besoin avec MINI : ${n(m.requiredCapacity)} VO/j`,.5,1.0,8.3,.32,16,C.blue,true);b+=tx(id++,`Repère actuel ${m.currentRow}% Box / ${m.currentCol}% Fixline · cible minimale ${m.targetRow}% / ${m.targetCol}%`,8.35,1.02,4.4,.3,10,C.muted,false,"r");const x0=.55,y0=1.55,rowH=.52,labelW=1.65,cellW=1.12;b+=box(id++,x0,y0,labelW,rowH,C.blue,C.white,false);b+=tx(id++,"Box \\ Fixline",x0+.08,y0+.14,labelW-.16,.18,9,C.white,true);m.colLabels.forEach((c,j)=>{const x=x0+labelW+j*cellW;b+=box(id++,x,y0,cellW,rowH,"5B9BD5",C.white,false);b+=tx(id++,`${c}%`,x,y0+.13,cellW,.2,10,C.white,true,"ctr")});m.rowLabels.forEach((r,i)=>{const y=y0+(i+1)*rowH;b+=box(id++,x0,y,labelW,rowH,"5B9BD5",C.white,false);b+=tx(id++,`${r}%`,x0,y+.13,labelW-.08,.2,10,C.white,true,"r");m.colLabels.forEach((c,j)=>{const x=x0+labelW+j*cellW,val=m.values[i][j],isCur=r===m.currentRow&&c===m.currentCol,isTar=r===m.targetRow&&c===m.targetCol,ok=val>=m.requiredCapacity;const fill=isCur?"FFE08A":isTar?C.cyan:ok?"E8F7F0":"EEF3F7";const color=isTar?C.white:isCur?C.blue:ok?"1B7353":C.blue;b+=box(id++,x,y,cellW,rowH,fill,C.white,false);b+=tx(id++,n(val),x,y+.13,cellW,.2,10,color,true,"ctr")})});b+=box(id++,10.6,2.0,2.1,1.05,"FFF8E4",C.yellow);b+=tx(id++,"REPÈRE ACTUEL",10.8,2.2,1.7,.2,9,"8A6900",true);b+=tx(id++,`${n(m.currentCapacity)} VO/j`,10.8,2.52,1.7,.28,18,C.blue,true);b+=box(id++,10.6,3.3,2.1,1.05,"E8F8FD",C.cyan);b+=tx(id++,"CIBLE MINI",10.8,3.5,1.7,.2,9,C.blue,true);b+=tx(id++,`${n(m.requiredCapacity)} VO/j`,10.8,3.82,1.7,.28,18,C.cyan,true);b+=tx(id++,"La matrice est recalée sur le débit Carrosserie observé à Lens. Elle conserve la sensibilité relative Box / Fixline du référentiel fourni.",.6,6.3,12,.42,10,C.muted);b+=footer();return slideXml(b)}
function slideLevers(d:CapacityPptInput){let id=10,b=titleBar("LEVIERS DE CAPACITÉ",`${d.monthLabel} · arbitrage productivité / ETP`);b+=tx(id++,"Deux leviers alternatifs — combinables",.5,1.05,6,.32,19,C.blue,true);d.rows.forEach((r,i)=>{const y=1.65+i*.78,col=SECTOR[r.sectorKey]??C.blue;b+=box(id++,.5,y,12.3,.62,C.white,col);b+=tx(id++,r.sectorLabel,.72,y+.18,1.75,.22,12,col,true);b+=tx(id++,r.productivity==null?"Prod actuelle —":`${n(r.productivity)} %`,2.6,y+.18,1.45,.22,11,C.ink,true);b+=tx(id++,r.targetProd==null?"Cible —":`→ ${n(r.targetProd)} %`,4.15,y+.18,1.4,.22,11,C.blue,true);b+=tx(id++,r.points==null?"—":`+${n(r.points)} pts`,5.7,y+.18,1.15,.22,11,r.points!=null&&r.points>10?C.red:r.points!=null&&r.points>5?"9A7600":C.green,true);b+=tx(id++,"OU",6.95,y+.18,.5,.22,9,C.muted,true,"ctr");b+=tx(id++,r.extraEtp==null?"—":`+${n(r.extraEtp)} ETP`,7.55,y+.18,1.35,.22,11,C.ink,true);b+=tx(id++,`cible ${r.extraEtp==null?"—":n(r.selectedEtp+r.extraEtp)} ETP`,9.05,y+.18,1.5,.22,10,C.muted);b+=tx(id++,verdictLabel(r.verdict),10.65,y+.18,1.85,.22,10,r.verdict==="critical"?C.red:r.verdict==="tension"?"9A7600":C.green,true,"r")});b+=footer();return slideXml(b)}
function slideActions(d:CapacityPptInput){let id=10,b=titleBar("PLAN D'ACTION",`${d.monthLabel} · scénario ${d.mini} MINI`);const priority=[...d.rows].sort((a,b)=>(b.points??-1)-(a.points??-1));b+=tx(id++,"Priorités proposées",.5,1.05,4,.32,19,C.blue,true);priority.forEach((r,i)=>{const y=1.62+i*.78,col=SECTOR[r.sectorKey]??C.blue;const action=r.points==null?"Fiabiliser la donnée de référence.":r.points<=5?`Sécuriser +${n(r.points)} pt(s) ou ${n(r.extraEtp??0)} ETP.`:r.points<=10?`Plan de tension : +${n(r.points)} pts ou ${n(r.extraEtp??0)} ETP.`:`Plan critique : viser ${n(r.targetProd??0)} % ou +${n(r.extraEtp??0)} ETP.`;b+=box(id++,.55,y,.12,.55,col,col,false);b+=tx(id++,`${i+1}. ${r.sectorLabel}`,.82,y+.06,2.1,.22,12,col,true);b+=tx(id++,action,3.0,y+.06,7.0,.3,11,C.ink);b+=tx(id++,`+${n(r.miniHours,0)} h MINI`,10.3,y+.06,1.3,.22,10,col,true,"r");b+=tx(id++,verdictLabel(r.verdict),11.7,y+.06,1.0,.22,9,r.verdict==="critical"?C.red:r.verdict==="tension"?"9A7600":C.green,true,"r")});b+=tx(id++,"Décision recommandée",.55,6.35,2.3,.25,13,C.blue,true);b+=tx(id++,d.overall==="critical"?"Capacité insuffisante sans action : sécuriser les leviers avant validation du volume.":d.overall==="tension"?"Volume traitable sous conditions : verrouiller les gains de productivité / renforts identifiés.":"Volume absorbable avec le dispositif sélectionné.",2.85,6.30,9.4,.38,12,d.overall==="critical"?C.red:d.overall==="tension"?"8A6900":C.green,true);b+=footer();return slideXml(b)}

function crc32(data:Uint8Array){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1))}return(c^0xffffffff)>>>0}
function u16(v:number){return new Uint8Array([v&255,(v>>>8)&255])}
function u32(v:number){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255])}
function cat(parts:Uint8Array[]){const len=parts.reduce((s,p)=>s+p.length,0),o=new Uint8Array(len);let at=0;for(const p of parts){o.set(p,at);at+=p.length}return o}
function zip(files:Record<string,string>){const enc=new TextEncoder(),locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let offset=0;for(const[name,txt]of Object.entries(files)){const nb=enc.encode(name),data=enc.encode(txt),crc=crc32(data),local=cat([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(nb.length),u16(0),nb,data]);locals.push(local);const central=cat([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(nb.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nb]);centrals.push(central);offset+=local.length}const localBlob=cat(locals),centralBlob=cat(centrals),end=cat([u32(0x06054b50),u16(0),u16(0),u16(centrals.length),u16(centrals.length),u32(centralBlob.length),u32(localBlob.length),u16(0)]);return cat([localBlob,centralBlob,end])}
function packageFiles(slides:string[]){const ctSlides=slides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join("");const relSlides=slides.map((_,i)=>`<Relationship Id="rId${i+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`).join("");const ids=slides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+2}"/>`).join("");const files:Record<string,string>={
"[Content_Types].xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>${ctSlides}</Types>`,
"_rels/.rels":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`,
"docProps/core.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>Simulateur MINI CRVO</dc:title><dc:creator>KPI CRVO</dc:creator><cp:lastModifiedBy>KPI CRVO</cp:lastModifiedBy><dcterms:created xsi:type="dcterms:W3CDTF">${new Date().toISOString()}</dcterms:created></cp:coreProperties>`,
"docProps/app.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>KPI CRVO</Application><PresentationFormat>Widescreen</PresentationFormat><Slides>${slides.length}</Slides></Properties>`,
"ppt/presentation.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>${ids}</p:sldIdLst><p:sldSz cx="${xy(W)}" cy="${xy(H)}" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`,
"ppt/_rels/presentation.xml.rels":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>${relSlides}</Relationships>`,
"ppt/slideMasters/slideMaster1.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`,
"ppt/slideMasters/_rels/slideMaster1.xml.rels":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`,
"ppt/slideLayouts/slideLayout1.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`,
"ppt/slideLayouts/_rels/slideLayout1.xml.rels":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`,
"ppt/theme/theme1.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="CRVO"><a:themeElements><a:clrScheme name="CRVO"><a:dk1><a:srgbClr val="173447"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="004F9F"/></a:dk2><a:lt2><a:srgbClr val="F2F6F9"/></a:lt2><a:accent1><a:srgbClr val="004F9F"/></a:accent1><a:accent2><a:srgbClr val="009EDB"/></a:accent2><a:accent3><a:srgbClr val="FEC82F"/></a:accent3><a:accent4><a:srgbClr val="47B9B4"/></a:accent4><a:accent5><a:srgbClr val="EB5B56"/></a:accent5><a:accent6><a:srgbClr val="8D5EC7"/></a:accent6><a:hlink><a:srgbClr val="0563C1"/></a:hlink><a:folHlink><a:srgbClr val="954F72"/></a:folHlink></a:clrScheme><a:fontScheme name="CRVO"><a:majorFont><a:latin typeface="Arial"/></a:majorFont><a:minorFont><a:latin typeface="Arial"/></a:minorFont></a:fontScheme><a:fmtScheme name="CRVO"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>`};slides.forEach((s,i)=>{files[`ppt/slides/slide${i+1}.xml`]=s;files[`ppt/slides/_rels/slide${i+1}.xml.rels`]=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`});return files}

export function exportCapacityPptx(data:CapacityPptInput){const slides=[slideCover(data),slideSummary(data),slideWorkload(data),slideMatrix(data),slideLevers(data),slideActions(data)];const bytes=zip(packageFiles(slides));const blob=new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.presentationml.presentation"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`CRVO_Simulateur_MINI_${data.month}.pptx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}