"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./intelligence.module.css";

type Risk = "critique" | "tension" | "maitrise";
type Priority = { registration:string|null; workOrder:string|null; client:string|null; status:string|null; ageDays:number; statusAgeDays:number; alert:string|null; urgency:string|null; pending:string[]|null; score:number };
type Sector = { key:string; label:string; cadence:number; threshold:number; current:number; pending:number; futureLoad:number; daysOfDemand:number; urgent:number; over15:number; over20:number; avgAge:number; ageBuckets:{d0_2:number;d3_5:number;d6_10:number;d11_15:number;over15:number}; risk:Risk; priorities:Priority[] };
type Production = { latestAt:string|null; snapshotCount:number; profileDays:number; sectors:Array<{key:string;label:string;current:number;target:number;projected:number;gapProjected:number;attainmentProjected:number;confidence:string;profileDays:number}> };
type Forecast = { key:string;label:string;current:number;pending:number;avgEntries:number;avgExits:number;avgNet:number;d1:number;d2:number;d3:number;riskD1:Risk };
type Weather = { level:"critique"|"tension"|"stable";title:string;detail:string };
type Walking = { causes:Array<{cause:string;vehicles:number;over20:number;over30:number;avgAge:number;maxAge:number}>; top:Array<{registration:string|null;workOrder:string|null;client:string|null;status:string|null;cause:string|null;ageDays:number;statusAgeDays:number;alert:string|null;partAvailable:string|null;pending:string[]|null}> };
type LeadComponent = {avg:number;median:number;p90:number;samples:number};
type LeadTime = { sourceModifiedAt:string|null;vehicles:number;outbound:LeadComponent;storage:LeadComponent;factory:LeadComponent;parts:LeadComponent;return:LeadComponent } | null;
type Intelligence = { connected:boolean;mode:string;generatedAt:string;sourceModifiedAt:string|null;summary:{stock:number;over15:number;over20:number;activeVehicles:number;walkingVehicles:number};weather:{now:Weather;tonight:Weather;tomorrow?:Weather};sectors:Sector[];production:Production;actions:Array<{rank:number;sectorKey:string;sectorLabel:string;title:string;detail:string;vehicles:Priority[]}>;walking:Walking;leadTime:LeadTime;learning:{productionProfileDays:number;projectionMode:string;statusHistoryDays?:number;lastHistoryDate?:string|null};forecast?:Forecast[];flow?:Array<{key:string;avgEntries:number;avgExits:number;avgNet:number}>;stageDurations?:Array<{key:string;observations:number;medianHours:number;p90Hours:number}>;rework?:{vehiclesWithRework:number;totalRepeatEntries:number;qualityReturns:number;bySector:Array<{sectorKey:string;vehicles:number;repeatEntries:number}>} };
type Drift = { registration:string|null;work_order:string|null;client:string|null;status:string|null;proactive_level:string;statusAgeDays:number|null;factoryAgeDays:number|null;medianDays:number|null;p90Days:number|null;abnormalityRatio:number|null };
type Focus = { vehicle:Record<string,unknown>; history:Array<{event_date:string;event_time:string|null;status:string|null;client?:string|null;work_order:string|null;registration:string|null;flow:string|null}> };
type View = "overview"|"flows"|"quality"|"vehicle";

const sectorLabels:Record<string,string>={expertise:"Expertise",chiffrage:"Chiffrage",controle_technique:"Contrôle technique",dsp:"DSP",jantes:"Jantes",mecanique:"Mécanique",carrosserie:"Carrosserie",parc_travaux:"Parc travaux",preparation:"Préparation",qualite:"Qualité",sortie_usine:"Sortie usine"};
const processOrder:Record<string,number>={expertise:1,chiffrage:2,controle_technique:3,parc_travaux:4,dsp:4,jantes:4,mecanique:4,carrosserie:4,preparation:5,qualite:6,sortie_usine:7,transport:8,autre:0};
function norm(value:unknown){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}
function sectorOf(status:string|null){const s=norm(status);if(s.includes("qualite"))return"qualite";if(s.includes("chiffrage"))return"chiffrage";if(s.includes("controle technique")||s.includes("depart ct")||s.includes("contre visite"))return"controle_technique";if(s.includes("dsp"))return"dsp";if(s.includes("jante"))return"jantes";if(s.includes("mecanique"))return"mecanique";if(s.includes("carrosserie")||s.includes("fixline"))return"carrosserie";if(s.includes("preparation")||s.includes("photo"))return"preparation";if(s.includes("expertise")||s.includes("lavage"))return"expertise";if(s.includes("parc d'attente travaux")||s.includes("parc d attente travaux"))return"parc_travaux";if(s.includes("sortie usine"))return"sortie_usine";if(s.includes("transport"))return"transport";return"autre";}
function fmtTime(value:string|null|undefined){if(!value)return"—";const d=new Date(value);if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(d);}
function fmtDate(value:string|null|undefined){if(!value)return"—";return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`));}
function fmtNumber(value:number,digits=0){return Number(value||0).toLocaleString("fr-FR",{maximumFractionDigits:digits});}
function riskLabel(level:string){return level==="critique"?"CRITIQUE":level==="tension"?"À SURVEILLER":"MAÎTRISÉ";}
function mergeLive(previous:Intelligence|null,live:Intelligence){if(!previous||previous.mode!=="deep")return live;return{...previous,...live,mode:"deep",forecast:previous.forecast,flow:previous.flow,stageDurations:previous.stageDurations,rework:previous.rework,weather:{...live.weather,tomorrow:previous.weather.tomorrow},learning:{...previous.learning,...live.learning,statusHistoryDays:previous.learning.statusHistoryDays,lastHistoryDate:previous.learning.lastHistoryDate}};}

function WeatherCard({title,item}:{title:string;item?:Weather}){if(!item)return <article className={`${styles.weatherCard} ${styles.weatherPending}`}><span>{title}</span><strong>CALCUL EN COURS</strong><p>Le moteur consolide l’historique disponible.</p></article>;return <article className={`${styles.weatherCard} ${styles[`weather_${item.level}`]}`}><span>{title}</span><strong>{item.title}</strong><p>{item.detail}</p></article>;}

export default function IntelligencePage(){
  const [data,setData]=useState<Intelligence|null>(null);const [deepLoading,setDeepLoading]=useState(true);const [error,setError]=useState("");const [selected,setSelected]=useState("mecanique");const [view,setView]=useState<View>("overview");const [drift,setDrift]=useState<Drift[]>([]);const [registration,setRegistration]=useState("");const [focus,setFocus]=useState<Focus|null>(null);const [focusError,setFocusError]=useState("");const [focusLoading,setFocusLoading]=useState(false);
  async function loadLive(){try{const r=await fetch(`/api/intelligence?mode=live&_=${Date.now()}`,{cache:"no-store"});const p=await r.json() as Intelligence&{error?:string};if(!r.ok)throw new Error(p.error||"Cockpit indisponible");setData(prev=>mergeLive(prev,p));setSelected(current=>p.sectors.some(s=>s.key===current)?current:(p.sectors.find(s=>s.risk==="critique")?.key||p.sectors[0]?.key||"mecanique"));setError("");}catch(e){setError(e instanceof Error?e.message:"Actualisation impossible");}}
  async function loadDeep(){setDeepLoading(true);try{const [r,d]=await Promise.all([fetch(`/api/intelligence?mode=deep&_=${Date.now()}`,{cache:"no-store"}),fetch(`/api/proactive-drift?_=${Date.now()}`,{cache:"no-store"})]);const p=await r.json() as Intelligence&{error?:string};if(!r.ok)throw new Error(p.error||"Analyse approfondie indisponible");setData(p);if(d.ok){const dp=await d.json() as {rows?:Drift[]};setDrift(dp.rows??[]);}setError("");}catch(e){setError(e instanceof Error?e.message:"Analyse approfondie impossible");}finally{setDeepLoading(false);}}
  useEffect(()=>{void loadLive();void loadDeep();const liveTimer=window.setInterval(()=>void loadLive(),60000);const deepTimer=window.setInterval(()=>void loadDeep(),900000);const visible=()=>{if(document.visibilityState==="visible")void loadLive();};document.addEventListener("visibilitychange",visible);return()=>{window.clearInterval(liveTimer);window.clearInterval(deepTimer);document.removeEventListener("visibilitychange",visible);};},[]);
  const current=useMemo(()=>data?.sectors.find(s=>s.key===selected)??null,[data,selected]);const currentForecast=useMemo(()=>data?.forecast?.find(f=>f.key===selected)??null,[data,selected]);
  async function searchVehicle(event?:FormEvent){event?.preventDefault();const query=registration.trim();if(!query)return;setFocusLoading(true);setFocusError("");try{const r=await fetch(`/api/client-dashboard?registration=${encodeURIComponent(query)}&_=${Date.now()}`,{cache:"no-store"});const p=await r.json() as Focus&{error?:string};if(!r.ok)throw new Error(p.error||"Dossier introuvable");setFocus(p);setView("vehicle");}catch(e){setFocus(null);setFocusError(e instanceof Error?e.message:"Dossier introuvable");}finally{setFocusLoading(false);}}
  function openVehicle(reg:string|null){if(!reg)return;setRegistration(reg);setTimeout(()=>void searchVehicle(),0);}
  const timeline=useMemo(()=>{if(!focus)return[];const chronological=[...focus.history].sort((a,b)=>`${a.event_date} ${a.event_time||""}`.localeCompare(`${b.event_date} ${b.event_time||""}`));const seen=new Map<string,number>();return chronological.map((item,index)=>{const next=chronological[index+1],sector=sectorOf(item.status),prev=index?sectorOf(chronological[index-1].status):null;const entry=sector!=="autre"&&sector!==prev;let repeat=false;if(entry){const count=seen.get(sector)??0;repeat=count>0;seen.set(sector,count+1);}const start=Date.parse(`${item.event_date}T${String(item.event_time||"00:00:00").slice(0,8)}Z`);const end=next?Date.parse(`${next.event_date}T${String(next.event_time||"00:00:00").slice(0,8)}Z`):NaN;const hours=Number.isFinite(start)&&Number.isFinite(end)?Math.max(0,(end-start)/3600000):null;const backwards=prev&&sector!==prev&&(processOrder[sector]??0)<(processOrder[prev]??0);return{...item,sector,repeat,backwards:Boolean(backwards),durationHours:hours};}).reverse();},[focus]);
  if(!data)return <main className={styles.loading}><div/><strong>Construction du cockpit prédictif…</strong><span>{error||"Consolidation des données opérationnelles"}</span></main>;
  return <main className={styles.page}>
    <header className={styles.header}><div><a href="/" className={styles.back}>← REPORTING CRVO</a><span className={styles.eyebrow}>CRVO INTELLIGENCE · AIDE À LA DÉCISION</span><h1>PILOTAGE PRÉDICTIF</h1><p>Voir la pression actuelle, anticiper les prochains goulots et identifier les dossiers qui peuvent réellement faire bouger la journée.</p></div><div className={styles.refresh}><span>RÉALISÉ À</span><strong>{fmtTime(data.sourceModifiedAt)}</strong><small>Actualisation automatique · 1 min</small><small>{data.learning.projectionMode}</small></div></header>
    <nav className={styles.tabs}><button className={view==="overview"?styles.activeTab:""} onClick={()=>setView("overview")}>Tour de contrôle</button><button className={view==="flows"?styles.activeTab:""} onClick={()=>setView("flows")}>Flux & causes</button><button className={view==="quality"?styles.activeTab:""} onClick={()=>setView("quality")}>Reprises & qualité</button><button className={view==="vehicle"?styles.activeTab:""} onClick={()=>setView("vehicle")}>Focus véhicule</button></nav>
    {error&&<div className={styles.warning}>{error}</div>}
    {view==="overview"&&<>
      <section className={styles.weatherGrid}><WeatherCard title="MAINTENANT" item={data.weather.now}/><WeatherCard title="CE SOIR" item={data.weather.tonight}/><WeatherCard title="DEMAIN MATIN" item={data.weather.tomorrow}/></section>
      <section className={styles.kpiGrid}><article><span>STOCK USINE</span><strong>{fmtNumber(data.summary.stock)}</strong><small>{fmtNumber(data.summary.over20)} véhicules &gt;20 j</small></article><article><span>DOSSIERS ACTIFS</span><strong>{fmtNumber(data.summary.activeVehicles)}</strong><small>{fmtNumber(data.summary.walkingVehicles)} au-delà de 15 j</small></article><article><span>SECTEURS CRITIQUES</span><strong>{data.sectors.filter(s=>s.risk==="critique").length}</strong><small>{data.sectors.filter(s=>s.risk==="tension").length} à surveiller</small></article><article><span>PROFIL DE JOURNÉE</span><strong>{data.production.profileDays}</strong><small>jour{data.production.profileDays>1?"s":""} appris · {data.production.snapshotCount} points aujourd’hui</small></article></section>
      <section className={styles.section}><div className={styles.sectionTitle}><div><span>PRESSION ATELIERS</span><h2>Encours actuel + charge à venir</h2></div><p>Le nombre « à faire » peut être supérieur à l’encours : un même véhicule peut encore devoir passer dans plusieurs secteurs.</p></div><div className={styles.sectorTable}><div className={styles.sectorHead}><span>SECTEUR</span><span>ENCOURS</span><span>À FAIRE</span><span>&gt;20 J</span><span>CHARGE</span><span>J+1</span><span>RISQUE</span></div>{data.sectors.map(s=>{const f=data.forecast?.find(x=>x.key===s.key);return <button key={s.key} onClick={()=>setSelected(s.key)} className={`${styles.sectorRow} ${selected===s.key?styles.selectedRow:""}`}><span><i className={styles[`dot_${s.risk}`]}/><b>{s.label}</b></span><strong>{s.current}</strong><strong>{s.pending}</strong><span>{s.over20}</span><span>{fmtNumber(s.daysOfDemand,1)} j</span><span>{f?f.d1:"—"}</span><em className={styles[`risk_${s.risk}`]}>{riskLabel(s.risk)}</em></button>;})}</div></section>
      {current&&<section className={styles.detailGrid}><article className={styles.pressureCard}><div className={styles.cardTitle}><div><span>FOCUS · {current.label.toUpperCase()}</span><h3>{current.pending} dossiers à traiter</h3></div><em className={styles[`risk_${current.risk}`]}>{riskLabel(current.risk)}</em></div><div className={styles.pressureNumbers}><div><span>Encours</span><strong>{current.current}</strong></div><div><span>Charge future</span><strong>+{current.futureLoad}</strong></div><div><span>Urgents</span><strong>{current.urgent}</strong></div><div><span>Âge moyen</span><strong>{fmtNumber(current.avgAge,1)} j</strong></div></div><div className={styles.ageHeat}><div><span>0–2 j</span><b>{current.ageBuckets.d0_2}</b></div><div><span>3–5 j</span><b>{current.ageBuckets.d3_5}</b></div><div><span>6–10 j</span><b>{current.ageBuckets.d6_10}</b></div><div><span>11–15 j</span><b>{current.ageBuckets.d11_15}</b></div><div className={styles.oldAge}><span>&gt;15 j</span><b>{current.ageBuckets.over15}</b></div></div>{currentForecast&&<div className={styles.radar}><div><span>AUJOURD’HUI</span><strong>{currentForecast.current}</strong></div><i/><div><span>J+1</span><strong>{currentForecast.d1}</strong></div><i/><div><span>J+2</span><strong>{currentForecast.d2}</strong></div><i/><div><span>J+3</span><strong>{currentForecast.d3}</strong></div></div>}</article><article className={styles.priorityCard}><div className={styles.cardTitle}><div><span>À FAIRE MAINTENANT</span><h3>Priorités opérationnelles</h3></div><small>Âge · urgence · travaux restants · disponibilité</small></div><div className={styles.priorityList}>{current.priorities.slice(0,8).map((v,index)=><button key={`${v.registration}-${index}`} onClick={()=>openVehicle(v.registration)}><b>{index+1}</b><div><strong>{v.registration||v.workOrder||"—"}</strong><span>{v.status||"Position non renseignée"}</span></div><div><strong>{fmtNumber(v.ageDays,1)} j</strong><span>{v.alert||`${v.pending?.length||0} passage(s) restant(s)`}</span></div></button>)}{!current.priorities.length&&<p className={styles.empty}>Aucun dossier immédiatement actionnable identifié sur ce secteur.</p>}</div></article></section>}
      <section className={styles.section}><div className={styles.sectionTitle}><div><span>TRAJECTOIRE DE FIN DE JOURNÉE</span><h2>Production projetée à 20h</h2></div><p>La projection apprend progressivement le profil horaire des journées. Tant que l’historique est court, elle privilégie la cadence observée aujourd’hui.</p></div><div className={styles.productionGrid}>{data.production.sectors.map(p=><article key={p.key} className={p.projected<p.target?styles.productionRisk:""}><span>{p.label.toUpperCase()}</span><div><strong>{p.current}</strong><i>→</i><b>{p.projected}</b></div><small>objectif {p.target} · projection {p.gapProjected>=0?"+":""}{p.gapProjected}</small><em>{p.confidence}</em></article>)}</div></section>
      <section className={styles.twoCols}><article className={styles.actionCard}><div className={styles.cardTitle}><div><span>5 ACTIONS PRIORITAIRES</span><h3>Où agir maintenant</h3></div></div>{data.actions.map(a=><button key={a.rank} onClick={()=>setSelected(a.sectorKey)}><b>{String(a.rank).padStart(2,"0")}</b><div><strong>{a.title}</strong><span>{a.detail}</span></div></button>)}</article><article className={styles.walkingCard}><div className={styles.cardTitle}><div><span>WALKING DEAD INTELLIGENT</span><h3>Causes des véhicules &gt;15 jours</h3></div></div>{data.walking.causes.slice(0,7).map(c=><div key={c.cause}><span>{c.cause}</span><strong>{c.vehicles}</strong><small>{c.over20} &gt;20 j · max {fmtNumber(c.maxAge,1)} j</small></div>)}</article></section>
      {data.leadTime&&<section className={styles.section}><div className={styles.sectionTitle}><div><span>LEAD TIME DÉCOMPOSÉ</span><h2>Où se consomme le délai</h2></div><p>{data.leadTime.vehicles} véhicules disponibles dans la source Lead Time.</p></div><div className={styles.leadGrid}>{([['outbound','Transport aller'],['storage','Stockage'],['factory','Usine'],['parts','Pièces'],['return','Transport retour']] as const).map(([key,label])=>{const x=data.leadTime?.[key];return <article key={key}><span>{label.toUpperCase()}</span><strong>{fmtNumber(x?.avg||0,1)} j</strong><small>médiane {fmtNumber(x?.median||0,1)} · P90 {fmtNumber(x?.p90||0,1)}</small><div><i style={{width:`${Math.min(100,(x?.avg||0)/Math.max(1,data.leadTime?.factory.avg||1)*100)}%`}}/></div></article>})}</div></section>}
    </>}
    {view==="flows"&&<>
      <section className={styles.section}><div className={styles.sectionTitle}><div><span>FLUX DES GOULOTS</span><h2>Ce qui entre, ce qui sort, ce qui gonfle</h2></div><p>{deepLoading?"Consolidation de l’historique…":`Moyenne calculée sur ${data.learning.statusHistoryDays||0} jours d’historique disponibles.`}</p></div><div className={styles.flowTable}><div className={styles.flowHead}><span>SECTEUR</span><span>ENTRÉES / J</span><span>SORTIES / J</span><span>NET</span><span>ENCOURS</span><span>J+1</span><span>J+2</span><span>J+3</span></div>{(data.forecast??[]).map(f=><button key={f.key} onClick={()=>setSelected(f.key)}><strong>{f.label}</strong><span>+{fmtNumber(f.avgEntries,1)}</span><span>-{fmtNumber(f.avgExits,1)}</span><em className={f.avgNet>0?styles.netBad:styles.netGood}>{f.avgNet>0?"+":""}{fmtNumber(f.avgNet,1)}</em><b>{f.current}</b><span>{f.d1}</span><span>{f.d2}</span><span>{f.d3}</span></button>)}</div></section>
      <section className={styles.twoCols}><article className={styles.stageCard}><div className={styles.cardTitle}><div><span>CAUSES RACINES</span><h3>Temps de traversée par secteur</h3></div></div>{(data.stageDurations??[]).slice(0,10).map(s=><div key={s.key}><span>{labelFor(s.key)}</span><strong>{fmtNumber(s.medianHours/24,1)} j méd.</strong><small>P90 {fmtNumber(s.p90Hours/24,1)} j · {s.observations} observations</small></div>)}</article><article className={styles.stageCard}><div className={styles.cardTitle}><div><span>DÉRIVES AVANT 15 JOURS</span><h3>Statuts anormalement longs</h3></div></div>{drift.slice(0,10).map((d,index)=><button key={`${d.registration}-${index}`} onClick={()=>openVehicle(d.registration)}><span>{d.registration||d.work_order||"—"}</span><strong>{d.status||"Statut"}</strong><small>{fmtNumber(d.statusAgeDays||0,1)} j sur statut · P90 {fmtNumber(d.p90Days||0,1)} j</small></button>)}</article></section>
    </>}
    {view==="quality"&&<>
      <section className={styles.kpiGrid}><article><span>VÉHICULES AVEC REPRISE</span><strong>{data.rework?.vehiclesWithRework??"—"}</strong><small>au moins un retour dans un secteur</small></article><article><span>PASSAGES RÉPÉTÉS</span><strong>{data.rework?.totalRepeatEntries??"—"}</strong><small>entrées supplémentaires détectées</small></article><article><span>RETOURS APRÈS QUALITÉ</span><strong>{data.rework?.qualityReturns??"—"}</strong><small>vers un métier en amont</small></article><article><span>HISTORIQUE ANALYSÉ</span><strong>{data.learning.statusHistoryDays??"—"}</strong><small>jours de logs actuellement disponibles</small></article></section>
      <section className={styles.section}><div className={styles.sectionTitle}><div><span>BOUCLES & REPRISES</span><h2>Où les véhicules repassent plusieurs fois</h2></div><p>Un passage répété correspond à un retour dans un secteur après l’avoir quitté. Cet indicateur met en évidence les non-qualités et reprises invisibles dans un simple encours.</p></div><div className={styles.reworkGrid}>{(data.rework?.bySector??[]).map(r=><article key={r.sectorKey}><span>{labelFor(r.sectorKey).toUpperCase()}</span><strong>{r.vehicles}</strong><small>véhicules · {r.repeatEntries} passage(s) supplémentaire(s)</small></article>)}</div></section>
      <section className={styles.section}><div className={styles.sectionTitle}><div><span>ANALYSE D’UN DOSSIER</span><h2>Identifier précisément le retour</h2></div><p>Recherche une immatriculation : la timeline marque automatiquement les retours en arrière et les passages répétés.</p></div><form className={styles.searchInline} onSubmit={searchVehicle}><input value={registration} onChange={e=>setRegistration(e.target.value)} placeholder="Ex. AB-123-CD"/><button disabled={focusLoading}>{focusLoading?"ANALYSE…":"ANALYSER LE DOSSIER"}</button></form>{focusError&&<p className={styles.focusError}>{focusError}</p>}</section>
    </>}
    {view==="vehicle"&&<section className={styles.section}><div className={styles.sectionTitle}><div><span>FOCUS VÉHICULE</span><h2>Parcours complet & temps perdu</h2></div><p>Le journal est reconstruit à partir des changements de statuts connus. Les badges « RETOUR » signalent une reprise ou un retour vers une étape déjà traversée.</p></div><form className={styles.searchInline} onSubmit={searchVehicle}><input value={registration} onChange={e=>setRegistration(e.target.value)} placeholder="Rechercher une immatriculation"/><button disabled={focusLoading}>{focusLoading?"RECHERCHE…":"OUVRIR LE DOSSIER"}</button></form>{focusError&&<p className={styles.focusError}>{focusError}</p>}{focus&&<div className={styles.focusLayout}><article className={styles.focusSummary}><span>DOSSIER</span><h3>{String(focus.vehicle.registration??registration).toUpperCase()}</h3><div><small>Position actuelle</small><strong>{String(focus.vehicle.status??"—")}</strong></div><div><small>Âge usine</small><strong>{fmtNumber(Number(focus.vehicle.factory_age_days??focus.vehicle.status_age_days??0),1)} j</strong></div><div><small>Reste à faire</small><strong>{["pending_expertise","pending_chiffrage","pending_controle_technique","pending_dsp","pending_jantes","pending_mecanique","pending_carrosserie","pending_preparation","pending_qualite","pending_sortie_usine"].filter(k=>focus.vehicle[k]===true).map(k=>k.replace("pending_","").replace("controle_technique","CT")).join(" · ")||"—"}</strong></div><div><small>Événements connus</small><strong>{timeline.length}</strong></div><div><small>Retours détectés</small><strong>{timeline.filter(t=>t.repeat||t.backwards).length}</strong></div></article><article className={styles.timeline}><div className={styles.cardTitle}><div><span>LOG DU DOSSIER</span><h3>Du plus récent au plus ancien</h3></div></div>{timeline.map((t,index)=><div key={`${t.event_date}-${t.event_time}-${index}`} className={t.repeat||t.backwards?styles.returnLog:""}><i/><div><strong>{t.status||"Statut"}</strong><span>{fmtDate(t.event_date)} · {String(t.event_time||"").slice(0,5)||"—"} · {sectorLabels[t.sector]||t.sector}</span></div><div>{t.repeat||t.backwards?<em>RETOUR</em>:null}{t.durationHours!=null&&t.durationHours>=24?<b>{fmtNumber(t.durationHours/24,1)} j</b>:t.durationHours!=null?<small>{fmtNumber(t.durationHours,1)} h</small>:null}</div></div>)}</article></div>}</section>}
  </main>;
}

function labelFor(key:string){return sectorLabels[key]??key;}
