"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./animation-mensuelle.module.css";

type Actor={userId:string;displayName:string;role:"admin"|"user";accessProfile:"admin"|"service_manager"|"team_manager"|"custom";scopes:string[];teams:string[];canManage:boolean};
type WorkflowSummary={id:string;month:string;status:string;validationMode:string;openedAt:string;closedAt:string|null;sourceFilename:string|null;audit:Record<string,unknown>;totals:Record<string,unknown>};
type Component={id:string;sourceComponentKey:string;employeeKey:string|null;matricule:string|null;employeeName:string;population:string;jobKey:string;sectorKey:string|null;sectorLabel:string|null;teamCode:string|null;presenceHours:number|null;billedHours:number|null;absenceHours:number|null;productivity:number|null;absenceRate:number|null;thresholds:(number|null)[];theoreticalTier:number|null;teamTier:number|null;serviceTier:number|null;finalTier:number|null;collectiveLabel:string|null;collectiveAmountEur:number|null;collectiveProration:number|null;individualBaseEur:number|null;coefficient:number|null;individualAmountEur:number|null;exceptionalAmountEur:number|null;totalAmountEur:number|null;sourcePayload:Record<string,unknown>;frozen:boolean};
type Detail={actor:Actor;workflow:{id:string;month:string;status:string;validationMode:string;sourceFilename:string|null;sourceSha256:string|null;sourceSnapshot:Record<string,unknown>;audit:Record<string,unknown>;currentAudit:Record<string,unknown>;totals:Record<string,unknown>;frozenHash:string|null};components:Component[];manualInputs:Array<{id:string;scopeType:string;scopeKey:string;inputKey:string;numericValue:number|null;textValue:string|null;source:string;comment:string|null;updatedAt:string}>};
type ListPayload={actor:Actor;workflows:WorkflowSummary[]};
type AuditItem={code?:string;count?:number;message?:string};

const STATUS_LABELS:Record<string,string>={inputs:"Données fin de mois",calculated:"Calcul effectué",team_validation:"Chef d’équipe",service_validation:"Chef de service",direction_audit:"Audit direction",closed:"Clôturé",legacy_closed:"Historique figé"};
const STEPS=["Préparation","Données complètes","Calcul","Chef d'équipe","Chef de service","Audit Direction","Clôturé"];
const INPUT_KEYS=[
  ["working_days","Jours ouvrés"],["collective_amount_eur","Prime collective sortie usine €"],["factory_output","Sorties usine"],["fixline_result","Résultat Fixline"],["small_supplies","Petites fournitures"],["quality_claim_rate","Taux réclamation qualité (0,0135 = 1,35 %)"],
  ["cleanliness","Propreté secteur (0,90 = 90 %)"],["safety_cleanliness","Audit sécurité / propreté CE"],["at_count","Nombre d'AT"],["bon_direct","BON DIRECT (0,90 = 90 %)"],["lead_time","Lead Time"],["team_p3","Équipe au palier 3 ? (texte OUI/NON)"],["criterion_1","Critère métier 1"],["criterion_2","Critère métier 2"],["expert_error_rate","Taux d'erreur expert"],["manual_tier","Palier manuel métier sans règle"],["exceptional_amount_eur","Prime exceptionnelle €"]
];

function money(value:number|null|undefined){return value==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(value);}
function number(value:number|null|undefined,digits=1){return value==null?"—":new Intl.NumberFormat("fr-FR",{maximumFractionDigits:digits}).format(value);}
function percent(value:number|null|undefined){return value==null?"—":`${number(value*100,1)} %`;}
function monthLabel(month:string){const [y,m]=month.split("-").map(Number);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(y,m-1,1));}
function statusClass(status:string){return status==="legacy_closed"?`${styles.status} ${styles.legacy}`:status==="closed"?`${styles.status} ${styles.closed}`:styles.status;}
function stepIndex(status:string){return status==="inputs"?1:status==="calculated"?2:status==="team_validation"?3:status==="service_validation"?4:status==="direction_audit"?5:status==="closed"||status==="legacy_closed"?6:0;}

export default function MonthlyAnimationPage(){
  const [list,setList]=useState<ListPayload|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [selected,setSelected]=useState<string>("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(false);const [tab,setTab]=useState("synthese");
  const [openMonth,setOpenMonth]=useState(new Date().toISOString().slice(0,7));const [search,setSearch]=useState("");const [population,setPopulation]=useState("");const [sector,setSector]=useState("");const [team,setTeam]=useState("");
  const [scopeType,setScopeType]=useState("global");const [scopeKey,setScopeKey]=useState("*");const [inputKey,setInputKey]=useState("working_days");const [inputValue,setInputValue]=useState("");const [inputText,setInputText]=useState("");const [inputComment,setInputComment]=useState("");

  async function api(url:string,options?:RequestInit){const response=await fetch(url,{...options,cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Opération impossible.");return payload;}
  async function loadList(preferred?:string){setError("");const payload=await api("/api/monthly-animation") as ListPayload;setList(payload);const id=preferred||selected||payload.workflows?.[0]?.id||"";setSelected(id);if(id)await loadDetail(id);else setDetail(null);}
  async function loadDetail(id:string){setLoading(true);try{setDetail(await api(`/api/monthly-animation?workflowId=${encodeURIComponent(id)}`) as Detail);}catch(e){setError(e instanceof Error?e.message:"Lecture impossible.");}finally{setLoading(false);}}
  useEffect(()=>{void loadList();},[]);

  async function action(body:Record<string,unknown>,message:string){setLoading(true);setError("");setNotice("");try{const payload=await api("/api/monthly-animation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setNotice(message);const id=String(payload.workflowId??body.workflowId??selected);await loadList(id||undefined);}catch(e){setError(e instanceof Error?e.message:"Opération impossible.");}finally{setLoading(false);}}
  async function openWorkflow(){await action({action:"open",month:openMonth},`Workflow ${openMonth} ouvert et Payplan figé pour le mois.`);}
  async function validateRow(c:Component,level:"team"|"service"){
    const reference=level==="team"?c.theoreticalTier:(c.teamTier??c.theoreticalTier);const current=level==="team"?c.teamTier:c.serviceTier;
    const raw=prompt(`Palier ${level==="team"?"chef d'équipe":"chef de service"} pour ${c.employeeName} (0 à 5)`,String(current??reference??0));if(raw==null)return;const tier=Number(raw);if(!Number.isInteger(tier)||tier<0||tier>5){setError("Palier invalide : valeur de 0 à 5 attendue.");return;}
    let comment="";if(tier!==reference){comment=prompt(`Motif obligatoire du changement P${reference??"?"} → P${tier}`,"")??"";if(comment.trim().length<3){setError("Le commentaire est obligatoire lorsqu'un palier est modifié.");return;}}
    await action({action:"validate",componentId:c.id,level,tier,comment},`${c.employeeName} validé au palier ${tier}.`);
  }
  async function saveInput(event:FormEvent){event.preventDefault();await action({action:"input",workflowId:selected,scopeType,scopeKey,inputKey,numericValue:inputText?null:inputValue,textValue:inputText||null,comment:inputComment},"Donnée de fin de mois enregistrée et moteur recalculé.");setInputValue("");setInputText("");setInputComment("");}
  async function logPdf(employeeKey:string){try{await api("/api/monthly-animation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"log-export",workflowId:selected,exportType:"pdf",employeeKey,metadata:{via:"print_report"}})});}catch{} }

  const components=detail?.components??[];
  const filtered=useMemo(()=>components.filter(c=>(!search||`${c.employeeName} ${c.matricule??""}`.toLowerCase().includes(search.toLowerCase()))&&(!population||c.population===population)&&(!sector||c.sectorKey===sector)&&(!team||c.teamCode===team)),[components,search,population,sector,team]);
  const sectors=useMemo(()=>[...new Map(components.filter(c=>c.sectorKey).map(c=>[c.sectorKey!,c.sectorLabel||c.sectorKey!])).entries()].sort((a,b)=>a[1].localeCompare(b[1],"fr")),[components]);
  const teams=useMemo(()=>[...new Set(components.map(c=>c.teamCode).filter(Boolean) as string[])].sort(),[components]);
  const overrides=components.filter(c=>c.theoreticalTier!=null&&c.finalTier!=null&&c.theoreticalTier!==c.finalTier).length;
  const sourceOverrides=components.filter(c=>Boolean(c.sourcePayload?.sourceOverride)).length;
  const sourceNoComment=components.filter(c=>Boolean(c.sourcePayload?.sourceOverrideWithoutComment)).length;
  const sourceErrors=Number(detail?.workflow.audit?.sourceFormulaErrors??0);
  const audit=detail?.workflow.currentAudit??{};const blockers=(audit.blockers??[]) as AuditItem[];const warnings=(audit.warnings??[]) as AuditItem[];
  const locked=detail?.workflow.status==="closed"||detail?.workflow.status==="legacy_closed";const legacy=detail?.workflow.validationMode==="legacy_excel";const actor=detail?.actor??list?.actor;
  const canTeam=Boolean(actor&&(actor.canManage||actor.accessProfile==="team_manager"));const canService=Boolean(actor&&(actor.canManage||actor.accessProfile==="service_manager"));
  const currentStep=detail?stepIndex(detail.workflow.status):0;

  return <main className={styles.page}>
    <header className={styles.hero}><div><a href="/">← KPI CRVO</a><span>PERFORMANCE · RÉMUNÉRATION VARIABLE</span><h1>Animation mensuelle</h1><p>Calcul, validation managériale, audit et clôture des primes. Chaque workflow conserve son Payplan, ses données, ses décisions et son empreinte de clôture.</p></div><div className={styles.heroActions}>{actor?.role==="admin"&&<a href="/animation-mensuelle/payplan">PAYPLAN</a>}{actor?.role==="admin"&&<a href="/animation-mensuelle/acces">ACCÈS WORKFLOW</a>}</div></header>
    <div className={styles.shell}>
      <aside className={styles.history}><span className={styles.eyebrow}>HISTORIQUE FIGÉ</span><h2>Mois</h2><div className={styles.historyList}>{(list?.workflows??[]).map(w=><button key={w.id} className={`${styles.historyItem} ${selected===w.id?styles.active:""}`} onClick={()=>{setSelected(w.id);void loadDetail(w.id);}}><strong>{monthLabel(w.month)}</strong><small>{STATUS_LABELS[w.status]??w.status}{w.closedAt?` · ${new Date(w.closedAt).toLocaleDateString("fr-FR")}`:""}</small></button>)}</div>
        {list?.actor.canManage&&<div className={styles.openBox}><span className={styles.eyebrow}>OUVRIR UN WORKFLOW</span><input type="month" value={openMonth} onChange={e=>setOpenMonth(e.target.value)}/><button className={styles.button} onClick={openWorkflow} disabled={loading||!openMonth}>OUVRIR LE MOIS</button><small>Cette action est réservée à Cyril. Le Payplan actif est immédiatement copié dans une version mensuelle figée.</small></div>}
      </aside>
      <section className={styles.main}>{!detail?<div className={styles.empty}>{loading?"Chargement du workflow…":"Aucun workflow disponible."}</div>:<>
        <div className={styles.workflowHeader}><div><span className={styles.eyebrow}>{monthLabel(detail.workflow.month).toUpperCase()}</span><h2>Workflow de primes</h2><div className={statusClass(detail.workflow.status)}><i/>{STATUS_LABELS[detail.workflow.status]??detail.workflow.status}</div></div><div className={styles.footerActions}>{!locked&&<button className={styles.buttonAlt} disabled={loading} onClick={()=>action({action:"recalculate",workflowId:selected},"Moteur de calcul relancé.")}>RECALCULER</button>}{<button className={styles.buttonAlt} disabled={loading} onClick={()=>action({action:"audit",workflowId:selected},"Audit actualisé.")}>AUDITER</button>}{actor?.canManage&&!locked&&<button className={styles.buttonDanger} disabled={loading||!Boolean(audit.passed)} onClick={()=>{if(confirm("Clôturer définitivement ce mois ? Les valeurs deviendront immuables."))void action({action:"close",workflowId:selected},"Workflow clôturé et figé.");}}>CLÔTURER</button>}</div></div>
        <div className={styles.workflowLine}>{STEPS.map((step,i)=><div key={step} className={`${styles.step} ${i<currentStep?styles.done:""} ${i===currentStep?styles.current:""}`}>{step}</div>)}</div>
        {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
        {legacy&&<div className={styles.legacyBanner}><strong>JUILLET 2026 · RÉFÉRENCE EXCEL FIGÉE</strong>Les 242 composants ont été conservés tels qu'ils apparaissent dans le classeur v4.2. Le fichier contient <b>{sourceErrors} erreurs de formule</b>, <b>{sourceOverrides} changements de palier</b> et <b>{sourceNoComment} changements sans commentaire</b>. Aucun montant € n'est inventé : la valeur collective est « BIMESTRE » et la base monétaire individuelle n'est pas déterminable de façon fiable dans le classeur.</div>}
        <div className={styles.kpis}><div className={styles.kpi}><span>Composants</span><strong>{components.length}</strong></div><div className={styles.kpi}><span>Productifs</span><strong>{components.filter(c=>c.population==="productif").length}</strong></div><div className={styles.kpi}><span>Chefs équipe</span><strong>{components.filter(c=>c.population==="chef_equipe").length}</strong></div><div className={styles.kpi}><span>Préprod</span><strong>{components.filter(c=>c.population==="preprod").length}</strong></div><div className={styles.kpi}><span>Fixline</span><strong>{components.filter(c=>c.population==="fixline").length}</strong></div><div className={styles.kpi}><span>Écarts palier</span><strong>{legacy?sourceOverrides:overrides}</strong></div></div>
        <div className={styles.tabs}><button className={tab==="synthese"?styles.active:""} onClick={()=>setTab("synthese")}>SYNTHÈSE</button><button className={tab==="collabs"?styles.active:""} onClick={()=>setTab("collabs")}>ÉQUIPES & COLLABORATEURS</button><button className={tab==="inputs"?styles.active:""} onClick={()=>setTab("inputs")}>DONNÉES FIN DE MOIS</button><button className={tab==="audit"?styles.active:""} onClick={()=>setTab("audit")}>CONTRÔLES & AUDIT</button><button className={tab==="exports"?styles.active:""} onClick={()=>setTab("exports")}>EXPORTS</button></div>

        {tab==="synthese"&&<div className={styles.cards}><article className={styles.card}><span className={styles.eyebrow}>SOURCE & GEL</span><h2>Traçabilité du mois</h2><p>Source : <b>{detail.workflow.sourceFilename??"Flux KPI CRVO"}</b></p><p>SHA source : <span className={styles.hash}>{detail.workflow.sourceSha256??"—"}</span></p><p>Empreinte de clôture : <span className={styles.hash}>{detail.workflow.frozenHash??"Pas encore clôturé"}</span></p></article><article className={styles.card}><span className={styles.eyebrow}>FINANCIER</span><h2>Total paie</h2><p className={legacy?styles.moneyMissing:""}>{detail.workflow.totals?.totalPayrollEur==null?"Non calculable depuis la source historique":money(Number(detail.workflow.totals.totalPayrollEur))}</p><p>Le total paie n'est généré que lorsque toutes les bases €, règles de proratisation, validations et contrôles sont complets.</p></article></div>}

        {tab==="collabs"&&<><div className={styles.filterbar}><input placeholder="Rechercher nom ou matricule" value={search} onChange={e=>setSearch(e.target.value)}/><select value={population} onChange={e=>setPopulation(e.target.value)}><option value="">Toutes populations</option><option value="productif">Productifs</option><option value="chef_equipe">Chefs d'équipe</option><option value="preprod">Pré-production</option><option value="fixline">Fixline</option></select><select value={sector} onChange={e=>setSector(e.target.value)}><option value="">Tous secteurs</option>{sectors.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Toutes équipes</option>{teams.map(t=><option key={t} value={t}>{t}</option>)}</select></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Collaborateur</th><th>Population / secteur</th><th>Heures achetées</th><th>Heures vendues</th><th>Rendement</th><th>Absence</th><th>Théo.</th><th>CE</th><th>CDS</th><th>Final</th><th>Collectif</th><th>Total</th><th>Validation / rapport</th><th>Commentaire source</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td className={styles.name}><strong>{c.employeeName}</strong><small>{c.matricule??"Sans matricule"}</small></td><td>{c.population}<br/><span className={styles.muted}>{c.sectorLabel??"—"} · {c.teamCode??"—"}</span></td><td>{number(c.presenceHours,2)} h</td><td>{number(c.billedHours,2)} h</td><td>{percent(c.productivity)}</td><td>{number(c.absenceHours,2)} h</td><td className={styles.tier}>{c.theoreticalTier==null?"—":`P${c.theoreticalTier}`}</td><td className={styles.tier}>{c.teamTier==null?"—":`✓ P${c.teamTier}`}</td><td className={styles.tier}>{c.serviceTier==null?"—":`✓ P${c.serviceTier}`}</td><td className={styles.tier}>{c.finalTier==null?"—":`P${c.finalTier}`}</td><td>{c.collectiveAmountEur==null?(c.collectiveLabel??"—"):money(c.collectiveAmountEur)}<br/><span className={styles.muted}>{c.collectiveProration==null?"":`Prorata indiv. ${percent(c.collectiveProration)}`}</span></td><td>{money(c.totalAmountEur)}</td><td><div className={styles.footerActions}>{!locked&&canTeam&&<button className={styles.buttonAlt} onClick={()=>void validateRow(c,"team")}>VALIDER CE</button>}{!locked&&canService&&<button className={styles.buttonAlt} onClick={()=>void validateRow(c,"service")}>VALIDER CDS</button>}{locked&&c.employeeKey&&<a className={styles.buttonAlt} onClick={()=>void logPdf(c.employeeKey!)} href={`/animation-mensuelle/rapport?workflowId=${encodeURIComponent(selected)}&employeeKey=${encodeURIComponent(c.employeeKey!)}`} target="_blank">RAPPORT PDF</a>}</div></td><td className={styles.sourceComment}>{String(c.sourcePayload?.sourceComment??"")}</td></tr>)}</tbody></table></div></>}

        {tab==="inputs"&&<div className={styles.cards}><article className={styles.card}><span className={styles.eyebrow}>SAISIE CONTRÔLÉE</span><h2>Donnée fin de mois</h2>{locked?<p>Workflow figé : aucune saisie n'est modifiable.</p>:<form className={styles.inputForm} onSubmit={saveInput}><label>Périmètre<select value={scopeType} onChange={e=>setScopeType(e.target.value)}><option value="global">Global</option><option value="sector">Secteur</option><option value="team">Équipe (secteur|équipe)</option><option value="employee">Collaborateur (employeeKey)</option></select></label><label>Clé périmètre<input value={scopeKey} onChange={e=>setScopeKey(e.target.value)} placeholder="* / mecanique / mecanique|A"/></label><label>Donnée<select value={inputKey} onChange={e=>setInputKey(e.target.value)}>{INPUT_KEYS.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Valeur numérique<input inputMode="decimal" value={inputValue} onChange={e=>{setInputValue(e.target.value);if(e.target.value)setInputText("");}}/></label><label>Ou valeur texte<input value={inputText} onChange={e=>{setInputText(e.target.value);if(e.target.value)setInputValue("");}} placeholder="ex. OUI"/></label><label>Commentaire<input value={inputComment} onChange={e=>setInputComment(e.target.value)} placeholder="obligatoire pour exception"/></label><button className={styles.button} disabled={loading||(!inputValue&&!inputText)}>ENREGISTRER & RECALCULER</button></form>}</article><article className={styles.card}><span className={styles.eyebrow}>VALEURS DU WORKFLOW</span><h2>Données enregistrées</h2><div className={styles.auditList}>{detail.manualInputs.map(i=><div className={styles.auditRow} key={i.id}><strong>{i.scopeType} · {i.scopeKey} · {i.inputKey}</strong><span>{i.numericValue??i.textValue??"—"}</span></div>)}</div></article></div>}

        {tab==="audit"&&<div className={styles.cards}><article className={styles.card}><span className={styles.eyebrow}>AUDIT DE CLÔTURE</span><h2>{Boolean(audit.passed)?"Contrôles satisfaits":"Clôture bloquée"}</h2>{blockers.length===0?<div className={styles.notice}>Aucune anomalie bloquante détectée par l'audit courant.</div>:<div className={styles.auditList}>{blockers.map((item,i)=><div key={`${item.code}-${i}`} className={`${styles.auditRow} ${styles.block}`}><strong>{item.message??item.code}</strong><span>{item.count??""}</span></div>)}</div>}</article><article className={styles.card}><span className={styles.eyebrow}>AVERTISSEMENTS</span><h2>Points documentés</h2>{warnings.length===0?<p>Aucun avertissement.</p>:<div className={styles.auditList}>{warnings.map((item,i)=><div key={`${item.code}-${i}`} className={`${styles.auditRow} ${styles.warn}`}><strong>{item.message??item.code}</strong><span>{item.count??""}</span></div>)}</div>}{legacy&&<div className={styles.auditList}><div className={`${styles.auditRow} ${styles.warn}`}><strong>Erreurs de formule dans l'Excel source</strong><span>{sourceErrors}</span></div><div className={`${styles.auditRow} ${styles.warn}`}><strong>Overrides sans commentaire dans l'Excel source</strong><span>{sourceNoComment}</span></div><div className={`${styles.auditRow} ${styles.warn}`}><strong>Montants € non reconstituables</strong><span>BIMESTRE</span></div></div>}</article></div>}

        {tab==="exports"&&<div className={styles.cards}><article className={styles.card}><span className={styles.eyebrow}>PAIE</span><h2>Export XLS figé</h2><p>L'export paie est construit exclusivement à partir des valeurs clôturées et contient un onglet AUDIT avec la source, les empreintes et le statut du workflow.</p>{locked&&actor?.role==="admin"?<a className={styles.button} href={`/api/monthly-animation/export?workflowId=${encodeURIComponent(selected)}`}>EXPORTER XLS PAIE</a>:locked?<p>Export paie réservé à la Direction / administration.</p>:<p>Disponible uniquement après clôture.</p>}</article><article className={styles.card}><span className={styles.eyebrow}>RAPPORT COLLABORATEUR</span><h2>PDF mensuel individuel</h2><p>Depuis l'onglet collaborateurs, ouvre « RAPPORT PDF » puis imprime/enregistre le document. Le rapport reprend la chaîne de calcul et la version figée du mois.</p></article></div>}
      </>}</section>
    </div>
  </main>;
}
