"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "../client-quote.module.css";

type ClientCase={registration:string|null;workOrder:string|null;vin:string|null;client:string|null;model:string|null;mileage:number|null;status:string;revision:number;totalHt:number;totalTtc:number;submittedAt:string|null;firstOpenedAt:string|null;clientDecidedAt:string|null};
type Item={key:string;category:string;label:string;defect:string|null;justification:string|null;method:string|null;photoData:string|null;amountHt:number;amountTtc:number;clientSelectable:boolean;clientChoice:boolean|null};
type Message={id:number;authorRole:"expert"|"client";authorName:string;body:string;createdAt:string};
type Snapshot={expertConclusion?:string;record?:{grade?:string|null;general?:{generalComment?:string}};vehicle?:Record<string,unknown>};
type Payload={connected?:boolean;case?:ClientCase;snapshot?:Snapshot|null;items?:Item[];messages?:Message[];error?:string};
function money(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(value||0);}
function dt(value?:string|null){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(date);}
function statusLabel(status?:string){const labels:Record<string,string>={submitted:"Soumis",viewed:"Consulté",accepted:"Accepté",partially_accepted:"Accepté partiellement",refused:"Refusé"};return labels[status??""]??status??"Dossier";}

export default function ClientQuote({token}:{token:string}){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tax,setTax]=useState<"HT"|"TTC">("TTC"),[choices,setChoices]=useState<Record<string,boolean>>({}),[comment,setComment]=useState(""),[message,setMessage]=useState(""),[sending,setSending]=useState(false);
 async function load(initial=false){try{const response=await fetch(`/api/expertise/client/${encodeURIComponent(token)}?_=${Date.now()}`,{cache:"no-store"});const payload=await response.json() as Payload;if(!response.ok||payload.connected===false)throw new Error(payload.error||"Dossier indisponible");setData(payload);setError("");if(initial){setChoices(Object.fromEntries((payload.items??[]).filter(item=>item.clientSelectable).map(item=>[item.key,item.clientChoice??true])));}}catch(e){setError(e instanceof Error?e.message:"Dossier indisponible");}finally{setLoading(false);}}
 useEffect(()=>{void load(true);const timer=window.setInterval(()=>void load(false),12000);return()=>window.clearInterval(timer);},[token]);
 const items=data?.items??[],caseData=data?.case,decided=Boolean(caseData?.clientDecidedAt)||["accepted","partially_accepted","refused"].includes(caseData?.status??"");
 const selected=useMemo(()=>items.filter(item=>!item.clientSelectable||(choices[item.key]??true)),[items,choices]);
 const total=useMemo(()=>selected.reduce((sum,item)=>sum+(tax==="HT"?Number(item.amountHt):Number(item.amountTtc)),0),[selected,tax]);
 const optionalCount=items.filter(item=>item.clientSelectable).length;
 async function decide(action:"accept"|"refuse"){setSending(true);setError("");try{const response=await fetch(`/api/expertise/client/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,choices:items.filter(item=>item.clientSelectable).map(item=>({key:item.key,accepted:choices[item.key]??true})),comment})});const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error||"Réponse non enregistrée");setData(payload);setComment("");}catch(e){setError(e instanceof Error?e.message:"Réponse non enregistrée");}finally{setSending(false);}}
 async function sendMessage(){if(!message.trim())return;const body=message.trim();setMessage("");setSending(true);try{const response=await fetch(`/api/expertise/client/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"message",message:body})});const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error||"Message non envoyé");setData(payload);}catch(e){setError(e instanceof Error?e.message:"Message non envoyé");}finally{setSending(false);}}
 if(loading)return <main className={styles.page}><div className={styles.loading}><div><strong>Ouverture de votre dossier…</strong><span>Chargement du rapport d'expertise CRVO.</span></div></div></main>;
 if(!caseData)return <main className={styles.page}><div className={styles.shell}><div className={styles.error}>{error||"Ce dossier n'est pas disponible."}</div></div></main>;
 const conclusion=data?.snapshot?.expertConclusion||data?.snapshot?.record?.general?.generalComment||"Le rapport détaille les constats réalisés sur le véhicule et les interventions proposées.";
 return <main className={styles.page}><div className={styles.shell}>
   <header className={styles.top}><img src="/crvo-logo.png" alt="CRVO"/><div className={styles.topRight}><span>DOSSIER D'EXPERTISE · RÉVISION {caseData.revision}</span><strong>{statusLabel(caseData.status)} · transmis le {dt(caseData.submittedAt)}</strong></div></header>
   <section className={styles.hero}><div><span className={styles.eyebrow}>VOTRE VÉHICULE</span><h1>{caseData.registration||caseData.model||"Dossier véhicule"}</h1><p>{caseData.client||"Client"} · {caseData.model||"Modèle non renseigné"}</p><div className={styles.meta}><span>OR {caseData.workOrder||"—"}</span><span>VIN {caseData.vin||"—"}</span><span>{Math.round(Number(caseData.mileage||0)).toLocaleString("fr-FR")} km</span><span>Dossier ouvert le {dt(caseData.firstOpenedAt)}</span></div></div><div className={styles.total}><small>TOTAL SELON VOS CHOIX</small><strong>{money(total)} {tax}</strong><div className={styles.toggle}><button className={tax==="HT"?styles.active:""} onClick={()=>setTax("HT")}>HT</button><button className={tax==="TTC"?styles.active:""} onClick={()=>setTax("TTC")}>TTC</button></div></div></section>
   <section className={styles.intro}><h2>Pourquoi ces interventions ?</h2><p>{conclusion}</p></section>{error&&<div className={styles.error}>{error}</div>}
   <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>DEVIS DÉTAILLÉ</span><h2>Constat → justification → coût</h2><p>{optionalCount?`${optionalCount} intervention${optionalCount>1?"s":""} laissée${optionalCount>1?"s":""} à votre choix par l'expert.`:"Toutes les interventions présentées sont nécessaires dans ce dossier."}</p></div><span className={styles.status}>{statusLabel(caseData.status)}</span></div><div className={styles.lines}>{items.map(item=><article className={styles.line} key={item.key}><div className={styles.photo}>{item.photoData?<img src={item.photoData} alt={item.defect||item.label}/>:<span>{item.category.toUpperCase()}</span>}</div><div className={styles.lineInfo}><strong>{item.label}</strong><b>{item.defect||item.category}</b>{item.justification&&<p>{item.justification}</p>}<small>{item.method||"Méthode définie par l'expert"}</small></div><div className={styles.lineAction}><span className={styles.linePrice}>{money(tax==="HT"?Number(item.amountHt):Number(item.amountTtc))} {tax}</span>{item.clientSelectable?<label className={styles.choice}><input type="checkbox" checked={choices[item.key]??true} disabled={decided} onChange={e=>setChoices(current=>({...current,[item.key]:e.target.checked}))}/> Je souhaite cette intervention</label>:<span className={styles.mandatory}>NÉCESSAIRE · INCLUSE</span>}</div></article>)}</div>{!items.length&&<p>Aucune intervention facturée n'est proposée sur ce dossier.</p>}</section>
   {decided?<div className={`${styles.decision} ${caseData.status==="refused"?styles.refused:""}`}><strong>{caseData.status==="refused"?"Vous avez refusé les interventions proposées.":caseData.status==="partially_accepted"?"Votre sélection a été enregistrée.":"Votre accord a été enregistré."}</strong><span>Décision horodatée le {dt(caseData.clientDecidedAt)}. L'équipe CRVO conserve cette version du dossier et votre choix.</span></div>:<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>VOTRE DÉCISION</span><h2>Confirmer ou poser une question</h2><p>Vous pouvez décocher uniquement les interventions que l'expert a rendues optionnelles. Les lignes nécessaires ne peuvent pas être retirées depuis ce parcours.</p></div></div><textarea className={styles.comment} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Commentaire facultatif lié à votre décision…"/><div className={styles.summary}><div><span>MONTANT DE VOTRE SÉLECTION</span><strong>{money(total)} {tax}</strong><small>{selected.length} intervention{selected.length>1?"s":""} retenue{selected.length>1?"s":""}</small></div><div className={styles.actions}><button className={styles.danger} disabled={sending} onClick={()=>void decide("refuse")}>REFUSER LE DEVIS</button><button className={styles.primary} disabled={sending} onClick={()=>void decide("accept")}>{sending?"ENREGISTREMENT…":"ACCEPTER MA SÉLECTION"}</button></div></div></section>}
   <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>ÉCHANGES</span><h2>Une question sur le devis ?</h2><p>Votre message est ajouté au dossier et horodaté. L'expert retrouve le même échange dans son interface.</p></div></div><div className={styles.chatGrid}><div className={styles.messages}>{(data?.messages??[]).map(m=><div className={`${styles.message} ${m.authorRole==="client"?styles.client:""}`} key={m.id}><strong>{m.authorRole==="client"?"Vous":m.authorName||"Expert CRVO"}</strong><span>{m.body}</span><small>{dt(m.createdAt)}</small></div>)}{!(data?.messages?.length)&&<small>Aucun message pour le moment.</small>}</div><div className={styles.chatBox}><h3>Écrire à l'expert</h3><p>Décrivez précisément votre question : défaut, intervention, coût ou choix.</p><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Votre question…"/><button className={styles.ghost} disabled={sending||!message.trim()} onClick={()=>void sendMessage()}>ENVOYER MON MESSAGE</button></div></div></section>
 </div></main>;
}
