"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./payplan.module.css";

type Rule={id:string;population:string;jobKey:string;label:string;ruleType:string;thresholds:(number|null)[];coefficients:number[];baseAmountEur:number|null;settings:Record<string,unknown>;sourceReference:string|null};
type Payload={canManage:boolean;version:{id:string;code:string;label:string;effectiveFrom:string;status:string;sourceFilename:string|null;settings:Record<string,unknown>};rules:Rule[]};
function value(v:number|null|undefined){return v==null?"":String(v)}
function populationLabel(key:string){return key==="productif"?"Productifs":key==="chef_equipe"?"Chefs d'équipe":key==="preprod"?"Pré-production / administratif":key==="fixline"?"Fixline":key;}
function displayThreshold(rule:Rule,v:number|null|undefined){if(v==null)return"";return rule.ruleType==="productivity"?String(Math.round(v*10000)/100):String(v)}
function parseThreshold(rule:Rule,v:string){if(v==="")return null;const n=Number(v.replace(",","."));return rule.ruleType==="productivity"?n/100:n;}

export default function PayplanPage(){
  const [data,setData]=useState<Payload|null>(null);const [rules,setRules]=useState<Rule[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState<string>("");
  async function load(){setError("");const response=await fetch("/api/payplan",{cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Payplan indisponible.");return;}setData(payload);setRules(payload.rules??[]);}
  useEffect(()=>{void load();},[]);
  function patch(id:string,fn:(rule:Rule)=>Rule){setRules(current=>current.map(rule=>rule.id===id?fn(rule):rule));}
  async function save(rule:Rule){setSaving(rule.id);setError("");setNotice("");try{const response=await fetch("/api/payplan",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"rule",ruleId:rule.id,thresholds:rule.thresholds,coefficients:rule.coefficients,baseAmountEur:rule.baseAmountEur,settings:rule.settings})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Enregistrement impossible.");setNotice(`${rule.label} enregistré dans le Payplan actif.`);await load();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setSaving("");}}
  const groups=useMemo(()=>[...new Set(rules.map(r=>r.population))],[rules]);
  if(!data&&!error)return <main className={styles.page}><div className={styles.shell}>Chargement du Payplan…</div></main>;
  return <main className={styles.page}><header className={styles.header}><div><a href="/animation-mensuelle">← ANIMATION VARIABLE</a><span>PARAMÉTRAGE FINANCIER VERSIONNÉ</span><h1>Payplan</h1><p>Cette page définit uniquement <b>l'attendu</b> : seuils P1 à P5, coefficients et bases €. Le résultat réellement obtenu est saisi dans le workflow du mois, puis figé à la clôture.</p></div>{data&&<div style={{display:"grid",gap:8,alignContent:"center"}}><div className={`${styles.badge} ${!data.canManage?styles.readonly:""}`}>{data.canManage?"MODIFICATION AUTORISÉE":"LECTURE SEULE"}</div>{data.canManage&&<a href="/animation-mensuelle/resultats" style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:42,borderRadius:11,background:"#004f9f",color:"#fff",textDecoration:"none",fontSize:10,fontWeight:800,padding:"0 14px"}}>SAISIR LES RÉSULTATS DU MOIS</a>}</div>}</header><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{data&&<>
    <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>LOGIQUE</span><h2>Attendu ≠ réalisé</h2></div></div><div className={styles.settings}><div className={styles.setting}><span>PAYPLAN</span><strong>Je définis les paliers attendus P1 → P5</strong></div><div className={styles.setting}><span>RÉSULTATS DU MOIS</span><strong>Je saisis la valeur réellement obtenue</strong></div><div className={styles.setting}><span>WORKFLOW</span><strong>Le moteur calcule puis CE / CDS / Direction valident</strong></div></div><p className={styles.footer}>Exemple Facturation : ici tu définis P3 = 7 devis à envoyer / 42 dossiers en attente accord. En fin de mois, si le réalisé est 6 devis / 38 dossiers, tu le saisis dans « Résultats du mois », pas dans le Payplan.</p></section>
    <section className={styles.version}><div><span>Version active</span><strong>{data.version.code}</strong></div><div><span>Date d'effet</span><strong>{new Date(data.version.effectiveFrom).toLocaleDateString("fr-FR")}</strong></div><div><span>Source initiale</span><strong>{data.version.sourceFilename??"KPI CRVO"}</strong></div><div><span>Statut</span><strong>{data.version.status.toUpperCase()}</strong></div></section>
    {groups.map(group=><section className={styles.group} key={group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>ATTENDUS DU PAYPLAN</span><h2>{populationLabel(group)}</h2></div><span className={styles.eyebrow}>{rules.filter(r=>r.population===group).length} MÉTIERS</span></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Métier</th><th>P1</th><th>P2</th><th>P3</th><th>P4</th><th>P5</th><th>Coef P1</th><th>Coef P2</th><th>Coef P3</th><th>Coef P4</th><th>Coef P5</th><th>Base €</th><th>Action</th></tr></thead><tbody>{rules.filter(r=>r.population===group).map(rule=><tr key={rule.id}><td className={styles.label}><strong>{rule.label}</strong><small>{rule.ruleType} · {rule.sourceReference??"KPI"}{rule.ruleType==="productivity"?" · seuils en %":""}</small></td>{[0,1,2,3,4].map(index=><td key={`t-${index}`}><input disabled={!data.canManage} value={displayThreshold(rule,rule.thresholds[index])} onChange={e=>patch(rule.id,r=>{const next=[...r.thresholds];next[index]=parseThreshold(r,e.target.value);return{...r,thresholds:next};})}/>{rule.ruleType==="productivity"&&<small style={{display:"block",marginTop:2,color:"#8396a2"}}>%</small>}</td>)}{[0,1,2,3,4].map(index=><td key={`c-${index}`}><input disabled={!data.canManage} value={value(rule.coefficients[index]*100)} onChange={e=>patch(rule.id,r=>{const next=[...r.coefficients];next[index]=Number(e.target.value.replace(",","."))/100;return{...r,coefficients:next};})}/><small style={{display:"block",marginTop:2,color:"#8396a2"}}>%</small></td>)}<td><input className={styles.base} disabled={!data.canManage} value={value(rule.baseAmountEur)} placeholder="à définir" onChange={e=>patch(rule.id,r=>({...r,baseAmountEur:e.target.value===""?null:Number(e.target.value.replace(",","."))}))}/></td><td><button disabled={!data.canManage||saving===rule.id} onClick={()=>void save(rule)}>{saving===rule.id?"…":"ENREGISTRER"}</button></td></tr>)}</tbody></table></div></section>)}
    <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>POLITIQUE DU MOTEUR</span><h2>Paramètres hérités du fichier de juillet</h2></div></div><div className={styles.settings}><div className={styles.setting}><span>Heures standard / jour</span><strong>{String(data.version.settings.standardHoursPerDay??7.5)} h</strong></div><div className={styles.setting}><span>Chefs d'équipe / jour</span><strong>{String(data.version.settings.teamManagerHoursPerDay??7.8)} h</strong></div><div className={styles.setting}><span>Collectif</span><strong>{data.version.settings.collectivePolicyNeedsConfirmation?"Politique à confirmer avant clôture native":"Politique validée"}</strong></div></div><p className={styles.footer}>Les bases € restent volontairement vides tant qu'une source contractuelle fiable n'est pas renseignée. C'est un contrôle bloquant.</p></section>
  </>}</div></main>;
}
