"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./payplan.module.css";

type Rule={id:string;population:string;jobKey:string;label:string;ruleType:string;thresholds:(number|null)[];coefficients:number[];baseAmountEur:number|null;settings:Record<string,unknown>;sourceReference:string|null};
type Payload={canManage:boolean;version:{id:string;code:string;label:string;effectiveFrom:string;status:string;sourceFilename:string|null;settings:Record<string,unknown>};rules:Rule[]};

const PAL=[0,1,2,3,4] as const;
function raw(v:number|null|undefined){return v==null?"":String(v)}
function pct(v:number|null|undefined){return v==null?"":String(Math.round(v*10000)/100)}
function num(v:number|null|undefined,d=2){return v==null?"—":new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(v)}
function label1(rule:Rule){return String(rule.settings?.criterion_1_label??"Critère 1");}
function label2(rule:Rule){return String(rule.settings?.criterion_2_label??"Critère 2");}
function criterion2(rule:Rule){return Array.isArray(rule.settings?.criterion_2)?(rule.settings.criterion_2 as number[]):[];}
function direction(rule:Rule){return String(rule.settings?.direction??"lte")==="gte"?"≥":"≤";}
function inputNumber(value:string){const n=Number(value.replace(",","."));return Number.isFinite(n)?n:null;}

export default function PayplanPage(){
  const [data,setData]=useState<Payload|null>(null);const [rules,setRules]=useState<Rule[]>([]);const [common,setCommon]=useState<number[]>([.5,.75,1,1.15,1.3]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState("");
  async function load(){setError("");const r=await fetch("/api/payplan",{cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok){setError(p.error||"Payplan indisponible.");return;}const payload=p as Payload;setData(payload);setRules(payload.rules??[]);const configured=Array.isArray(payload.version?.settings?.commonCoefficients)?payload.version.settings.commonCoefficients as number[]:payload.rules?.[0]?.coefficients;if(Array.isArray(configured)&&configured.length===5)setCommon(configured.map(Number));}
  useEffect(()=>{void load();},[]);
  function patch(id:string,fn:(r:Rule)=>Rule){setRules(current=>current.map(r=>r.id===id?fn(r):r));}
  async function request(body:Record<string,unknown>,message:string,key:string){setSaving(key);setError("");setNotice("");try{const r=await fetch("/api/payplan",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Enregistrement impossible.");setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setSaving("");}}
  async function saveRule(rule:Rule){await request({action:"rule",ruleId:rule.id,thresholds:rule.thresholds,coefficients:common,baseAmountEur:rule.baseAmountEur,settings:rule.settings},`${rule.label} enregistré.`,rule.id);}
  async function saveCommon(){await request({action:"common_coefficients",coefficients:common},"Coefficients P1 à P5 appliqués à tout le Payplan actif.","common");}

  const productives=useMemo(()=>rules.filter(r=>r.population==="productif"&&r.jobKey!=="fixline_productif"),[rules]);
  const admin=useMemo(()=>rules.filter(r=>r.population==="preprod"),[rules]);
  const fixline=rules.find(r=>r.population==="fixline");
  const ce=rules.find(r=>r.population==="chef_equipe");
  if(!data&&!error)return <main className={styles.page}><div className={styles.shell}>Chargement du Payplan…</div></main>;
  return <main className={styles.page}>
    <header className={styles.header}><div><a href="/animation-mensuelle">← ANIMATION VARIABLE</a><span>PARAMÈTRES · ATTENDUS DU PAYPLAN</span><h1>Paramètres Payplan</h1><p>Cette page contient uniquement les <b>règles de référence</b>. Elle reprend la logique du fichier Excel : les productifs sont pilotés par rendement, l'administratif peut avoir un ou deux critères, Fixline partage un objectif service et les Chefs d'équipe cumulent cinq sujets de prime.</p></div>{data&&<div className={styles.headerTools}><div className={`${styles.badge} ${!data.canManage?styles.readonly:""}`}>{data.canManage?"MODIFICATION AUTORISÉE":"LECTURE SEULE"}</div><a className={styles.primaryLink} href="/animation-mensuelle/resultats">RÉSULTATS DU MOIS →</a></div>}</header>
    <div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{data&&<>
      <section className={styles.version}><div><span>Version active</span><strong>{data.version.code}</strong></div><div><span>Date d'effet</span><strong>{new Date(data.version.effectiveFrom).toLocaleDateString("fr-FR")}</strong></div><div><span>Source de référence</span><strong>{data.version.sourceFilename??"KPI CRVO"}</strong></div><div><span>Statut</span><strong>{data.version.status.toUpperCase()}</strong></div></section>

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>COMMUN À TOUT LE MONDE</span><h2>Coefficients de prime</h2><p className={styles.footer}>Un seul réglage pour tout le Payplan. Il est copié dans le snapshot du mois à l'ouverture du workflow.</p></div></div><div className={styles.coefficientGrid}>{PAL.map(i=><label key={i}><span>P{i+1}</span><div><input disabled={!data.canManage} value={raw((common[i]??0)*100)} onChange={e=>{const n=inputNumber(e.target.value);setCommon(c=>c.map((v,j)=>j===i?(n??0)/100:v));}}/><b>%</b></div></label>)}<button disabled={!data.canManage||saving==="common"} onClick={()=>void saveCommon()}>{saving==="common"?"…":"ENREGISTRER POUR TOUS"}</button></div></section>

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>PRODUCTIFS · CALCUL AUTOMATIQUE</span><h2>Rendement attendu par métier</h2><p className={styles.footer}>Aucune saisie de résultat mensuel : le rendement est calculé automatiquement avec heures vendues / heures achetées, puis comparé à ces seuils.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Métier</th>{PAL.map(i=><th key={i}>P{i+1}</th>)}<th>Base €</th><th/></tr></thead><tbody>{productives.map(rule=><tr key={rule.id}><td className={styles.label}><strong>{rule.label}</strong><small>Rendement mensuel</small></td>{PAL.map(i=><td key={i}><div className={styles.unitInput}><input disabled={!data.canManage} value={pct(rule.thresholds[i])} onChange={e=>patch(rule.id,r=>{const n=inputNumber(e.target.value);const t=[...r.thresholds];t[i]=n==null?null:n/100;return{...r,thresholds:t};})}/><b>%</b></div></td>)}<td><input className={styles.base} disabled={!data.canManage} value={raw(rule.baseAmountEur)} placeholder="à définir" onChange={e=>patch(rule.id,r=>({...r,baseAmountEur:inputNumber(e.target.value)}))}/></td><td><button disabled={!data.canManage||saving===rule.id} onClick={()=>void saveRule(rule)}>ENREGISTRER</button></td></tr>)}</tbody></table></div></section>

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>ADMINISTRATIF / PRÉ-PRODUCTION</span><h2>Attendus par sujet de prime</h2><p className={styles.footer}>Comme dans <b>BASE PAYPLAN PRE-PROD</b> : un métier peut avoir un ou deux critères. Pour atteindre un palier, tous les critères du palier doivent être satisfaits.</p></div></div><div className={styles.criteriaCards}>{admin.map(rule=>{const c2=criterion2(rule),manual=Boolean(rule.settings?.manual_tier);return <article className={styles.criteriaCard} key={rule.id}><div className={styles.criteriaTitle}><div><strong>{rule.label}</strong><small>{manual?"Règle absente du BASE PAYPLAN Excel":`${direction(rule)} attendu`}</small></div><input className={styles.base} disabled={!data.canManage} value={raw(rule.baseAmountEur)} placeholder="Base €" onChange={e=>patch(rule.id,r=>({...r,baseAmountEur:inputNumber(e.target.value)}))}/></div>{manual?<div className={styles.manualRule}>Palier manuel dans le fichier de référence. À formaliser avant utilisation native.</div>:<div className={styles.criteriaTable}><div className={styles.criteriaHead}><b>Sujet</b>{PAL.map(i=><b key={i}>P{i+1}</b>)}</div><div className={styles.criteriaRow}><span><em>{direction(rule)}</em>{label1(rule)}</span>{PAL.map(i=><input key={i} disabled={!data.canManage} value={raw(rule.thresholds[i])} onChange={e=>patch(rule.id,r=>{const t=[...r.thresholds];t[i]=inputNumber(e.target.value);return{...r,thresholds:t};})}/>)}</div>{c2.length>0&&<div className={styles.criteriaRow}><span><em>{direction(rule)}</em>{label2(rule)}</span>{PAL.map(i=><input key={i} disabled={!data.canManage} value={raw(c2[i])} onChange={e=>patch(rule.id,r=>{const next=criterion2(r);next[i]=inputNumber(e.target.value)??0;return{...r,settings:{...r.settings,criterion_2:next}};})}/>)}</div>}</div>}<button className={styles.cardSave} disabled={!data.canManage||saving===rule.id} onClick={()=>void saveRule(rule)}>{saving===rule.id?"…":"ENREGISTRER CE MÉTIER"}</button></article>})}</div></section>

      {fixline&&<section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>FIXLINE · OBJECTIF COMMUN SERVICE</span><h2>Nombre de véhicules passés</h2><p className={styles.footer}>Une seule performance mensuelle est comparée à ces cinq seuils. Tous les collaborateurs Fixline reçoivent donc le même palier théorique avant règles individuelles d'absence/proratisation.</p></div></div><div className={styles.singleRule}><div className={styles.criteriaHead}><b>Résultat Fixline</b>{PAL.map(i=><b key={i}>P{i+1}</b>)}</div><div className={styles.criteriaRow}><span><em>≥</em>Véhicules passés / mois</span>{PAL.map(i=><input key={i} disabled={!data.canManage} value={raw(fixline.thresholds[i])} onChange={e=>patch(fixline.id,r=>{const t=[...r.thresholds];t[i]=inputNumber(e.target.value);return{...r,thresholds:t};})}/>)}</div></div><div className={styles.inlineActions}><input className={styles.base} disabled={!data.canManage} value={raw(fixline.baseAmountEur)} placeholder="Base €" onChange={e=>patch(fixline.id,r=>({...r,baseAmountEur:inputNumber(e.target.value)}))}/><button disabled={!data.canManage||saving===fixline.id} onClick={()=>void saveRule(fixline)}>ENREGISTRER FIXLINE</button></div></section>}

      {ce&&<section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>CHEFS D'ÉQUIPE · 5 SUJETS</span><h2>Un sujet validé = un palier gagné</h2><p className={styles.footer}>C'est la logique exacte du fichier Excel : le système teste cinq sujets indépendants. 0/5 = P0, 1/5 = P1 … 5/5 = P5.</p></div></div><div className={styles.tableWrap}><table className={`${styles.table} ${styles.ceTable}`}><thead><tr><th>Sujet de prime</th><th>Condition</th><th>Attendu</th><th>Lecture</th></tr></thead><tbody><CeCriterion label="Audit sécurité / propreté + EPI" operator=">" value={ce.thresholds[0]} percent disabled={!data.canManage} onChange={v=>patch(ce.id,r=>{const t=[...r.thresholds];t[0]=v;return{...r,thresholds:t};})}/><tr><td><strong>Palier de l'équipe</strong></td><td>=</td><td><strong>OUI</strong></td><td>L'équipe atteint au moins le palier 3</td></tr><CeCriterion label="Lead Time" operator="<" value={ce.thresholds[2]} disabled={!data.canManage} onChange={v=>patch(ce.id,r=>{const t=[...r.thresholds];t[2]=v;return{...r,thresholds:t};})}/><CeCriterion label="Qualité · taux de réclamation" operator="<" value={ce.thresholds[3]} percent disabled={!data.canManage} onChange={v=>patch(ce.id,r=>{const t=[...r.thresholds];t[3]=v;return{...r,thresholds:t};})}/><CeCriterion label="Sécurité · nombre d'AT" operator="=" value={ce.thresholds[4]} disabled={!data.canManage} onChange={v=>patch(ce.id,r=>{const t=[...r.thresholds];t[4]=v;return{...r,thresholds:t};})}/></tbody></table></div><div className={styles.inlineActions}><input className={styles.base} disabled={!data.canManage} value={raw(ce.baseAmountEur)} placeholder="Base €" onChange={e=>patch(ce.id,r=>({...r,baseAmountEur:inputNumber(e.target.value)}))}/><button disabled={!data.canManage||saving===ce.id} onClick={()=>void saveRule(ce)}>ENREGISTRER LES 5 SUJETS CE</button></div></section>}

      <section className={styles.group}><div className={styles.groupHead}><div><span className={styles.eyebrow}>FLUX MENSUEL</span><h2>Où saisir le réalisé ?</h2></div></div><div className={styles.settings}><div className={styles.setting}><span>PRODUCTIFS</span><strong>Automatique via rendement</strong></div><div className={styles.setting}><span>ADMIN / FIXLINE / CE</span><strong>Page Résultats du mois</strong></div><div className={styles.setting}><span>AUTOMATISATION</span><strong>Les KPI fiables sont pré-calculés depuis les flux CRVO</strong></div></div><a className={styles.bigAction} href="/animation-mensuelle/resultats">OUVRIR LES RÉSULTATS DU MOIS →</a></section>
    </>}</div>
  </main>;
}

function CeCriterion({label,operator,value,percent,disabled,onChange}:{label:string;operator:string;value:number|null|undefined;percent?:boolean;disabled:boolean;onChange:(v:number|null)=>void}){return <tr><td><strong>{label}</strong></td><td>{operator}</td><td><div className={styles.unitInput}><input disabled={disabled} value={percent?pct(value):raw(value)} onChange={e=>{const n=inputNumber(e.target.value);onChange(n==null?null:percent?n/100:n);}}/>{percent&&<b>%</b>}</div></td><td>{operator} {percent?`${num((value??0)*100)} %`:num(value)}</td></tr>}
