"use client";

import { DragEvent, useRef, useState } from "react";
import styles from "./data-rh.module.css";

type SourceKey = "rh" | "billed_time" | "finance" | "workload";
type ImportResult = { imported?: boolean; duplicate?: boolean; rows?: number; staffSaved?: number; committedRows?: number; remainingRows?: number; dateRange?: { min?: string | null; max?: string | null }; filename?: string; error?: string };
type BatchStart = ImportResult & { ready?: boolean; batchId?: string };
type ParsedFile = { headers: string[]; rows: Record<string, unknown>[]; sha256: string; byteSize: number };
type RhRow = { row_index: number; work_date: string; mechanic_name: string; time_code: string | null; time_description: string | null; time_value: number; matricule: string | null; service: string | null; team_code: string | null; first_name: string | null; last_name: string | null };
type OpsRow = { row_index: number; data_date: string | null; payload: Record<string, unknown> };
type Normalized = { rows: OpsRow[]; headers: string[]; minDate: string; maxDate: string; sha256: string; byteSize: number };
type Zone = { source: SourceKey; badge: string; title: string; subtitle: string; detail: string };

const zones: Zone[] = [
  { source: "rh", badge: "1", title: "Data RH", subtitle: "Temps de présence", detail: "Date, collaborateur, code présence, métier, équipe, matricule et durée." },
  { source: "billed_time", badge: "2", title: "Temps pointé facturé", subtitle: "Productivité", detail: "Export CRVO : No OR, Atelier, Mécanicien, Equipe, Section, Temps Facturés." },
  { source: "finance", badge: "3", title: "Factures & chiffre d’affaires", subtitle: "CA mensuel réalisé", detail: "Export CRVO : No OR, No Facture, Date Facture, Heures MO, Mt Net L. MO, Total Net, VIN." },
  { source: "workload", badge: "4", title: "OR en cours", subtitle: "Charge & CA encours", detail: "Export CRVO : OR, section intervention, heures MO et montants des dossiers en production." },
];

function key(value: unknown) { return String(value ?? "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, ""); }
function text(value: unknown, max = 300) { const s = String(value ?? "").trim(); return s ? s.slice(0, max) : null; }
function numberValue(value: unknown) {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  let s = String(value ?? "").trim().replace(/[\s\u00a0€]/g, "").replace(/[^0-9,.-]/g, "");
  if (!s) return null;
  const comma = s.lastIndexOf(","), dot = s.lastIndexOf(".");
  if (comma >= 0 && dot >= 0) s = comma > dot ? s.replace(/\./g, "").replace(",", ".") : s.replace(/,/g, "");
  else if (comma >= 0) s = s.replace(",", ".");
  const n = Number(s); return Number.isFinite(n) ? n : null;
}
function hoursValue(value: unknown) { const s=String(value??"").trim(); const m=s.match(/^(-?\d{1,4}):([0-5]\d)(?::([0-5]\d))?$/); if(m){const sign=Number(m[1])<0?-1:1;return Number(m[1])+sign*(Number(m[2])/60+Number(m[3]??0)/3600);} return numberValue(value); }
function isoDate(year:number,month:number,day:number){const d=new Date(Date.UTC(year,month-1,day));if(d.getUTCFullYear()!==year||d.getUTCMonth()!==month-1||d.getUTCDate()!==day)return null;return `${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;}
function dateValue(value: unknown) {
  if (value instanceof Date && !Number.isNaN(value.getTime())) return isoDate(value.getFullYear(),value.getMonth()+1,value.getDate());
  if (typeof value === "number" && Number.isFinite(value) && value > 20000 && value < 80000) { const d=new Date(Date.UTC(1899,11,30)+Math.round(value*86400000)); return isoDate(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate()); }
  const s=String(value??"").trim();
  if (/^\d+(?:\.\d+)?$/.test(s)) { const n=Number(s); if(n>20000&&n<80000){const d=new Date(Date.UTC(1899,11,30)+Math.round(n*86400000));return isoDate(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate());} }
  let m=s.match(/^(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})/); if(m)return isoDate(Number(m[1]),Number(m[2]),Number(m[3]));
  m=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](20\d{2})/); if(m)return isoDate(Number(m[3]),Number(m[2]),Number(m[1]));
  m=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{2})$/); if(m)return isoDate(2000+Number(m[3]),Number(m[2]),Number(m[1]));
  return null;
}
function pick(row:Record<string,unknown>,aliases:string[]){for(const a of aliases){const v=row[key(a)];if(v!==undefined&&v!==null&&String(v).trim()!=="")return v;}return null;}
function sum(values:Array<number|null>){const xs=values.filter((v):v is number=>v!==null&&Number.isFinite(v));return xs.length?xs.reduce((a,b)=>a+b,0):null;}
function firstNumber(values:Array<number|null>){return values.find((v):v is number=>v!==null&&Number.isFinite(v))??null;}
function compactDate(value?:string|null){if(!value)return null;return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`));}
function parisToday(){const parts=new Intl.DateTimeFormat("fr-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const g=(t:string)=>parts.find(p=>p.type===t)?.value??"";return `${g("year")}-${g("month")}-${g("day")}`;}
function parisMonth(){return parisToday().slice(0,7);}
function normalizeTeam(value:unknown){const s=String(value??"").toUpperCase();const m=s.match(/(?:^|\b|[._ -])([ABC])(?:\b|[._ -]|$)/);return m?.[1]??null;}
function parseIdentity(raw:unknown){const full=text(raw,280)??"";const m=full.match(/^(.*)-([^-]+)-([A-Z])-([0-9]+)$/i);if(!m)return{raw:full,name:full,service:null as string|null,team:null as string|null,matricule:null as string|null};const t=["A","B","C"].includes(m[3].toUpperCase())?m[3].toUpperCase():null;return{raw:full,name:m[1].trim(),service:m[2].trim().toUpperCase(),team:t,matricule:m[4]};}
function activityFrom(values:{section?:unknown;service?:unknown;teamLabel?:unknown;intervention?:unknown}){
  const svc=String(values.service??"").toUpperCase().trim();
  const all=key([values.section,values.teamLabel,values.intervention].filter(Boolean).join(" "));
  if(svc==="FIX")return{sectorKey:"carrosserie",sectorLabel:"Carrosserie",workcenterKey:"fixline"};
  if(svc==="BOX")return{sectorKey:"carrosserie",sectorLabel:"Carrosserie",workcenterKey:"box"};
  if(svc==="TOL")return{sectorKey:"carrosserie",sectorLabel:"Carrosserie",workcenterKey:"tolerie"};
  if(svc==="DSP")return{sectorKey:"dsp",sectorLabel:"DSP",workcenterKey:"dsp"};
  if(svc==="MEC")return{sectorKey:"mecanique",sectorLabel:"Mécanique",workcenterKey:"mecanique"};
  if(svc==="EXP"||svc==="DYN")return{sectorKey:"expertise",sectorLabel:"Expertise",workcenterKey:"expertise"};
  if(svc==="JAN")return{sectorKey:"jantes",sectorLabel:"Jantes",workcenterKey:"jantes"};
  if(svc==="PRE")return{sectorKey:"preparation",sectorLabel:"Préparation",workcenterKey:"preparation"};
  if(svc==="QUA"||svc==="OQF")return{sectorKey:"qualite",sectorLabel:"Qualité",workcenterKey:"qualite"};
  if(svc==="PHO")return{sectorKey:"photo",sectorLabel:"Photo",workcenterKey:"photo"};
  if(svc==="LAV")return{sectorKey:"lavage",sectorLabel:"Lavage",workcenterKey:"lavage"};
  if(svc==="TRA")return{sectorKey:"diagnostic",sectorLabel:"Diagnostic",workcenterKey:"diagnostic"};
  if(svc==="MGN"||svc==="ACH"||svc==="LAB")return{sectorKey:"magasin",sectorLabel:"Magasin",workcenterKey:"magasin"};
  if(/mecan|mecani/.test(all))return{sectorKey:"mecanique",sectorLabel:"Mécanique",workcenterKey:"mecanique"};
  if(/deboss/.test(all))return{sectorKey:"dsp",sectorLabel:"DSP",workcenterKey:"dsp"};
  if(/expert/.test(all))return{sectorKey:"expertise",sectorLabel:"Expertise",workcenterKey:"expertise"};
  if(/jante/.test(all))return{sectorKey:"jantes",sectorLabel:"Jantes",workcenterKey:"jantes"};
  if(/prepar|centre_de_preparation/.test(all))return{sectorKey:"preparation",sectorLabel:"Préparation",workcenterKey:"preparation"};
  if(/qualit/.test(all))return{sectorKey:"qualite",sectorLabel:"Qualité",workcenterKey:"qualite"};
  if(/labo_photo|photo/.test(all))return{sectorKey:"photo",sectorLabel:"Photo",workcenterKey:"photo"};
  if(/lavage/.test(all))return{sectorKey:"lavage",sectorLabel:"Lavage",workcenterKey:"lavage"};
  if(/transport/.test(all))return{sectorKey:"transport",sectorLabel:"Transport",workcenterKey:"transport"};
  if(/peinture/.test(all))return{sectorKey:"carrosserie",sectorLabel:"Carrosserie",workcenterKey:"fixline"};
  if(/carross/.test(all))return{sectorKey:"carrosserie",sectorLabel:"Carrosserie",workcenterKey:"carrosserie"};
  return{sectorKey:"non_classe",sectorLabel:"Non classé",workcenterKey:"non_classe"};
}

const headerHints=new Set(["date","date_facture","date_ouverture_or","codet","type_temps","nombre_heures","nom_prenom","no_or","no_facture","heures_mo","mt_net_l_mo","total_net","vin","immat","client_facture_code","groupe_imputation","mt_net_l_divers","pa_ligne_divers","mt_net_l_piece","mt_net_l_peinture","mt_net_l_forfait","intervention","section_intervention","v_comptable","atelier","mecanicien","equipe","section_intervention_code","section","temps_factures"]);
function gridToRecords(grid:unknown[][]){if(!grid.length)return{headers:[] as string[],rows:[] as Record<string,unknown>[]};const headerIndex=grid.slice(0,40).map((r,i)=>{const n=r.map(key).filter(Boolean);return{i,score:n.filter(x=>headerHints.has(x)).length*25+Math.min(n.length,20)}}).sort((a,b)=>b.score-a.score)[0]?.i??0;const seen=new Map<string,number>();const headers=(grid[headerIndex]??[]).map((v,i)=>key(v)||`col_${i+1}`).map(n=>{const c=(seen.get(n)??0)+1;seen.set(n,c);return c===1?n:`${n}_${c}`});const rows=grid.slice(headerIndex+1).filter(r=>r.some(v=>String(v??"").trim())).map(r=>{const o:Record<string,unknown>={};headers.forEach((h,i)=>o[h]=r[i]??null);return o;});return{headers,rows};}
function parseDelimited(source:string){const first=source.split(/\r?\n/,1)[0]??"";const delim=[";","\t",","].map(d=>({d,n:first.split(d).length})).sort((a,b)=>b.n-a.n)[0]?.d??";";const grid:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===delim&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);cell="";if(row.some(v=>v.trim()))grid.push(row);row=[];}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))grid.push(row);return gridToRecords(grid);}
async function sha256File(file:File){const d=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
async function parseFile(file:File):Promise<ParsedFile>{
  if(file.size<=0||file.size>25*1024*1024)throw new Error("Le fichier est vide ou dépasse 25 Mo.");
  let parsed:{headers:string[];rows:Record<string,unknown>[]};
  if(/\.csv$/i.test(file.name)) parsed=parseDelimited(await file.text());
  else if(/\.(xlsx|xls)$/i.test(file.name)){
    const XLSX=await import("@e965/xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});if(!wb.SheetNames.length)throw new Error("Le classeur Excel ne contient aucune feuille.");let best:unknown[][]=[],count=-1;for(const name of wb.SheetNames){const sh=wb.Sheets[name];if(!sh)continue;const grid=XLSX.utils.sheet_to_json<unknown[]>(sh,{header:1,raw:true,defval:null}) as unknown[][];const n=grid.filter(r=>Array.isArray(r)&&r.some(v=>String(v??"").trim())).length;if(n>count){best=grid;count=n;}}parsed=gridToRecords(best);
  } else throw new Error("Format refusé. Utilise CSV, XLSX ou XLS.");
  if(!parsed.rows.length)throw new Error("Aucune donnée exploitable trouvée dans le fichier.");
  return{...parsed,sha256:await sha256File(file),byteSize:file.size};
}

async function normalizeRh(file:File):Promise<{rows:RhRow[];headers:string[];minDate:string;maxDate:string;sha256:string;byteSize:number}>{const p=await parseFile(file);const rows:RhRow[]=[];p.rows.forEach((r,i)=>{const ident=parseIdentity(pick(r,["nom_prenom","collaborateur","mecanicien","nom"]));const d=dateValue(pick(r,["date","work_date","date_pointage"]));const h=hoursValue(pick(r,["nombre_heures","time_value","temps","heures","duree"]));if(!d||!ident.raw||h===null)return;const team=normalizeTeam(pick(r,["equipe","team","groupe"]))??ident.team;rows.push({row_index:i+1,work_date:d,mechanic_name:ident.raw,time_code:text(pick(r,["codet","time_code","code_pointage"]),80),time_description:text(pick(r,["type_temps","time_description","libelle"])),time_value:h,matricule:text(pick(r,["matricule"]),100)??ident.matricule,service:text(pick(r,["service","secteur","atelier"]),160)??ident.service,team_code:team,first_name:text(pick(r,["prenom"]),120),last_name:text(pick(r,["nom_famille"]),120)});});if(!rows.length)throw new Error(`Aucune ligne RH reconnue. Colonnes : ${p.headers.join(", ")}.`);const ds=rows.map(r=>r.work_date).sort();return{rows,headers:p.headers,minDate:ds[0],maxDate:ds.at(-1)!,sha256:p.sha256,byteSize:p.byteSize};}

async function normalizeOps(source:Exclude<SourceKey,"rh">,file:File,month:string):Promise<Normalized>{const p=await parseFile(file);const out:OpsRow[]=[];const monthDate=/^20\d{2}-\d{2}$/.test(month)?`${month}-01`:`${parisMonth()}-01`;
  if(source==="billed_time")p.rows.forEach((r,i)=>{const wo=text(pick(r,["no_or","work_order","ordre_reparation","or","dossier"]),64);const h=hoursValue(pick(r,["temps_factures","temps_facture","heures_facturees","labor_hours","temps_pointe"]));if(!wo||h===null)return;const ident=parseIdentity(pick(r,["mecanicien","mechanic_name","collaborateur","nom_prenom"]));const mechanic=ident.raw||"NON AFFECTE";const teamLabel=pick(r,["equipe","team"]);const section=pick(r,["section","section_intervention"]);const a=activityFrom({section,service:ident.service,teamLabel,intervention:section});const team=normalizeTeam(teamLabel)??ident.team;out.push({row_index:i+1,data_date:monthDate,payload:{work_date:monthDate,invoice_date:null,invoice_number:null,work_order:wo,mechanic_name:mechanic,time_code:text(pick(r,["section_intervention_code","section_intervention_code_section","time_code"]),80),time_description:text(section),labor_hours:h,sector_key:a.sectorKey,sector_label:a.sectorLabel,workcenter_key:a.workcenterKey,team_code:team,matricule:ident.matricule,intervention:text(section),metadata:{atelier:text(pick(r,["atelier"]),120),original_team:text(teamLabel,120),section:text(section,160),import_month:month}}});});
  if(source==="finance"){const groups=new Map<string,Record<string,unknown>[]>();p.rows.forEach(r=>{const inv=text(pick(r,["no_facture","invoice_number","numero_facture","facture"]),64);const d=dateValue(pick(r,["date_facture","invoice_date","date"]));if(!inv||!d)return;const k=`${d}|${inv}`;const xs=groups.get(k)??[];xs.push(r);groups.set(k,xs);});let i=0;for(const[k,rows]of groups){i++;const[d,inv]=k.split("|");const first=rows[0];const total=firstNumber(rows.map(r=>numberValue(pick(r,["total_net","revenue_total","total_ht","chiffre_affaires","ca"]))))??0;const labor=sum(rows.map(r=>numberValue(pick(r,["mt_net_l_mo","labor_revenue","ca_mo"]))))??0;const hours=sum(rows.map(r=>hoursValue(pick(r,["heures_mo","labor_hours","heures_facturees"]))))??0;out.push({row_index:i,data_date:d,payload:{invoice_number:inv,registration:null,work_order:text(pick(first,["no_or","work_order","or"]),64),client:null,revenue_total:total,labor_revenue:labor,parts_revenue:null,other_revenue:total-labor,vin:text(pick(first,["vin"]),40),labor_hours:hours,metadata:{source_columns:p.headers}}});}}
  if(source==="workload"){const groups=new Map<string,{date:string;sector:ReturnType<typeof activityFrom>;rows:Record<string,unknown>[];rowIndex:number}>();p.rows.forEach((r,i)=>{const wo=text(pick(r,["no_or","work_order","or","dossier"]),64);if(!wo)return;const section=pick(r,["section_intervention","section"]);const a=activityFrom({section,intervention:pick(r,["intervention"])});const snap=dateValue(pick(r,["snapshot_at","date_snapshot","date_extraction"]))??parisToday();const k=`${snap}|${wo}|${a.sectorKey}`;const g=groups.get(k)??{date:snap,sector:a,rows:[],rowIndex:i+1};g.rows.push(r);groups.set(k,g);});for(const g of groups.values()){const first=g.rows[0];const hours=sum(g.rows.map(r=>hoursValue(pick(r,["heures_mo","remaining_hours","heures_restantes"]))))??0;const labor=sum(g.rows.map(r=>numberValue(pick(r,["mt_net_l_mo","potential_labor_revenue"]))))??0;const divers=sum(g.rows.map(r=>numberValue(pick(r,["mt_net_l_divers"]))))??0;const parts=sum(g.rows.map(r=>numberValue(pick(r,["mt_net_l_piece"]))))??0;const paint=sum(g.rows.map(r=>numberValue(pick(r,["mt_net_l_peinture"]))))??0;const forfait=sum(g.rows.map(r=>numberValue(pick(r,["mt_net_l_forfait"]))))??0;const total=labor+divers+parts+paint+forfait;out.push({row_index:g.rowIndex,data_date:g.date,payload:{registration:text(pick(first,["immat","immatriculation"]),32),work_order:text(pick(first,["no_or","work_order","or"]),64),client:text(pick(first,["client_facture_code","client_facture","client"]),100),sector_key:g.sector.sectorKey,sector_label:g.sector.sectorLabel,status:null,status_since:null,age_days:null,remaining_minutes:hours*60,booked_minutes:null,estimated_total_minutes:hours*60,vin:null,opened_at:dateValue(pick(first,["date_ouverture_or","date_ouverture"])),potential_revenue_total:total,potential_labor_revenue:labor,potential_parts_revenue:parts+paint,potential_other_revenue:divers+forfait,primary_activity:text(pick(first,["intervention","section_intervention"]),300),metadata:{workcenter_key:g.sector.workcenterKey,section_intervention:text(pick(first,["section_intervention"]),160),groupe_imputation:text(pick(first,["groupe_imputation"]),120),v_comptable:text(pick(first,["v_comptable"]),120)}}});}}
  if(!out.length){const expected=source==="billed_time"?"No OR + Mécanicien + Temps Facturés":source==="finance"?"No Facture + Date Facture + Total Net":"No OR + Section Intervention + Heures MO / montants";throw new Error(`Aucune ligne reconnue. Format attendu : ${expected}. Colonnes : ${p.headers.join(", ")}.`);}const ds=out.map(r=>r.data_date).filter((v):v is string=>Boolean(v)).sort();return{rows:out,headers:p.headers,minDate:ds[0]??parisToday(),maxDate:ds.at(-1)??parisToday(),sha256:p.sha256,byteSize:p.byteSize};}

async function readPayload<T extends{error?:string}>(r:Response,fallback:string):Promise<T>{const raw=await r.text();if(!raw)return{error:`${fallback} (HTTP ${r.status})`} as T;try{return JSON.parse(raw) as T}catch{return{error:`${fallback} (HTTP ${r.status}) · ${raw.slice(0,180)}`} as T}}
function UploadZone({zone}:{zone:Zone}){const ref=useRef<HTMLInputElement>(null);const[drag,setDrag]=useState(false);const[loading,setLoading]=useState(false);const[fileName,setFileName]=useState("");const[progress,setProgress]=useState("");const[result,setResult]=useState<ImportResult|null>(null);const[month,setMonth]=useState(parisMonth());
  async function uploadRh(file:File){setProgress("Lecture locale du fichier RH…");const n=await normalizeRh(file);const sr=await fetch("/api/data-import/rh-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"start",filename:file.name,sha256:n.sha256,byteSize:n.byteSize,minDate:n.minDate,maxDate:n.maxDate,totalRows:n.rows.length,headers:n.headers})});const s=await readPayload<BatchStart>(sr,"Initialisation RH illisible");if(!sr.ok)throw new Error(s.error||`Initialisation RH refusée (${sr.status})`);if(s.duplicate){setResult(s);return;}if(!s.ready||!s.batchId)throw new Error("Lot RH non créé.");for(let o=0;o<n.rows.length;o+=1200){const rows=n.rows.slice(o,o+1200);const rr=await fetch("/api/data-import/rh-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"chunk",batchId:s.batchId,rows})});const x=await readPayload<{error?:string}>(rr,"Bloc RH illisible");if(!rr.ok)throw new Error(x.error||`Bloc RH refusé (${rr.status})`);setProgress(`RH ${Math.round(Math.min(o+rows.length,n.rows.length)/n.rows.length*100)} %`);}const fr=await fetch("/api/data-import/rh-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"finish",batchId:s.batchId})});const f=await readPayload<ImportResult>(fr,"Finalisation RH illisible");if(!fr.ok||!f.imported)throw new Error(f.error||`Finalisation RH refusée (${fr.status})`);setResult(f);}
  async function uploadOps(file:File){setProgress("Lecture et validation locale…");const n=await normalizeOps(zone.source as Exclude<SourceKey,"rh">,file,month);const sr=await fetch("/api/data-import/ops-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"start",source:zone.source,filename:file.name,sha256:n.sha256,byteSize:n.byteSize,minDate:n.minDate,maxDate:n.maxDate,totalRows:n.rows.length,headers:n.headers})});const s=await readPayload<BatchStart>(sr,"Initialisation illisible");if(!sr.ok)throw new Error(s.error||`Initialisation refusée (${sr.status})`);if(s.duplicate){setResult(s);return;}if(!s.ready||!s.batchId)throw new Error("Lot d’import non créé.");for(let o=0;o<n.rows.length;o+=1200){const rows=n.rows.slice(o,o+1200);const rr=await fetch("/api/data-import/ops-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"chunk",batchId:s.batchId,rows})});const x=await readPayload<{error?:string}>(rr,"Bloc illisible");if(!rr.ok)throw new Error(x.error||`Bloc refusé (${rr.status})`);setProgress(`Chargement ${Math.round(Math.min(o+rows.length,n.rows.length)/n.rows.length*70)} %`);}let final:ImportResult={};for(let i=0;i<150;i++){const rr=await fetch("/api/data-import/ops-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"commit",batchId:s.batchId,limit:3000})});const x=await readPayload<ImportResult>(rr,"Consolidation illisible");if(!rr.ok)throw new Error(x.error||`Consolidation refusée (${rr.status})`);final=x;const c=Number(x.committedRows??0);setProgress(`Consolidation ${Math.min(99,70+Math.round(c/n.rows.length*30))} %`);if(x.imported)break;}if(!final.imported)throw new Error("Consolidation incomplète : le lot reste disponible pour diagnostic.");setResult(final);}
  async function upload(file?:File){if(!file||loading)return;setFileName(file.name);setResult(null);setProgress("");setLoading(true);try{if(zone.source==="rh")await uploadRh(file);else await uploadOps(file);}catch(e){setResult({error:e instanceof Error?e.message:"Import impossible."});}finally{setLoading(false);setProgress("");if(ref.current)ref.current.value="";}}
  const min=compactDate(result?.dateRange?.min),max=compactDate(result?.dateRange?.max),range=min&&max?(min===max?min:`${min} → ${max}`):null;return <article className={styles.uploadCard}><div className={styles.uploadHead}><span>{zone.badge}</span><div><strong>{zone.title}</strong><small>{zone.subtitle}</small></div></div>{zone.source==="billed_time"&&<label style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,margin:"0 0 10px",padding:"9px 11px",border:"1px solid #d7e6ef",borderRadius:10,background:"#fff",fontSize:10,color:"#60798a"}}><span><b style={{color:"#004f9f"}}>Mois de rattachement</b><br/><small>Le fichier ne contient pas de date.</small></span><input type="month" value={month} onChange={e=>setMonth(e.target.value)} style={{border:"1px solid #cfe0ea",borderRadius:8,padding:"7px 9px",color:"#004f9f",fontWeight:700,background:"#f8fbfd"}}/></label>}<div className={`${styles.dropZone} ${drag?styles.dropZoneActive:""} ${result?.error?styles.dropZoneError:result?.imported||result?.duplicate?styles.dropZoneSuccess:""}`} onDragEnter={e=>{e.preventDefault();setDrag(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDrag(false)} onDrop={(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDrag(false);void upload(e.dataTransfer.files?.[0])}} onClick={()=>ref.current?.click()} role="button" tabIndex={0}><input ref={ref} className={styles.fileInput} type="file" accept=".csv,.xlsx,.xls" onChange={e=>void upload(e.target.files?.[0])}/><b>{loading?"Analyse et intégration…":"Glisse le fichier ici"}</b><span>{loading?(progress||fileName):"ou clique pour choisir un fichier"}</span><small>CSV · XLSX · XLS · 25 Mo max</small></div><p className={styles.uploadHint}>{zone.detail}</p>{result?.imported&&<div className={styles.importOk}><strong>IMPORTÉ</strong><span>{result.rows??0} lignes intégrées{range?` · ${range}`:""}{zone.source==="rh"&&result.staffSaved?` · ${result.staffSaved} collaborateurs`:""}</span></div>}{result?.duplicate&&<div className={styles.importDuplicate}><strong>DÉJÀ INTÉGRÉ</strong><span>{result.filename||fileName}</span></div>}{result?.error&&<div className={styles.importError}><strong>À CORRIGER</strong><span>{result.error}</span></div>}</article>}
export default function DirectFileImportV3(){return <section className={styles.importSection}><div className={styles.importTitle}><div><span>IMPORT DIRECT</span><h2>Dépose les 4 fichiers</h2></div><p>Lecture native CSV/XLSX/XLS sur ton poste, reconnaissance des colonnes CRVO réelles, dates Excel comprises, puis intégration sécurisée par blocs.</p></div><div className={styles.uploadGrid}>{zones.map(z=><UploadZone key={z.source} zone={z}/>)}</div></section>}
