"use client";

import { DragEvent, useRef, useState } from "react";
import styles from "./data-rh.module.css";

type ImportResult={imported?:boolean;duplicate?:boolean;rows?:number;committedRows?:number;remainingRows?:number;dateRange?:{min?:string|null;max?:string|null};filename?:string;error?:string};
type BatchStart=ImportResult&{ready?:boolean;batchId?:string};
type OpsRow={row_index:number;data_date:string;payload:Record<string,unknown>};
type Parsed={headers:string[];rows:Record<string,unknown>[];fileHash:string;byteSize:number};

function key(value:unknown){return String(value??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"");}
function text(value:unknown,max=300){const s=String(value??"").trim();return s?s.slice(0,max):null;}
function numberValue(value:unknown){if(typeof value==="number")return Number.isFinite(value)?value:null;let s=String(value??"").trim().replace(/[\s\u00a0€]/g,"").replace(/[^0-9,.-]/g,"");if(!s)return null;const comma=s.lastIndexOf(","),dot=s.lastIndexOf(".");if(comma>=0&&dot>=0)s=comma>dot?s.replace(/\./g,"").replace(",", "."):s.replace(/,/g,"");else if(comma>=0)s=s.replace(",", ".");const n=Number(s);return Number.isFinite(n)?n:null;}
function hoursValue(value:unknown){const s=String(value??"").trim();const m=s.match(/^(-?\d{1,4}):([0-5]\d)(?::([0-5]\d))?$/);if(m){const sign=Number(m[1])<0?-1:1;return Number(m[1])+sign*(Number(m[2])/60+Number(m[3]??0)/3600);}return numberValue(value);}
function pick(row:Record<string,unknown>,aliases:string[]){for(const alias of aliases){const value=row[key(alias)];if(value!==undefined&&value!==null&&String(value).trim()!=="")return value;}return null;}
function parisToday(){const parts=new Intl.DateTimeFormat("fr-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const g=(t:string)=>parts.find(p=>p.type===t)?.value??"";return `${g("year")}-${g("month")}-${g("day")}`;}
function parisMonth(){return parisToday().slice(0,7);}
function monthEnd(month:string){const [year,m]=month.split("-").map(Number);return new Date(Date.UTC(year,m,0)).toISOString().slice(0,10);}
function cutoffFor(month:string){const end=monthEnd(month),today=parisToday();return month===today.slice(0,7)?today:end<today?end:today;}
function compactDate(value?:string|null){if(!value)return"—";return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${value}T12:00:00`));}
function normalizeTeam(value:unknown){const s=String(value??"").toUpperCase();const m=s.match(/(?:^|\b|[._ -])([ABC])(?:\b|[._ -]|$)/);return m?.[1]??null;}
function parseIdentity(raw:unknown){const full=text(raw,280)??"";const m=full.match(/^(.*)-([^-]+)-([A-Z])-([0-9]+)$/i);if(!m)return{raw:full,service:null as string|null,team:null as string|null,matricule:null as string|null};return{raw:full,service:m[2].trim().toUpperCase(),team:["A","B","C"].includes(m[3].toUpperCase())?m[3].toUpperCase():null,matricule:m[4]};}
function activityFrom(section:unknown,service:unknown,teamLabel:unknown){const svc=String(service??"").toUpperCase().trim();const all=key([section,teamLabel].filter(Boolean).join(" "));if(svc==="FIX")return["carrosserie","Carrosserie","fixline"];if(svc==="BOX")return["carrosserie","Carrosserie","box"];if(svc==="TOL")return["carrosserie","Carrosserie","tolerie"];if(svc==="DSP"||/deboss/.test(all))return["dsp","DSP","dsp"];if(svc==="MEC"||/mecan|mecani/.test(all))return["mecanique","Mécanique","mecanique"];if(svc==="EXP"||svc==="DYN"||/expert/.test(all))return["expertise","Expertise","expertise"];if(svc==="JAN"||/jante/.test(all))return["jantes","Jantes","jantes"];if(svc==="PRE"||/prepar|centre_de_preparation/.test(all))return["preparation","Préparation","preparation"];if(svc==="QUA"||svc==="OQF"||/qualit/.test(all))return["qualite","Qualité","qualite"];if(svc==="PHO"||/photo/.test(all))return["photo","Photo","photo"];if(/peinture/.test(all))return["carrosserie","Carrosserie","fixline"];if(/carross/.test(all))return["carrosserie","Carrosserie","carrosserie"];return["non_classe","Non classé","non_classe"];}

const headerHints=new Set(["no_or","atelier","mecanicien","equipe","section_intervention_code","section","temps_factures","temps_facture","heures_facturees"]);
function gridToRecords(grid:unknown[][]){if(!grid.length)return{headers:[] as string[],rows:[] as Record<string,unknown>[]};const headerIndex=grid.slice(0,40).map((r,i)=>{const normalized=r.map(key).filter(Boolean);return{i,score:normalized.filter(x=>headerHints.has(x)).length*25+Math.min(normalized.length,20)}}).sort((a,b)=>b.score-a.score)[0]?.i??0;const seen=new Map<string,number>();const headers=(grid[headerIndex]??[]).map((v,i)=>key(v)||`col_${i+1}`).map(name=>{const count=(seen.get(name)??0)+1;seen.set(name,count);return count===1?name:`${name}_${count}`});const rows=grid.slice(headerIndex+1).filter(r=>r.some(v=>String(v??"").trim())).map(r=>{const o:Record<string,unknown>={};headers.forEach((h,i)=>o[h]=r[i]??null);return o;});return{headers,rows};}
function parseDelimited(source:string){const first=source.split(/\r?\n/,1)[0]??"";const delim=[";","\t",","].map(d=>({d,n:first.split(d).length})).sort((a,b)=>b.n-a.n)[0]?.d??";";const grid:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===delim&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);cell="";if(row.some(v=>v.trim()))grid.push(row);row=[];}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))grid.push(row);return gridToRecords(grid);}
async function hashBytes(value:ArrayBuffer|string){const input=typeof value==="string"?new TextEncoder().encode(value):value;const digest=await crypto.subtle.digest("SHA-256",input);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");}
async function parseFile(file:File):Promise<Parsed>{if(file.size<=0||file.size>25*1024*1024)throw new Error("Le fichier est vide ou dépasse 25 Mo.");const bytes=await file.arrayBuffer();let parsed:{headers:string[];rows:Record<string,unknown>[]};if(/\.csv$/i.test(file.name))parsed=parseDelimited(new TextDecoder().decode(bytes));else if(/\.(xlsx|xls)$/i.test(file.name)){const XLSX=await import("@e965/xlsx");const wb=XLSX.read(bytes,{type:"array",cellDates:true});if(!wb.SheetNames.length)throw new Error("Le classeur Excel ne contient aucune feuille.");let best:unknown[][]=[],count=-1;for(const name of wb.SheetNames){const sh=wb.Sheets[name];if(!sh)continue;const grid=XLSX.utils.sheet_to_json<unknown[]>(sh,{header:1,raw:true,defval:null}) as unknown[][];const n=grid.filter(r=>Array.isArray(r)&&r.some(v=>String(v??"").trim())).length;if(n>count){best=grid;count=n;}}parsed=gridToRecords(best);}else throw new Error("Format refusé. Utilise CSV, XLSX ou XLS.");if(!parsed.rows.length)throw new Error("Aucune donnée exploitable trouvée dans le fichier.");return{...parsed,fileHash:await hashBytes(bytes),byteSize:file.size};}
async function readPayload<T extends{error?:string}>(response:Response,fallback:string):Promise<T>{const raw=await response.text();if(!raw)return{error:`${fallback} (HTTP ${response.status})`} as T;try{return JSON.parse(raw) as T}catch{return{error:`${fallback} (HTTP ${response.status}) · ${raw.slice(0,180)}`} as T;}}

export default function StrictBilledTimeImport(){
  const ref=useRef<HTMLInputElement>(null);
  const [month,setMonth]=useState(parisMonth());
  const [cutoff,setCutoff]=useState(cutoffFor(parisMonth()));
  const [drag,setDrag]=useState(false);
  const [loading,setLoading]=useState(false);
  const [fileName,setFileName]=useState("");
  const [progress,setProgress]=useState("");
  const [result,setResult]=useState<ImportResult|null>(null);
  const periodStart=`${month}-01`;

  function changeMonth(value:string){setMonth(value);setCutoff(cutoffFor(value));setResult(null);}
  function validatePeriod(){if(!/^20\d{2}-\d{2}$/.test(month))throw new Error("Mois de productivité invalide.");if(!/^20\d{2}-\d{2}-\d{2}$/.test(cutoff)||cutoff.slice(0,7)!==month)throw new Error("La date d'arrêté doit appartenir au mois sélectionné.");if(cutoff<periodStart||cutoff>parisToday())throw new Error("La date d'arrêté ne peut pas être future ni antérieure au début du mois.");}

  async function upload(file?:File){if(!file||loading)return;setFileName(file.name);setResult(null);setProgress("");setLoading(true);try{
    validatePeriod();
    setProgress("Lecture et contrôle de l'extraction…");
    const parsed=await parseFile(file);const rows:OpsRow[]=[];
    parsed.rows.forEach((r,i)=>{const wo=text(pick(r,["no_or","work_order","ordre_reparation","or","dossier"]),64);const sold=hoursValue(pick(r,["temps_factures","temps_facture","heures_facturees","labor_hours","temps_pointe"]));if(!wo||sold===null)return;const ident=parseIdentity(pick(r,["mecanicien","mechanic_name","collaborateur","nom_prenom"]));const mechanic=ident.raw||"NON AFFECTE";const teamLabel=pick(r,["equipe","team"]);const section=pick(r,["section","section_intervention"]);const [sectorKey,sectorLabel,workcenterKey]=activityFrom(section,ident.service,teamLabel);rows.push({row_index:i+1,data_date:periodStart,payload:{work_date:periodStart,invoice_date:null,invoice_number:null,work_order:wo,mechanic_name:mechanic,time_code:text(pick(r,["section_intervention_code","section_intervention_code_section","time_code"]),80),time_description:text(section),labor_hours:sold,sector_key:sectorKey,sector_label:sectorLabel,workcenter_key:workcenterKey,team_code:normalizeTeam(teamLabel)??ident.team,matricule:ident.matricule,intervention:text(section),metadata:{atelier:text(pick(r,["atelier"]),120),original_team:text(teamLabel,120),section:text(section,160),period_start:periodStart,period_end:cutoff,period_basis:"user_confirmed_cutoff",original_file_sha256:parsed.fileHash}}});});
    if(!rows.length)throw new Error(`Aucune ligne reconnue. Format attendu : No OR + Mécanicien + Temps Facturés. Colonnes : ${parsed.headers.join(", ")}.`);
    const importHash=await hashBytes(`${parsed.fileHash}:${periodStart}:${cutoff}:productivity-period-v1`);
    const startResponse=await fetch("/api/data-import/ops-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"start",source:"billed_time",filename:file.name,sha256:importHash,byteSize:parsed.byteSize,minDate:periodStart,maxDate:cutoff,totalRows:rows.length,headers:parsed.headers})});
    const start=await readPayload<BatchStart>(startResponse,"Initialisation illisible");if(!startResponse.ok)throw new Error(start.error||`Initialisation refusée (${startResponse.status})`);if(start.duplicate){setResult(start);return;}if(!start.ready||!start.batchId)throw new Error("Lot d'import non créé.");
    for(let offset=0;offset<rows.length;offset+=1200){const chunk=rows.slice(offset,offset+1200);const response=await fetch("/api/data-import/ops-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"chunk",batchId:start.batchId,rows:chunk})});const x=await readPayload<{error?:string}>(response,"Bloc illisible");if(!response.ok)throw new Error(x.error||`Bloc refusé (${response.status})`);setProgress(`Chargement ${Math.round(Math.min(offset+chunk.length,rows.length)/rows.length*70)} %`);}
    let final:ImportResult={};for(let step=0;step<150;step++){const response=await fetch("/api/data-import/ops-batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"commit",batchId:start.batchId,limit:3000})});const x=await readPayload<ImportResult>(response,"Consolidation illisible");if(!response.ok)throw new Error(x.error||`Consolidation refusée (${response.status})`);final=x;const committed=Number(x.committedRows??0);setProgress(`Consolidation ${Math.min(99,70+Math.round(committed/rows.length*30))} %`);if(x.imported)break;}if(!final.imported)throw new Error("Consolidation incomplète : le lot reste disponible pour diagnostic.");setResult({...final,dateRange:{min:periodStart,max:cutoff}});
  }catch(error){setResult({error:error instanceof Error?error.message:"Import impossible."});}finally{setLoading(false);setProgress("");if(ref.current)ref.current.value="";}}

  return <section className={styles.strictProductivity}>
    <div className={styles.strictHead}><div><span>2 · PRODUCTIVITÉ SÉCURISÉE</span><h3>Temps pointé facturé</h3><p>La productivité n'est calculée que si les heures vendues et les heures achetées couvrent exactement la même période.</p></div><strong>MÊME PÉRIODE OBLIGATOIRE</strong></div>
    <div className={styles.periodInputs}><label>Mois<input type="month" value={month} max={parisMonth()} onChange={e=>changeMonth(e.target.value)}/></label><label>Début de période<input type="date" value={periodStart} disabled/></label><label>Arrêté au<input type="date" value={cutoff} min={periodStart} max={cutoffFor(month)} onChange={e=>{setCutoff(e.target.value);setResult(null);}}/></label></div>
    <div className={`${styles.dropZone} ${drag?styles.dropZoneActive:""} ${result?.error?styles.dropZoneError:result?.imported||result?.duplicate?styles.dropZoneSuccess:""}`} onDragEnter={e=>{e.preventDefault();setDrag(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDrag(false)} onDrop={(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDrag(false);void upload(e.dataTransfer.files?.[0])}} onClick={()=>ref.current?.click()} role="button" tabIndex={0}>
      <input ref={ref} className={styles.fileInput} type="file" accept=".csv,.xlsx,.xls" onChange={e=>void upload(e.target.files?.[0])}/><b>{loading?"Analyse et intégration…":"Glisse le fichier Temps pointé facturé ici"}</b><span>{loading?(progress||fileName):`Période certifiée : ${compactDate(periodStart)} → ${compactDate(cutoff)}`}</span><small>CSV · XLSX · XLS · 25 Mo max</small>
    </div>
    <p className={styles.uploadHint}>Export CRVO : No OR, Atelier, Mécanicien, Équipe, Section, Temps Facturés. Le fichier doit être un cumul depuis le 1er du mois jusqu'à la date d'arrêté choisie.</p>
    {result?.imported&&<div className={styles.importOk}><strong>IMPORTÉ · PÉRIODE CERTIFIÉE</strong><span>{result.rows??0} lignes · {compactDate(periodStart)} → {compactDate(cutoff)}</span></div>}
    {result?.duplicate&&<div className={styles.importDuplicate}><strong>DÉJÀ INTÉGRÉ POUR CETTE PÉRIODE</strong><span>{result.filename||fileName} · {compactDate(periodStart)} → {compactDate(cutoff)}</span></div>}
    {result?.error&&<div className={styles.importError}><strong>À CORRIGER</strong><span>{result.error}</span></div>}
  </section>;
}
