create table if not exists public.kpi_capacity_simulator_settings (
  site_code text primary key,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.kpi_capacity_simulator_history (
  id bigint generated by default as identity primary key,
  site_code text not null,
  settings jsonb not null,
  saved_at timestamptz not null default now(),
  saved_by text
);

create index if not exists kpi_capacity_simulator_history_site_saved_idx
  on public.kpi_capacity_simulator_history(site_code, saved_at desc);

alter table public.kpi_capacity_simulator_settings enable row level security;
alter table public.kpi_capacity_simulator_history enable row level security;

comment on table public.kpi_capacity_simulator_settings is 'Parametrage courant du simulateur capacitaire KPI CRVO, accessible uniquement cote serveur avec la cle service.';
comment on table public.kpi_capacity_simulator_history is 'Historique auditable des sauvegardes du simulateur capacitaire KPI CRVO.';
