create or replace function public.kpi_training_dashboard(p_session_hash text)
returns jsonb language plpgsql stable security definer set search_path='public' as $$
declare ctx record; result jsonb;begin
  select * into ctx from public.kpi_training_access_context(p_session_hash);
  if ctx.user_id is null then raise exception 'training_forbidden' using errcode='42501'; end if;
  select jsonb_build_object(
    'access',jsonb_build_object('userId',ctx.user_id,'displayName',ctx.display_name,'profile',ctx.access_profile,'canEdit',ctx.can_edit,'canAdmin',ctx.can_admin,'canFinance',public.kpi_training_is_finance_user(ctx.user_id),'canDecide',public.kpi_training_is_finance_user(ctx.user_id)),
    'people',coalesce((select jsonb_agg(jsonb_build_object('employeeKey',p.employee_key,'employeeName',p.employee_name,'matricule',p.matricule,'team',p.team_code,'service',p.service) order by p.team_code nulls last,p.service,p.employee_name) from public.kpi_worktime_population_for_date(current_date) p where p.sector_key='carrosserie'),'[]'::jsonb),
    'tracks',coalesce((select jsonb_agg(jsonb_build_object('key',t.key,'label',t.label,'levelLabel',t.level_label,'description',t.description,'sourceLabel',t.source_label,'sortOrder',t.sort_order,'blocks',coalesce((select jsonb_agg(jsonb_build_object('key',b.key,'code',b.code,'label',b.label,'description',b.description,'sortOrder',b.sort_order,'skills',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'skillKey',s.skill_key,'label',s.label,'indicator',s.indicator,'sourceRef',s.source_ref,'sortOrder',s.sort_order) order by s.sort_order,s.label) from public.kpi_training_skills s where s.block_key=b.key and s.active),'[]'::jsonb)) order by b.sort_order,b.code) from public.kpi_training_blocks b where b.track_key=t.key),'[]'::jsonb)) order by t.sort_order,t.label) from public.kpi_training_tracks t where t.active),'[]'::jsonb),
    'trainers',coalesce((select jsonb_agg(jsonb_build_object('id',tr.id,'displayName',tr.display_name,'specialty',tr.specialty,'active',tr.active,'userId',tr.user_id,'notes',tr.notes) order by tr.active desc,tr.display_name) from public.kpi_training_trainers tr),'[]'::jsonb),
    'plans',coalesce((select jsonb_agg(jsonb_build_object('id',pl.id,'employeeKey',pl.employee_key,'employeeName',pl.employee_name,'matricule',pl.matricule,'team',pl.team_code,'service',pl.service,'trackKey',pl.track_key,'status',pl.status,'priority',pl.priority,'targetDate',pl.target_date,'objective',pl.objective,'trainerId',pl.trainer_id,'trainerName',tr.display_name,'createdByName',pl.created_by_name,'createdAt',pl.created_at,'updatedAt',pl.updated_at) order by case pl.priority when 'critical' then 1 when 'high' then 2 when 'normal' then 3 else 4 end,pl.target_date nulls last,pl.updated_at desc) from public.kpi_training_plans pl left join public.kpi_training_trainers tr on tr.id=pl.trainer_id where pl.status<>'cancelled'),'[]'::jsonb),
    'evaluations',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'employeeKey',e.employee_key,'employeeName',e.employee_name,'trackKey',e.track_key,'evaluationDate',e.evaluation_date,'kind',e.kind,'sessionId',e.session_id,'overallScore',e.overall_score,'overallPct',e.overall_pct,'pilotageLevel',e.pilotage_level,'summary',e.summary,'evaluatorName',e.evaluator_name,'createdAt',e.created_at) order by e.evaluation_date desc,e.created_at desc) from public.kpi_training_evaluations e),'[]'::jsonb),
    'legacySnapshots',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'employeeKey',l.employee_key,'employeeName',l.employee_name,'teamLabel',l.team_label,'trackKey',l.track_key,'blockScores',l.block_scores,'overallPoints',l.overall_points,'overallPct',l.overall_pct,'legacyStatus',l.legacy_status,'comments',l.comments,'sourceSheet',l.source_sheet,'sourceEvaluationDate',l.source_evaluation_date,'importedAt',l.imported_at) order by l.employee_name,l.track_key) from public.kpi_training_legacy_snapshots l),'[]'::jsonb),
    'sessions',coalesce((select jsonb_agg(jsonb_build_object('id',se.id,'title',se.title,'trackKey',se.track_key,'trainerId',se.trainer_id,'trainerName',tr.display_name,'startAt',se.start_at,'endAt',se.end_at,'status',se.status,'workflowStatus',se.workflow_status,'workflowDecisionName',se.workflow_decision_name,'workflowDecisionComment',se.workflow_decision_comment,'workflowDecidedAt',se.workflow_decided_at,'location',se.location,'objective',se.objective,'focusSkillKeys',se.focus_skill_keys,'notes',se.notes,'fundingStatus',case when public.kpi_training_is_finance_user(ctx.user_id) then se.funding_status else null end,'participants',coalesce((select jsonb_agg(jsonb_build_object('employeeKey',a.employee_key,'employeeName',a.employee_name,'status',a.status,'preEvaluationId',a.pre_evaluation_id,'postEvaluationId',a.post_evaluation_id,'attendanceStatus',att.attendance_status,'learnerSignedAt',att.learner_signed_at,'trainerSignedAt',att.trainer_signed_at) order by a.employee_name) from public.kpi_training_session_attendees a left join public.kpi_training_attendance att on att.session_id=a.session_id and att.employee_key=a.employee_key where a.session_id=se.id),'[]'::jsonb)) order by se.start_at desc) from public.kpi_training_sessions se left join public.kpi_training_trainers tr on tr.id=se.trainer_id where se.start_at>=now()-interval '12 months'),'[]'::jsonb),
    'requests',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'employeeKey',r.employee_key,'employeeName',r.employee_name,'matricule',r.matricule,'team',r.team_code,'service',r.service,'trackKey',r.requested_track_key,'difficulties',r.difficulties,'acquiredSkills',r.acquired_skills,'requestedSkills',r.requested_skills,'operationalContext',r.operational_context,'urgency',r.urgency,'status',r.status,'requestedByName',r.requested_by_name,'requestedByPosition',r.requested_by_position,'createdAt',r.created_at,'decisionComment',r.decision_comment,'decidedByName',r.decided_by_name,'decidedAt',r.decided_at,'linkedSessionId',r.linked_session_id) order by case r.status when 'pending' then 0 else 1 end,r.created_at desc) from public.kpi_training_requests r),'[]'::jsonb),
    'observations',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'employeeKey',o.employee_key,'employeeName',o.employee_name,'category',o.category,'content',o.content,'sessionId',o.session_id,'trackKey',o.track_key,'createdByName',o.created_by_name,'createdAt',o.created_at) order by o.created_at desc) from (select * from public.kpi_training_observations order by created_at desc limit 250) o),'[]'::jsonb)
  ) into result; return result;
end;$$;

create or replace function public.kpi_training_request_context(p_session_hash text)
returns jsonb language plpgsql stable security definer set search_path='public' as $$
declare uid uuid;uname text;scope record;begin
  select u.id,u.display_name into uid,uname from public.crvo_auth_sessions s join public.crvo_auth_users u on u.id=s.user_id where s.token_hash=p_session_hash and s.revoked_at is null and s.expires_at>now() and u.is_active limit 1;
  if uid is null then raise exception 'training_request_forbidden' using errcode='42501'; end if;
  select * into scope from public.kpi_worktime_scope_for_user(uid,'CRVO');
  if coalesce(scope.level_code,'') not in ('supervisor','industrial_manager') and not exists(select 1 from public.crvo_auth_users where id=uid and (role='admin' or access_profile in ('service_manager','hr'))) then raise exception 'training_request_forbidden' using errcode='42501'; end if;
  return jsonb_build_object(
    'access',jsonb_build_object('displayName',uname,'level',scope.level_code,'positionKey',scope.position_key,'teams',scope.team_codes),
    'people',coalesce((select jsonb_agg(jsonb_build_object('employeeKey',p.employee_key,'employeeName',p.employee_name,'matricule',p.matricule,'team',p.team_code,'service',p.service) order by p.team_code,p.employee_name) from public.kpi_worktime_population_for_date(current_date) p where p.sector_key='carrosserie' and (scope.all_access or p.team_code=any(scope.team_codes))),'[]'::jsonb),
    'tracks',coalesce((select jsonb_agg(jsonb_build_object('key',t.key,'label',t.label,'levelLabel',t.level_label) order by t.sort_order,t.label) from public.kpi_training_tracks t where t.active),'[]'::jsonb),
    'requests',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'employeeKey',r.employee_key,'employeeName',r.employee_name,'team',r.team_code,'trackKey',r.requested_track_key,'difficulties',r.difficulties,'acquiredSkills',r.acquired_skills,'requestedSkills',r.requested_skills,'operationalContext',r.operational_context,'urgency',r.urgency,'status',r.status,'requestedByName',r.requested_by_name,'createdAt',r.created_at,'decisionComment',r.decision_comment,'decidedByName',r.decided_by_name,'decidedAt',r.decided_at) order by r.created_at desc) from public.kpi_training_requests r where r.requested_by=uid or scope.all_access or r.team_code=any(scope.team_codes)),'[]'::jsonb)
  );
end;$$;

revoke all on function public.kpi_training_request_context(text) from public;
grant execute on function public.kpi_training_request_context(text) to anon,authenticated,service_role;
notify pgrst,'reload schema';
