create table if not exists public.kpi_transphere_transport_settings (
  id smallint primary key default 1 check (id = 1),
  cost_weight numeric(5,2) not null default 100 check (cost_weight between 0 and 100),
  lead_time_weight numeric(5,2) not null default 0 check (lead_time_weight between 0 and 100),
  updated_at timestamptz not null default now(),
  updated_by uuid
);

insert into public.kpi_transphere_transport_settings(id,cost_weight,lead_time_weight)
values (1,100,0)
on conflict (id) do nothing;

create table if not exists public.kpi_transphere_transport_tariffs (
  id bigint generated by default as identity primary key,
  crvo text not null check (crvo in ('LENS','INGRANDES','LYON','ISTRES')),
  pdv_name text not null,
  address text,
  postal_code text,
  country text not null default 'FR',
  carrier text not null,
  carrier_type text not null default 'PARTNER' check (carrier_type in ('INTERNAL','PARTNER')),
  direction text not null default 'BOTH' check (direction in ('BOTH','PDV_TO_CRVO','CRVO_TO_PDV')),
  scenario text not null default 'STANDARD' check (scenario in ('STANDARD','OPTIMIZED','EMPTY')),
  cost_per_vehicle numeric(10,2) not null check (cost_per_vehicle >= 0),
  lead_time_days numeric(6,2) check (lead_time_days is null or lead_time_days >= 0),
  source_label text,
  source_kind text not null default 'MANUAL' check (source_kind in ('CONTRACT','EMAIL','MANUAL')),
  valid_from date,
  valid_to date,
  active boolean not null default true,
  source_key text unique,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create index if not exists kpi_transphere_transport_tariffs_lookup_idx
  on public.kpi_transphere_transport_tariffs(crvo,pdv_name,postal_code,carrier,active);

alter table public.kpi_transphere_transport_settings enable row level security;
alter table public.kpi_transphere_transport_tariffs enable row level security;
revoke all on table public.kpi_transphere_transport_settings from anon,authenticated;
revoke all on table public.kpi_transphere_transport_tariffs from anon,authenticated;
grant select,insert,update,delete on public.kpi_transphere_transport_settings to service_role;
grant select,insert,update,delete on public.kpi_transphere_transport_tariffs to service_role;

create or replace function public.kpi_transphere_transport_matrix_admin(p_session_hash text)
returns jsonb
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_can_edit boolean := false;
  v_settings jsonb;
  v_tariffs jsonb;
begin
  if not public.crvo_auth_has_page_permission(p_session_hash,'transphere') then
    raise exception 'Accès Transphère requis.' using errcode='42501';
  end if;

  select exists(
    select 1
    from public.crvo_auth_sessions s
    join public.crvo_auth_users u on u.id=s.user_id
    where s.token_hash=p_session_hash
      and s.revoked_at is null
      and s.expires_at>now()
      and u.is_active=true
      and (u.role='admin' or coalesce(u.access_profile,'')='transphere_manager')
  ) into v_can_edit;

  select jsonb_build_object(
    'costWeight',cost_weight,
    'leadTimeWeight',lead_time_weight,
    'updatedAt',updated_at
  ) into v_settings
  from public.kpi_transphere_transport_settings
  where id=1;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id,'crvo',crvo,'pdvName',pdv_name,'address',address,'postalCode',postal_code,'country',country,
    'carrier',carrier,'carrierType',carrier_type,'direction',direction,'scenario',scenario,
    'costPerVehicle',cost_per_vehicle,'leadTimeDays',lead_time_days,'sourceLabel',source_label,
    'sourceKind',source_kind,'validFrom',valid_from,'validTo',valid_to,'active',active,'updatedAt',updated_at
  ) order by crvo,pdv_name,carrier,scenario,direction),'[]'::jsonb)
  into v_tariffs
  from public.kpi_transphere_transport_tariffs;

  return jsonb_build_object(
    'connected',true,'canEdit',v_can_edit,
    'settings',coalesce(v_settings,jsonb_build_object('costWeight',100,'leadTimeWeight',0)),
    'tariffs',v_tariffs
  );
end
$$;

create or replace function public.kpi_transphere_transport_tariff_upsert_admin(
  p_session_hash text,
  p_id bigint default null,
  p_crvo text default null,
  p_pdv_name text default null,
  p_address text default null,
  p_postal_code text default null,
  p_country text default 'FR',
  p_carrier text default null,
  p_carrier_type text default 'PARTNER',
  p_direction text default 'BOTH',
  p_scenario text default 'STANDARD',
  p_cost_per_vehicle numeric default null,
  p_lead_time_days numeric default null,
  p_source_label text default null,
  p_valid_from date default null,
  p_valid_to date default null,
  p_active boolean default true
)
returns bigint
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_user_id uuid;
  v_id bigint;
begin
  select u.id into v_user_id
  from public.crvo_auth_sessions s
  join public.crvo_auth_users u on u.id=s.user_id
  where s.token_hash=p_session_hash
    and s.revoked_at is null
    and s.expires_at>now()
    and u.is_active=true
    and (u.role='admin' or coalesce(u.access_profile,'')='transphere_manager')
  limit 1;

  if v_user_id is null then raise exception 'Modification des tarifs Transphère non autorisée.' using errcode='42501'; end if;
  if p_crvo not in ('LENS','INGRANDES','LYON','ISTRES') then raise exception 'CRVO invalide.'; end if;
  if nullif(trim(p_pdv_name),'') is null then raise exception 'PDV requis.'; end if;
  if nullif(trim(p_carrier),'') is null then raise exception 'Société requise.'; end if;
  if p_carrier_type not in ('INTERNAL','PARTNER') then raise exception 'Type société invalide.'; end if;
  if p_direction not in ('BOTH','PDV_TO_CRVO','CRVO_TO_PDV') then raise exception 'Sens invalide.'; end if;
  if p_scenario not in ('STANDARD','OPTIMIZED','EMPTY') then raise exception 'Scénario invalide.'; end if;
  if p_cost_per_vehicle is null or p_cost_per_vehicle < 0 then raise exception 'Coût au véhicule invalide.'; end if;
  if p_lead_time_days is not null and p_lead_time_days < 0 then raise exception 'Lead-time invalide.'; end if;

  if p_id is null then
    insert into public.kpi_transphere_transport_tariffs(
      crvo,pdv_name,address,postal_code,country,carrier,carrier_type,direction,scenario,cost_per_vehicle,
      lead_time_days,source_label,source_kind,valid_from,valid_to,active,updated_by
    ) values (
      p_crvo,trim(p_pdv_name),nullif(trim(coalesce(p_address,'')),''),nullif(trim(coalesce(p_postal_code,'')),''),
      upper(coalesce(nullif(trim(p_country),''),'FR')),trim(p_carrier),p_carrier_type,p_direction,p_scenario,
      p_cost_per_vehicle,p_lead_time_days,coalesce(nullif(trim(coalesce(p_source_label,'')),''),'Saisie manuelle Transphère'),
      'MANUAL',p_valid_from,p_valid_to,p_active,v_user_id
    ) returning id into v_id;
  else
    update public.kpi_transphere_transport_tariffs set
      crvo=p_crvo,pdv_name=trim(p_pdv_name),address=nullif(trim(coalesce(p_address,'')),''),
      postal_code=nullif(trim(coalesce(p_postal_code,'')),''),country=upper(coalesce(nullif(trim(p_country),''),'FR')),
      carrier=trim(p_carrier),carrier_type=p_carrier_type,direction=p_direction,scenario=p_scenario,
      cost_per_vehicle=p_cost_per_vehicle,lead_time_days=p_lead_time_days,
      source_label=coalesce(nullif(trim(coalesce(p_source_label,'')),''),source_label),
      valid_from=p_valid_from,valid_to=p_valid_to,active=p_active,updated_at=now(),updated_by=v_user_id
    where id=p_id returning id into v_id;
    if v_id is null then raise exception 'Tarif introuvable.'; end if;
  end if;
  return v_id;
end
$$;

create or replace function public.kpi_transphere_transport_tariff_delete_admin(p_session_hash text,p_id bigint)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
declare v_allowed boolean;
begin
  select exists(
    select 1 from public.crvo_auth_sessions s join public.crvo_auth_users u on u.id=s.user_id
    where s.token_hash=p_session_hash and s.revoked_at is null and s.expires_at>now() and u.is_active=true
      and (u.role='admin' or coalesce(u.access_profile,'')='transphere_manager')
  ) into v_allowed;
  if not v_allowed then raise exception 'Suppression non autorisée.' using errcode='42501'; end if;
  delete from public.kpi_transphere_transport_tariffs where id=p_id;
  return found;
end
$$;

create or replace function public.kpi_transphere_transport_settings_update_admin(p_session_hash text,p_cost_weight numeric,p_lead_time_weight numeric)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
declare v_user_id uuid;
begin
  select u.id into v_user_id
  from public.crvo_auth_sessions s join public.crvo_auth_users u on u.id=s.user_id
  where s.token_hash=p_session_hash and s.revoked_at is null and s.expires_at>now() and u.is_active=true
    and (u.role='admin' or coalesce(u.access_profile,'')='transphere_manager') limit 1;
  if v_user_id is null then raise exception 'Paramétrage non autorisé.' using errcode='42501'; end if;
  if p_cost_weight is null or p_lead_time_weight is null or p_cost_weight<0 or p_lead_time_weight<0
     or p_cost_weight>100 or p_lead_time_weight>100 or abs((p_cost_weight+p_lead_time_weight)-100)>0.01 then
    raise exception 'La somme des pondérations doit être égale à 100.';
  end if;
  update public.kpi_transphere_transport_settings
    set cost_weight=p_cost_weight,lead_time_weight=p_lead_time_weight,updated_at=now(),updated_by=v_user_id
    where id=1;
  return true;
end
$$;

revoke all on function public.kpi_transphere_transport_matrix_admin(text) from public;
revoke all on function public.kpi_transphere_transport_tariff_upsert_admin(text,bigint,text,text,text,text,text,text,text,text,text,numeric,numeric,text,date,date,boolean) from public;
revoke all on function public.kpi_transphere_transport_tariff_delete_admin(text,bigint) from public;
revoke all on function public.kpi_transphere_transport_settings_update_admin(text,numeric,numeric) from public;
grant execute on function public.kpi_transphere_transport_matrix_admin(text) to anon,authenticated;
grant execute on function public.kpi_transphere_transport_tariff_upsert_admin(text,bigint,text,text,text,text,text,text,text,text,text,numeric,numeric,text,date,date,boolean) to anon,authenticated;
grant execute on function public.kpi_transphere_transport_tariff_delete_admin(text,bigint) to anon,authenticated;
grant execute on function public.kpi_transphere_transport_settings_update_admin(text,numeric,numeric) to anon,authenticated;

-- Les grilles contractuelles sont des données métier administrables et sont chargées dans la table
-- kpi_transphere_transport_tariffs. Elles ne sont pas figées dans la migration afin de permettre leur
-- modification individuelle depuis l'onglet Paramètres sans réécrire le schéma.
