create table if not exists public.kpi_staff_operational_overrides (
  employee_key text primary key references public.kpi_staff_registry(employee_key) on delete cascade,
  entry_date_override date,
  primary_job_key_override text references public.kpi_skill_catalog(skill_key),
  team_code_override text,
  neutralized boolean not null default false,
  neutralized_reason text,
  updated_by uuid references public.crvo_auth_users(id),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint kpi_staff_operational_team_chk check (team_code_override is null or team_code_override in ('A','B','C'))
);

create table if not exists public.kpi_staff_operational_events (
  id bigint generated by default as identity primary key,
  employee_key text not null references public.kpi_staff_registry(employee_key) on delete cascade,
  event_type text not null,
  actor_id uuid references public.crvo_auth_users(id),
  created_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);
create index if not exists kpi_staff_operational_events_employee_idx on public.kpi_staff_operational_events(employee_key,created_at desc);
create index if not exists kpi_staff_operational_overrides_neutralized_idx on public.kpi_staff_operational_overrides(neutralized) where neutralized;

alter table public.kpi_staff_operational_overrides enable row level security;
alter table public.kpi_staff_operational_events enable row level security;
revoke all on public.kpi_staff_operational_overrides from public,anon,authenticated;
revoke all on public.kpi_staff_operational_events from public,anon,authenticated;

drop view if exists public.kpi_staff_effective;
create view public.kpi_staff_effective as
select
  r.employee_key,
  r.matricule,
  r.first_name,
  r.last_name,
  r.full_name,
  r.name_key,
  r.service,
  coalesce(o.team_code_override,r.team_code) team_code,
  r.job_title,
  coalesce(o.entry_date_override,r.entry_date) entry_date,
  r.exit_date,
  r.employment_status,
  r.active,
  r.source_filename,
  r.source_sha256,
  r.source_imported_at,
  r.metadata,
  case
    when o.primary_job_key_override='fixline' then 'fixline'
    when sc_override.skill_key is not null and sc_override.productive then 'productif'
    else r.primary_population
  end primary_population,
  coalesce(o.primary_job_key_override,r.primary_job_key) primary_job_key,
  coalesce(sc_override.sector_key,r.primary_sector_key) primary_sector_key,
  coalesce(sc_override.sector_label,r.primary_sector_label) primary_sector_label,
  case when o.primary_job_key_override is not null then o.primary_job_key_override else r.primary_scope end primary_scope,
  coalesce(sc_override.label,sc_base.label,r.job_title) primary_job_label,
  coalesce(o.neutralized,false) neutralized,
  o.neutralized_reason,
  o.updated_at operational_updated_at,
  (o.employee_key is not null) operational_override
from public.kpi_staff_registry r
left join public.kpi_staff_operational_overrides o on o.employee_key=r.employee_key
left join public.kpi_skill_catalog sc_override on sc_override.skill_key=o.primary_job_key_override and sc_override.active
left join public.kpi_skill_catalog sc_base on sc_base.skill_key=r.primary_job_key;
revoke all on public.kpi_staff_effective from public,anon,authenticated;

create or replace function public.kpi_staff_alias_neutralized(p_name_key text,p_matricule text default null)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1
    from public.kpi_staff_effective r
    where r.active
      and r.neutralized
      and (
        r.name_key=p_name_key
        or (
          nullif(btrim(p_matricule),'') is not null
          and nullif(btrim(r.matricule),'') is not null
          and ltrim(r.matricule,'0')=ltrim(p_matricule,'0')
        )
      )
  );
$$;
revoke all on function public.kpi_staff_alias_neutralized(text,text) from public;
grant execute on function public.kpi_staff_alias_neutralized(text,text) to anon,authenticated,service_role;

create or replace function public.kpi_rh_update_staff_operational(
  p_session_hash text,
  p_employee_key text,
  p_entry_date date default null,
  p_primary_job_key text default null,
  p_team_code text default null,
  p_neutralized boolean default false,
  p_neutralized_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  a record;
  v_actor uuid;
  r public.kpi_staff_registry%rowtype;
  s public.kpi_skill_catalog%rowtype;
  v_team text:=upper(nullif(btrim(p_team_code),''));
  v_before jsonb;
  v_after jsonb;
begin
  select * into a from public.kpi_data_rh_access(p_session_hash) limit 1;
  if a is null then raise exception 'Droit Data RH requis.' using errcode='42501'; end if;
  select id into v_actor from public.crvo_auth_users where username=a.username limit 1;
  select * into r from public.kpi_staff_registry where employee_key=p_employee_key;
  if r.employee_key is null then raise exception 'Collaborateur introuvable.'; end if;
  if v_team is not null and v_team not in ('A','B','C') then raise exception 'Équipe invalide.'; end if;
  if p_primary_job_key is not null then
    select * into s from public.kpi_skill_catalog where skill_key=p_primary_job_key and active;
    if s.skill_key is null then raise exception 'Métier principal inconnu.'; end if;
  end if;
  if p_entry_date is not null and r.exit_date is not null and p_entry_date>r.exit_date then raise exception 'La date d’embauche ne peut pas être postérieure à la date de sortie.'; end if;

  select to_jsonb(e) into v_before from public.kpi_staff_effective e where e.employee_key=r.employee_key;

  insert into public.kpi_staff_operational_overrides(employee_key,entry_date_override,primary_job_key_override,team_code_override,neutralized,neutralized_reason,updated_by,updated_at,metadata)
  values(r.employee_key,p_entry_date,p_primary_job_key,v_team,coalesce(p_neutralized,false),case when p_neutralized then nullif(btrim(p_neutralized_reason),'') else null end,v_actor,now(),jsonb_build_object('updatedBy',a.display_name,'source','rh_operational_module'))
  on conflict(employee_key) do update set
    entry_date_override=excluded.entry_date_override,
    primary_job_key_override=excluded.primary_job_key_override,
    team_code_override=excluded.team_code_override,
    neutralized=excluded.neutralized,
    neutralized_reason=excluded.neutralized_reason,
    updated_by=excluded.updated_by,
    updated_at=now(),
    metadata=kpi_staff_operational_overrides.metadata||excluded.metadata;

  if p_primary_job_key is not null and s.productive and v_team is not null then
    insert into public.kpi_productivity_team_assignment(name_key,mechanic_name,team_code,scope,role_label,active,updated_at)
    values(r.name_key,r.full_name,v_team,p_primary_job_key,s.label,true,now())
    on conflict(name_key) do update set mechanic_name=excluded.mechanic_name,team_code=excluded.team_code,scope=excluded.scope,role_label=excluded.role_label,active=true,updated_at=now();
  elsif v_team is null then
    update public.kpi_productivity_team_assignment set active=false,updated_at=now() where name_key=r.name_key;
  end if;

  select to_jsonb(e) into v_after from public.kpi_staff_effective e where e.employee_key=r.employee_key;
  insert into public.kpi_staff_operational_events(employee_key,event_type,actor_id,payload)
  values(r.employee_key,'operational_update',v_actor,jsonb_build_object('before',v_before,'after',v_after,'actor',a.display_name));

  return jsonb_build_object('ok',true,'staff',v_after);
end $$;
revoke all on function public.kpi_rh_update_staff_operational(text,text,date,text,text,boolean,text) from public;
grant execute on function public.kpi_rh_update_staff_operational(text,text,date,text,text,boolean,text) to anon,authenticated,service_role;

create or replace function public.kpi_rh_staff_directory(p_session_hash text, p_month date default null)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  a record;
  v_start date:=date_trunc('month',coalesce(p_month,current_date))::date;
  v_end date:=(date_trunc('month',coalesce(p_month,current_date))+interval '1 month')::date;
  v_presence_through date;
  v_billed_through date;
  v_payroll_at timestamptz;
  v_result jsonb;
begin
  select * into a from public.kpi_data_rh_access(p_session_hash) limit 1;
  if a is null then raise exception 'Droit Data RH requis.' using errcode='42501'; end if;

  select max(work_date) into v_presence_through from public.kpi_sql_presence_facts where source_name='Direct Data RH';
  select max(coalesce(work_date,invoice_date)) into v_billed_through from public.kpi_billed_time_facts where source_name='Direct Temps pointé facturé';
  select max(source_imported_at) into v_payroll_at from public.kpi_staff_registry where metadata->>'source'='payroll_import';

  with staff_base as (
    select * from public.kpi_staff_effective
  ), presence as (
    select r.employee_key,sum(p.time_value) bought
    from staff_base r
    join public.kpi_sql_presence_facts p on public.kpi_normalize_person_name(public.kpi_rh_base_name(p.mechanic_name))=r.name_key
    join public.kpi_rh_presence_code_map m on m.time_code=p.time_code and m.counts_as_presence and not m.excluded
    where p.work_date>=v_start and p.work_date<v_end
    group by r.employee_key
  ), billed_resolved as (
    select b.labor_hours,b.work_order,coalesce(b.work_date,b.invoice_date) work_date,r.employee_key
    from public.kpi_billed_time_facts b
    join lateral (
      select rr.employee_key
      from staff_base rr
      where rr.name_key=public.kpi_normalize_person_name(public.kpi_rh_base_name(b.mechanic_name))
         or (nullif(btrim(b.matricule),'') is not null and rr.matricule=btrim(b.matricule) and (select count(*) from staff_base rx where rx.matricule=btrim(b.matricule))=1)
      order by (rr.name_key=public.kpi_normalize_person_name(public.kpi_rh_base_name(b.mechanic_name))) desc,rr.active desc,rr.source_imported_at desc
      limit 1
    ) r on true
    where b.source_name='Direct Temps pointé facturé' and coalesce(b.work_date,b.invoice_date)>=v_start and coalesce(b.work_date,b.invoice_date)<v_end
  ), billed as (
    select employee_key,sum(labor_hours) sold,count(distinct work_order) jobs from billed_resolved group by employee_key
  ), skill_bought_90 as (
    select r.employee_key,sc.skill_key,sum(p.time_value)::numeric bought_hours_90d
    from staff_base r
    join public.kpi_sql_presence_facts p on public.kpi_normalize_person_name(public.kpi_rh_base_name(p.mechanic_name))=r.name_key
    join public.kpi_rh_presence_code_map m on m.time_code=p.time_code and m.counts_as_presence and not m.excluded
    join public.kpi_skill_catalog sc on sc.active and sc.productive and sc.sector_key=m.sector_key
      and (coalesce(cardinality(sc.workcenter_keys),0)=0 or m.workcenter_key=any(sc.workcenter_keys))
    where p.work_date between current_date-89 and current_date
    group by r.employee_key,sc.skill_key
  ), rows as (
    select r.*,
           p.bought,
           b.sold,
           b.jobs,
           case when r.primary_population='productif' and p.bought>0 and b.sold is not null then round(b.sold/p.bought*100,1) else null end productivity,
           case when r.primary_population='productif' then 'individual' when r.primary_population='fixline' then 'team_only' else 'not_applicable' end productivity_mode,
           coalesce((select jsonb_agg(jsonb_build_object(
             'skillKey',c.skill_key,'label',sc.label,'sectorKey',sc.sector_key,'sectorLabel',sc.sector_label,'status',c.status,
             'validatedAt',c.validated_at,'validFrom',c.valid_from,'validUntil',c.valid_until,'note',c.note,
             'lastUsedDate',u.last_used_date,'hours90d',coalesce(u.hours_90d,0),'jobs90d',coalesce(u.jobs_90d,0),'days90d',coalesce(u.days_90d,0),
             'soldHours90d',coalesce(u.hours_90d,0),'boughtHours90d',sb.bought_hours_90d,
             'productivity90d',case when sb.bought_hours_90d>0 and u.hours_90d is not null then round(u.hours_90d/sb.bought_hours_90d*100,1) else null end
           ) order by sc.label)
           from public.kpi_staff_competencies c
           join public.kpi_skill_catalog sc on sc.skill_key=c.skill_key
           left join public.kpi_staff_skill_usage u on u.employee_key=c.employee_key and u.skill_key=c.skill_key
           left join skill_bought_90 sb on sb.employee_key=c.employee_key and sb.skill_key=c.skill_key
           where c.employee_key=r.employee_key and c.status<>'inactive'),'[]'::jsonb) competencies,
           coalesce((select jsonb_agg(jsonb_build_object(
             'skillKey',sc.skill_key,'label',sc.label,'sectorKey',sc.sector_key,'sectorLabel',sc.sector_label,
             'lastUsedDate',u.last_used_date,'hours90d',coalesce(u.hours_90d,0),'jobs90d',coalesce(u.jobs_90d,0),'days90d',coalesce(u.days_90d,0),
             'soldHours90d',coalesce(u.hours_90d,0),'boughtHours90d',sb.bought_hours_90d,
             'productivity90d',case when sb.bought_hours_90d>0 and u.hours_90d is not null then round(u.hours_90d/sb.bought_hours_90d*100,1) else null end
           ) order by u.last_used_date desc,sc.label)
           from public.kpi_staff_skill_usage u
           join public.kpi_skill_catalog sc on sc.skill_key=u.skill_key
           left join skill_bought_90 sb on sb.employee_key=u.employee_key and sb.skill_key=u.skill_key
           where u.employee_key=r.employee_key and u.skill_key is distinct from r.primary_job_key
             and not exists(select 1 from public.kpi_staff_competencies c where c.employee_key=r.employee_key and c.skill_key=u.skill_key and c.status<>'inactive')),'[]'::jsonb) observed_skills,
           (select max(u.last_used_date) from public.kpi_staff_competencies c join public.kpi_staff_skill_usage u on u.employee_key=c.employee_key and u.skill_key=c.skill_key where c.employee_key=r.employee_key and c.status='active') last_poly_use
    from staff_base r
    left join presence p on p.employee_key=r.employee_key
    left join billed b on b.employee_key=r.employee_key
  )
  select jsonb_build_object(
    'month',to_char(v_start,'YYYY-MM'),
    'coverage',jsonb_build_object('presenceThrough',v_presence_through,'billedThrough',v_billed_through,'payrollImportedAt',v_payroll_at),
    'counts',jsonb_build_object(
      'total',(select count(*) from rows),
      'active',(select count(*) from rows where active),
      'exited',(select count(*) from rows where not active),
      'neutralized',(select count(*) from rows where active and neutralized),
      'polycompetent',(select count(*) from rows where jsonb_array_length(competencies)>0),
      'observedUnconfirmed',(select count(*) from rows where jsonb_array_length(observed_skills)>0),
      'missingEntryDate',(select count(*) from rows where active and entry_date is null),
      'missingPrimaryJob',(select count(*) from rows where active and primary_job_key is null)
    ),
    'availableMonths',coalesce((select jsonb_agg(m order by m desc) from (select distinct to_char(date_trunc('month',d),'YYYY-MM') m from (select work_date d from public.kpi_sql_presence_facts where work_date is not null union all select coalesce(work_date,invoice_date) d from public.kpi_billed_time_facts where coalesce(work_date,invoice_date) is not null) z) q),'[]'::jsonb),
    'skills',coalesce((select jsonb_agg(jsonb_build_object('skillKey',skill_key,'label',label,'sectorKey',sector_key,'sectorLabel',sector_label) order by sector_label,label) from public.kpi_skill_catalog where active),'[]'::jsonb),
    'staff',coalesce((select jsonb_agg(jsonb_build_object(
      'employeeKey',employee_key,'matricule',matricule,'firstName',first_name,'lastName',last_name,'fullName',full_name,
      'service',service,'teamCode',team_code,'jobTitle',job_title,'entryDate',entry_date,'exitDate',exit_date,'employmentStatus',employment_status,'active',active,
      'primaryPopulation',primary_population,'primaryJobKey',primary_job_key,'primaryJobLabel',primary_job_label,'primarySectorKey',primary_sector_key,'primarySectorLabel',primary_sector_label,
      'boughtHours',bought,'soldHours',sold,'productivity',productivity,'productivityMode',productivity_mode,'jobs',coalesce(jobs,0),
      'neutralized',neutralized,'neutralizedReason',neutralized_reason,'operationalUpdatedAt',operational_updated_at,'operationalOverride',operational_override,
      'competencies',competencies,'observedSkills',observed_skills,'lastPolyUse',last_poly_use,'sourceFilename',source_filename,'sourceImportedAt',source_imported_at
    ) order by active desc,full_name) from rows),'[]'::jsonb)
  ) into v_result;
  return v_result;
end $$;
revoke all on function public.kpi_rh_staff_directory(text,date) from public;
grant execute on function public.kpi_rh_staff_directory(text,date) to anon,authenticated,service_role;

do $$
declare v_def text;
begin
  select pg_get_functiondef(p.oid) into v_def
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname='kpi_productivity_month_unscoped' and p.prokind='f' limit 1;
  if v_def is not null and position('kpi_staff_alias_neutralized' in v_def)=0 then
    v_def:=replace(v_def,
      'on cur.name_key=public.kpi_normalize_person_name(public.kpi_rh_base_name(p.mechanic_name))',
      'on cur.name_key=public.kpi_normalize_person_name(public.kpi_rh_base_name(p.mechanic_name)) and not public.kpi_staff_alias_neutralized(cur.name_key,cur.matricule)');
    v_def:=replace(v_def,
      'join public.kpi_staff_authoritative_alias cur on cur.name_key=b.resolved_key',
      'join public.kpi_staff_authoritative_alias cur on cur.name_key=b.resolved_key and not public.kpi_staff_alias_neutralized(cur.name_key,cur.matricule)');
    execute v_def;
  end if;
end $$;

do $$
declare v_def text;
begin
  select pg_get_functiondef(p.oid) into v_def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='kpi_capacity_roster' and p.prokind='f' limit 1;
  if v_def is not null then
    v_def:=replace(v_def,'from public.kpi_staff_registry r','from public.kpi_staff_effective r');
    if position('and not r.neutralized' in v_def)=0 then
      v_def:=replace(v_def,'where r.active=true','where r.active=true and not r.neutralized');
    end if;
    execute v_def;
  end if;

  select pg_get_functiondef(p.oid) into v_def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='kpi_capacity_simple' and p.prokind='f' limit 1;
  if v_def is not null then
    v_def:=replace(v_def,'from public.kpi_staff_registry r','from public.kpi_staff_effective r');
    if position('and not r.neutralized' in v_def)=0 then
      v_def:=replace(v_def,'where r.active=true','where r.active=true and not r.neutralized');
    end if;
    execute v_def;
  end if;
end $$;

do $$
declare v_def text;
begin
  select pg_get_functiondef(p.oid) into v_def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='kpi_polycompetence_suggestions' and p.prokind='f' limit 1;
  if v_def is not null and position('kpi_staff_effective r' in v_def)=0 then
    v_def:=replace(v_def,'join public.kpi_staff_registry r on r.employee_key=pc.employee_key and r.active','join public.kpi_staff_effective r on r.employee_key=pc.employee_key and r.active and not r.neutralized');
    execute v_def;
  end if;
end $$;