"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./pr-workspace.module.css";

type Summary={references:number;stockValueHt:number;negativeReferences?:number;cmmWindowMonths:number};
type Item={id:string;reference:string;manufacturerLabel?:string|null;description:string;family?:string|null;onHand:number;reserved:number;available:number;averageCostHt:number;stockValueHt:number;cmm:number;coverageDays?:number|null;provisionalStock?:boolean};
type Dossier={workOrder:string;registration?:string|null;vin?:string|null;client?:string|null;model?:string|null;partStatus:"to_order"|"ordered"|"backorder";orderedDays?:number|null};
type Supply={id:string;reference:string;description:string;manufacturerLabel?:string|null;workOrder:string;quantity:number;status:"to_order"|"ordered"|"backorder"|"received"|"cancelled";supplierName?:string|null};
type Row={label:string;lines:number;valueHt:number;percent?:number};
type Reorder={itemId:string;reference:string;description:string;family?:string|null;available:number;openDemand:number;projected:number;cmm:number;coverageDays?:number|null};
type BodyMonth={monthStart:string;amountHt:number;vop:number;perVop:number};
type Snapshot={summary:Summary;items:Item[];inventories:Array<{id:string;code:string;status:string;lineCount:number;countedCount:number;recountCount:number;varianceValue:number}>;dossierParts?:Dossier[];supplyLines?:Supply[];procurement?:{liveCounts?:{toOrder:number;ordered:number;backorder:number};orderedByBrand?:Row[];orderedByFamily?:Row[];topBuyers?:Row[];reorderWatch?:Reorder[]};bodyshopConsumables?:{cessionWorkOrder?:string;targetEuroPerVop?:number;current?:BodyMonth;months?:BodyMonth[]};settings?:{bodyshop_consumables?:{cessionWorkOrder?:string;targetEuroPerVop?:number}};error?:string};
type OrDetail={vehicle:{workOrder:string;registration?:string|null;vin?:string|null;client?:string|null;model?:string|null;status?:string|null};supplyLines?:Supply[]};
type Tab="dashboard"|"orders"|"stock"|"inventories"|"replenishment"|"bodyshop"|"settings";
const LABEL:Record<string,string>={to_order:"À commander",ordered:"Commandée",backorder:"Back order",received:"Reçue",cancelled:"Annulée"};
const TONE:Record<string,string>={to_order:"warning",ordered:"info",backorder:"danger",received:"success",cancelled:"muted"};
const money=(v:unknown)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(Number(v)||0);
const num=(v:unknown)=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:2}).format(Number(v)||0);

export default function MagasinWorkspace(){
 const [tab,setTab]=useState<Tab>("dashboard"),[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[family,setFamily]=useState("all"),[selected,setSelected]=useState(""),[detail,setDetail]=useState<OrDetail|null>(null),[cessionOr,setCessionOr]=useState(""),[target,setTarget]=useState("0");
 async function load(){setLoading(true);try{const r=await fetch("/api/development/pr",{cache:"no-store"}),j=await r.json() as Snapshot;if(!r.ok)throw new Error(j.error||"Magasin indisponible");setData(j);setError("");const bs=j.settings?.bodyshop_consumables;setCessionOr(bs?.cessionWorkOrder||"");setTarget(String(bs?.targetEuroPerVop||0))}catch(e){setError(e instanceof Error?e.message:"Magasin indisponible")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function post(body:Record<string,unknown>){setBusy(true);setError("");try{const r=await fetch("/api/development/pr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||"Action impossible");return j}catch(e){setError(e instanceof Error?e.message:"Action impossible");throw e}finally{setBusy(false)}}
 async function openOr(or:string){setSelected(or);setBusy(true);try{const r=await fetch(`/api/development/pr?workOrder=${encodeURIComponent(or)}`,{cache:"no-store"}),j=await r.json() as OrDetail;if(!r.ok)throw new Error("Dossier indisponible");setDetail(j)}catch(e){setError(e instanceof Error?e.message:"Dossier indisponible")}finally{setBusy(false)}}
 async function changeSupply(line:Supply,next:string){try{await post({action:"supply-action",payload:{action:"status",lineId:line.id,status:next}});setNotice("Commande mise à jour.");await load();await openOr(line.workOrder)}catch{}}
 async function saveBodyshop(){try{await post({action:"saveSetting",key:"bodyshop_consumables",value:{cessionWorkOrder:cessionOr.trim(),targetEuroPerVop:Number(target)||0}});setNotice("Réglage carrosserie enregistré.");await load()}catch{}}
 const summary=data?.summary||{references:0,stockValueHt:0,negativeReferences:0,cmmWindowMonths:6},proc=data?.procurement||{},dossiers=data?.dossierParts||[],items=data?.items||[],families=useMemo(()=>Array.from(new Set(items.map(x=>x.family||"Autres"))).sort(),[items]);
 const visibleDossiers=useMemo(()=>dossiers.filter(x=>status==="all"||x.partStatus===status).filter(x=>!search||`${x.workOrder} ${x.registration||""} ${x.vin||""} ${x.client||""}`.toLowerCase().includes(search.toLowerCase())),[dossiers,status,search]);
 const visibleItems=useMemo(()=>items.filter(x=>family==="all"||(x.family||"Autres")===family).filter(x=>!search||`${x.reference} ${x.manufacturerLabel||""} ${x.description}`.toLowerCase().includes(search.toLowerCase())),[items,family,search]);
 const tabs:Array<[Tab,string,string]>=[["dashboard","Dashboard","⌂"],["orders","Commandes & dossiers","▤"],["stock","Stock","▦"],["inventories","Inventaires","◎"],["replenishment","CMM & réappro","↻"],["bodyshop","Consommables carrosserie","◫"],["settings","Réglages","⚙"]];
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.hero}><div><span className={styles.eyebrow}>TOOLBOX · MAGASIN</span><h1>Magasin</h1><p>Commandes, dossiers, stock et réapprovisionnement dans un cockpit unique.</p></div><button className={styles.refresh} onClick={()=>void load()} disabled={loading||busy}>↻ Actualiser</button></header>
  {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
  <nav className={styles.tabs}>{tabs.map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?styles.active:""}><span>{icon}</span>{label}</button>)}</nav>
  {tab==="dashboard"&&<><section className={styles.kpis}><Kpi label="À commander" value={proc.liveCounts?.toOrder||0} note="dossiers ICAR" tone="warning"/><Kpi label="Pièces commandées" value={proc.liveCounts?.ordered||0} note="dossiers en attente"/><Kpi label="Back order" value={proc.liveCounts?.backorder||0} note="à surveiller" tone="danger"/><Kpi label="Valeur du stock" value={money(summary.stockValueHt)} note={`${summary.references} références`}/><Kpi label="Stocks négatifs" value={summary.negativeReferences||0} note="situation provisoire" tone={(summary.negativeReferences||0)>0?"warning":""}/></section><section className={styles.dashboardGrid}><Panel title="Commandes par marque / fournisseur"><Bars rows={proc.orderedByBrand||[]}/></Panel><Panel title="Commandes par famille"><Bars rows={proc.orderedByFamily||[]}/></Panel><Panel title="Top acheteurs"><div className={styles.ranking}>{(proc.topBuyers||[]).slice(0,7).map((r,i)=><div key={r.label}><b>{i+1}</b><span><strong>{r.label}</strong><small>{r.lines} lignes · {money(r.valueHt)}</small></span></div>)}{!(proc.topBuyers||[]).length&&<Empty/>}</div></Panel><Panel title="Réappro à surveiller"><div className={styles.watch}>{(proc.reorderWatch||[]).slice(0,8).map(r=><button key={r.itemId} onClick={()=>{setSearch(r.reference);setTab("stock")}}><span><strong>{r.reference}</strong><small>{r.description}</small></span><b className={r.projected<=0?styles.red:styles.amber}>{num(r.projected)} · {r.coverageDays==null?"—":`${num(r.coverageDays)} j`}</b></button>)}{!(proc.reorderWatch||[]).length&&<Empty/>}</div></Panel></section></>}
  {tab==="orders"&&<section className={styles.sectionCard}><Head eyebrow="FLUX ICAR + MAGASIN" title="Commandes & dossiers" text="Chaque besoin PR reste rattaché à son OR et à son véhicule."><div className={styles.filters}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="OR, immat., VIN, client…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous les statuts</option><option value="to_order">À commander</option><option value="ordered">Commandée</option><option value="backorder">Back order</option></select></div></Head><div className={styles.split}><div className={styles.orderList}>{visibleDossiers.map(d=><button key={d.workOrder} className={`${styles.orderCard} ${selected===d.workOrder?styles.selected:""}`} onClick={()=>void openOr(d.workOrder)}><div><span className={`${styles.status} ${styles[TONE[d.partStatus]]}`}>{LABEL[d.partStatus]}</span><strong>OR {d.workOrder}</strong><small>{d.registration||"Sans immat."} · {d.model||d.client||"Dossier ICAR"}</small></div><div className={styles.orderAge}><b>{d.orderedDays??0} j</b><span>attente PR</span></div></button>)}{!visibleDossiers.length&&<Empty/>}</div><aside className={styles.drawer}>{detail?<><div className={styles.drawerHead}><span>OR {detail.vehicle.workOrder}</span><h3>{detail.vehicle.registration||"Dossier"}</h3><p>{detail.vehicle.vin||"VIN non renseigné"}</p></div><div className={styles.drawerMeta}><span>Client <b>{detail.vehicle.client||"—"}</b></span><span>Modèle <b>{detail.vehicle.model||"—"}</b></span><span>Statut <b>{detail.vehicle.status||"—"}</b></span></div><h4>Pièces liées au dossier</h4><div className={styles.supplyList}>{(detail.supplyLines||[]).map(l=><div key={l.id}><span><strong>{l.reference}</strong><small>{l.description}</small><em>{l.supplierName||l.manufacturerLabel||"Fournisseur à préciser"} · Qté {num(l.quantity)}</em></span><aside><i className={`${styles.status} ${styles[TONE[l.status]]}`}>{LABEL[l.status]}</i>{l.status==="to_order"&&<button onClick={()=>void changeSupply(l,"ordered")}>Commander</button>}{l.status==="ordered"&&<><button onClick={()=>void changeSupply(l,"received")}>Réceptionner</button><button className={styles.linkDanger} onClick={()=>void changeSupply(l,"backorder")}>Back order</button></>}{l.status==="backorder"&&<button onClick={()=>void changeSupply(l,"received")}>Réceptionner</button>}</aside></div>)}{!(detail.supplyLines||[]).length&&<Empty label="Aucune ligne magasin créée sur cet OR."/>}</div></>:<div className={styles.drawerEmpty}>Sélectionne un dossier pour afficher son véhicule et ses commandes PR.</div>}</aside></div></section>}
  {tab==="stock"&&<section className={styles.sectionCard}><Head eyebrow="STOCK MAGASIN" title="Références & disponibilité" text="Stock physique, réservé, disponible, PAMP, CMM et couverture."><div className={styles.filters}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Référence, marque, désignation…"/><select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">Toutes les familles</option>{families.map(f=><option key={f}>{f}</option>)}</select></div></Head><div className={styles.tableWrap}><table><thead><tr><th>Référence</th><th>Famille</th><th>Physique</th><th>Réservé</th><th>Disponible</th><th>PAMP</th><th>CMM</th><th>Couverture</th><th>Valeur</th></tr></thead><tbody>{visibleItems.map(i=><tr key={i.id} className={i.onHand<0?styles.negativeRow:""}><td><strong>{i.reference}</strong><small>{i.manufacturerLabel||""} · {i.description}</small>{i.provisionalStock&&<em>Provisoire</em>}</td><td>{i.family||"Autres"}</td><td>{num(i.onHand)}</td><td>{num(i.reserved)}</td><td><b className={i.available<0?styles.red:""}>{num(i.available)}</b></td><td>{money(i.averageCostHt)}</td><td>{num(i.cmm)}</td><td>{i.coverageDays==null?"—":`${num(i.coverageDays)} j`}</td><td>{money(i.stockValueHt)}</td></tr>)}</tbody></table></div></section>}
  {tab==="inventories"&&<section className={styles.sectionCard}><Head eyebrow="CONTRÔLE DU STOCK" title="Inventaires" text="Inventaires tournants et suivi des écarts."/><div className={styles.inventoryGrid}>{(data?.inventories||[]).map(i=><article key={i.id}><span className={`${styles.status} ${i.status==="closed"?styles.success:styles.info}`}>{i.status==="closed"?"Clôturé":"En cours"}</span><h3>{i.code}</h3><p>{i.lineCount} références · {i.countedCount} comptées</p><div><span>Recomptages <b>{i.recountCount}</b></span><span>Écart <b>{money(i.varianceValue)}</b></span></div></article>)}{!(data?.inventories||[]).length&&<Empty/>}</div></section>}
  {tab==="replenishment"&&<section className={styles.sectionCard}><Head eyebrow="CMM & ROTATION" title="Réapprovisionnement" text="Stock projeté après besoins ouverts et priorité aux références tendues."><span className={styles.period}>CMM {summary.cmmWindowMonths} mois</span></Head><div className={styles.reorderGrid}>{(proc.reorderWatch||[]).map(r=><article key={r.itemId} className={r.projected<=0?styles.urgent:""}><div><span>{r.family||"Autres"}</span><strong>{r.reference}</strong><small>{r.description}</small></div><div className={styles.reorderNums}><span>Disponible <b>{num(r.available)}</b></span><span>Besoins <b>{num(r.openDemand)}</b></span><span>Projeté <b className={r.projected<=0?styles.red:""}>{num(r.projected)}</b></span><span>Couverture <b>{r.coverageDays==null?"—":`${num(r.coverageDays)} j`}</b></span></div></article>)}{!(proc.reorderWatch||[]).length&&<Empty/>}</div></section>}
  {tab==="bodyshop"&&<Bodyshop data={data?.bodyshopConsumables}/>} 
  {tab==="settings"&&<section className={styles.settings}><aside><button className={styles.activeSetting}>Référentiel</button><button>Prix & règles</button><button>Forfaits</button><button>Comptabilité</button><button>Stock & CMM</button><button>Consommables carrosserie</button><button>Imports</button></aside><div className={styles.settingContent}><h2>Réglages Magasin</h2><p>Les réglages métier sont regroupés ici et ne sont plus exposés dans la navigation quotidienne.</p><div className={styles.settingBox}><h3>Consommables carrosserie</h3><label><span>OR cession carrosserie</span><input value={cessionOr} onChange={e=>setCessionOr(e.target.value)} placeholder="N° OR"/></label><label><span>Objectif €/VOP</span><input type="number" step="0.01" value={target} onChange={e=>setTarget(e.target.value)}/></label><button className={styles.primary} onClick={()=>void saveBodyshop()} disabled={busy}>Enregistrer</button></div><div className={styles.infoBox}><strong>Stock de développement</strong><span>Les quantités importées, y compris négatives, restent identifiées comme provisoires jusqu'à l'inventaire réel.</span></div></div></section>}
 </div></main>
}

function Kpi({label,value,note,tone=""}:{label:string;value:string|number;note:string;tone?:string}){return <article className={tone?styles[`kpi${tone[0].toUpperCase()+tone.slice(1)}`]:""}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <article className={styles.panel}><div className={styles.panelHead}><h2>{title}</h2></div>{children}</article>}
function Bars({rows}:{rows:Row[]}){if(!rows.length)return <Empty/>;const max=Math.max(...rows.map(r=>r.lines),1);return <div className={styles.bars}>{rows.slice(0,8).map(r=><div key={r.label}><div><strong>{r.label}</strong><span>{r.lines} · {r.percent??Math.round(r.lines/max*100)}%</span></div><i><b style={{width:`${Math.max(3,r.percent??r.lines/max*100)}%`}}/></i><small>{money(r.valueHt)}</small></div>)}</div>}
function Empty({label="Aucune donnée pour le moment."}:{label?:string}){return <div className={styles.empty}>{label}</div>}
function Head({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:React.ReactNode}){return <div className={styles.sectionHead}><div><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{children}</div>}
function Bodyshop({data}:{data?:Snapshot["bodyshopConsumables"]}){const months=data?.months||[],max=Math.max(...months.map(m=>m.perVop),1);return <section className={styles.sectionCard}><Head eyebrow="CONSOMMABLES CARROSSERIE" title="Petite fourniture par VOP" text="Sorties sur l'OR de cession rapprochées des VOP du mois.">{data?.cessionWorkOrder&&<span className={styles.period}>OR {data.cessionWorkOrder}</span>}</Head><section className={styles.bodyKpis}><Kpi label="Montant du mois" value={money(data?.current?.amountHt||0)} note="sorties cession"/><Kpi label="VOP du mois" value={num(data?.current?.vop||0)} note="production"/><Kpi label="Petite fourniture / VOP" value={money(data?.current?.perVop||0)} note="indicateur magasin"/><Kpi label="Objectif" value={money(data?.targetEuroPerVop||0)} note="€/VOP"/></section><div className={styles.monthChart}>{months.map(m=><div key={m.monthStart}><span>{new Date(`${m.monthStart}T12:00:00`).toLocaleDateString("fr-FR",{month:"short"})}</span><div><i style={{height:`${Math.max(4,m.perVop/max*100)}%`}}/><b>{money(m.perVop)}</b></div><small>{money(m.amountHt)} · {m.vop} VOP</small></div>)}</div></section>}
