"use client";

import { type FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./pr-workspace.module.css";

type Summary={references:number;stockUnits:number;reservedUnits:number;availableUnits:number;stockValueHt:number;locations:number;openInventories:number;movements30d:number;cmmWindowMonths:number};
type Item={id:string;reference:string;manufacturerCode?:string|null;manufacturerLabel?:string|null;description:string;ean?:string|null;family?:string|null;category?:string|null;unit:string;listPriceHt?:number|null;standardPurchasePriceHt?:number|null;vatRate:number;isActive:boolean;onHand:number;reserved:number;available:number;averageCostHt:number;stockValueHt:number;cmm:number;coverageDays?:number|null;lastIssueAt?:string|null};
type Movement={id:string;createdAt:string;movementType:string;reference:string;description:string;locationCode:string;quantityDelta:number;unitCostHt:number;valueDeltaHt:number;balanceAfter:number;workOrder?:string|null;registration?:string|null;vin?:string|null;documentReference?:string|null;reason?:string|null;actorName?:string|null};
type Inventory={id:string;code:string;inventoryType:string;status:string;blindCount:boolean;createdAt:string;closedAt?:string|null;lineCount:number;countedCount:number;recountCount:number;varianceValue:number};
type Package={id:string;code:string;label:string;description?:string|null;fixedPriceHt?:number|null;discountPercent:number;isActive:boolean;lineCount:number};
type DiscountRule={id:string;code:string;label:string;scopeType:string;scopeValue?:string|null;discountType:string;discountValue:number;priority:number;validFrom?:string|null;validTo?:string|null;isActive:boolean};
type Settings={stock_policy?:{allowNegativeStock?:boolean;defaultLocationCode?:string};cmm_policy?:{windowMonths?:number;dormantDays?:number;slowCoverageDays?:number};sage_mapping?:{journalStock?:string;accountStock?:string;accountVariation?:string;analyticAxis1?:string;analyticAxis2?:string}};
type Snapshot={connected:boolean;mode:string;summary:Summary;items:Item[];movements:Movement[];inventories:Inventory[];packages:Package[];discountRules:DiscountRule[];settings:Settings;error?:string};
type WorkOrderDetail={connected:boolean;vehicle:{workOrder:string;registration?:string|null;vin?:string|null;metadata?:Record<string,unknown>};reservations:Array<{id:string;reference:string;description:string;locationCode:string;quantity:number;status:string;createdAt:string;servedAt?:string|null;releasedAt?:string|null}>;movements:Array<{id:string;reference:string;description:string;movementType:string;quantityDelta:number;unitCostHt:number;valueDeltaHt:number;createdAt:string;actorName?:string|null}>};
type InventoryDetail={connected:boolean;session:{id:string;code:string;inventoryType:string;status:string;blindCount:boolean;quantityRecountThreshold:number;valueRecountThreshold:number;createdAt:string;closedAt?:string|null};lines:Array<{id:string;reference:string;description:string;locationCode:string;theoreticalQty?:number|null;firstCountQty?:number|null;secondCountQty?:number|null;finalQty?:number|null;varianceQty?:number|null;varianceValue?:number|null;recountRequired:boolean;countedBy?:string|null;countedAt?:string|null}>};
type Tab="cockpit"|"stock"|"or"|"inventories"|"cmm"|"forfaits"|"compta"|"settings";
type PackageLine={lineType:"part"|"labor"|"fee";reference:string;label:string;quantity:string;laborMinutes:string;publicUnitPriceHt:string;costUnitHt:string};

const EMPTY_SUMMARY:Summary={references:0,stockUnits:0,reservedUnits:0,availableUnits:0,stockValueHt:0,locations:0,openInventories:0,movements30d:0,cmmWindowMonths:6};
const MOVEMENT_SIGNS:Record<string,1|-1|0>={initial_stock:1,receipt:1,issue_work_order:-1,return_work_order:1,transfer_in:1,transfer_out:-1,inventory_adjustment:0,manual_adjustment:0};
const MOVEMENT_LABELS:Record<string,string>={initial_stock:"Stock initial",receipt:"Réception fournisseur",issue_work_order:"Débit OR",return_work_order:"Retour OR",inventory_adjustment:"Ajustement inventaire",transfer_in:"Transfert entrant",transfer_out:"Transfert sortant",manual_adjustment:"Correction manuelle",package_issue:"Sortie forfait"};

function money(v:unknown){const n=Number(v)||0;return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(n);}
function qty(v:unknown){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:3}).format(Number(v)||0);}
function dateTime(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(d);}
function coverageLabel(item:Item){if(item.cmm<=0)return "Sans conso";if((item.coverageDays||0)>180)return "Surstock";if((item.coverageDays||0)>120)return "Lent";if((item.coverageDays||0)<20)return "Tendu";return "Normal";}
function uid(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}

export default function PrWorkspace(){
  const [tab,setTab]=useState<Tab>("cockpit");
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [search,setSearch]=useState("");
  const [workOrder,setWorkOrder]=useState("");
  const [workOrderDetail,setWorkOrderDetail]=useState<WorkOrderDetail|null>(null);
  const [inventoryDetail,setInventoryDetail]=useState<InventoryDetail|null>(null);
  const [counts,setCounts]=useState<Record<string,string>>({});
  const [newItem,setNewItem]=useState({reference:"",description:"",manufacturerLabel:"",ean:"",family:"",category:"",standardPurchasePriceHt:"",listPriceHt:""});
  const [movement,setMovement]=useState({movementType:"receipt",reference:"",quantity:"1",unitCostHt:"",workOrder:"",documentReference:"",reason:""});
  const [reservation,setReservation]=useState({reference:"",quantity:"1"});
  const [discount,setDiscount]=useState({code:"",label:"",scopeType:"global",scopeValue:"",discountType:"percent",discountValue:"0"});
  const [pack,setPack]=useState({code:"",label:"",description:"",fixedPriceHt:"",discountPercent:"0"});
  const [packageLines,setPackageLines]=useState<PackageLine[]>([{lineType:"part",reference:"",label:"",quantity:"1",laborMinutes:"",publicUnitPriceHt:"",costUnitHt:""},{lineType:"labor",reference:"",label:"Main-d'œuvre",quantity:"1",laborMinutes:"30",publicUnitPriceHt:"",costUnitHt:""}]);
  const [cmm,setCmm]=useState({windowMonths:"6",dormantDays:"180",slowCoverageDays:"120"});
  const [sage,setSage]=useState({journalStock:"",accountStock:"",accountVariation:"",analyticAxis1:"",analyticAxis2:""});

  async function load(q=""){
    setLoading(true);
    try{
      const r=await fetch(`/api/development/pr${q?`?q=${encodeURIComponent(q)}`:""}`,{cache:"no-store"});
      const data=await r.json() as Snapshot;
      if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);
      setSnapshot(data);setError("");
      const cp=data.settings?.cmm_policy||{};setCmm({windowMonths:String(cp.windowMonths||6),dormantDays:String(cp.dormantDays||180),slowCoverageDays:String(cp.slowCoverageDays||120)});
      const sm=data.settings?.sage_mapping||{};setSage({journalStock:sm.journalStock||"",accountStock:sm.accountStock||"",accountVariation:sm.accountVariation||"",analyticAxis1:sm.analyticAxis1||"",analyticAxis2:sm.analyticAxis2||""});
    }catch(e){setError(e instanceof Error?e.message:"Module PR indisponible");}
    finally{setLoading(false);}
  }

  useEffect(()=>{void load();},[]);

  async function post(body:Record<string,unknown>){
    setBusy(true);setNotice("");setError("");
    try{
      const r=await fetch("/api/development/pr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
      const data=await r.json() as Record<string,unknown>;
      if(!r.ok)throw new Error(String(data.error||`HTTP ${r.status}`));
      return data;
    }catch(e){setError(e instanceof Error?e.message:"Action impossible");throw e;}
    finally{setBusy(false);}
  }

  async function addItem(e:FormEvent){e.preventDefault();try{await post({action:"upsertItem",item:{...newItem,standardPurchasePriceHt:newItem.standardPurchasePriceHt||null,listPriceHt:newItem.listPriceHt||null}});setNotice("Référence enregistrée.");setNewItem({reference:"",description:"",manufacturerLabel:"",ean:"",family:"",category:"",standardPurchasePriceHt:"",listPriceHt:""});await load(search);}catch{}}
  async function addMovement(e:FormEvent){e.preventDefault();const raw=Number(movement.quantity);if(!Number.isFinite(raw)||raw===0){setError("Quantité invalide.");return;}const sign=MOVEMENT_SIGNS[movement.movementType]??0;const delta=sign===0?raw:Math.abs(raw)*sign;try{await post({action:"movement",payload:{movementType:movement.movementType,reference:movement.reference.trim(),quantityDelta:delta,unitCostHt:movement.unitCostHt||null,workOrder:movement.workOrder||null,documentReference:movement.documentReference||null,reason:movement.reason||null,idempotencyKey:uid("pr-mvt")}});setNotice("Mouvement de stock comptabilisé.");setMovement(v=>({...v,reference:"",quantity:"1",unitCostHt:"",documentReference:"",reason:""}));await load(search);}catch{}}
  async function openWorkOrder(e?:FormEvent){e?.preventDefault();if(!workOrder.trim())return;setBusy(true);try{const r=await fetch(`/api/development/pr?workOrder=${encodeURIComponent(workOrder.trim())}`,{cache:"no-store"});const data=await r.json() as WorkOrderDetail;if(!r.ok)throw new Error((data as unknown as {error?:string}).error||`HTTP ${r.status}`);setWorkOrderDetail(data);setError("");}catch(e2){setError(e2 instanceof Error?e2.message:"OR indisponible");}finally{setBusy(false);}}
  async function reservePart(e:FormEvent){e.preventDefault();if(!workOrder.trim())return;try{await post({action:"reserve",payload:{reference:reservation.reference.trim(),quantity:Number(reservation.quantity),workOrder:workOrder.trim(),idempotencyKey:uid("pr-res")}});setNotice("Pièce réservée sur l'OR.");setReservation({reference:"",quantity:"1"});await openWorkOrder();await load();}catch{}}
  async function reservationAction(action:"serveReservation"|"releaseReservation",id:string){try{await post({action,reservationId:id});setNotice(action==="serveReservation"?"Réservation servie et stock débité.":"Réservation libérée.");await openWorkOrder();await load();}catch{}}
  async function createInventory(){try{const data=await post({action:"createInventory",filters:{inventoryType:"cycle",blindCount:true,locationCode:"MAG-PR",includeZeroStock:false,quantityRecountThreshold:1,valueRecountThreshold:50}});setNotice(`Inventaire ${String(data.code||"")} créé · ${String(data.lineCount||0)} lignes.`);await load();if(data.sessionId)await openInventory(String(data.sessionId));}catch{}}
  async function openInventory(id:string){setBusy(true);try{const r=await fetch(`/api/development/pr?inventory=${encodeURIComponent(id)}`,{cache:"no-store"});const data=await r.json() as InventoryDetail;if(!r.ok)throw new Error((data as unknown as {error?:string}).error||`HTTP ${r.status}`);setInventoryDetail(data);setCounts({});setError("");}catch(e){setError(e instanceof Error?e.message:"Inventaire indisponible");}finally{setBusy(false);}}
  async function countLine(id:string){const value=Number(counts[id]);if(!Number.isFinite(value)||value<0){setError("Comptage invalide.");return;}try{await post({action:"countInventoryLine",lineId:id,count:value});setNotice("Comptage enregistré.");if(inventoryDetail)await openInventory(inventoryDetail.session.id);await load();}catch{}}
  async function closeInventory(){if(!inventoryDetail)return;try{await post({action:"closeInventory",sessionId:inventoryDetail.session.id});setNotice("Inventaire clôturé : les écarts ont été transformés en mouvements de stock.");await openInventory(inventoryDetail.session.id);await load();}catch{}}
  async function saveDiscount(e:FormEvent){e.preventDefault();try{await post({action:"upsertDiscountRule",rule:{...discount,discountValue:Number(discount.discountValue),priority:100,isActive:true}});setNotice("Règle de rabais enregistrée.");setDiscount({code:"",label:"",scopeType:"global",scopeValue:"",discountType:"percent",discountValue:"0"});await load();}catch{}}
  async function savePackage(e:FormEvent){e.preventDefault();try{await post({action:"upsertPackage",package:{...pack,fixedPriceHt:pack.fixedPriceHt||null,discountPercent:Number(pack.discountPercent)||0,isActive:true,lines:packageLines.map(l=>({...l,quantity:Number(l.quantity)||1,laborMinutes:l.laborMinutes||null,publicUnitPriceHt:l.publicUnitPriceHt||null,costUnitHt:l.costUnitHt||null}))}});setNotice("Forfait enregistré.");setPack({code:"",label:"",description:"",fixedPriceHt:"",discountPercent:"0"});await load();}catch{}}
  async function saveSetting(key:string,value:Record<string,unknown>,message:string){try{await post({action:"saveSetting",key,value});setNotice(message);await load();}catch{}}

  const summary=snapshot?.summary||EMPTY_SUMMARY;
  const items=snapshot?.items||[];
  const critical=useMemo(()=>items.filter(i=>i.cmm>0&&(i.coverageDays||0)<20).slice(0,8),[items]);
  const dormant=useMemo(()=>items.filter(i=>i.cmm===0&&i.onHand>0).sort((a,b)=>b.stockValueHt-a.stockValueHt).slice(0,8),[items]);
  const tabs:Array<[Tab,string]>=[["cockpit","Cockpit"],["stock","Stock & mouvements"],["or","Dossiers / OR"],["inventories","Inventaires"],["cmm","CMM & rotations"],["forfaits","Forfaits & rabais"],["compta","Comptabilité Sage"],["settings","Paramètres"]];

  return <main className={styles.page}>
    <div className={styles.shell}>
      <header className={styles.hero}>
        <div><div className={styles.eyebrow}>SAS DÉVELOPPEMENT · MODULE PR / MAGASIN</div><h1>Pièces de rechange</h1><p>Grand livre de stock, PAMP, réservations et débits OR, inventaires tournants, CMM, forfaits pièce + MO, rabais et préparation comptable.</p></div>
        <div className={styles.heroRight}><span className={styles.devBadge}>DEV · ADMIN ONLY</span><button onClick={()=>void load(search)} disabled={loading||busy}>↻ Actualiser</button></div>
      </header>

      <section className={styles.kpis}>
        <article><span>Valeur stock HT</span><strong>{money(summary.stockValueHt)}</strong><small>PAMP × stock physique</small></article>
        <article><span>Références</span><strong>{summary.references}</strong><small>{summary.locations} emplacement(s)</small></article>
        <article><span>Stock disponible</span><strong>{qty(summary.availableUnits)}</strong><small>{qty(summary.reservedUnits)} réservé</small></article>
        <article><span>Inventaires ouverts</span><strong>{summary.openInventories}</strong><small>{summary.movements30d} mvts / 30 j</small></article>
        <article><span>CMM</span><strong>{summary.cmmWindowMonths} mois</strong><small>Fenêtre paramétrable</small></article>
      </section>

      {summary.references===0&&!loading&&<div className={styles.readyBanner}><strong>Environnement PR prêt.</strong> La base est vide volontairement : j'attends le stock réel pour créer la situation initiale sans polluer le référentiel avec de fausses pièces.</div>}
      {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}

      <nav className={styles.tabs}>{tabs.map(([key,label])=><button key={key} className={tab===key?styles.active:""} onClick={()=>setTab(key)}>{label}</button>)}</nav>

      {tab==="cockpit"&&<section className={styles.grid2}>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>PILOTAGE STOCK</span><h2>Alertes de couverture</h2></div></div>{critical.length?<div className={styles.list}>{critical.map(i=><div key={i.id} className={styles.row}><div><strong>{i.reference}</strong><span>{i.description}</span></div><div className={styles.right}><b>{qty(i.available)} dispo</b><span>{qty(i.cmm)} CMM · {qty(i.coverageDays)} j</span></div></div>)}</div>:<div className={styles.empty}>Aucune référence sous 20 jours de couverture.</div>}</div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>CAPITAL IMMOBILISÉ</span><h2>Stock sans consommation</h2></div></div>{dormant.length?<div className={styles.list}>{dormant.map(i=><div key={i.id} className={styles.row}><div><strong>{i.reference}</strong><span>{i.description}</span></div><div className={styles.right}><b>{money(i.stockValueHt)}</b><span>{qty(i.onHand)} en stock</span></div></div>)}</div>:<div className={styles.empty}>Aucun stock dormant identifié.</div>}</div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.cardTitle}><div><span>TRACABILITÉ</span><h2>Derniers mouvements</h2></div></div><MovementTable rows={(snapshot?.movements||[]).slice(0,12)}/></div>
      </section>}

      {tab==="stock"&&<section className={styles.grid2}>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.toolbar}><div><span className={styles.miniLabel}>CATALOGUE & STOCK</span><h2>Références PR</h2></div><form onSubmit={e=>{e.preventDefault();void load(search)}} className={styles.search}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Référence, désignation, EAN…"/><button>Rechercher</button></form></div><div className={styles.tableWrap}><table><thead><tr><th>Référence</th><th>Désignation</th><th>Stock</th><th>Réservé</th><th>Dispo</th><th>PAMP</th><th>CMM</th><th>Couverture</th><th>Valeur</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.reference}</b><small>{i.manufacturerLabel||i.family||"—"}</small></td><td>{i.description}</td><td>{qty(i.onHand)}</td><td>{qty(i.reserved)}</td><td><b>{qty(i.available)}</b></td><td>{money(i.averageCostHt)}</td><td>{qty(i.cmm)}</td><td><span className={styles.pill}>{i.coverageDays==null?"—":`${qty(i.coverageDays)} j`} · {coverageLabel(i)}</span></td><td>{money(i.stockValueHt)}</td></tr>)}</tbody></table>{!items.length&&<div className={styles.empty}>Aucune référence chargée.</div>}</div></div>
        <form className={styles.card} onSubmit={addItem}><div className={styles.cardTitle}><div><span>RÉFÉRENTIEL</span><h2>Créer / mettre à jour une pièce</h2></div></div><Field label="Référence"><input required value={newItem.reference} onChange={e=>setNewItem({...newItem,reference:e.target.value})}/></Field><Field label="Désignation"><input required value={newItem.description} onChange={e=>setNewItem({...newItem,description:e.target.value})}/></Field><div className={styles.cols}><Field label="Constructeur"><input value={newItem.manufacturerLabel} onChange={e=>setNewItem({...newItem,manufacturerLabel:e.target.value})}/></Field><Field label="EAN"><input value={newItem.ean} onChange={e=>setNewItem({...newItem,ean:e.target.value})}/></Field></div><div className={styles.cols}><Field label="Famille"><input value={newItem.family} onChange={e=>setNewItem({...newItem,family:e.target.value})}/></Field><Field label="Catégorie"><input value={newItem.category} onChange={e=>setNewItem({...newItem,category:e.target.value})}/></Field></div><div className={styles.cols}><Field label="PA standard HT"><input type="number" step="0.0001" value={newItem.standardPurchasePriceHt} onChange={e=>setNewItem({...newItem,standardPurchasePriceHt:e.target.value})}/></Field><Field label="Tarif public HT"><input type="number" step="0.0001" value={newItem.listPriceHt} onChange={e=>setNewItem({...newItem,listPriceHt:e.target.value})}/></Field></div><button className={styles.primary} disabled={busy}>Enregistrer la référence</button></form>
        <form className={styles.card} onSubmit={addMovement}><div className={styles.cardTitle}><div><span>GRAND LIVRE</span><h2>Passer un mouvement</h2></div></div><Field label="Type"><select value={movement.movementType} onChange={e=>setMovement({...movement,movementType:e.target.value})}>{Object.entries(MOVEMENT_LABELS).filter(([k])=>k!=="package_issue").map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><div className={styles.cols}><Field label="Référence"><input required value={movement.reference} onChange={e=>setMovement({...movement,reference:e.target.value})}/></Field><Field label="Quantité"><input required type="number" step="0.001" value={movement.quantity} onChange={e=>setMovement({...movement,quantity:e.target.value})}/></Field></div><div className={styles.cols}><Field label="Coût unitaire HT"><input type="number" step="0.0001" value={movement.unitCostHt} onChange={e=>setMovement({...movement,unitCostHt:e.target.value})}/></Field><Field label="N° OR"><input value={movement.workOrder} onChange={e=>setMovement({...movement,workOrder:e.target.value})}/></Field></div><Field label="Pièce / BL fournisseur"><input value={movement.documentReference} onChange={e=>setMovement({...movement,documentReference:e.target.value})}/></Field><Field label="Motif"><input value={movement.reason} onChange={e=>setMovement({...movement,reason:e.target.value})}/></Field><button className={styles.primary} disabled={busy}>Valider le mouvement</button><small className={styles.hint}>Une écriture validée n'est jamais supprimée : une correction passe par un mouvement inverse.</small></form>
      </section>}

      {tab==="or"&&<section className={styles.grid2}>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>DOSSIER ATELIER</span><h2>Charger un OR</h2></div></div><form className={styles.inlineForm} onSubmit={openWorkOrder}><input value={workOrder} onChange={e=>setWorkOrder(e.target.value)} placeholder="N° d'OR"/><button className={styles.primary}>Ouvrir</button></form>{workOrderDetail&&<div className={styles.vehicle}><b>OR {workOrderDetail.vehicle.workOrder}</b><span>Immat. {workOrderDetail.vehicle.registration||"—"}</span><span>VIN {workOrderDetail.vehicle.vin||"—"}</span></div>}<form onSubmit={reservePart} className={styles.subForm}><h3>Réserver une pièce</h3><div className={styles.cols}><Field label="Référence"><input required value={reservation.reference} onChange={e=>setReservation({...reservation,reference:e.target.value})}/></Field><Field label="Quantité"><input required type="number" min="0.001" step="0.001" value={reservation.quantity} onChange={e=>setReservation({...reservation,quantity:e.target.value})}/></Field></div><button className={styles.primary} disabled={!workOrderDetail||busy}>Réserver sur l'OR</button></form></div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>RÉSERVATIONS</span><h2>Pièces engagées</h2></div></div>{workOrderDetail?.reservations.length?<div className={styles.list}>{workOrderDetail.reservations.map(r=><div className={styles.row} key={r.id}><div><strong>{r.reference} × {qty(r.quantity)}</strong><span>{r.description} · {r.status}</span></div>{r.status==="active"&&<div className={styles.actions}><button onClick={()=>void reservationAction("serveReservation",r.id)}>Servir</button><button className={styles.ghostDanger} onClick={()=>void reservationAction("releaseReservation",r.id)}>Libérer</button></div>}</div>)}</div>:<div className={styles.empty}>Aucune réservation sur cet OR.</div>}</div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.cardTitle}><div><span>CONSOMMATION DOSSIER</span><h2>Débits et retours de l'OR</h2></div></div>{workOrderDetail?.movements.length?<div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Référence</th><th>Désignation</th><th>Mouvement</th><th>Qté</th><th>Coût</th><th>Valeur</th></tr></thead><tbody>{workOrderDetail.movements.map(m=><tr key={m.id}><td>{dateTime(m.createdAt)}</td><td><b>{m.reference}</b></td><td>{m.description}</td><td>{MOVEMENT_LABELS[m.movementType]||m.movementType}</td><td>{qty(m.quantityDelta)}</td><td>{money(m.unitCostHt)}</td><td>{money(m.valueDeltaHt)}</td></tr>)}</tbody></table></div>:<div className={styles.empty}>Charge un OR pour consulter ses consommations PR.</div>}</div>
      </section>}

      {tab==="inventories"&&<section className={styles.grid2}>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>INVENTAIRE TOURNANT</span><h2>Sessions</h2></div><button className={styles.primary} onClick={()=>void createInventory()} disabled={busy}>+ Nouvel inventaire</button></div><div className={styles.list}>{(snapshot?.inventories||[]).map(inv=><button key={inv.id} className={`${styles.inventoryRow} ${inventoryDetail?.session.id===inv.id?styles.selected:""}`} onClick={()=>void openInventory(inv.id)}><div><strong>{inv.code}</strong><span>{inv.inventoryType} · {dateTime(inv.createdAt)}</span></div><div className={styles.right}><b>{inv.countedCount}/{inv.lineCount}</b><span>{inv.status} · {money(inv.varianceValue)}</span></div></button>)}{!(snapshot?.inventories||[]).length&&<div className={styles.empty}>Aucun inventaire démarré.</div>}</div></div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>RÈGLES</span><h2>Recomptage automatique</h2></div></div><p className={styles.copy}>Le premier comptage est aveugle. Un recomptage est exigé si l'écart atteint au moins <b>1 pièce</b> ou <b>50 €</b> de valeur. La clôture génère ensuite les mouvements d'ajustement, sans modification silencieuse du stock.</p><div className={styles.ruleBox}><span>0 ≠ non compté</span><span>Historique conservé</span><span>Clôture transactionnelle</span></div></div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.cardTitle}><div><span>COMPTAGE</span><h2>{inventoryDetail?.session.code||"Sélectionne un inventaire"}</h2></div>{inventoryDetail&&inventoryDetail.session.status!=="closed"&&<button className={styles.primary} onClick={()=>void closeInventory()} disabled={busy}>Clôturer</button>}</div>{inventoryDetail?<div className={styles.tableWrap}><table><thead><tr><th>Référence</th><th>Désignation</th><th>Casier</th><th>Théorique</th><th>1er comptage</th><th>Écart</th><th>Action</th></tr></thead><tbody>{inventoryDetail.lines.map(line=><tr key={line.id}><td><b>{line.reference}</b></td><td>{line.description}</td><td>{line.locationCode}</td><td>{line.theoreticalQty==null?"Masqué":qty(line.theoreticalQty)}</td><td>{line.firstCountQty==null?<input className={styles.countInput} type="number" min="0" step="0.001" value={counts[line.id]||""} onChange={e=>setCounts({...counts,[line.id]:e.target.value})}/>:qty(line.firstCountQty)}</td><td>{line.varianceQty==null?"—":`${qty(line.varianceQty)} / ${money(line.varianceValue)}`}</td><td>{line.finalQty!=null?<span className={styles.ok}>Validé</span>:<div className={styles.actions}>{line.recountRequired&&<span className={styles.recount}>Recomptage</span>}<input className={styles.countInput} type="number" min="0" step="0.001" value={counts[line.id]||""} onChange={e=>setCounts({...counts,[line.id]:e.target.value})}/><button onClick={()=>void countLine(line.id)}>Valider</button></div>}</td></tr>)}</tbody></table>{!inventoryDetail.lines.length&&<div className={styles.empty}>Le stock est vide : aucune ligne à compter.</div>}</div>:<div className={styles.empty}>Ouvre une session pour commencer le comptage.</div>}</div>
      </section>}

      {tab==="cmm"&&<section className={styles.grid2}>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.cardTitle}><div><span>ROTATION</span><h2>CMM & couverture du stock</h2></div></div><div className={styles.tableWrap}><table><thead><tr><th>Référence</th><th>Désignation</th><th>Disponible</th><th>CMM</th><th>Couverture</th><th>Dernière sortie</th><th>Classe</th><th>Valeur</th></tr></thead><tbody>{[...items].sort((a,b)=>b.cmm-a.cmm).map(i=><tr key={i.id}><td><b>{i.reference}</b></td><td>{i.description}</td><td>{qty(i.available)}</td><td><b>{qty(i.cmm)}</b></td><td>{i.coverageDays==null?"—":`${qty(i.coverageDays)} j`}</td><td>{dateTime(i.lastIssueAt)}</td><td><span className={styles.pill}>{coverageLabel(i)}</span></td><td>{money(i.stockValueHt)}</td></tr>)}</tbody></table></div></div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>PARAMÉTRAGE</span><h2>Fenêtre CMM</h2></div></div><div className={styles.cols}><Field label="Mois observés"><input type="number" min="1" max="24" value={cmm.windowMonths} onChange={e=>setCmm({...cmm,windowMonths:e.target.value})}/></Field><Field label="Dormant après (jours)"><input type="number" value={cmm.dormantDays} onChange={e=>setCmm({...cmm,dormantDays:e.target.value})}/></Field></div><Field label="Couverture lente au-delà de (jours)"><input type="number" value={cmm.slowCoverageDays} onChange={e=>setCmm({...cmm,slowCoverageDays:e.target.value})}/></Field><button className={styles.primary} onClick={()=>void saveSetting("cmm_policy",{windowMonths:Number(cmm.windowMonths),dormantDays:Number(cmm.dormantDays),slowCoverageDays:Number(cmm.slowCoverageDays)},"Politique CMM enregistrée.")}>Enregistrer</button></div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>MÉTHODE</span><h2>Calcul transparent</h2></div></div><p className={styles.copy}><b>CMM = sorties atelier de la période / nombre de mois observés.</b> Les inventaires, transferts et réceptions ne gonflent pas la consommation. La couverture correspond au stock disponible / CMM × 30 jours.</p></div>
      </section>}

      {tab==="forfaits"&&<section className={styles.grid2}>
        <form className={styles.card} onSubmit={saveDiscount}><div className={styles.cardTitle}><div><span>POLITIQUE COMMERCIALE</span><h2>Créer un rabais</h2></div></div><div className={styles.cols}><Field label="Code"><input required value={discount.code} onChange={e=>setDiscount({...discount,code:e.target.value})}/></Field><Field label="Libellé"><input required value={discount.label} onChange={e=>setDiscount({...discount,label:e.target.value})}/></Field></div><div className={styles.cols}><Field label="Portée"><select value={discount.scopeType} onChange={e=>setDiscount({...discount,scopeType:e.target.value})}><option value="global">Global</option><option value="client">Client</option><option value="family">Famille</option><option value="category">Catégorie</option><option value="item">Référence</option><option value="package">Forfait</option></select></Field><Field label="Valeur de portée"><input value={discount.scopeValue} onChange={e=>setDiscount({...discount,scopeValue:e.target.value})}/></Field></div><div className={styles.cols}><Field label="Type"><select value={discount.discountType} onChange={e=>setDiscount({...discount,discountType:e.target.value})}><option value="percent">Pourcentage</option><option value="amount">Montant €</option></select></Field><Field label="Rabais"><input type="number" step="0.01" value={discount.discountValue} onChange={e=>setDiscount({...discount,discountValue:e.target.value})}/></Field></div><button className={styles.primary}>Enregistrer le rabais</button></form>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>RÈGLES ACTIVES</span><h2>Rabais enregistrés</h2></div></div><div className={styles.list}>{(snapshot?.discountRules||[]).map(r=><div className={styles.row} key={r.id}><div><strong>{r.code} · {r.label}</strong><span>{r.scopeType}{r.scopeValue?` : ${r.scopeValue}`:""}</span></div><div className={styles.right}><b>{r.discountType==="percent"?`${qty(r.discountValue)} %`:money(r.discountValue)}</b><span>{r.isActive?"Actif":"Inactif"}</span></div></div>)}{!(snapshot?.discountRules||[]).length&&<div className={styles.empty}>Aucune règle de rabais.</div>}</div></div>
        <form className={`${styles.card} ${styles.wide}`} onSubmit={savePackage}><div className={styles.cardTitle}><div><span>FORFAIT PIÈCES + MO</span><h2>Composer un forfait</h2></div></div><div className={styles.cols3}><Field label="Code"><input required value={pack.code} onChange={e=>setPack({...pack,code:e.target.value})}/></Field><Field label="Libellé"><input required value={pack.label} onChange={e=>setPack({...pack,label:e.target.value})}/></Field><Field label="Prix forfait HT"><input type="number" step="0.01" value={pack.fixedPriceHt} onChange={e=>setPack({...pack,fixedPriceHt:e.target.value})}/></Field></div><div className={styles.cols}><Field label="Description"><input value={pack.description} onChange={e=>setPack({...pack,description:e.target.value})}/></Field><Field label="Rabais forfait %"><input type="number" step="0.01" value={pack.discountPercent} onChange={e=>setPack({...pack,discountPercent:e.target.value})}/></Field></div><div className={styles.packageLines}>{packageLines.map((line,index)=><div className={styles.packageLine} key={index}><select value={line.lineType} onChange={e=>{const next=[...packageLines];next[index]={...line,lineType:e.target.value as PackageLine["lineType"]};setPackageLines(next)}}><option value="part">Pièce</option><option value="labor">MO</option><option value="fee">Frais</option></select><input placeholder={line.lineType==="part"?"Référence":"Libellé"} value={line.lineType==="part"?line.reference:line.label} onChange={e=>{const next=[...packageLines];next[index]=line.lineType==="part"?{...line,reference:e.target.value}:{...line,label:e.target.value};setPackageLines(next)}}/><input placeholder="Qté" type="number" step="0.001" value={line.quantity} onChange={e=>{const next=[...packageLines];next[index]={...line,quantity:e.target.value};setPackageLines(next)}}/><input placeholder="Min MO" type="number" value={line.laborMinutes} onChange={e=>{const next=[...packageLines];next[index]={...line,laborMinutes:e.target.value};setPackageLines(next)}}/><input placeholder="PV HT" type="number" step="0.01" value={line.publicUnitPriceHt} onChange={e=>{const next=[...packageLines];next[index]={...line,publicUnitPriceHt:e.target.value};setPackageLines(next)}}/><input placeholder="Coût HT" type="number" step="0.01" value={line.costUnitHt} onChange={e=>{const next=[...packageLines];next[index]={...line,costUnitHt:e.target.value};setPackageLines(next)}}/><button type="button" className={styles.ghostDanger} onClick={()=>setPackageLines(packageLines.filter((_,i)=>i!==index))}>×</button></div>)}</div><div className={styles.actions}><button type="button" onClick={()=>setPackageLines([...packageLines,{lineType:"part",reference:"",label:"",quantity:"1",laborMinutes:"",publicUnitPriceHt:"",costUnitHt:""}])}>+ Ligne</button><button className={styles.primary}>Enregistrer le forfait</button></div></form>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.cardTitle}><div><span>CATALOGUE FORFAITS</span><h2>Forfaits disponibles</h2></div></div><div className={styles.list}>{(snapshot?.packages||[]).map(p=><div className={styles.row} key={p.id}><div><strong>{p.code} · {p.label}</strong><span>{p.lineCount} ligne(s) · rabais {qty(p.discountPercent)} %</span></div><div className={styles.right}><b>{p.fixedPriceHt==null?"Prix calculé":money(p.fixedPriceHt)}</b><span>{p.isActive?"Actif":"Inactif"}</span></div></div>)}{!(snapshot?.packages||[]).length&&<div className={styles.empty}>Aucun forfait configuré.</div>}</div></div>
      </section>}

      {tab==="compta"&&<section className={styles.grid2}>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>SAGE 100</span><h2>Mapping comptable</h2></div></div><Field label="Journal stock"><input value={sage.journalStock} onChange={e=>setSage({...sage,journalStock:e.target.value})} placeholder="ex. STK"/></Field><div className={styles.cols}><Field label="Compte de stock"><input value={sage.accountStock} onChange={e=>setSage({...sage,accountStock:e.target.value})}/></Field><Field label="Compte de variation"><input value={sage.accountVariation} onChange={e=>setSage({...sage,accountVariation:e.target.value})}/></Field></div><div className={styles.cols}><Field label="Axe analytique 1"><input value={sage.analyticAxis1} onChange={e=>setSage({...sage,analyticAxis1:e.target.value})}/></Field><Field label="Axe analytique 2"><input value={sage.analyticAxis2} onChange={e=>setSage({...sage,analyticAxis2:e.target.value})}/></Field></div><button className={styles.primary} onClick={()=>void saveSetting("sage_mapping",sage,"Mapping Sage enregistré.")}>Enregistrer le mapping</button></div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>EXPORT</span><h2>Passerelle comptable</h2></div></div><p className={styles.copy}>La structure d'export est préparée pour produire des lots figés, numérotés et non réexportables deux fois. Je n'active pas encore la génération finale tant que nous n'avons pas la <b>version Sage exacte</b>, le journal et le plan de comptes validés par la comptabilité.</p><div className={styles.ruleBox}><span>Sage 100 paramétrable</span><span>FEC possible</span><span>Traçabilité par mouvement</span></div></div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.cardTitle}><div><span>PRINCIPE</span><h2>Stock → écritures</h2></div></div><div className={styles.flow}><div>Grand livre PR</div><b>→</b><div>Lot comptable figé</div><b>→</b><div>Contrôles débit = crédit</div><b>→</b><div>Export Sage</div></div></div>
      </section>}

      {tab==="settings"&&<section className={styles.grid2}>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>POLITIQUE STOCK</span><h2>Garde-fous</h2></div></div><div className={styles.ruleBox}><span>Stock négatif interdit</span><span>Emplacement par défaut MAG-PR</span><span>Mouvements idempotents</span><span>PAMP transactionnel</span></div><p className={styles.copy}>Ces règles sont volontairement strictes pendant le SAS. On pourra ouvrir des dérogations par profil après les tests terrain.</p></div>
        <div className={styles.card}><div className={styles.cardTitle}><div><span>SOURCES À RACCORDER</span><h2>Référentiels externes</h2></div></div><div className={styles.list}><div className={styles.row}><div><strong>Stock initial</strong><span>En attente du fichier magasin actuel</span></div><span className={styles.pending}>À FOURNIR</span></div><div className={styles.row}><div><strong>Tarifs constructeurs</strong><span>Historisation tarifaire déjà prévue</span></div><span className={styles.pending}>À RACCORDER</span></div><div className={styles.row}><div><strong>AAA Data</strong><span>Point d'enrichissement véhicule prévu, sous licence</span></div><span className={styles.pending}>À RACCORDER</span></div></div></div>
      </section>}
    </div>
  </main>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
function MovementTable({rows}:{rows:Movement[]}){return <div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Référence</th><th>Type</th><th>Qté</th><th>OR</th><th>Valeur</th><th>Stock après</th><th>Acteur</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{dateTime(m.createdAt)}</td><td><b>{m.reference}</b><small>{m.description}</small></td><td>{MOVEMENT_LABELS[m.movementType]||m.movementType}</td><td>{qty(m.quantityDelta)}</td><td>{m.workOrder||"—"}</td><td>{money(m.valueDeltaHt)}</td><td>{qty(m.balanceAfter)}</td><td>{m.actorName||"—"}</td></tr>)}</tbody></table>{!rows.length&&<div className={styles.empty}>Aucun mouvement enregistré.</div>}</div>}
