"use client";

import {useEffect,useMemo,useState} from "react";
import QrCode from "./qr-code";
import styles from "./quality-claims-v2.module.css";

type Claim={id:string;claim_number:string;site_code:string;source:string;client_name:string;partner_label:string|null;dealer_code:string|null;registration:string;work_order:string|null;vin:string|null;model:string|null;mileage:number|null;category:string;subcategory:string|null;description:string;priority:string;status:string;decision:string|null;committee_response:string|null;requested_info:string|null;estimate_amount:number|null;accepted_amount:number|null;sector_key:string|null;sector_label:string|null;responsible_employee_key:string|null;responsible_employee_name:string|null;quality_should_detect:boolean|null;quality_employee_key:string|null;quality_employee_name:string|null;root_cause:string|null;corrective_action:string|null;recurrence_key:string|null;declared_at:string;decision_at:string|null;closed_at:string|null;updated_at:string;network_contact_email?:string|null;network_contact_phone?:string|null;vehicle_returned_at?:string|null;source_status?:string|null;source_app?:string|null;external_photo_urls?:unknown;external_document_urls?:unknown};
type Message={id:number;visibility:"NETWORK"|"INTERNAL";author_role:"NETWORK"|"CRVO";author_name:string|null;body:string;created_at:string};
type Attachment={id:string;visibility:"NETWORK"|"INTERNAL";kind:string;file_name:string;mime_type:string;size_bytes:number;created_at:string;uploaded_by:string|null};
type Audit={id:number;event_type:string;actor_role:string;actor_name:string|null;details:Record<string,unknown>;created_at:string};
type Detail={claim:Claim;messages:Message[];attachments:Attachment[];audit:Audit[]};
type Staff={employeeKey:string;matricule:string|null;name:string;service:string|null;sectorKey:string|null;sectorLabel:string|null};
type NetworkAccess={id:string;client_scope:string;partner_label:string;dealer_code:string|null;site_code:string;is_active:boolean;expires_at:string|null;created_at:string;last_used_at:string|null;network_type:string;username:string|null;brand:string|null;contact_name:string|null;contact_email:string|null;contact_emails:unknown;production_clients:string[];install_platform:string|null;install_completed_at:string|null;last_login_at:string|null;last_seen_at:string|null};
type ImportBatch={id:string;file_name:string;row_count:number;inserted_count:number;skipped_count:number;error_count:number;created_at:string;imported_by:string|null};
type Monthly={month_key:string;claims:number;accepted:number;cost:number;output:number;complaint_rate:number|null};
type Dashboard={connected:boolean;context:{displayName:string;canConfigure:boolean};period:{from:string;to:string;firstClaimDate:string|null};detail:Detail|null;settings:{site_code:string;sla_analysis_hours:number;sla_decision_hours:number;max_attachments:number;max_attachment_bytes:number};metrics:{total:number;open:number;analysis:number;waitingNetwork:number;committee:number;accepted:number;refused:number;acceptanceRate:number|null;qualityEscapeRate:number|null;averageDecisionDays:number|null;acceptedAmount:number;periodOutput:number;complaintRate:number|null};claims:Claim[];staff:Staff[];clients:Array<{client:string;vehicleCount:number}>;networkAccess:NetworkAccess[];imports:ImportBatch[];analytics:{categories:Array<{category:string;claims:number;accepted:number;cost:number}>;sectors:Array<{sector:string;claims:number;accepted:number;cost:number}>;collaborators:Array<{collaborator:string;responsible_employee_key:string|null;claims:number;accepted:number;interventions:number}>;monthly:Monthly[]};historyQuality:{enrichedEmail:number;enrichedPhotos:number;enrichedDocuments:number}};
type Tab="pilotage"|"claims"|"analysis"|"settings";
type Credentials={username:string;temporaryPassword:string;portalUrl:string;partnerLabel?:string;client?:string};

const statusNames:Record<string,string>={RECEIVED:"Reçue",ANALYSIS:"En analyse",WAITING_NETWORK:"Complément demandé",COMMITTEE:"Comité",ACCEPTED:"Acceptée",REFUSED:"Refusée",CLOSED:"Clôturée"};
const categories=["Mécanique","Carrosserie","Préparation esthétique","Pneus / Jantes","Vitrage","Sellerie","Facturation / Carburant","Autre"];
const statuses=["RECEIVED","ANALYSIS","WAITING_NETWORK","COMMITTEE","ACCEPTED","REFUSED","CLOSED"];
const months=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"];
function pad(v:number){return String(v).padStart(2,"0")}
function monthBounds(value:string){const [y,m]=value.split("-").map(Number);const last=new Date(Date.UTC(y,m,0)).getUTCDate();return{from:`${y}-${pad(m)}-01`,to:`${y}-${pad(m)}-${pad(last)}`}}
function yearBounds(y:number){return{from:`${y}-01-01`,to:`${y}-12-31`}}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
function pct(v:unknown,digits=1){const x=Number(v);return Number.isFinite(x)?`${x.toLocaleString("fr-FR",{minimumFractionDigits:digits,maximumFractionDigits:digits})} %`:"—"}
function money(v:unknown){const x=Number(v);return Number.isFinite(x)?new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(x):"—"}
function dt(v:string|null|undefined){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(d)}
function dshort(v:string|null|undefined){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric",timeZone:"Europe/Paris"}).format(d)}
function normalize(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function jsonUrls(value:unknown){if(Array.isArray(value))return value.map(String).filter(Boolean);if(typeof value==="string"){try{const v=JSON.parse(value);return Array.isArray(v)?v.map(String).filter(Boolean):[]}catch{return value.startsWith("http")?[value]:[]}}return[]}
function emails(value:unknown,primary?:string|null){const arr=Array.isArray(value)?value.map(String):[];if(primary)arr.unshift(primary);return Array.from(new Set(arr.map(x=>x.trim().toLowerCase()).filter(x=>x.includes("@"))))}
function tone(status:string){if(status==="ACCEPTED")return styles.good;if(status==="REFUSED"||status==="CLOSED")return styles.muted;if(status==="WAITING_NETWORK")return styles.warn;if(status==="COMMITTEE")return styles.info;return styles.live}
function monthLabel(key:string){const [y,m]=key.split("-").map(Number);return`${months[m-1]} ${y}`}
async function sha256File(file:File){const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}
function dateIso(v:unknown){if(!v)return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString();if(typeof v==="number"&&v>20000&&v<80000)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString();const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()}
function decisionValue(v:unknown){const s=normalize(String(v??""));if(!s)return null;if(s.includes("non recev")||s.includes("refus")||s.trim()==="non")return"REFUSED";if(s.includes("recev")||s.includes("accept")||s.trim()==="oui")return"ACCEPTED";return null}

export default function QualityClaimsV2({sessionName,canConfigure}:{sessionName:string;canConfigure:boolean}){
  const today=new Date();const currentMonth=`${today.getFullYear()}-${pad(today.getMonth()+1)}`;const initial=monthBounds(currentMonth);
  const[tab,setTab]=useState<Tab>("pilotage"),[data,setData]=useState<Dashboard|null>(null),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const[dateFrom,setDateFrom]=useState(initial.from),[dateTo,setDateTo]=useState(initial.to),[month,setMonth]=useState(currentMonth),[year,setYear]=useState(today.getFullYear()),[search,setSearch]=useState(""),[filterStatus,setFilterStatus]=useState(""),[filterCategory,setFilterCategory]=useState("");
  const[edit,setEdit]=useState<Record<string,unknown>>({}),[message,setMessage]=useState(""),[note,setNote]=useState("");
  const[selectedAccount,setSelectedAccount]=useState<NetworkAccess|null>(null),[accountEmails,setAccountEmails]=useState(""),[accountClients,setAccountClients]=useState(""),[accountName,setAccountName]=useState(""),[accountUsername,setAccountUsername]=useState(""),[credentials,setCredentials]=useState<Credentials|null>(null);
  const[importFile,setImportFile]=useState<File|null>(null),[importRows,setImportRows]=useState<Record<string,unknown>[]>([]),[importStatus,setImportStatus]=useState("");

  async function api<T>(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:"no-store",headers:{"Content-Type":"application/json",...(init?.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.error||"Service indisponible"));return p as T}
  async function refresh(quiet=false){if(!quiet)setLoading(true);try{const q=new URLSearchParams({dateFrom,dateTo});if(search.trim())q.set("search",search.trim());const p=await api<Dashboard>(`/api/quality-claims-v2?${q.toString()}&_=${Date.now()}`);setData(p);setError("")}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.")}finally{if(!quiet)setLoading(false)}}
  async function openClaim(id:string){setLoading(true);try{const q=new URLSearchParams({dateFrom,dateTo,claimId:id});const p=await api<Dashboard>(`/api/quality-claims-v2?${q.toString()}&_=${Date.now()}`);if(p.detail){setDetail(p.detail);hydrate(p.detail.claim);setTab("claims")}}catch(e){setError(e instanceof Error?e.message:"Dossier indisponible.")}finally{setLoading(false)}}
  function hydrate(c:Claim){setEdit({category:c.category,priority:c.priority,status:c.status,sectorLabel:c.sector_label??"",responsibleEmployeeKey:c.responsible_employee_key??"",qualityShouldDetect:c.quality_should_detect==null?"":String(c.quality_should_detect),qualityEmployeeKey:c.quality_employee_key??"",rootCause:c.root_cause??"",correctiveAction:c.corrective_action??"",acceptedAmount:c.accepted_amount??"",committeeResponse:c.committee_response??"",requestedInfo:c.requested_info??""})}
  async function oldPost(action:string,claimId:string,payload:Record<string,unknown>){setSaving(true);try{const p=await api<{detail?:Detail}>("/api/quality-claims",{method:"POST",body:JSON.stringify({action,claimId,payload})});if(p.detail){setDetail(p.detail);hydrate(p.detail.claim)}await refresh(true);return p}catch(e){setError(e instanceof Error?e.message:"Action impossible.");throw e}finally{setSaving(false)}}
  useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(true),60000);return()=>window.clearInterval(t)},[]);

  const filtered=useMemo(()=>{const q=normalize(search.trim());return(data?.claims??[]).filter(c=>(!filterStatus||c.status===filterStatus)&&(!filterCategory||c.category===filterCategory)&&(!q||normalize(`${c.claim_number} ${c.registration} ${c.client_name} ${c.description}`).includes(q)))},[data,search,filterStatus,filterCategory]);
  const qualityStaff=useMemo(()=>data?.staff.filter(s=>normalize(`${s.service??""} ${s.sectorLabel??""}`).includes("qualit"))??[],[data]);
  const periodLabel=useMemo(()=>{const f=new Date(`${dateFrom}T12:00:00`),t=new Date(`${dateTo}T12:00:00`);if(f.getFullYear()===t.getFullYear()&&f.getMonth()===t.getMonth()&&f.getDate()===1&&t.getMonth()!==11&&t.getDate()===new Date(t.getFullYear(),t.getMonth()+1,0).getDate())return`${months[f.getMonth()]} ${f.getFullYear()}`;return`${dshort(dateFrom)} → ${dshort(dateTo)}`},[dateFrom,dateTo]);

  function applyMonth(v:string){setMonth(v);const b=monthBounds(v);setDateFrom(b.from);setDateTo(b.to);setTimeout(()=>void refresh(),0)}
  function applyYear(v:number){setYear(v);const b=yearBounds(v);setDateFrom(b.from);setDateTo(b.to);setTimeout(()=>void refresh(),0)}
  function applyAll(){const from=data?.period.firstClaimDate?.slice(0,10)||"2024-09-01";setDateFrom(from);setDateTo(`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`);setTimeout(()=>void refresh(),0)}
  function previousMonth(){const[y,m]=month.split("-").map(Number);const d=new Date(y,m-2,1);applyMonth(`${d.getFullYear()}-${pad(d.getMonth()+1)}`)}

  async function saveClassification(){if(!detail)return;const responsible=data?.staff.find(s=>s.employeeKey===String(edit.responsibleEmployeeKey??""));const quality=data?.staff.find(s=>s.employeeKey===String(edit.qualityEmployeeKey??""));await oldPost("UPDATE",detail.claim.id,{...edit,responsibleEmployeeName:responsible?.name||detail.claim.responsible_employee_name,sectorKey:responsible?.sectorKey||detail.claim.sector_key,sectorLabel:responsible?.sectorLabel||String(edit.sectorLabel||"")||null,qualityEmployeeName:quality?.name||detail.claim.quality_employee_name,qualityShouldDetect:edit.qualityShouldDetect===""?null:edit.qualityShouldDetect==="true"})}
  async function decide(decision:"ACCEPTED"|"REFUSED"|"NEEDS_INFO"){if(!detail)return;await oldPost("DECIDE",detail.claim.id,{decision,committeeResponse:String(edit.committeeResponse??"")||null,requestedInfo:decision==="NEEDS_INFO"?String(edit.requestedInfo??"")||null:null,acceptedAmount:edit.acceptedAmount||null})}
  async function send(kind:"MESSAGE"|"NOTE"){if(!detail)return;const body=kind==="MESSAGE"?message:note;if(!body.trim())return;await oldPost(kind,detail.claim.id,{body:body.trim()});if(kind==="MESSAGE")setMessage("");else setNote("")}

  function openAccount(a:NetworkAccess){setSelectedAccount(a);setAccountName(a.contact_name||"");setAccountUsername(a.username||"");setAccountEmails(emails(a.contact_emails,a.contact_email).join("\n"));setAccountClients((a.production_clients||[]).join("\n"));setCredentials(null)}
  async function saveAccount(){if(!selectedAccount)return;setSaving(true);try{const list=accountEmails.split(/[\n;,]+/).map(x=>x.trim().toLowerCase()).filter(Boolean);const clients=accountClients.split(/[\n;,]+/).map(x=>x.trim()).filter(Boolean);await api("/api/quality-claims-v2",{method:"POST",body:JSON.stringify({action:"updateNetworkAccess",accessId:selectedAccount.id,payload:{client:selectedAccount.client_scope,partnerLabel:selectedAccount.partner_label,dealerCode:selectedAccount.dealer_code,siteCode:selectedAccount.site_code,networkType:selectedAccount.network_type,username:accountUsername||selectedAccount.username,brand:selectedAccount.brand,contactName:accountName,contactEmail:list[0]||null,contactEmails:list,productionClients:clients,isActive:selectedAccount.is_active}})});await refresh(true);setError("")}catch(e){setError(e instanceof Error?e.message:"Compte non enregistré.")}finally{setSaving(false)}}
  async function regenerate(){if(!selectedAccount)return;setSaving(true);try{const p=await api<Credentials>("/api/quality-claims-v2",{method:"POST",body:JSON.stringify({action:"regenerateNetworkAccess",accessId:selectedAccount.id,partnerLabel:selectedAccount.partner_label,client:selectedAccount.client_scope,username:selectedAccount.username})});setCredentials(p);setAccountUsername(p.username);await refresh(true)}catch(e){setError(e instanceof Error?e.message:"Régénération impossible.")}finally{setSaving(false)}}
  async function toggleAccount(){if(!selectedAccount)return;setSaving(true);try{await api("/api/quality-claims-v2",{method:"POST",body:JSON.stringify({action:"toggleNetworkAccess",accessId:selectedAccount.id,enabled:!selectedAccount.is_active})});setSelectedAccount({...selectedAccount,is_active:!selectedAccount.is_active});await refresh(true)}catch(e){setError(e instanceof Error?e.message:"Modification impossible.")}finally{setSaving(false)}}

  async function parseImport(file:File){setImportFile(file);setImportStatus("Lecture du fichier…");try{const XLSX=await import("@e965/xlsx");const book=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sheet=book.Sheets[book.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:"",raw:true});setImportRows(rows.slice(0,5000));setImportStatus(`${rows.length.toLocaleString("fr-FR")} ligne(s) détectée(s).`)}catch(e){setImportRows([]);setImportStatus(e instanceof Error?e.message:"Fichier illisible.")}}
  async function launchImport(){if(!importFile||!importRows.length)return;setSaving(true);try{const key=(row:Record<string,unknown>,names:string[])=>{const found=Object.keys(row).find(k=>names.some(n=>normalize(k).includes(normalize(n))));return found?row[found]:null};const rows=importRows.map((raw,i)=>{const registration=String(key(raw,["immatriculation","immat","recl","plaque"])??"").trim();const client=String(key(raw,["client","concession","etablissement","réseau","reseau"])??"HISTORIQUE COMITÉ - À RAPPROCHER").trim();const dec=decisionValue(key(raw,["recevable","decision","décision","accord"]));return{client,registration,declaredAt:dateIso(key(raw,["date du comité","date reclamation","date réclamation","date"])),category:String(key(raw,["catégorie","categorie","sujet","type"])??"Autre"),description:String(key(raw,["motif","description","réclamation","reclamation","anomalie"])??"Réclamation externe importée"),decision:dec,status:dec?"CLOSED":"COMMITTEE",acceptedAmount:key(raw,["montant","avoir"]),sectorLabel:String(key(raw,["secteur","service","origine"])??"")||null,responsibleEmployeeName:String(key(raw,["compagnon prod","collaborateur","responsable"])??"")||null,qualityEmployeeName:String(key(raw,["compagnon qualité","compagnon qualite","qualiticien"])??"")||null,sourceExternalId:String(key(raw,["n°or","numero","numéro","id"])??i+2),siteCode:"LENS",raw:{row:i+2,...raw}}}).filter(r=>r.registration);const hash=await sha256File(importFile);const p=await api<{duplicateFile?:boolean;inserted?:number;skipped?:number;errors?:number}>("/api/quality-claims",{method:"POST",body:JSON.stringify({action:"import",fileName:importFile.name,fileSha256:hash,rows,mapping:{mode:"auto-v2"}})});setImportStatus(p.duplicateFile?"Fichier déjà injecté : aucun doublon créé.":`${n(p.inserted)} injectée(s) · ${n(p.skipped)} doublon(s) · ${n(p.errors)} erreur(s)`);await refresh(true)}catch(e){setImportStatus(e instanceof Error?e.message:"Import impossible.")}finally{setSaving(false)}}

  if(loading&&!data)return <main className={styles.page}><div className={styles.loading}>Initialisation du cockpit Qualité…</div></main>;
  return <main className={styles.page}><div className={styles.shell}>
    <header className={styles.hero}><div><a href="/metiers/relation-client">← RELATION CLIENT</a><span>TOOLBOX CRVO LENS · QUALITÉ RÉSEAU</span><h1>Réclamations Qualité</h1><p>Un cockpit unique pour suivre les retours réseau, décider, mesurer les échappements et transformer chaque réclamation en action d’amélioration.</p></div><div className={styles.session}><small>SESSION</small><strong>{sessionName}</strong><em>DONNÉES ACTUALISÉES · 60 S</em></div></header>
    <nav className={styles.tabs}><button className={tab==="pilotage"?styles.active:""} onClick={()=>setTab("pilotage")}>Pilotage</button><button className={tab==="claims"?styles.active:""} onClick={()=>setTab("claims")}>Réclamations</button><button className={tab==="analysis"?styles.active:""} onClick={()=>setTab("analysis")}>Analyse Qualité</button>{canConfigure&&<button className={tab==="settings"?styles.active:""} onClick={()=>setTab("settings")}>Paramètres & accès réseau</button>}</nav>
    {error&&<div className={styles.error}>{error}<button onClick={()=>setError("")}>×</button></div>}
    <section className={styles.period}><div><span>PÉRIODE D’AFFICHAGE</span><strong>{periodLabel}</strong></div><div className={styles.quick}><button onClick={()=>applyMonth(currentMonth)}>CE MOIS</button><button onClick={previousMonth}>MOIS PRÉCÉDENT</button><button onClick={()=>applyYear(today.getFullYear())}>ANNÉE {today.getFullYear()}</button><button onClick={applyAll}>TOUT L’HISTORIQUE</button></div><label>Mois<input type="month" value={month} onChange={e=>applyMonth(e.target.value)}/></label><label>Année<select value={year} onChange={e=>applyYear(Number(e.target.value))}>{[2024,2025,2026,2027].map(y=><option key={y}>{y}</option>)}</select></label><label>Du<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>Au<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><button className={styles.apply} onClick={()=>void refresh()}>APPLIQUER</button></section>

    {tab==="pilotage"&&data&&<><section className={styles.kpis}><article className={styles.primaryKpi}><span>TAUX DE RÉCLAMATION</span><strong>{pct(data.metrics.complaintRate,2)}</strong><small>{data.metrics.accepted} réclamation(s) approuvée(s) / {n(data.metrics.periodOutput).toLocaleString("fr-FR")} VO reconditionné(s)</small></article><article><span>RÉCLAMATIONS</span><strong>{data.metrics.total}</strong><small>{data.metrics.open} dossier(s) encore ouvert(s)</small></article><article><span>TAUX RECEVABLE</span><strong>{pct(data.metrics.acceptanceRate)}</strong><small>{data.metrics.accepted} acceptée(s) · {data.metrics.refused} refusée(s)</small></article><article><span>ÉCHAPPEMENT QUALITÉ</span><strong>{pct(data.metrics.qualityEscapeRate)}</strong><small>acceptées qui auraient dû être détectées</small></article><article><span>COÛT QUALITÉ</span><strong>{money(data.metrics.acceptedAmount)}</strong><small>avoirs / prises en charge approuvés</small></article><article><span>DÉLAI DÉCISION</span><strong>{data.metrics.averageDecisionDays==null?"—":`${n(data.metrics.averageDecisionDays).toLocaleString("fr-FR",{maximumFractionDigits:1})} j`}</strong><small>de la déclaration à la décision</small></article></section>
      <section className={styles.grid2}><div className={styles.card}><div className={styles.cardHead}><div><span>À TRAITER</span><h2>File Qualité</h2></div><button onClick={()=>setTab("claims")}>VOIR TOUT</button></div><div className={styles.queue}>{data.claims.filter(c=>!["CLOSED","REFUSED"].includes(c.status)).slice(0,10).map(c=><button key={c.id} onClick={()=>void openClaim(c.id)}><div><strong>{c.registration}</strong><span>{c.client_name}</span><small>{c.category} · {dshort(c.declared_at)}</small></div><em className={`${styles.badge} ${tone(c.status)}`}>{statusNames[c.status]||c.status}</em></button>)}{!data.metrics.open&&<p className={styles.empty}>Aucune réclamation ouverte sur cette période.</p>}</div></div><div className={styles.card}><div className={styles.cardHead}><div><span>PARETO</span><h2>Origines des réclamations</h2></div><button onClick={()=>setTab("analysis")}>ANALYSER</button></div><div className={styles.pareto}>{data.analytics.categories.slice(0,8).map((x,i)=><div key={x.category}><b>{i+1}</b><div><strong>{x.category}</strong><small>{x.accepted} approuvée(s) · {money(x.cost)}</small></div><em>{x.claims}</em></div>)}</div></div></section></>}

    {tab==="claims"&&data&&<section className={styles.claimLayout}><div className={styles.card}><div className={styles.cardHead}><div><span>DOSSIERS</span><h2>{filtered.length} réclamation(s)</h2></div></div><div className={styles.filters}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void refresh()}} placeholder="Immatriculation, dossier, client…"/><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">Tous les statuts</option>{statuses.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select><select value={filterCategory} onChange={e=>setFilterCategory(e.target.value)}><option value="">Toutes catégories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>void refresh()}>RECHERCHER</button></div><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Dossier</th><th>Client / VO</th><th>Catégorie</th><th>Décision</th><th>Montant</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className={detail?.claim.id===c.id?styles.selected:""} onClick={()=>void openClaim(c.id)}><td>{dshort(c.declared_at)}</td><td><strong>{c.claim_number}</strong></td><td><b>{c.registration}</b><small>{c.client_name}</small></td><td>{c.category}</td><td><em className={`${styles.badge} ${tone(c.status)}`}>{statusNames[c.status]||c.status}</em></td><td>{money(c.accepted_amount)}</td></tr>)}</tbody></table></div></div>
      <div className={styles.detail}>{detail?<><div className={styles.detailHero}><div><span>{detail.claim.claim_number}</span><h2>{detail.claim.registration}</h2><p>{detail.claim.client_name} · {dt(detail.claim.declared_at)}</p></div><em className={`${styles.badge} ${tone(detail.claim.status)}`}>{statusNames[detail.claim.status]||detail.claim.status}</em></div><div className={styles.vehicle}><div><span>OR</span><strong>{detail.claim.work_order||"—"}</strong></div><div><span>VIN</span><strong>{detail.claim.vin||"—"}</strong></div><div><span>Modèle</span><strong>{detail.claim.model||"—"}</strong></div><div><span>Kilométrage</span><strong>{detail.claim.mileage?`${n(detail.claim.mileage).toLocaleString("fr-FR")} km`:"—"}</strong></div></div><div className={styles.claimText}><span>RÉCLAMATION</span><p>{detail.claim.description}</p>{detail.claim.network_contact_email&&<small>{detail.claim.network_contact_email}{detail.claim.network_contact_phone?` · ${detail.claim.network_contact_phone}`:""}</small>}</div>
      {(jsonUrls(detail.claim.external_photo_urls).length>0||jsonUrls(detail.claim.external_document_urls).length>0||detail.attachments.length>0)&&<div className={styles.section}><h3>Photos & documents</h3><div className={styles.files}>{jsonUrls(detail.claim.external_photo_urls).map((u,i)=><a key={`p${i}`} href={u} target="_blank" rel="noreferrer">PHOTO {i+1}</a>)}{jsonUrls(detail.claim.external_document_urls).map((u,i)=><a key={`d${i}`} href={u} target="_blank" rel="noreferrer">DOCUMENT {i+1}</a>)}{detail.attachments.map(a=><a key={a.id} href={`/api/quality-claims?attachmentId=${encodeURIComponent(a.id)}`} target="_blank">{a.kind} · {a.file_name}</a>)}</div></div>}
      <div className={styles.section}><h3>Qualification CRVO</h3><div className={styles.formGrid}><label>Catégorie<select value={String(edit.category??"")} onChange={e=>setEdit({...edit,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Statut<select value={String(edit.status??"")} onChange={e=>setEdit({...edit,status:e.target.value})}>{statuses.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select></label><label>Compagnon<select value={String(edit.responsibleEmployeeKey??"")} onChange={e=>setEdit({...edit,responsibleEmployeeKey:e.target.value})}><option value="">Non attribué</option>{data.staff.map(s=><option key={s.employeeKey} value={s.employeeKey}>{s.name} · {s.sectorLabel||s.service||""}</option>)}</select></label><label>Qualité devait détecter ?<select value={String(edit.qualityShouldDetect??"")} onChange={e=>setEdit({...edit,qualityShouldDetect:e.target.value})}><option value="">À qualifier</option><option value="true">Oui</option><option value="false">Non</option></select></label><label>Contrôleur Qualité<select value={String(edit.qualityEmployeeKey??"")} onChange={e=>setEdit({...edit,qualityEmployeeKey:e.target.value})}><option value="">Non attribué</option>{qualityStaff.map(s=><option key={s.employeeKey} value={s.employeeKey}>{s.name}</option>)}</select></label><label>Montant accordé (€)<input type="number" step="0.01" value={String(edit.acceptedAmount??"")} onChange={e=>setEdit({...edit,acceptedAmount:e.target.value})}/></label></div><label className={styles.full}>Cause racine<textarea value={String(edit.rootCause??"")} onChange={e=>setEdit({...edit,rootCause:e.target.value})}/></label><label className={styles.full}>Action corrective<textarea value={String(edit.correctiveAction??"")} onChange={e=>setEdit({...edit,correctiveAction:e.target.value})}/></label><button className={styles.primaryButton} disabled={saving} onClick={()=>void saveClassification()}>ENREGISTRER LA QUALIFICATION</button></div>
      <div className={styles.section}><h3>Décision comité</h3><label className={styles.full}>Réponse<textarea value={String(edit.committeeResponse??"")} onChange={e=>setEdit({...edit,committeeResponse:e.target.value})}/></label><label className={styles.full}>Complément demandé<textarea value={String(edit.requestedInfo??"")} onChange={e=>setEdit({...edit,requestedInfo:e.target.value})}/></label><div className={styles.decisions}><button disabled={saving} onClick={()=>void decide("ACCEPTED")}>ACCEPTER</button><button disabled={saving} onClick={()=>void decide("NEEDS_INFO")}>DEMANDER UN COMPLÉMENT</button><button disabled={saving} onClick={()=>void decide("REFUSED")}>REFUSER</button></div></div>
      <div className={styles.section}><h3>Échanges</h3><div className={styles.chat}>{detail.messages.map(m=><div key={m.id} className={m.visibility==="INTERNAL"?styles.internal:m.author_role==="CRVO"?styles.crvo:styles.network}><strong>{m.visibility==="INTERNAL"?"NOTE INTERNE":m.author_name||m.author_role}</strong><p>{m.body}</p><small>{dt(m.created_at)}</small></div>)}</div><div className={styles.compose}><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Réponse visible par le réseau…"/><button disabled={saving||!message.trim()} onClick={()=>void send("MESSAGE")}>ENVOYER</button></div><div className={styles.compose}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Note interne CRVO…"/><button disabled={saving||!note.trim()} onClick={()=>void send("NOTE")}>AJOUTER</button></div></div></>:<div className={styles.detailEmpty}><b>RQ</b><h3>Ouvrez un dossier</h3><p>La fiche complète, les preuves, la décision comité et les échanges apparaîtront ici.</p></div>}</div></section>}

    {tab==="analysis"&&data&&<><section className={styles.grid2}><div className={styles.card}><div className={styles.cardHead}><div><span>ÉVOLUTION</span><h2>Taux de réclamation par mois</h2></div></div><div className={styles.monthly}>{data.analytics.monthly.map(x=><div key={x.month_key}><div><strong>{monthLabel(x.month_key)}</strong><small>{x.accepted} approuvée(s) / {n(x.output).toLocaleString("fr-FR")} sorties</small></div><b>{pct(x.complaint_rate,2)}</b></div>)}</div></div><div className={styles.card}><div className={styles.cardHead}><div><span>SECTEURS</span><h2>Pareto origine</h2></div></div><div className={styles.pareto}>{data.analytics.sectors.slice(0,12).map((x,i)=><div key={x.sector}><b>{i+1}</b><div><strong>{x.sector}</strong><small>{x.accepted} approuvée(s) · {money(x.cost)}</small></div><em>{x.claims}</em></div>)}</div></div></section><section className={styles.card}><div className={styles.cardHead}><div><span>COLLABORATEURS</span><h2>Réclamations rapportées à l’activité</h2></div><p>Le volume brut est affiché avec le nombre d’interventions de la période pour éviter de pénaliser mécaniquement les collaborateurs les plus actifs.</p></div><div className={styles.tableWrap}><table><thead><tr><th>Collaborateur</th><th>Réclamations</th><th>Approuvées</th><th>Interventions</th><th>Taux / interventions</th></tr></thead><tbody>{data.analytics.collaborators.slice(0,40).map(x=><tr key={`${x.collaborator}-${x.responsible_employee_key}`}><td><strong>{x.collaborator}</strong></td><td>{x.claims}</td><td>{x.accepted}</td><td>{x.interventions}</td><td>{x.interventions?pct(100*x.accepted/x.interventions,2):"—"}</td></tr>)}</tbody></table></div></section></>}

    {tab==="settings"&&canConfigure&&data&&<><section className={styles.grid2}><div className={styles.card}><div className={styles.cardHead}><div><span>ACCÈS RÉSEAU</span><h2>{data.networkAccess.length} comptes concession</h2></div><p>Chaque compte est isolé par périmètre réseau. Ouvrez une fiche pour gérer plusieurs e-mails et régénérer ses accès.</p></div><div className={styles.accountSearch}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher concession, code, identifiant…"/></div><div className={styles.accounts}>{data.networkAccess.filter(a=>!search.trim()||normalize(`${a.partner_label} ${a.client_scope} ${a.dealer_code||""} ${a.username||""}`).includes(normalize(search))).map(a=><button key={a.id} onClick={()=>openAccount(a)}><div><strong>{a.partner_label}</strong><span>{a.network_type} · {a.dealer_code||a.client_scope}</span><small>{emails(a.contact_emails,a.contact_email).join(" · ")||"Aucun e-mail"}</small></div><em className={a.is_active?styles.good:styles.muted}>{a.is_active?"ACTIF":"INACTIF"}</em></button>)}</div></div><div className={styles.card}><div className={styles.cardHead}><div><span>HISTORIQUE</span><h2>Qualité des données injectées</h2></div></div><div className={styles.dataQuality}><article><strong>{data.metrics.total}</strong><span>réclamations sur la période</span></article><article><strong>{data.historyQuality.enrichedEmail}</strong><span>fiches enrichies avec e-mail</span></article><article><strong>{data.historyQuality.enrichedPhotos}</strong><span>fiches avec photos externes</span></article><article><strong>{data.historyQuality.enrichedDocuments}</strong><span>fiches avec documents externes</span></article></div><div className={styles.importBox}><h3>Injecter un fichier Excel externe</h3><p>Le moteur détecte automatiquement les colonnes usuelles : immatriculation, date, client/concession, décision, montant, secteur et collaborateurs. Les doublons sont neutralisés par empreinte.</p><label>CHOISIR UN XLS / XLSX<input type="file" accept=".xlsx,.xls" onChange={e=>{const f=e.target.files?.[0];if(f)void parseImport(f)}}/></label>{importStatus&&<small>{importStatus}</small>}<button disabled={saving||!importRows.length} onClick={()=>void launchImport()}>INJECTER {importRows.length?`${importRows.length} LIGNES`:"LE FICHIER"}</button></div><div className={styles.importHistory}>{data.imports.slice(0,8).map(b=><div key={b.id}><strong>{b.file_name}</strong><span>{b.inserted_count} injectée(s) · {b.skipped_count} doublon(s)</span><small>{dt(b.created_at)}</small></div>)}</div></div></section></>}

    {selectedAccount&&<div className={styles.modalBackdrop} onMouseDown={e=>{if(e.currentTarget===e.target)setSelectedAccount(null)}}><aside className={styles.modal}><div className={styles.modalHead}><div><span>FICHE UTILISATEUR RÉSEAU</span><h2>{selectedAccount.partner_label}</h2><p>{selectedAccount.network_type} · {selectedAccount.dealer_code||selectedAccount.client_scope}</p></div><button onClick={()=>setSelectedAccount(null)}>×</button></div><div className={styles.accountState}><span className={selectedAccount.is_active?styles.good:styles.muted}>{selectedAccount.is_active?"COMPTE ACTIF":"COMPTE SUSPENDU"}</span><small>Dernière connexion : {dt(selectedAccount.last_login_at||selectedAccount.last_used_at)}</small></div><div className={styles.formGrid}><label>Nom du contact<input value={accountName} onChange={e=>setAccountName(e.target.value)}/></label><label>Identifiant actuel<input value={accountUsername} onChange={e=>setAccountUsername(e.target.value)}/></label></div><label className={styles.full}>Adresses e-mail associées <small>une par ligne</small><textarea value={accountEmails} onChange={e=>setAccountEmails(e.target.value)} placeholder="direction@...\nchefdesventes@...\nsecretariat@..."/></label><label className={styles.full}>Périmètres / clients de production <small>un par ligne</small><textarea value={accountClients} onChange={e=>setAccountClients(e.target.value)}/></label><div className={styles.accountActions}><button onClick={()=>void saveAccount()} disabled={saving}>ENREGISTRER LA FICHE</button><button className={styles.secondary} onClick={()=>void toggleAccount()} disabled={saving}>{selectedAccount.is_active?"SUSPENDRE":"RÉACTIVER"}</button></div><div className={styles.regenerate}><span>ACCÈS & QR CODE</span><h3>Régénérer complètement l’accès</h3><p>Cette action invalide immédiatement l’ancien QR, génère un nouvel identifiant et un nouveau mot de passe temporaire.</p><button disabled={saving} onClick={()=>void regenerate()}>RÉGÉNÉRER QR + IDENTIFIANT + MOT DE PASSE</button></div>{credentials&&<div className={styles.credentials}><div className={styles.qr}><QrCode value={credentials.portalUrl}/></div><div><span>NOUVEAUX ACCÈS</span><label>Identifiant<strong>{credentials.username}</strong><button onClick={()=>navigator.clipboard.writeText(credentials.username)}>COPIER</button></label><label>Mot de passe temporaire<strong>{credentials.temporaryPassword}</strong><button onClick={()=>navigator.clipboard.writeText(credentials.temporaryPassword)}>COPIER</button></label><label>Lien QR<strong className={styles.url}>{credentials.portalUrl}</strong><button onClick={()=>navigator.clipboard.writeText(credentials.portalUrl)}>COPIER</button></label><small>Le mot de passe n’est plus récupérable après fermeture de cette fiche. Le QR ci-contre est généré localement dans le navigateur : l’URL d’accès n’est envoyée à aucun service QR externe.</small></div></div>}</aside></div>}
  </div></main>;
}
