"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./quality-claims.module.css";

type Claim = {
  id:string;claim_number:string;site_code:string;source:string;client_name:string;partner_label:string|null;dealer_code:string|null;
  registration:string;work_order:string|null;vin:string|null;model:string|null;mileage:number|null;category:string;subcategory:string|null;
  description:string;priority:string;status:string;decision:string|null;committee_response:string|null;requested_info:string|null;
  estimate_amount:number|null;accepted_amount:number|null;sector_key:string|null;sector_label:string|null;
  responsible_employee_key:string|null;responsible_employee_name:string|null;quality_should_detect:boolean|null;quality_employee_key:string|null;quality_employee_name:string|null;
  root_cause:string|null;corrective_action:string|null;recurrence_key:string|null;declared_at:string;decision_at:string|null;closed_at:string|null;updated_at:string;
};
type Message={id:number;visibility:"NETWORK"|"INTERNAL";author_role:"NETWORK"|"CRVO";author_name:string|null;body:string;created_at:string};
type Attachment={id:string;visibility:"NETWORK"|"INTERNAL";kind:string;file_name:string;mime_type:string;size_bytes:number;created_at:string;uploaded_by:string|null};
type Audit={id:number;event_type:string;actor_role:string;actor_name:string|null;details:Record<string,unknown>;created_at:string};
type Detail={claim:Claim;messages:Message[];attachments:Attachment[];audit:Audit[]};
type Staff={employeeKey:string;matricule:string|null;name:string;service:string|null;sectorKey:string|null;sectorLabel:string|null};
type Client={client:string;vehicleCount:number};
type NetworkAccess={id:string;client_scope:string;partner_label:string;dealer_code:string|null;site_code:string;is_active:boolean;expires_at:string|null;created_at:string;last_used_at:string|null};
type ImportBatch={id:string;file_name:string;row_count:number;inserted_count:number;skipped_count:number;error_count:number;created_at:string;imported_by:string|null};
type Dashboard={
  connected:boolean;context:{displayName:string;canConfigure:boolean};detail:Detail|null;
  settings:{site_code:string;sla_analysis_hours:number;sla_decision_hours:number;max_attachments:number;max_attachment_bytes:number};
  metrics:{total:number;open:number;analysis:number;waitingNetwork:number;committee:number;accepted:number;refused:number;acceptanceRate:number|null;qualityEscapeRate:number|null;averageDecisionDays:number|null;acceptedAmount:number;siteOutput365:number;claimsPer1000Output365:number|null};
  claims:Claim[];staff:Staff[];clients:Client[];networkAccess:NetworkAccess[];imports:ImportBatch[];
  analytics:{categories:Array<{category:string;claims:number;accepted:number;cost:number}>;sectors:Array<{sector:string;claims:number;accepted:number;cost:number}>;collaborators:Array<{collaborator:string;responsible_employee_key:string|null;claims:number;accepted:number;interventions365:number}>;monthly:Array<{month_key:string;claims:number;accepted:number;cost:number}>};
};
type Tab="pilotage"|"claims"|"analysis"|"settings";
type ImportField="client"|"registration"|"declaredAt"|"category"|"description"|"decision"|"acceptedAmount"|"sectorLabel"|"responsibleEmployeeName"|"qualityEmployeeName"|"sourceExternalId";

type ImportRow=Record<string,unknown>;

const categories=["Mécanique","Carrosserie","Préparation esthétique","Pneus / Jantes","Vitrage","Sellerie","Facturation / Carburant","Autre"];
const statuses=["RECEIVED","ANALYSIS","WAITING_NETWORK","COMMITTEE","ACCEPTED","REFUSED","CLOSED"];
const statusNames:Record<string,string>={RECEIVED:"Reçue",ANALYSIS:"En analyse",WAITING_NETWORK:"Complément demandé",COMMITTEE:"Comité",ACCEPTED:"Acceptée",REFUSED:"Refusée",CLOSED:"Clôturée"};
const priorities=["BASSE","NORMAL","HAUTE","CRITIQUE"];
const fieldLabels:Record<ImportField,string>={client:"Client / concession",registration:"Immatriculation",declaredAt:"Date réclamation",category:"Catégorie",description:"Description",decision:"Recevabilité / décision",acceptedAmount:"Montant / avoir",sectorLabel:"Secteur",responsibleEmployeeName:"Compagnon",qualityEmployeeName:"Qualiticien",sourceExternalId:"N° historique"};
const aliases:Record<ImportField,string[]>={
  client:["client","concession","nom client","site client","etablissement","réseau","reseau"],registration:["immatriculation","immat","registration","plaque"],declaredAt:["date","date reclamation","date réclamation","date de reclamation","date de réclamation","date demande"],category:["categorie","catégorie","type","nature","motif"],description:["description","commentaire","reclamation","réclamation","anomalie","detail","détail"],decision:["recevable","recevabilite","recevabilité","decision","décision","accord"],acceptedAmount:["montant","montant avoir","avoir","cout","coût","prise en charge"],sectorLabel:["secteur","service","origine","secteur origine"],responsibleEmployeeName:["compagnon","collaborateur","responsable","operateur","opérateur"],qualityEmployeeName:["qualiticien","controleur qualite","contrôleur qualité","qualite","qualité"],sourceExternalId:["numero","numéro","n°","id","numero reclamation","numéro réclamation"]
};

function n(value:unknown){const x=Number(value);return Number.isFinite(x)?x:0;}
function money(value:unknown){const x=Number(value);return Number.isFinite(x)?new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(x):"—";}
function dt(value:string|null|undefined){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(d);}
function pct(value:unknown){const x=Number(value);return Number.isFinite(x)?`${x.toLocaleString("fr-FR",{maximumFractionDigits:1})} %`:"—";}
function normalizeKey(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function boolValue(value:unknown){const s=normalizeKey(String(value??""));if(["oui","yes","true","1","vrai"].includes(s))return true;if(["non","no","false","0","faux"].includes(s))return false;return null;}
function decisionValue(value:unknown){const s=normalizeKey(String(value??""));if(!s)return null;if(s.includes("non recev")||s.includes("refus")||s==="non")return"REFUSED";if(s.includes("recev")||s.includes("accept")||s==="oui")return"ACCEPTED";return null;}
function numericValue(value:unknown){if(value==null||value==="")return null;const x=Number(String(value).replace(/\s/g,"").replace(",","."));return Number.isFinite(x)?x:null;}
function dateIso(value:unknown){if(!value)return null;if(value instanceof Date&&!Number.isNaN(value.getTime()))return value.toISOString();if(typeof value==="number"&&value>20000&&value<80000){const d=new Date(Date.UTC(1899,11,30)+value*86400000);return d.toISOString();}const s=String(value).trim();const fr=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/);if(fr){const y=Number(fr[3])<100?2000+Number(fr[3]):Number(fr[3]);return new Date(Date.UTC(y,Number(fr[2])-1,Number(fr[1]),12)).toISOString();}const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString();}
async function fileBase64(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const text=String(reader.result??"");resolve(text.includes(",")?text.slice(text.indexOf(",")+1):text);};reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
async function sha256File(file:File){const data=await file.arrayBuffer();const digest=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");}
function claimTone(status:string){if(status==="ACCEPTED")return styles.good;if(status==="REFUSED"||status==="CLOSED")return styles.muted;if(status==="WAITING_NETWORK")return styles.warn;if(status==="COMMITTEE")return styles.info;return styles.live;}

export default function QualityClaimsWorkspace({sessionName,canConfigure}:{sessionName:string;canConfigure:boolean}){
  const [tab,setTab]=useState<Tab>("pilotage");
  const [data,setData]=useState<Dashboard|null>(null);
  const [detail,setDetail]=useState<Detail|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [search,setSearch]=useState("");
  const [filterStatus,setFilterStatus]=useState("");
  const [filterCategory,setFilterCategory]=useState("");
  const [saving,setSaving]=useState(false);
  const [edit,setEdit]=useState<Record<string,unknown>>({});
  const [message,setMessage]=useState("");
  const [note,setNote]=useState("");
  const [committeeResponse,setCommitteeResponse]=useState("");
  const [requestedInfo,setRequestedInfo]=useState("");
  const [newClaim,setNewClaim]=useState({client:"",registration:"",category:"Mécanique",description:""});
  const [showCreate,setShowCreate]=useState(false);
  const [networkForm,setNetworkForm]=useState({client:"",partnerLabel:"",dealerCode:"",expiresAt:""});
  const [newPortalUrl,setNewPortalUrl]=useState("");
  const [settingsForm,setSettingsForm]=useState({slaAnalysisHours:24,slaDecisionHours:120,maxAttachments:8,maxAttachmentBytes:6291456});
  const [importFile,setImportFile]=useState<File|null>(null);
  const [importRows,setImportRows]=useState<ImportRow[]>([]);
  const [importHeaders,setImportHeaders]=useState<string[]>([]);
  const [importMapping,setImportMapping]=useState<Record<ImportField,string>>({client:"",registration:"",declaredAt:"",category:"",description:"",decision:"",acceptedAmount:"",sectorLabel:"",responsibleEmployeeName:"",qualityEmployeeName:"",sourceExternalId:""});
  const [importResult,setImportResult]=useState("");

  async function api<T>(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:"no-store",headers:{"Content-Type":"application/json",...(init?.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.error||"Donnée indisponible"));return p as T;}
  async function refresh(quiet=false){if(!quiet)setLoading(true);try{const p=await api<Dashboard>(`/api/quality-claims?search=${encodeURIComponent(search.trim())}&_=${Date.now()}`);setData(p);setError("");if(!quiet&&p.settings)setSettingsForm({slaAnalysisHours:n(p.settings.sla_analysis_hours)||24,slaDecisionHours:n(p.settings.sla_decision_hours)||120,maxAttachments:n(p.settings.max_attachments)||8,maxAttachmentBytes:n(p.settings.max_attachment_bytes)||6291456});}catch(e){setError(e instanceof Error?e.message:"Réclamations Qualité indisponibles.");}finally{if(!quiet)setLoading(false);}}
  async function openClaim(id:string){setLoading(true);try{const p=await api<Dashboard>(`/api/quality-claims?claimId=${encodeURIComponent(id)}&_=${Date.now()}`);if(p.detail){setDetail(p.detail);hydrateEdit(p.detail.claim);setTab("claims");}}catch(e){setError(e instanceof Error?e.message:"Dossier indisponible.");}finally{setLoading(false);}}
  function hydrateEdit(c:Claim){setEdit({category:c.category,subcategory:c.subcategory??"",priority:c.priority,status:c.status,sectorKey:c.sector_key??"",sectorLabel:c.sector_label??"",responsibleEmployeeKey:c.responsible_employee_key??"",responsibleEmployeeName:c.responsible_employee_name??"",qualityShouldDetect:c.quality_should_detect==null?"":String(c.quality_should_detect),qualityEmployeeKey:c.quality_employee_key??"",qualityEmployeeName:c.quality_employee_name??"",rootCause:c.root_cause??"",correctiveAction:c.corrective_action??"",recurrenceKey:c.recurrence_key??"",estimateAmount:c.estimate_amount??"",acceptedAmount:c.accepted_amount??"",committeeResponse:c.committee_response??"",requestedInfo:c.requested_info??""});setCommitteeResponse(c.committee_response??"");setRequestedInfo(c.requested_info??"");}
  async function post(action:string,claimId?:string|null,payload?:Record<string,unknown>){setSaving(true);try{const p=await api<{detail?:Detail}>("/api/quality-claims",{method:"POST",body:JSON.stringify({action,claimId,payload})});if(p.detail){setDetail(p.detail);hydrateEdit(p.detail.claim);}await refresh(true);setError("");return p;}catch(e){setError(e instanceof Error?e.message:"Action impossible.");throw e;}finally{setSaving(false);}}

  useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(true),60000);return()=>window.clearInterval(t);},[]);
  useEffect(()=>{if(!data)return;setSettingsForm({slaAnalysisHours:n(data.settings.sla_analysis_hours)||24,slaDecisionHours:n(data.settings.sla_decision_hours)||120,maxAttachments:n(data.settings.max_attachments)||8,maxAttachmentBytes:n(data.settings.max_attachment_bytes)||6291456});},[data?.settings?.updated_at]);

  const filtered=useMemo(()=>{const q=normalizeKey(search);return (data?.claims??[]).filter(c=>(!filterStatus||c.status===filterStatus)&&(!filterCategory||c.category===filterCategory)&&(!q||normalizeKey(`${c.claim_number} ${c.registration} ${c.client_name} ${c.description}`).includes(q)));},[data,search,filterStatus,filterCategory]);
  const qualityStaff=useMemo(()=>data?.staff.filter(s=>normalizeKey(`${s.service??""} ${s.sectorLabel??""}`).includes("qualit"))??[],[data]);

  async function saveClassification(){if(!detail)return;const staff=data?.staff.find(s=>s.employeeKey===String(edit.responsibleEmployeeKey??""));const quality=data?.staff.find(s=>s.employeeKey===String(edit.qualityEmployeeKey??""));await post("UPDATE",detail.claim.id,{...edit,responsibleEmployeeName:staff?.name||String(edit.responsibleEmployeeName??"")||null,sectorKey:staff?.sectorKey||String(edit.sectorKey??"")||null,sectorLabel:staff?.sectorLabel||String(edit.sectorLabel??"")||null,qualityEmployeeName:quality?.name||String(edit.qualityEmployeeName??"")||null,qualityShouldDetect:edit.qualityShouldDetect===""?null:edit.qualityShouldDetect==="true"});}
  async function decide(decision:"ACCEPTED"|"REFUSED"|"NEEDS_INFO"){if(!detail)return;await post("DECIDE",detail.claim.id,{decision,committeeResponse:committeeResponse.trim()||null,requestedInfo:decision==="NEEDS_INFO"?requestedInfo.trim()||null:null,acceptedAmount:edit.acceptedAmount||null});}
  async function sendText(kind:"MESSAGE"|"NOTE"){if(!detail)return;const body=kind==="MESSAGE"?message:note;if(!body.trim())return;await post(kind,detail.claim.id,{body});if(kind==="MESSAGE")setMessage("");else setNote("");}
  async function uploadAttachments(files:FileList|null,visibility:"NETWORK"|"INTERNAL"="NETWORK"){if(!detail||!files?.length)return;setSaving(true);try{for(const file of Array.from(files)){if(file.size>6291456)throw new Error(`${file.name} dépasse 6 Mo.`);const fileData=await fileBase64(file);await api("/api/quality-claims",{method:"POST",body:JSON.stringify({action:"attachment",claimId:detail.claim.id,attachment:{visibility,kind:file.type.startsWith("image/")?"PHOTO":file.type==="application/pdf"?"QUOTE":"OTHER",fileName:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,fileData}})});}await openClaim(detail.claim.id);}catch(e){setError(e instanceof Error?e.message:"Téléversement impossible.");}finally{setSaving(false);}}
  async function createInternalClaim(){if(!newClaim.client||!newClaim.registration||!newClaim.description.trim())return;const p=await post("CREATE",null,newClaim);setShowCreate(false);setNewClaim({client:"",registration:"",category:"Mécanique",description:""});if(p.detail)await openClaim(p.detail.claim.id);}

  async function createNetworkAccess(){setSaving(true);try{const p=await api<{portalUrl:string}>("/api/quality-claims",{method:"POST",body:JSON.stringify({action:"createNetworkAccess",payload:{...networkForm,siteCode:"LENS",expiresAt:networkForm.expiresAt||null}})});setNewPortalUrl(p.portalUrl);await refresh(true);}catch(e){setError(e instanceof Error?e.message:"Création d’accès impossible.");}finally{setSaving(false);}}
  async function toggleNetworkAccess(id:string,enabled:boolean){setSaving(true);try{await api("/api/quality-claims",{method:"POST",body:JSON.stringify({action:"toggleNetworkAccess",accessId:id,enabled})});await refresh(true);}catch(e){setError(e instanceof Error?e.message:"Modification impossible.");}finally{setSaving(false);}}
  async function saveSettings(){setSaving(true);try{await api("/api/quality-claims",{method:"POST",body:JSON.stringify({action:"settings",payload:{siteCode:"LENS",...settingsForm}})});await refresh(true);}catch(e){setError(e instanceof Error?e.message:"Paramétrage impossible.");}finally{setSaving(false);}}

  function autoMapping(headers:string[]){const normalized=headers.map(h=>[h,normalizeKey(h)] as const);const next={...importMapping};(Object.keys(aliases) as ImportField[]).forEach(field=>{const found=normalized.find(([,norm])=>aliases[field].some(a=>norm===normalizeKey(a)||norm.includes(normalizeKey(a))));next[field]=found?.[0]??"";});return next;}
  async function parseImport(file:File){setImportResult("");setImportFile(file);try{const XLSX=await import("@e965/xlsx");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<ImportRow>(sheet,{defval:"",raw:true});if(!rows.length)throw new Error("Aucune ligne détectée dans le fichier.");const headers=Array.from(new Set(rows.flatMap(row=>Object.keys(row))));setImportRows(rows.slice(0,5000));setImportHeaders(headers);setImportMapping(autoMapping(headers));}catch(e){setImportRows([]);setImportHeaders([]);setImportResult(e instanceof Error?e.message:"Lecture du fichier impossible.");}}
  async function launchImport(){if(!importFile||!importRows.length)return;if(!importMapping.client||!importMapping.registration){setImportResult("Associe au minimum Client / concession et Immatriculation.");return;}setSaving(true);setImportResult("");try{const rows=importRows.map((raw,index)=>{const get=(field:ImportField)=>importMapping[field]?raw[importMapping[field]]:null;const decision=decisionValue(get("decision"));return{client:String(get("client")??"").trim(),registration:String(get("registration")??"").trim(),declaredAt:dateIso(get("declaredAt")),category:String(get("category")??"").trim()||"Autre",description:String(get("description")??"").trim()||"Réclamation historique importée",decision,status:"CLOSED",acceptedAmount:numericValue(get("acceptedAmount")),sectorLabel:String(get("sectorLabel")??"").trim()||null,responsibleEmployeeName:String(get("responsibleEmployeeName")??"").trim()||null,qualityEmployeeName:String(get("qualityEmployeeName")??"").trim()||null,sourceExternalId:String(get("sourceExternalId")??"").trim()||null,siteCode:"LENS",raw:{row:index+2,...raw}};});const hash=await sha256File(importFile);const p=await api<{duplicateFile?:boolean;inserted?:number;skipped?:number;errors?:number}>("/api/quality-claims",{method:"POST",body:JSON.stringify({action:"import",fileName:importFile.name,fileSha256:hash,rows,mapping:importMapping})});setImportResult(p.duplicateFile?"Ce fichier a déjà été injecté : aucun doublon créé.":`${n(p.inserted)} réclamation(s) injectée(s), ${n(p.skipped)} doublon(s) ignoré(s), ${n(p.errors)} erreur(s).`);await refresh(true);}catch(e){setImportResult(e instanceof Error?e.message:"Import impossible.");}finally{setSaving(false);}}

  if(loading&&!data)return <main className={styles.page}><div className={styles.loading}>Initialisation du cockpit Qualité…</div></main>;

  return <main className={styles.page}>
    <div className={styles.shell}>
      <header className={styles.hero}><div><a href="/metiers/relation-client" className={styles.back}>← RELATION CLIENT</a><span className={styles.eyebrow}>TOOLBOX CRVO LENS · AMÉLIORATION CONTINUE</span><h1>Réclamations Qualité</h1><p>Transformer chaque retour réseau en décision traçable, cause racine et action d’amélioration.</p></div><div className={styles.heroMeta}><span>SESSION</span><strong>{sessionName}</strong><small>Actualisation automatique · 60 s</small></div></header>

      <nav className={styles.tabs} aria-label="Navigation Réclamations Qualité">
        <button className={tab==="pilotage"?styles.active:""} onClick={()=>setTab("pilotage")}>Pilotage</button>
        <button className={tab==="claims"?styles.active:""} onClick={()=>setTab("claims")}>Réclamations</button>
        <button className={tab==="analysis"?styles.active:""} onClick={()=>setTab("analysis")}>Analyse Qualité</button>
        <button className={tab==="settings"?styles.active:""} onClick={()=>setTab("settings")}>Paramètres & imports</button>
      </nav>

      {error&&<div className={styles.error}>{error}<button onClick={()=>setError("")}>×</button></div>}

      {tab==="pilotage"&&data&&<>
        <section className={styles.kpis}>
          <article><span>OUVERTES</span><strong>{data.metrics.open}</strong><small>{data.metrics.analysis} en analyse</small></article>
          <article className={styles.kpiWarn}><span>ATTENTE RÉSEAU</span><strong>{data.metrics.waitingNetwork}</strong><small>compléments attendus</small></article>
          <article><span>TAUX RECEVABLE</span><strong>{pct(data.metrics.acceptanceRate)}</strong><small>{data.metrics.accepted} acceptées · {data.metrics.refused} refusées</small></article>
          <article><span>ÉCHAPPEMENT QUALITÉ</span><strong>{pct(data.metrics.qualityEscapeRate)}</strong><small>acceptées qui auraient dû être détectées</small></article>
          <article><span>DÉLAI DE DÉCISION</span><strong>{data.metrics.averageDecisionDays==null?"—":`${n(data.metrics.averageDecisionDays).toLocaleString("fr-FR",{maximumFractionDigits:1})} j`}</strong><small>SLA décision {data.settings.sla_decision_hours} h</small></article>
          <article><span>COÛT QUALITÉ</span><strong>{money(data.metrics.acceptedAmount)}</strong><small>prises en charge acceptées</small></article>
          <article><span>TAUX / SORTIES</span><strong>{data.metrics.claimsPer1000Output365==null?"—":`${n(data.metrics.claimsPer1000Output365).toLocaleString("fr-FR",{maximumFractionDigits:2})} ‰`}</strong><small>{n(data.metrics.siteOutput365).toLocaleString("fr-FR")} sorties · 365 j</small></article>
        </section>
        <section className={styles.split}><div className={styles.card}><div className={styles.sectionHead}><div><span>À TRAITER</span><h2>File Qualité</h2></div><button onClick={()=>setTab("claims")}>VOIR TOUT</button></div><div className={styles.queue}>{data.claims.filter(c=>!["CLOSED","REFUSED"].includes(c.status)).slice(0,10).map(c=><button key={c.id} onClick={()=>void openClaim(c.id)}><div><strong>{c.claim_number}</strong><span>{c.client_name} · {c.registration}</span></div><div><em className={`${styles.badge} ${claimTone(c.status)}`}>{statusNames[c.status]||c.status}</em><small>{dt(c.declared_at)}</small></div></button>)}{!data.metrics.open&&<p className={styles.empty}>Aucune réclamation ouverte.</p>}</div></div><div className={styles.card}><div className={styles.sectionHead}><div><span>PARETO</span><h2>Causes déclarées</h2></div><button onClick={()=>setTab("analysis")}>ANALYSER</button></div><div className={styles.pareto}>{data.analytics.categories.slice(0,8).map((x,i)=><div key={x.category}><span>{i+1}</span><div><strong>{x.category}</strong><small>{x.accepted} recevable(s) · {money(x.cost)}</small></div><b>{x.claims}</b></div>)}{!data.analytics.categories.length&&<p className={styles.empty}>Le Pareto se construira dès les premières réclamations.</p>}</div></div></section>
      </>}

      {tab==="claims"&&data&&<section className={styles.claimsLayout}>
        <div className={styles.claimListCard}><div className={styles.sectionHead}><div><span>DOSSIERS</span><h2>{filtered.length} réclamation{filtered.length>1?"s":""}</h2></div><button className={styles.primary} onClick={()=>setShowCreate(v=>!v)}>+ SAISIE INTERNE</button></div>
          {showCreate&&<div className={styles.createBox}><select value={newClaim.client} onChange={e=>setNewClaim({...newClaim,client:e.target.value})}><option value="">Client / concession…</option>{data.clients.map(c=><option key={c.client}>{c.client}</option>)}</select><input value={newClaim.registration} onChange={e=>setNewClaim({...newClaim,registration:e.target.value.toUpperCase()})} placeholder="Immatriculation"/><select value={newClaim.category} onChange={e=>setNewClaim({...newClaim,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select><textarea value={newClaim.description} onChange={e=>setNewClaim({...newClaim,description:e.target.value})} placeholder="Description de l’anomalie"/><button disabled={saving} onClick={()=>void createInternalClaim()}>CRÉER LE DOSSIER</button></div>}
          <div className={styles.filters}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="N° dossier, immatriculation, client…"/><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">Tous les statuts</option>{statuses.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select><select value={filterCategory} onChange={e=>setFilterCategory(e.target.value)}><option value="">Toutes les catégories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>void refresh()}>ACTUALISER</button></div>
          <div className={styles.tableWrap}><table><thead><tr><th>Dossier</th><th>Véhicule</th><th>Client</th><th>Catégorie</th><th>Statut</th><th>Déclarée</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className={detail?.claim.id===c.id?styles.selected:""} onClick={()=>void openClaim(c.id)}><td><strong>{c.claim_number}</strong></td><td><b>{c.registration}</b><small>{c.model||c.work_order||"—"}</small></td><td>{c.client_name}</td><td>{c.category}</td><td><span className={`${styles.badge} ${claimTone(c.status)}`}>{statusNames[c.status]||c.status}</span></td><td>{dt(c.declared_at)}</td></tr>)}</tbody></table></div>
        </div>
        <div className={styles.detailCard}>{detail?<ClaimDetail detail={detail} data={data} edit={edit} setEdit={setEdit} qualityStaff={qualityStaff} saving={saving} committeeResponse={committeeResponse} setCommitteeResponse={setCommitteeResponse} requestedInfo={requestedInfo} setRequestedInfo={setRequestedInfo} message={message} setMessage={setMessage} note={note} setNote={setNote} saveClassification={saveClassification} decide={decide} sendText={sendText} uploadAttachments={uploadAttachments} closeClaim={()=>void post("CLOSE",detail.claim.id,{})}/>:<div className={styles.detailEmpty}><span>RQ</span><h3>Sélectionnez une réclamation</h3><p>La fiche complète, les photos, les échanges, les responsabilités et la décision comité s’ouvriront ici.</p></div>}</div>
      </section>}

      {tab==="analysis"&&data&&<section className={styles.analysisGrid}>
        <div className={styles.card}><div className={styles.sectionHead}><div><span>PARETO</span><h2>Réclamations par catégorie</h2></div></div><AnalyticsTable rows={data.analytics.categories.map(x=>[x.category,x.claims,x.accepted,money(x.cost)])} headers={["Catégorie","Réclamations","Recevables","Coût"]}/></div>
        <div className={styles.card}><div className={styles.sectionHead}><div><span>SECTEURS</span><h2>Origine des non-conformités</h2></div></div><AnalyticsTable rows={data.analytics.sectors.map(x=>[x.sector,x.claims,x.accepted,money(x.cost)])} headers={["Secteur","Réclamations","Recevables","Coût"]}/></div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.sectionHead}><div><span>COLLABORATEURS</span><h2>Responsabilité ramenée à l’activité</h2></div><p>Le taux utilise le nombre de dossiers distincts facturés sur 365 jours lorsqu’un rapprochement collaborateur existe.</p></div><AnalyticsTable rows={data.analytics.collaborators.map(x=>[x.collaborator,x.claims,x.accepted,x.interventions365,x.interventions365?`${(1000*x.accepted/x.interventions365).toLocaleString("fr-FR",{maximumFractionDigits:2})} ‰`:"—"])} headers={["Collaborateur","Réclamations","Recevables","Interventions 365 j","Recevables / 1000"]}/></div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.sectionHead}><div><span>TENDANCE</span><h2>Historique mensuel</h2></div></div><AnalyticsTable rows={data.analytics.monthly.map(x=>[x.month_key,x.claims,x.accepted,money(x.cost)])} headers={["Mois","Réclamations","Recevables","Coût"]}/></div>
      </section>}

      {tab==="settings"&&data&&<section className={styles.settingsGrid}>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.sectionHead}><div><span>IMPORT HISTORIQUE</span><h2>Injecter Excel / CSV sans doublon</h2></div><p>Le fichier brut reste conservé ligne par ligne dans la donnée source. Le mapping sert uniquement à normaliser l’analyse.</p></div><div className={styles.importZone}><label className={styles.fileDrop}>CHOISIR UN FICHIER .XLSX / .CSV<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void parseImport(f);}}/></label>{importFile&&<strong>{importFile.name} · {importRows.length} ligne(s) détectée(s)</strong>}{importHeaders.length>0&&<><div className={styles.mappingGrid}>{(Object.keys(fieldLabels) as ImportField[]).map(field=><label key={field}><span>{fieldLabels[field]}{["client","registration"].includes(field)?" *":""}</span><select value={importMapping[field]} onChange={e=>setImportMapping({...importMapping,[field]:e.target.value})}><option value="">Non associé</option>{importHeaders.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><div className={styles.importPreview}><strong>Aperçu brut</strong><pre>{JSON.stringify(importRows.slice(0,3),null,2)}</pre></div><button className={styles.primary} disabled={saving||!importMapping.client||!importMapping.registration} onClick={()=>void launchImport()}>INJECTER {importRows.length} LIGNES</button></>}{importResult&&<p className={styles.result}>{importResult}</p>}<div className={styles.importHistory}>{data.imports.slice(0,8).map(b=><div key={b.id}><span>{b.file_name}</span><strong>{b.inserted_count} injectées</strong><small>{dt(b.created_at)} · {b.error_count} erreur(s)</small></div>)}</div></div></div>
        {canConfigure&&<><div className={styles.card}><div className={styles.sectionHead}><div><span>PORTAIL RÉSEAU</span><h2>Créer un accès concession</h2></div></div><div className={styles.formStack}><label>Client / périmètre<select value={networkForm.client} onChange={e=>setNetworkForm({...networkForm,client:e.target.value})}><option value="">Sélectionner…</option>{data.clients.map(c=><option key={c.client}>{c.client}</option>)}</select></label><label>Nom affiché<input value={networkForm.partnerLabel} onChange={e=>setNetworkForm({...networkForm,partnerLabel:e.target.value})} placeholder="Ex. Concession BMW Lille"/></label><label>Code concession<input value={networkForm.dealerCode} onChange={e=>setNetworkForm({...networkForm,dealerCode:e.target.value})}/></label><label>Expiration optionnelle<input type="date" value={networkForm.expiresAt} onChange={e=>setNetworkForm({...networkForm,expiresAt:e.target.value})}/></label><button className={styles.primary} disabled={saving||!networkForm.client||!networkForm.partnerLabel} onClick={()=>void createNetworkAccess()}>GÉNÉRER L’ACCÈS SÉCURISÉ</button>{newPortalUrl&&<div className={styles.portalUrl}><input readOnly value={newPortalUrl}/><button onClick={()=>void navigator.clipboard.writeText(newPortalUrl)}>COPIER</button><small>Le secret n’est affiché qu’à sa création. La base ne conserve que son empreinte SHA-256.</small></div>}</div></div>
        <div className={styles.card}><div className={styles.sectionHead}><div><span>SLA & PIÈCES</span><h2>Règles Lens</h2></div></div><div className={styles.formStack}><label>Analyse initiale (heures)<input type="number" value={settingsForm.slaAnalysisHours} onChange={e=>setSettingsForm({...settingsForm,slaAnalysisHours:n(e.target.value)})}/></label><label>Décision comité (heures)<input type="number" value={settingsForm.slaDecisionHours} onChange={e=>setSettingsForm({...settingsForm,slaDecisionHours:n(e.target.value)})}/></label><label>Pièces jointes max.<input type="number" value={settingsForm.maxAttachments} onChange={e=>setSettingsForm({...settingsForm,maxAttachments:n(e.target.value)})}/></label><label>Taille max. par fichier (octets)<input type="number" value={settingsForm.maxAttachmentBytes} onChange={e=>setSettingsForm({...settingsForm,maxAttachmentBytes:n(e.target.value)})}/></label><button className={styles.primary} disabled={saving} onClick={()=>void saveSettings()}>ENREGISTRER LES RÈGLES</button></div></div>
        <div className={`${styles.card} ${styles.wide}`}><div className={styles.sectionHead}><div><span>ACCÈS ACTIFS</span><h2>Périmètres réseau</h2></div></div><div className={styles.accessTable}>{data.networkAccess.map(a=><div key={a.id}><div><strong>{a.partner_label}</strong><span>{a.client_scope}{a.dealer_code?` · ${a.dealer_code}`:""}</span></div><div><small>Dernière utilisation : {dt(a.last_used_at)}</small><button className={a.is_active?styles.danger:styles.primary} disabled={saving} onClick={()=>void toggleNetworkAccess(a.id,!a.is_active)}>{a.is_active?"DÉSACTIVER":"RÉACTIVER"}</button></div></div>)}{!data.networkAccess.length&&<p className={styles.empty}>Aucun accès réseau créé pour le moment.</p>}</div></div></>}
      </section>}
      <footer className={styles.footer}><span>CRVO Lens · Réclamations Qualité</span><span>Données cloisonnées · audit complet · réseau séparé des notes internes</span></footer>
    </div>
  </main>;
}

function ClaimDetail({detail,data,edit,setEdit,qualityStaff,saving,committeeResponse,setCommitteeResponse,requestedInfo,setRequestedInfo,message,setMessage,note,setNote,saveClassification,decide,sendText,uploadAttachments,closeClaim}:{detail:Detail;data:Dashboard;edit:Record<string,unknown>;setEdit:(v:Record<string,unknown>)=>void;qualityStaff:Staff[];saving:boolean;committeeResponse:string;setCommitteeResponse:(v:string)=>void;requestedInfo:string;setRequestedInfo:(v:string)=>void;message:string;setMessage:(v:string)=>void;note:string;setNote:(v:string)=>void;saveClassification:()=>Promise<void>;decide:(d:"ACCEPTED"|"REFUSED"|"NEEDS_INFO")=>Promise<void>;sendText:(k:"MESSAGE"|"NOTE")=>Promise<void>;uploadAttachments:(f:FileList|null,v?:"NETWORK"|"INTERNAL")=>Promise<void>;closeClaim:()=>void}){
  const c=detail.claim;const set=(key:string,value:unknown)=>setEdit({...edit,[key]:value});
  return <div className={styles.detailInner}><div className={styles.detailTop}><div><span>{c.claim_number}</span><h2>{c.registration}</h2><p>{c.client_name} · {c.model||"Modèle non renseigné"}</p></div><span className={`${styles.badge} ${claimTone(c.status)}`}>{statusNames[c.status]||c.status}</span></div><div className={styles.vehicleGrid}><div><span>OR</span><strong>{c.work_order||"—"}</strong></div><div><span>VIN</span><strong>{c.vin||"—"}</strong></div><div><span>KM</span><strong>{c.mileage?n(c.mileage).toLocaleString("fr-FR"):"—"}</strong></div><div><span>DÉCLARÉE</span><strong>{dt(c.declared_at)}</strong></div></div><section className={styles.claimText}><span>ANOMALIE DÉCLARÉE</span><p>{c.description}</p>{c.estimate_amount!=null&&<small>Devis / estimation : {money(c.estimate_amount)}</small>}</section>
  <section className={styles.detailSection}><h3>Qualification & responsabilité</h3><div className={styles.mappingGrid}><label><span>Catégorie</span><select value={String(edit.category??"")} onChange={e=>set("category",e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Priorité</span><select value={String(edit.priority??"NORMAL")} onChange={e=>set("priority",e.target.value)}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Phase</span><select value={String(edit.status??c.status)} onChange={e=>set("status",e.target.value)}>{statuses.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select></label><label><span>Compagnon responsable</span><select value={String(edit.responsibleEmployeeKey??"")} onChange={e=>set("responsibleEmployeeKey",e.target.value)}><option value="">Non attribué</option>{data.staff.map(s=><option key={s.employeeKey} value={s.employeeKey}>{s.name} · {s.sectorLabel||s.service||"CRVO"}</option>)}</select></label><label><span>La Qualité devait détecter ?</span><select value={String(edit.qualityShouldDetect??"")} onChange={e=>set("qualityShouldDetect",e.target.value)}><option value="">À statuer</option><option value="true">Oui</option><option value="false">Non</option></select></label><label><span>Qualiticien</span><select value={String(edit.qualityEmployeeKey??"")} onChange={e=>set("qualityEmployeeKey",e.target.value)}><option value="">Non attribué</option>{qualityStaff.map(s=><option key={s.employeeKey} value={s.employeeKey}>{s.name}</option>)}</select></label><label><span>Montant accepté €</span><input type="number" step="0.01" value={String(edit.acceptedAmount??"")} onChange={e=>set("acceptedAmount",e.target.value)}/></label><label><span>Clé de récurrence</span><input value={String(edit.recurrenceKey??"")} onChange={e=>set("recurrenceKey",e.target.value)} placeholder="Ex. CARRO-REMONTAGE"/></label></div><label className={styles.fullLabel}><span>Cause racine</span><textarea value={String(edit.rootCause??"")} onChange={e=>set("rootCause",e.target.value)} placeholder="Pourquoi le défaut est-il apparu ?"/></label><label className={styles.fullLabel}><span>Action corrective / préventive</span><textarea value={String(edit.correctiveAction??"")} onChange={e=>set("correctiveAction",e.target.value)} placeholder="Action qui évite la récurrence"/></label><button className={styles.primary} disabled={saving} onClick={()=>void saveClassification()}>ENREGISTRER LA QUALIFICATION</button></section>
  <section className={styles.detailSection}><h3>Comité Qualité</h3><label className={styles.fullLabel}><span>Réponse destinée au réseau</span><textarea value={committeeResponse} onChange={e=>setCommitteeResponse(e.target.value)} placeholder="Motiver clairement la décision…"/></label><label className={styles.fullLabel}><span>Complément demandé</span><textarea value={requestedInfo} onChange={e=>setRequestedInfo(e.target.value)} placeholder="Photos complémentaires, diagnostic, devis détaillé…"/></label><div className={styles.decisionButtons}><button disabled={saving} onClick={()=>void decide("ACCEPTED")}>ACCEPTER</button><button disabled={saving} onClick={()=>void decide("NEEDS_INFO")}>DEMANDER UN COMPLÉMENT</button><button className={styles.reject} disabled={saving} onClick={()=>void decide("REFUSED")}>REFUSER</button></div>{c.decision&&<p className={styles.decisionState}>Décision enregistrée : <strong>{c.decision}</strong> · {dt(c.decision_at)}</p>}</section>
  <section className={styles.detailSection}><h3>Photos & documents</h3><div className={styles.attachments}>{detail.attachments.map(a=><button key={a.id} onClick={()=>window.open(`/api/quality-claims?attachmentId=${encodeURIComponent(a.id)}`,"_blank","noopener,noreferrer")}><span>{a.kind==="PHOTO"?"PHOTO":a.kind==="QUOTE"?"DEVIS":"FICHIER"}</span><strong>{a.file_name}</strong><small>{Math.round(a.size_bytes/1024)} Ko · {a.visibility==="INTERNAL"?"interne":"réseau"}</small></button>)}{!detail.attachments.length&&<p className={styles.empty}>Aucune pièce jointe.</p>}</div><div className={styles.uploadRow}><label>AJOUTER AU DOSSIER RÉSEAU<input type="file" multiple accept="image/*,application/pdf" onChange={e=>void uploadAttachments(e.target.files,"NETWORK")}/></label><label>AJOUTER EN INTERNE<input type="file" multiple accept="image/*,application/pdf" onChange={e=>void uploadAttachments(e.target.files,"INTERNAL")}/></label></div></section>
  <section className={styles.detailSection}><h3>Conversation réseau</h3><div className={styles.chat}>{detail.messages.filter(m=>m.visibility==="NETWORK").map(m=><div key={m.id} className={m.author_role==="CRVO"?styles.fromCrvo:styles.fromNetwork}><strong>{m.author_name||m.author_role}</strong><p>{m.body}</p><small>{dt(m.created_at)}</small></div>)}</div><div className={styles.chatComposer}><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Répondre au réseau…"/><button disabled={saving||!message.trim()} onClick={()=>void sendText("MESSAGE")}>ENVOYER</button></div></section>
  <section className={styles.detailSection}><h3>Notes internes CRVO</h3><div className={styles.chat}>{detail.messages.filter(m=>m.visibility==="INTERNAL").map(m=><div key={m.id} className={styles.internalNote}><strong>{m.author_name||"CRVO"}</strong><p>{m.body}</p><small>{dt(m.created_at)}</small></div>)}</div><div className={styles.chatComposer}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Visible uniquement par le CRVO…"/><button disabled={saving||!note.trim()} onClick={()=>void sendText("NOTE")}>AJOUTER</button></div></section>
  <section className={styles.detailSection}><h3>Traçabilité</h3><div className={styles.audit}>{detail.audit.slice().reverse().slice(0,30).map(a=><div key={a.id}><span></span><div><strong>{a.event_type.replaceAll("_"," ")}</strong><p>{a.actor_name||a.actor_role}</p><small>{dt(a.created_at)}</small></div></div>)}</div>{c.status!=="CLOSED"&&<button className={styles.danger} disabled={saving} onClick={closeClaim}>CLÔTURER LE DOSSIER</button>}</section></div>;
}

function AnalyticsTable({headers,rows}:{headers:string[];rows:Array<Array<string|number>>}){return <div className={styles.tableWrap}><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className={styles.empty}>Les indicateurs apparaîtront avec les premières réclamations qualifiées.</p>}</div>}
